OpenDDS/OpenDDS

.gitignore
dds/DCPS/RTPS/ParameterListConverter.cpp
dds/DCPS/RTPS/RtpsBaseMessageTypes.idl
dds/DCPS/RTPS/Spdp.cpp

Avoids reading uninitialized memory when minimum profile is in effect, may fix built-in topics for those cases.

Updated RTPS SEDP to process all QoS policies even if some are disabled locally due to profiles

---

FACE/TS.hpp
dds/FACE/FaceTSS.cpp
tests/FACE/Messenger/Publisher/Publisher.cpp

Treat name and ID as both optional. If not provided, fill in, if both provided, validate, if neither provided, error. Connection_Id is only out param if specified as 0 otherwise will assume connection id has been specified.  Updated Messenger test's get connection params validation section with a couple additional scenarios to test new functionality.

TS API Update: Get_Connection_Parameters() - Redmine Task #2373

---

dds/FACE/FaceTSS.h
tests/FACE/Messenger/Subscriber/Subscriber.cpp

If multiple callbacks registered, all should get a copy of the message.
Adapt Messenger test to register 2 callbacks instead of just one.

TS API Update: If multiple callbacks registered, Task #2380

---

dds/DCPS/DataWriterImpl.cpp
dds/DCPS/DataWriterImpl.h
dds/DCPS/PublisherImpl.cpp
dds/DCPS/WriteDataContainer.cpp
dds/DCPS/WriteDataContainer.h
dds/DCPS/transport/framework/TransportCustomizedElement.cpp
dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp
dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.h

Working to resolve issues in the rtps transport layer (RtpsUdpDataLink) to deal with processing acknowledgements and lifetimes of transport queue elements (and derived) up to WriteDataContainer and DataSampleElements.  Moving away from handling the processing of acknowledgements in a timer based solution into a direct processing solution.

Rtps msg lifespan updates

---

dds/DCPS/Definitions.h
dds/DCPS/MultiTopicDataReaderBase.h
dds/DCPS/MultiTopicDataReader_T.h
dds/DCPS/RecorderImpl.cpp
dds/DCPS/RemoveAssociationSweeper.h
dds/DCPS/TypeSupportImpl.h

requires workaround to avoid compiler-generated copy ctor and assignment for a few classes

MSVC14 support

---

DevGuideExamples/FACE/Simple/face_config.ini
DevGuideExamples/FACE/Simple/face_config_static.ini
dds/DCPS/TypeSupportImpl.cpp
dds/DCPS/TypeSupportImpl.h
dds/DCPS/TypeSupportImpl_T.h
dds/FACE/FaceTSS.cpp
tests/DCPS/StaticDiscovery/run_test.pl
tests/DCPS/StaticDiscoveryReconnect/config.ini
tests/FACE/CallbackAndReceive/face_config.ini
tests/FACE/GetConnectionParameters/face_config.ini
tests/FACE/Header/face_config.ini
tests/FACE/Messenger/face_config.ini
tests/FACE/Messenger/face_config_static.ini
tests/FACE/MultiDomainMessenger/face_config.ini
tests/FACE/Partition/face_config.ini
tests/FACE/Reliability/face_config.ini

The old way was to use the IDL IfR ID for the generated TypeSupport interface.
This resulted in strings that look like "IDL:Scope/NameTypeSupport:1.0".
Since this DDS spec allows the implementation to pick any name, this commit
changes it to the simpler C++ scoped name, in this example Scope::Name.

Use a simpler string as the default type name in TypeSupport.

---

configure
dds/DCPS/transport/framework/NetworkAddress.cpp

Prevent error logs from ACE and DCPS.

Don't call get_ip_interfaces in safety profile.

---

dds/FACE/config/ConnectionSettings.cpp
dds/FACE/config/Parser.cpp
dds/FACE/config/TopicSettings.cpp

Convert ACE_OS::printf calls to ACE_DEBUG in FACE config file parsing.
All other printf like calls were checked to be calls to snprintf.

Convert ACE_OS::printf to ACE_DEBUG

---

dds/DCPS/DataReaderImpl.cpp
dds/DCPS/transport/framework/DataLink.h
dds/DCPS/transport/framework/DataLink.inl
dds/DCPS/transport/framework/DataLinkSet.h
dds/DCPS/transport/framework/DataLinkSet.inl
dds/DCPS/transport/framework/TransportClient.cpp
dds/DCPS/transport/framework/TransportClient.h
dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp
dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.h
tests/DCPS/StaticDiscovery/StaticDiscoveryTest.cpp

The following sequence was observed in the StaticDiscovery test:
Writer             Reader
Send last sample
...
Process last sample
...
Terminate
...
Wait for acks
...
Timeout
The goal is to avoid the timeout.  There are three options:
1. Decrease the WaitForAck timeout.
2. Add a delay to the reader so that it will receive a heartbeat from
the writer and send an acknack.
3. Have the reader send an acknack before it goes away.  If the writer
receives it then it will not timeout.
This commit implements option 3.
The StaticDiscoveryTest was modified to set the history depth when
available.

Send acknack when reader is going away

---

tests/FACE/MultiDomainMessenger/Subscriber/Subscriber.cpp

The same callback is used for two different FACE connections.  The
callback updates a global counter and flag.  The callback may be invoked
concurrently, thus, the counter and flag must be protected by a lock.

Fix datarace in callback subscriber for MultiDomainMessenger Test

---

bin/PerlDDS/Run_Test.pm

PerlDDS attempts to unlink log files before a test and scan log files for errors after the test.  Assume the test is running on a remote target whose file system appears in the local system.  (The target may be mounted by the host system or the host system can be mounted by target.)  The log files will appear on the local file system but must be translated to the mount point.

Translate log file names for remote target

---

bin/PerlDDS/Run_Test.pm
dds/DCPS/Service_Participant.cpp
tests/DCPS/CompatibilityTest/run_test.pl
tests/DCPS/Deadline/run_test.pl
tests/DCPS/DpShutdown/run_test.pl
tests/DCPS/GuardCondition/run_test.pl
tests/DCPS/ManyTopicTest/run_test.pl
tests/DCPS/RecorderReplayer/run_test.pl
tests/DCPS/RegisterInstance/run_test.pl
tests/DCPS/Rejects/run_test.pl
tests/DCPS/RtpsMessages/run_test.pl
tests/DCPS/Serializer/run_test.pl
tests/DCPS/SetQosDeadline/run_test.pl
tests/DCPS/SetQosPartition/run_test.pl
tests/DCPS/SetQosPartition/subscriber.cpp
tests/DCPS/TopicReuse/run_test.pl
tests/DCPS/UnitTests/run_test.pl
tests/DCPS/WriteDataContainer/run_test.pl
tests/DCPS/ZeroCopyRead/run_test.pl
tests/FACE/Compiler/idl_test1_main/run_test.pl
tests/FACE/Compiler/idl_test3_main/run_test.pl
tests/FACE/Compiler/idl_test_fixed/run_test.pl
tests/transport/rtps/publisher.cpp
tests/transport/rtps/run_test.pl
tests/transport/rtps/subscriber.cpp
tests/transport/rtps_reliability/run_test.pl

Removed the default safetyprofile.log.  Tests enabled in safety profile
must use the test framework whichw will supply and translate a log file
name.

Update safety profile logging

---

tests/DCPS/UnitTests/run_test.pl

test/DCPS/UnitTests/run_test.pl is failing on Windows complaining about
duplicate process names.  This fix creates a new test framework for each
executable.

Shorten test framework lifetime

---

bin/PerlDDS/ProcessFactory.pm
dds/DCPS/RTPS/Sedp.cpp
dds/DCPS/Service_Participant.cpp
dds/DCPS/Service_Participant.h
dds/DCPS/Service_Participant.inl
dds/DCPS/transport/rtps_udp/RtpsUdpInst.cpp

Safety profile builds must be configured with an address for discovery and transport.  One way to do this is to specify a local_address in the configuration file.  To avoid (1) manually editing every test configuration file and (2) parsing every configuration file to determine if and how the local_address should appear, we introduced a configuration variable for the common section (and command-line option) called DCPSDefaultAddress.  The default address overrides any that would be determined automatically but does not override a local_address appearing in a file.
This commit introduces the following changes:
* Adds default_address to the Service_Participant.
* Causes Sedp to use the default address when computing locators for Spdp.
* Causes Rtps to use the default address when computing …

Add -DCPSDefaultAddress

---

tests/DCPS/Partition/Partition_Table.h
tests/DCPS/Partition/run_test.pl

Expected counts of matched subscriptions were wrong.  Apparently, they did not take into acount "*" matching everything.  Adjusted the expected values and enabled error checking in log files.

Fix DCPS/Partition test

---

dds/DCPS/Service_Participant.cpp

The tcp, udp, and multicast transports have a local_address config parameter.  The value of DCPSDefaultAddress will be used in lieu of local_address if local_address is not set and DCPSDefaultAddress is set.

Apply DCPSDefaultTransport to tcp, udp, and multicast

---

dds/DCPS/PoolAllocator.h
dds/DCPS/RTPS/ParameterListConverter.cpp
dds/DCPS/RTPS/Sedp.cpp
dds/DCPS/RTPS/Spdp.cpp
dds/FACE/FaceTSS.cpp
tests/DCPS/FooTest4/main.cpp

For example GCC 4.1, which mistakenly causes free to be called.

Disable PoolAllocator use in standard library for the benefit of older compilers 

---

tests/DCPS/SharedTransport/TestCase.cpp

Fix test to wait for correct number of messages to be
delivered in cases where command line specified more
than one writer/publisher.

SharedTransport test:

---

DevGuideExamples/DCPS/Messenger/appveyor_run_test.pl

Set Default Address as a workaround due to failure currently
on appveyor to successfully connect on dynamically discovered
fully qualified hostname.

appveyor_run_test.pl update:

---

configure

Note that the version of ACE in use must have support for FreeBSD to make this usable.

Added FreeBSD to the configure script.

---

dds/dcps_optional_safety.mpb

Work-around what appears to be a bug in MPC, make sure that *S.h are known to the makefiles and thus get installed.

Fixing issue of some *S.h headers missing from "make install"

---

.gitignore
dds/DCPS/DataDurabilityCache.cpp
dds/DCPS/DataSampleElement.h
dds/DCPS/DataSampleElement.inl
dds/DCPS/DataWriterImpl.cpp
dds/DCPS/InstanceDataSampleList.cpp
dds/DCPS/InstanceDataSampleList.h
dds/DCPS/InstanceDataSampleList.inl
dds/DCPS/OwnershipManager.h
dds/DCPS/PublicationInstance.h
dds/DCPS/Qos_Helper.h
dds/DCPS/Qos_Helper.inl
dds/DCPS/SendStateDataSampleList.cpp
dds/DCPS/SendStateDataSampleList.h
dds/DCPS/SendStateDataSampleList.inl
dds/DCPS/WriteDataContainer.cpp
dds/DCPS/WriteDataContainer.h
dds/DCPS/WriterDataSampleList.h
dds/DCPS/transport/framework/NetworkAddress.cpp
tests/DCPS/FooTest3_0/PubDriver.cpp
tests/DCPS/WriteDataContainer/WriteDataContainerTest.cpp
tests/FACE/CallbackAndReceive/Subscriber/Subscriber.cpp
tests/FACE/Header/Subscriber/Subscriber.cpp
tests/FACE/Reliability/Publisher/Publisher.cpp
tests/FACE/Utils.h

- RESOURCE_LIMITS.max_samples_per_instance controls total samples that can be
stored per instance, independent of HISTORY
- HISTORY.depth controls number of samples (per instance) that will be made
available to late-joining readers if DURABILITY is enabled
- KEEP_ALL history uses max_samples_per_instance as its depth
- WriteDataContainer is more eager to remove samples that are no longer needed
- WriteDataContainer will not remove samples that are required to implement
DURABILITY, hence if RELIABILITY is enabled this can block a write() just
like other "no resource available" scenarios

Updated handling of QoS in WriteDataContainer:

---

dds/DCPS/SendStateDataSampleList.h
dds/DCPS/WriteDataContainer.cpp

-  Release buffers for resent samples upon callback to WDC
- Standard-conforming iterators (Forward or stronger) need default constructors.
- Adapt to non-standard SunCC standard library.

Portability and memory fixes for pull request #272

---

dds/DCPS/WriteDataContainer.cpp
dds/DCPS/transport/framework/DataLink.cpp
dds/DCPS/transport/framework/DataLink.h

- Check for invalid (but non-0) instance handle in write()
- One more fix to DataLink ref counting when interacting with Reactor

WriteDataContainer and DataLink bug fixes

---

FACE/TS_common.hpp
java/build_scripts/jni_check.pl

- Use the GNU version of nm (gnm) in jni_check.pl since solaris nm produces a slightly different output
- undef NOSIGNAL in FACE header if predefined by environment.

Solaris: Fix NOSIGNAL collision, nm variant

---

INSTALL
README.md
VERSION
dds/DdsDcps.mpc
docs/html/guidelines/guidelines.html
java/FAQ
java/INSTALL
java/jms/INSTALL

I started out thinking it'd be useful to show the Travis badge in the readme, like many github projects do. But then realized the readme would have to be converted into markdown format first. Hence the two commits.

Convert Readme to markdown and add Travis badge

---

java/dds/dcps_java.mpc
java/tests/hello/hello_java_client.mpc

Fixing java dependencies that are not setup correctly to compile after a clean build.  Redmine Task #3245.

Java dependencies

---

bin/dcps_tests.lst
dds/DCPS/DataReaderImpl.cpp
dds/DCPS/DataReaderImpl.h
dds/DCPS/DataReaderImpl_T.h
dds/DCPS/Watchdog.cpp
dds/DCPS/Watchdog.h
dds/DdsDcps.mpc
tests/DCPS/TimeBasedFilter/main.cpp

Time Based Filter Qos support is currently just filtering samples to prevent more than 1 sample for an instance being delivered by the data reader in the time based filter period.  Need to add support for Data readers with a Reliability Qos of Reliable, to deliver the last filtered sample after the time based filter period has expired.

Time Based Filter QoS (support for reliable readers) Issue #268

---

java/dds/dcps_java.mpc

Reverted "Ensure java files are generated to satisfy interdependency of DdsDcpsTopic and DdsDcpsDomain."
This reverts commit 5ccbac1041c6b0fe0fd0755b9ae4841ffc0eafee.

Revert previous java_dependencies commit

---

dds/DCPS/DataReaderImpl_T.h
tests/DCPS/TimeBasedFilter/main.cpp

Fixed error in DataReaderImpl_T::store_instance_data exposed by MultiTopic test.  Identified potential deadlock issue in FilterDelayedHandler with needed to release sample_lock_ before calling into reactor. And fixed warnings.

Reliable time based filter multitopic

---

tests/DCPS/LivelinessKeepAliveTest/AlertDataReaderListenerImpl.cpp

Update requirements for expected values.  Base pass/fail on alive_count instead of trying to track all variables in the liveliness update.  This is due to two possible states after receiving the SYSTEM_SHUTDOWN message.  Not alive count could go to 1 or straight to 0 based on how the writer shuts down but does not alter the actual test pass/fail requirements. (In a test-passing scenario the AlertDataReaderListenerImpl could receive either 2 or 3 liveliness updates depending on timing).

Liveliness Qos Updates - Fix failing test observed in some cases.

---

README.md
tools/modeling/codegen/model/Sync.h

* tools/modeling/codegen/model/Sync.h:

When we have C++11 we also use noexcept(false)

---

tests/DCPS/Priority/Publisher.cpp

DataWriterImpl::wait_for_acknowledgments() no longer work for TCP transport on cricket. This is the workaround for the bug.

Workaround for DataWriterImpl::wait_for_acknowledgments() bug

---

dds/DCPS/DataSampleHeader.cpp
dds/DCPS/WriteDataContainer.cpp
dds/DCPS/transport/framework/TransportDefs.h
dds/DCPS/transport/tcp/TcpDataLink.cpp
dds/DCPS/transport/tcp/TcpDataLink.h
tests/DCPS/Thrasher/run_test.pl

Even though only one thread is created for receiving data per transport, the underly message blocks may be passed up to DataReaderImpl and then processed by EndHistoricSamplesMissedSweeper from another thread. Therefore, the receive buffer allocators must be properly synchronized.

Fix transport receive buffer allocator synchronization problem

---

dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp

use process_acked_by_all_i to update tracking on samples in flight when one reader goes away

RtpsUdpDataLink::release_reservations_i

---

dds/DCPS/DataWriterImpl.cpp
dds/DCPS/WriteDataContainer.cpp
dds/DCPS/WriteDataContainer.h
tests/DCPS/WriteDataContainer/WriteDataContainerTest.cpp

...instead of seeing it as part of max_samples_per_instance.  When history is
KEEP_LAST, the writer side may replace older samples instead of blocking
the write until more space is available.

Made WriteDataContainer aware of history depth as a separate parameter

---

dds/DCPS/transport/rtps_udp/RtpsUdpInst.h
dds/DCPS/transport/rtps_udp/RtpsUdpTransport.cpp
dds/DCPS/transport/tcp/TcpInst.h
dds/DCPS/transport/tcp/TcpTransport.cpp
dds/DCPS/transport/udp/UdpDataLink.cpp
dds/DCPS/transport/udp/UdpInst.h

The old code uses the last ":" to check if the port is available in the text representation; however, it's not correct for IPv6 IP address without port.

Fix generating IPv6 text representation

---

dds/DCPS/DataWriterImpl.cpp
dds/DCPS/DataWriterImpl.h
dds/DCPS/MessageTracker.h

* dds/DCPS/DataWriterImpl.h:
* dds/DCPS/MessageTracker.h:

Remove datawriter pending_control operation, not used

---

tests/DCPS/FooTest3_0/DataReaderListener.cpp
tests/DCPS/FooTest3_0/DataReaderListener.h
tests/DCPS/FooTest3_0/SubDriver.cpp
tests/DCPS/FooTest3_0/SubDriver.h
tests/DCPS/FooTest3_0/run_test.pl

… correct number of disposed instance states in the listener
* tests/DCPS/FooTest3_0/DataReaderListener.cpp:
* tests/DCPS/FooTest3_0/DataReaderListener.h:
* tests/DCPS/FooTest3_0/SubDriver.cpp:
* tests/DCPS/FooTest3_0/SubDriver.h:
* tests/DCPS/FooTest3_0/run_test.pl:

FooTest3_0: check count of disposed instances

---

dds/DCPS/RTPS/RtpsDiscovery.cpp

* dds/DCPS/RTPS/RtpsDiscovery.cpp:

Initialise local variables to resolve gcc warnings

---

dds/DdsDcpsSubscriptionExt.idl
tests/DCPS/SampleLost/DataReaderListener.cpp
tests/DCPS/SampleLost/DataReaderListener.h
tests/DCPS/SampleLost/subscriber.cpp

Extend the test to log the number of sample lost, sample rejected, and budget exceeded callbacks

Sample lost test extension

---

tests/DCPS/DPFactoryQos/publisher.cpp
tests/DCPS/DPFactoryQos/subscriber.cpp
tests/DCPS/Lifespan/publisher.cpp
tests/DCPS/Lifespan/subscriber.cpp
tests/DCPS/LivelinessTimeout/publisher.cpp
tests/DCPS/LivelinessTimeout/subscriber.cpp

* tests/DCPS/DPFactoryQos/publisher.cpp:
* tests/DCPS/DPFactoryQos/subscriber.cpp:
* tests/DCPS/Lifespan/publisher.cpp:
* tests/DCPS/Lifespan/subscriber.cpp:
* tests/DCPS/LivelinessTimeout/publisher.cpp:
* tests/DCPS/LivelinessTimeout/subscriber.cpp:

Added missing includes for static builds

---

tools/repoctl/repoctl.cpp

Fixed typo in repoctl console output

---

bin/dcps_tests.lst
dds/DCPS/transport/framework/TransportClient.cpp
tests/DCPS/Messenger/rtps_disc_tcp_udp.ini
tests/DCPS/Messenger/run_test.pl

This fix the data reader listener not found issue when both tcp and rtps_udp transports are listed in the configuration file.

fix problem with multiple transports in configuration file

---

dds/DCPS/Serializer.h
dds/DCPS/Serializer.inl
tests/DCPS/Serializer/SerializerTest.cpp

* dds/DCPS/Serializer.h:
* dds/DCPS/Serializer.inl:

Disable std::(w)string insertion/extraction when using safety profile

---

bin/dcps_tests.lst
tests/DCPS/Reliability/rtps.ini

This fixes the problem where the tests/DCPS/Reliability/run_test.pl and tests/DCPS/WaitForAck/run_test.pl tests not running problem.

Fix dcps_tests.lst errors

---

bin/dcps_tests.lst

Inconsistenct_Qos test uses RTPS discovery while the executable only links the default discovery. Therefore, it won't run on static build.

Avoid running Inconsistent_Qos Test for static build

---

dds/FACE/FaceTSS.cpp
tests/DCPS/TcpReconnect/publisher.cpp

Initially to address 1454919 and 1454912 having to do with further exceptions not being caught from the bind_config call.

Coverity Scan updates

---

dds/InfoRepo/DCPSInfo_i.cpp
dds/InfoRepo/DCPS_IR_Domain.cpp
dds/InfoRepo/DCPS_IR_Participant.cpp
dds/InfoRepo/DCPS_IR_Publication.cpp
dds/InfoRepo/DCPS_IR_Subscription.cpp
dds/InfoRepo/DCPS_IR_Topic.cpp
dds/InfoRepo/DCPS_IR_Topic_Description.cpp

This would fix the memory leak for persistent inforepo. However, it won't fix the corruption of persistent file for asan build. I don't see any persistent file corruption for non-asan build.

Fix persistent Inforepo memory leak

---

dds/DCPS/Service_Participant.cpp

supports the scenario where OpenDDS is completely shutdown then restarted within a process

Service_Participant: re-init the MonitorFactory

---

configure
tools/IntermediateTypeLang/cpp/itl/itl.hpp
tools/dissector/README
tools/dissector/dissector.mpc
tools/dissector/macos_postbuild.sh
tools/dissector/sample_dissector.cpp
tools/dissector/sample_dissector.h
tools/dissector/sample_manager.cpp

Dissector macOS support as well as changing the configure script to reflect [MPC#48](https://github.com/DOCGroup/MPC/pull/48) and the dissector/README to reflect both of these.
Also:
- Some bits of the `Fixed` type support for the sample payload dissector are in here, but nowhere near done.
- The loose throw error that I failed to fix in the scoreboards.
- Default to `/usr/include/wireshark` if it exists and `--wireshark` was left blank to support wireshark development packages installed there.

Dissector macOS support, configure script, fixed throw spec problem

---

dds/idl/itl_generator.cpp
tools/IntermediateTypeLang/cpp/itl/itl.hpp
tools/dissector/packet-opendds.cpp
tools/dissector/sample_dissector.cpp
tools/dissector/sample_dissector.h
tools/dissector/sample_manager.cpp

Added support for dissection of OpenDDS fixed-point numbers which are
converted to doubles for numerical comparisons within Wireshark.
If ACE_CDR::Fixed is missing, a message will be displayed that this is so.
Also started marking some packets with a warning instead of marking it
as malformed. For example, when an individual field fails for some
reason or non essential information is unavailable, like the dissector
ITL file or Fixed type is missing like above.

dissector: Fixed Type Support and expert changes

---

configure
tools/dissector/sample_dissector.cpp
tools/dissector/sample_dissector.h

- Missing Macro Guard for older Wiresharks.
- Fix for configure script "wireshark" value being passed through $WIRESHARK_SRC.
- Missing serializer skips when we are going over but not extracting a Fixed data type.

Dissector Fixes for Fixed Type Support, Expert, and configure

---

docs/.gitignore
docs/doxygen_main_page.h
etc/dds.doxygen
tools/scripts/generate_combined_doxygen.pl
tools/scripts/gitrelease.pl

- Added `generate_combined_doxygen.pl`, which builds ACE/TAO Doxygen docs based on `$ACE_ROOT`, and builds OpenDDS Doxygen docs based on `$DDS_ROOT`. The script calls `generate_doxygen.pl` internally. The DDS docs will be linked to the ACE/TAO docs reference wise. It also generates a list of the ACE/TAO Doxygens included.
- Also updated `gitrelease.pl` to use `generate_combined_doxygen.pl` instead of `generate_doxygen.pl`.

Link Doxygen to a Built-In Copy of ACE/TAO Documentation

---

dds/DCPS/transport/framework/DataLink.inl
tests/DCPS/Reconnect/.gitignore
tests/DCPS/Reconnect/Writer.cpp
tests/DCPS/Reconnect/run_test.pl

- Re-added the `element->data_dropped()`s in `DataLink`, except for the one after `customize_element()`. `customize_element()` calls `data_dropped` or passes it to `TransportCustomizedElement` which drops it when it's no longer needed.
- The Reconnect test hides the program output. Huangming had changed it in 373f41c
from collecting individual program output in a single file to having one
for each program, except the InfoRepo. I added an InfoRepo log file and did
some cleanup/small improvements.
- For the Reconnect sub_init_crash test the publisher has always (or at least in the commit
before the WeakRcHandle PR) waited for subscribers until the test script
timedout, killed it and reported it as an error. The fact that no more
subscribers are spawned seems to be intentional, as it just …

Fix Reconnect Test and DataLink Leaks

---

dds/FACE/FaceTSS.h

In OpenDDS::FaceTSS::receive_message create_readcondition is called without ever removing the ReadCondition from the DataReader.   This leaks ReadConditions and destroys performance until the DataReader is destroyed.
This change ensures that the created ReadCondition is destroyed, preventing the leak.

Fix for readcondition leak in OpenDDS::FaceTSS::receive_message

---

tests/FACE/SingleProcessMessenger/SingleProcess/SingleProcess.cpp
tests/FACE/SingleProcessMessenger/face_config.ini
tests/FACE/SingleProcessMessenger/face_config_static.ini

Collapse unnecessary suba/subb connections to a single sub connection.
Register any callbacks before sending the message designed to trigger the callback.
Mark shared variables as volatile to prevent compiler optimization shenanigans.
Fixes #833

Adjust and simplify FACE/SingleProcessMessenger test.

---

dds/DCPS/transport/tcp/TcpConnection.cpp

This is a fix for ContentFilterTopic test timing out.

TcpConnection: Don't join reconnect thread if it's the current thread

---

configure

In response to #849 and #783 I looked up if ActiveState Perl came with any zip modules on Windows, and it does, `Archive::Zip`, at least with 5.24.2.203. I added it as an alternative if `Archive:Extract` isn't installed, and `configure` will fall back to the manual extraction error message if `Archive::Zip` isn't installed or if it fails.

configure: Added alt unzip method: Archive::Zip

---

dds/DCPS/transport/framework/TransportStrategy.h
dds/DCPS/transport/multicast/MulticastReceiveStrategy.cpp
dds/DCPS/transport/multicast/MulticastReceiveStrategy.h
dds/DCPS/transport/rtps_udp/RtpsUdpReceiveStrategy.h
dds/DCPS/transport/shmem/ShmemReceiveStrategy.h
dds/DCPS/transport/tcp/TcpReceiveStrategy.h
dds/DCPS/transport/udp/UdpReceiveStrategy.h

This is an attempt to correct a Access Violation on Windows when the ACE Reactor Implementation `WFMO_Reactor` for the Multicast Transport tries tries to access the Transport's `MulticastReceivedStrategy` as part of it's cleanup. The problem is that it has already been deleted earlier in the destruction of the transport. This enables `ACE_Event_Handler`'s reference counting policy on Windows and connects it to `MulticastReceiverStrategy`'s `RcObject` count, keeping the `MulticastReceivedStrategy` alive until `WFMO_Reactor` is done with it and calls `remove_reference()` in `make_changes_in_current_info()`.
This is based off `RcEventHandler`, which might be preferred to this.

Use RcEventHandler in TransportReceiveStrategy subclasses

---

tools/dissector/README
tools/dissector/packet-opendds.cpp
tools/dissector/sample_dissector.cpp
tools/dissector/sample_dissector.h
tools/dissector/sample_manager.cpp
tools/dissector/sample_manager.h
tools/dissector/ws_common.h

- Gave dissector proper return value for WS 2.2 and later.
- Some formatting fixes and more comments
- Fixed a malformed packet error where multiple samples caused a bounds check error inside Wireshark's ethernet dissector.
- Updated README to mention 2.6 where applicable
- Renamed for loop variable that clashed with it's parent for loop's variable (using `i` is very enticing).
- Updated Field Registration to allow for "canceling" of fields to be registered with Wireshark.

Dissector: Various Improvements 

---

tools/dissector/ws_common.h

In the last PR I tried to put the compatibility kludges in order by Wireshark version. This would have worked except that the <1.4 function for `ws_find_or_create_conversation` relies on the `ws_find_conversation`, which changed in 2.5 and so was defined after it was needed.

Fix ws_common.h for Wireshark 1.2 and 1.3

---

dds/DCPS/DataReaderImpl.cpp
dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp
dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.h
tests/DCPS/StaticDiscovery/DataReaderListenerImpl.cpp
tests/DCPS/StaticDiscovery/DataReaderListenerImpl.h
tests/DCPS/StaticDiscovery/StaticDiscoveryTest.cpp
tests/DCPS/StaticDiscovery/TestMsg.idl
tests/DCPS/StaticDiscovery/run_test.pl

Also adding per-writer message tracking, support for binding generated transport config sections even when using rtps discovery to help with debugging, and fixing a few typos and code guideline violations.

Adding durability / history depth to fix occasional StaticDiscoveryTest failures under load.

---

dds/DCPS/DomainParticipantImpl.cpp
dds/DCPS/QueryConditionImpl.h
tests/DCPS/ContentFilteredTopic/ContentFilteredTopicTest.cpp
tests/DCPS/QueryCondition/QueryConditionTest.cpp

QueryCondition test runs two almost identical subtests back to back. This fix ensures they don't interfere with each other by cleaning up after each one. This fails at the moment though because of #935 and should actually work after #936 is merged.

Fix Occasional QueryCondition Test Failure

---

dds/DCPS/DataReaderImpl.cpp
dds/DCPS/DataReaderImpl.h
dds/DCPS/MultiTopicDataReaderBase.cpp

 Wrong entity_refs_ counter when deleting data reader in the TopicDescriptionImpl

---

azure-pipelines.yml
dds/DdsDcps.mpc
dds/dcps_optional_safety.mpb

Fixing another odd configuration flag combination which caused a build error.

adding mpc idl gen support for safety profile without builtin topics

---

dds/DCPS/SubscriberImpl.cpp
dds/FACE/FaceTSS.cpp
tests/DCPS/QueryCondition/QueryConditionTest.cpp
tests/DCPS/ReadCondition/ReadConditionTest.cpp

The deletion of a DataReader is not allowed if there are any existing ReadCondition or QueryCondition objects that are attached to the DataReader

---

dds/DCPS/Dynamic_Cached_Allocator_With_Overflow_T.h
tests/DCPS/ConfigTransports/publisher.cpp

By learning from historical log revisions, we find some consistent updates of output format of log variables. Under the guidance of these consistent updates, we find several missed spot in the latest version. 
More information please see the following commits or leave a comment ^^

Update output format of log variables

---

dds/DCPS/Service_Participant.cpp

We find two patches between  OpenDDS-2.2 and OpenDDS-2.3. These two patches both **update the verbosity of log statements whose static text contains "notice" to LM_NOTICE**.  And find one missed spot in the latest version.
More information please see the commit or leave a comment^^

update verbosity of log statement whose static text contains "notice" to LM_NOTICE

---

dds/DCPS/transport/shmem/ShmemDataLink.cpp
dds/DCPS/transport/shmem/ShmemDataLink.h
dds/DCPS/transport/shmem/ShmemReceiveStrategy.cpp
dds/DCPS/transport/shmem/ShmemSendStrategy.cpp
dds/DCPS/transport/shmem/ShmemTransport.cpp

Created common shared memory platform macros to reduce redundancy.
Incorporated @jwillemsen's fix for older Android NDKs with newer APIs: #976

Shared Memory Transport Platform Macros

---

tools/scripts/jenkins_packages.sh

Try to fix PR jenkins when running `jenkins_packages.sh` by adding a `apt-get update`.
```
E: Failed to fetch http://security.debian.org/debian-security/pool/updates/main/g/ghostscript/libgs9-common_9.25~dfsg-0+deb9u1_all.deb 404 Not Found [IP: 151.101.44.204 80]
E: Failed to fetch http://security.debian.org/debian-security/pool/updates/main/g/ghostscript/libgs9_9.25~dfsg-0+deb9u1_amd64.deb 404 Not Found [IP: 151.101.44.204 80]
E: Aborting install.
```
Also fail script automatically by adding `set -e`.

Fix Jenkins PR build by adding "apt-get update" to jenkins_packages.sh

---

cmake/init.cmake

To prevent errors with Windows paths

CMake: Use TO_CMAKE_PATH on Paths

---

dds/DdsDcps.mpc
java/dds/dcps_java.mpc

For installed instances, we weren't copying user macros

Make install awareness of user_macros.GNU and improved Java bindings support

---

configure

Problem: configure does not download ACE with curl and --doc_group
The url for the tarball returns a redirect.
Solution: Add -L to curl to make it follow redirects.

configure does not download ACE with curl and --doc_group

---

.dockerignore
Dockerfile
bin/PerlDDS/Run_Test.pm
bin/dcps_tests.lst
tools/repeater/.editorconfig
tools/repeater/.eslintrc.js
tools/repeater/.gitignore
tools/repeater/README.rst
tools/repeater/gcp.js
tools/repeater/package-lock.json
tools/repeater/package.json
tools/repeater/repeater.js
tools/repeater/tests/basic_forward.pl
tools/repeater/tests/client.js
tools/repeater/tests/package-lock.json
tools/repeater/tests/package.json
tools/repeater/tests/receiver.js
tools/repeater/tests/sender.js

We are moving away from non-standard discovery (InfoRepo) and
transports (TCP, UDP, multicast, etc.) and moving toward RTPS
discovery and transport.  RTPS relies on multicast for discovery.
However, many environments, like the cloud and the public internet do
not support multicast.
Solution: Write a multicast to unicast repeater for discovery.  The
repeater runs on each host with a participant and subscribes to the
discovery multicast group.  When it receives a message from the
participant, it forwards it via unicast to other hosts running the
repeater.  When the repeater receives a message via its unicast
socket, it repeats it on the multicast group so the local participants
can receive the message.  The repeater only needs to be used for
participant discovery since SEDP and data …

Multicast repeater tool

---

tools/scripts/gitrelease.pl

- `--micro` causes the script to skip the devguide, doxygen, website,
and creating a new NEWS template. Added command line options for the
former 3.
- If passed X.Y.0, transform it to X.Y to remain uniform with the other
major releases.
- Tweaked the markdown being used for the NEWS template and Github
release.
- Refactored some (but not all) of the duplicate code/info.
- Enabled and attempted to fix website update.
- Fixed AUTHORS verify and added remedy for it.

gitrelease.pl: Support Micro Release, Other Fixes

---

dds/DCPS/RTPS/ParameterListConverter.cpp
dds/DCPS/RTPS/RtpsCore.idl
dds/DCPS/RTPS/Spdp.cpp

Problem: Participant properties do not get sent without security
Solution: Add properties to relevant data structures and the parameter
list converter.

Send participant properties when not using security

---

java/dds/dcps_java.mpc

Similar to previous issue for OpenDDS_DCPS.jar, need to update the class path for these two jar files.

Install/java: Fix classpath for i2jrt.jar and i2jrt_compact.jar in .mpbs

---

NEWS.md
tools/dissector/README.md
tools/dissector/packet-repo.cpp
tools/dissector/plugin.cpp

Wireshark lied in the 3.0 changelog when they said there was no major API changes. I wouldn't call changing the required symbols for all plugins a minor API change...

Updated Dissector for Wireshark 3.0

---

bin/dcps_tests.lst
dds/DCPS/DomainParticipantImpl.cpp
dds/DCPS/RTPS/Sedp.cpp
dds/DCPS/RTPS/Sedp.h
dds/DCPS/RTPS/Spdp.cpp
dds/DCPS/ReactorInterceptor.cpp
dds/DCPS/Service_Participant.cpp
dds/DCPS/transport/framework/TransportRegistry.cpp
dds/DCPS/transport/framework/TransportRegistry.h
dds/DCPS/transport/framework/TransportRegistry.inl
dds/DCPS/transport/rtps_udp/RtpsUdpLoader.cpp
dds/DCPS/transport/rtps_udp/RtpsUdpLoader.h
java/tests/hello/conditional_idlflags.mpb
java/tests/hello/hello_java_client.mpc
tests/DCPS/Restart/.gitignore
tests/DCPS/Restart/Messenger.idl
tests/DCPS/Restart/RestartTest.cpp
tests/DCPS/Restart/RestartTest.mpc
tests/DCPS/Restart/run_test.pl

Related to #1005 and possibly #991 
- Support restarting the same Service_Participant object after shutdown() 
- Updated RtpsUdpLoader to have an easy way to reload the transport (from application)
- Sedp: remove transport when we're done 
- TransportRegistry::remove_inst() calls shutdown on the transport

Service Participant, Transport Registry, RTPS libs updated to support certain Restart scenarios

---

configure

For @neeleym,
I'm still not really sure how this became broken on Ubuntu, but apparently it did. I'm thinking maybe it became broken when I worked having it work with Qt from vckpg.

configure: Fix Building with Qt on Ubuntu

---

about/articles/Article-Intro.html

Broken:
OMG Data Distribution Service (DDS) for Real-Time Systems (http://www.omg.org/docs/formal/07-05-02)
OMG "Introduction to DDS" Whitepaper (http://www.omg.org/news/whitepapers/Intro_To_DDS.pdf)
First link moved to DDS Spec page.
Broken link to Introduction to DDS is now to the OMG DDS Portal that has all of the introductory material.
Also fixed the MPC link to the Object Computing GitHub page for MPC.

Correct broken links in About-Intro.html

---

Dockerfile
README.md
configure
docs/android.md
tools/dissector/README.md

Replace underscore with dashes/minuses in `--doc_group` and
`--wireshark_*` options in the configure script. Updated any mention of
these arguments I could find that. The old options are still valid via
an alias map that processes the arguments before argument parsing.
Also fixed some typos in the Wireshark configure logic.

configure: s/_/-/g in options

---

dds/DCPS/DataSampleHeader.cpp
dds/DCPS/DisjointSequence.cpp
dds/DCPS/transport/framework/TransportReassembly.cpp
tests/DCPS/UnitTests/DisjointSequence.cpp
tests/DCPS/UnitTests/SequenceNumber.cpp
tests/DCPS/UnitTests/run_test.pl
tests/DCPS/common/TestSupport.h

It turns out that $(DDS_ROOT)/tests/DCPS/UnitTests/run_test.pl had a bug in it which prevented it from running any of the unit tests in that directory (despite printing their names and printing "test PASSED"). The tests now run and several bugs that would have been caught have now been caught and fixed. In addition, a few vaguely-related valgrind issues have been caught and cleaned up, as these were the motivating reason behind revisiting the unit tests.

Unit tests and valgrind issues cleanup

---

dds/DCPS/DataReaderImpl.cpp
dds/DCPS/DataReaderImpl.h
dds/DCPS/unique_ptr.h

Changes needed to avoid linking errors when compiling with C++/CLI.
Related Issue: #962

Visual Studio /clr leads to linking errors

---

dds/DCPS/RTPS/Sedp.h
dds/DCPS/transport/framework/DataLink.cpp

Fixing a deadlock issue encountered when datalink.cpp tries to call default listener while holding pub_sub_maps_lock_ mutex and encounters a full sedp task queue

Fixing a deadlock issue encountered under heavy discovery load

---

dds/DCPS/RTPS/Sedp.h
dds/DCPS/Service_Participant.cpp
dds/DCPS/security/AccessControlBuiltInImpl.cpp
dds/DCPS/security/AccessControlBuiltInImpl.h

Fixing leak in SEDP's Task MQ allocation (caused by previous pull request to increase MQ size to help alleviate deadlock issues), and also a singleton "leak" from SecurityRegistry.

Security Registry and cleanup

---

dds/DCPS/GuidUtils.h
dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp

Also includes cleanup for a few double-lookup situations in RtpsUdpDataLink where it was using both std::map::count() followed by std::map::operator[] instead of just using find().

Improve GUID lookup / comparison performance

---

dds/DCPS/DomainParticipantImpl.cpp

When using the monitor GUI a segmentation fault was occurring.  It was determined that the monitor's report functions were being called before a GUID was assigned in the DomainParticipantImpl::enable() function.  The calls were moved so that they did not execute until after a value GUID was obtained.

Issue 1100: Domain Participant interaction with Monitoring library

---

dds/DCPS/RTPS/ICE/EndpointManager.cpp
dds/DCPS/RTPS/ICE/Stun.cpp
dds/DCPS/RTPS/ICE/Stun.h

Problem: ICE code contains C++11 features and name lookup problems
Solution:  Rewrite to avoid compiler problems and warnings.

Fix build problems due to ICE code

---

configure

Fix for #1110.
Instead of relying on using regex on the version message, which might fail in at least one major localization (#1110) or future versions (#922).
Also fixes the final message for VS users to tell them how they can open the sln file right then and there.

configure: Detect MSVC Version Using C Macro

---

configure

Currently when there are multiple runs of configure, old setenv and other scripts are saved as what the current PID is.
The problem is, PIDs may not be predictable and as an average developer, I want to know exactly when my setenv was modified.
An alternative is to do a `ls -ltra ./setenv*`, but this way is cleaner and avoids any possible confusion. The date format chosen is based on ISO 8601, although the time aspect is modified to avoid having a ':' in the filename

Modified the configure script so subsequent runs are easier to identify

---

MPC/modules/IDLBase.pm

Provide a more accurate representation of dependencies if the version of MPC is 4.1.42 or higher.  We need the ProjectCreator in order to create .class file names from the .java files that we have based on forward declarations.

Provide a more accurate representation of dependencies

---

MPC/modules/IDLBase.pm
dds/DCPS/RTPS/ICE/Checklist.cpp
dds/DCPS/RTPS/ICE/Stun.cpp
dds/DCPS/RTPS/ParameterListConverter.cpp
dds/DCPS/RTPS/Spdp.cpp
dds/DCPS/StaticDiscovery.cpp
dds/DCPS/ZeroCopyAllocator_T.inl
dds/DCPS/security/UtilityImpl.cpp
dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp
java/dds/dcps_java_optional.mpb
performance-tests/DCPS/InfoRepo_population/SyncServer.cpp
performance-tests/DCPS/Sync/SyncServer.cpp
tests/DCPS/ContentFilteredTopic/ContentFilteredTopicTest.cpp
tests/DCPS/LivelinessTimeout/publisher.cpp
tests/DCPS/LivelinessTimeout/subscriber.cpp
tests/security/AccessControlTest.cpp
tests/security/Authentication/AuthenticationTest.cpp
tests/security/Authentication/LocalCredentialDataTest.cpp
tests/security/IDL_Serialization/PropertyTest.cpp
tests/security/RTPS/ParameterListConverterTest.cpp
tests/security/SSL/PrivateKeyTest.cpp
tests/security/SSL/SignedDocumentTest.cpp

Change type or use static_cast where necessary to address 64-bit build warnings.
Additional changes include replacing std::auto_ptr with std::unique_ptr.

Build Warnings

---

.gitignore
configure
dds/idl/be_produce.cpp
docs/android.md
java/idl2jni/codegen/be_global.cpp
java/idl2jni/codegen/be_produce.cpp
java/idl2jni/codegen/im_java.cpp
java/idl2jni/codegen/im_jni.cpp

- Update configure script and `android.md` for #1136 and #1137 
- Fix segfault in `i2jrt_codegen` and `opendds_idl` when no arguments are passed.
- Update `i2jrt_codegen` argument handing to match `opendds_idl`.
- Added `--host-tools-only` option to configure script that just builds the host tools.
- Fix compilation warnings in `idl2jni_codegen` by removing empty `default` cases.

Updates for Android

---

dds/DCPS/transport/rtps_udp/RtpsUdpReceiveStrategy.cpp

Initialized the numBits value before passing it to the get_gaps function.

Resolve Access Violations caused by uninitialized data

---

dds/DCPS/DataReaderImpl.cpp
dds/DCPS/SubscriberImpl.cpp
tests/DCPS/GroupPresentation/DataReaderListener.cpp
tests/DCPS/Presentation/main.cpp
tests/DCPS/ReadCondition/ReadConditionTest.cpp
tests/DCPS/ZeroCopyRead/main.cpp

Link: #1094
- Fixed leak in presentation test.
- Changed some of the errors in delete_datareader to be warnings for ZeroCopyRead and Readcondition tests which cause errors on purpose.
- Fix Instance Group Presentation test by allowing group coherent sets by instance to be accepted again.

Fixes for Bugs Introduced in 1094

---

dds/DCPS/DiscoveryBase.h
dds/DCPS/RTPS/ParameterListConverter.cpp
dds/DCPS/RTPS/RtpsCore.idl
dds/DCPS/RTPS/Sedp.cpp
dds/DCPS/RTPS/Sedp.h
dds/DCPS/RTPS/Spdp.cpp
dds/DCPS/RTPS/Spdp.h
dds/DCPS/StaticDiscovery.cpp
dds/DCPS/StaticDiscovery.h

This patch will safely remove the poorly-scaling vendor-specific extension for datareader announcements by adding new vendor-specific extension (OpenDDS Participant Flags) to participant announcements. The first (and only, so far) flag will indicate that incoming datareader annoucements are not expected to contain associated datawriters, allowing instances of OpenDDS that recognize this flag to refrain from sending these associations for/to this participant and its datawriters.

Backwards-Compatible Removal of "Associated Writers" from SEDP Datareader Announcements

---

dds/DCPS/DataReaderCallbacks.h
dds/DCPS/DataReaderImpl.cpp
dds/DCPS/DataReaderImpl.h
dds/DCPS/DataWriterCallbacks.h
dds/DCPS/DataWriterImpl.cpp
dds/DCPS/DataWriterImpl.h
dds/DCPS/Discovery.h
dds/DCPS/DiscoveryBase.h
dds/DCPS/DomainParticipantImpl.cpp
dds/DCPS/DomainParticipantImpl.h
dds/DCPS/InfoRepoDiscovery/InfoRepoDiscovery.cpp
dds/DCPS/InfoRepoDiscovery/InfoRepoDiscovery.h
dds/DCPS/RTPS/Sedp.cpp
dds/DCPS/RTPS/Sedp.h
dds/DCPS/RecorderImpl.cpp
dds/DCPS/RecorderImpl.h
dds/DCPS/ReplayerImpl.cpp
dds/DCPS/ReplayerImpl.h
dds/DCPS/TopicCallbacks.h
dds/DCPS/TopicDetails.h
dds/DCPS/TopicImpl.cpp
dds/DCPS/TopicImpl.h
tests/DCPS/DCPSInfoRepo/DCPSDataReaderI.h
tests/DCPS/DCPSInfoRepo/DCPSDataWriterI.h
tests/DCPS/DCPSInfoRepo/pubsub.cpp
tests/DCPS/InconsistentTopic/pubsub.cpp

Problem: Inconsistent topic only discovered with local reader/writer
A participant can only get inconconsistent topic when it has a local
reader or writer on that topic.  While usual, a participant should be
able to create a topic and then get inconsistent topic on it without
creating readers and writers.  This also lead to a race condition in
earlier versions of the InconsistentTopic test which made it fail
sporadically.  This is a fix for #995.
Solution: Track local and remote topics and link the local topic to
its impl through callbacks so that inconsistent topic can be reported
without a reader or writer.

Fix inconsistent topic test

---

dds/DCPS/RTPS/BaseMessageTypes.h
dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp
tools/rtpsrelay/RelayHandler.cpp
tools/rtpsrelay/RelayHandler.h

The beacon message size was increased to be 4 bytes.  The content of the message
is just zeriozed data.

Increase size of the RTPS relay beacon message

---

dds/DCPS/DataReaderImpl.cpp
dds/DCPS/DataWriterImpl.cpp
tools/modeling/tests/MessengerDpQos/publisher.cpp
tools/modeling/tests/MessengerPubQos/publisher.cpp
tools/modeling/tests/SubscriberQos/publisher.cpp
tools/modeling/tests/SubscriberQos/subscriber.cpp

Problem: Data(Reader|Writer)Impl don't check that topic is enabled
Solution: Return PRECONDITION_NOT_MET if the topic is not enabled.

Check that a topic is enabled when enabling data writer/reader

---

MPC/config/dcps.mpb
MPC/config/dcps_no_idl.mpb
MPC/config/dcps_optional_bidir_giop.mpb
MPC/config/dcps_optional_features.mpb
MPC/config/dds_any_support.mpb
MPC/config/dds_suppress_any_support.mpb

Pull all non-IDL related settings from dcps and inherited base projects into a separate set of base projects to allow for linking in OpenDDS without defining IDL compilation rules.

Pull all non-IDL related settings from dcps

---

dds/DCPS/RTPS/Spdp.cpp
dds/DCPS/ReactorTask.cpp
dds/DCPS/ReactorTask.h

InfoRepo has a static initializer which results in the construction of
a reactor.  This must be preceded by a call to ACE::init().
To fix this, we delay the creation of the reactor to the open method
of the ReactorTask.

InfoRepo does not start correctly on Windows

---

bin/dcps_tests.lst
tests/DCPS/Monitor/run_test.pl

A recent change removed some instances where samples of some Monitor
topics were being sent twice.  The passing threshold was lowered to account for
this.  The Monitor test was also added to the list of tests to run.

Fix pass/fail criteria for the Monitor test

---

dds/DCPS/RTPS/Sedp.cpp

Sedp sends unregister dispose in the clear
Solution: Check the security settings and use the secure writer when necessary.

Secure endpoint discovery dispose/unregister messages

---

dds/DCPS/RTPS/Sedp.cpp
dds/DCPS/RTPS/Sedp.h

Sedp writes unsecure data on association complete
Solution: A secure/unsecure SEDP writer should only write local
publications/subscriptions that are secure/unsecure.

Secure SEDP association_complete

---

bin/dcps_tests.lst
tests/DCPS/Monitor/Messenger.mpc

The monitor test has been disabled for configurations with no built-in-topics
and the safety profile.  The test will not be built in these configurations.

Disable Monitor tests for some configurations

---

dds/DCPS/ReactorTask.cpp

A ReactorTask is an ACE::Task_Base which caches a references to its
Thread_Manager.  If the Service_Participant is shutdown and ACE is
restarted (ACE::fini, ACE::init), then this reference is stale and
shows up as an access violation in the Restart test.
Solution: Reset the reference when the ReactorTask is stop so that it
will use the correct Thread_Mananger when restarted.

Reactor task in Service Participant has stale reference

---

dds/DCPS/DiscoveryBase.h

Follow-on to #1227 to make it work when security is enabled in the build but not at runtime.

Use LocalEndpoint to store endpoint security attribs, init them

---

tests/DCPS/ReadCondition/.gitignore
tests/DCPS/ReadCondition/Messenger.idl
tests/DCPS/ReadCondition/ReadCondition.mpc
tests/DCPS/ReadCondition/ReadConditionTest.cpp
tests/DCPS/ReadCondition/run_test.pl

This test is designed to show how to use the code generators differently.

ReadCondition test: restored to its state before consolidating messenger IDL

---

dds/DCPS/GroupRakeData.cpp
dds/DCPS/InstanceState.cpp
dds/DCPS/InstanceState.h
dds/DCPS/InstanceState.inl

switching InstanceState::reader_ from DataReaderImpl* to WeakRcHandle<DataReaderImpl> to avoid invalid reads when checking ownership, etc

switching InstanceState::reader_ from DataReaderImpl* to WeakRcHandle

---

dds/DCPS/DataReaderImpl.cpp
dds/DCPS/DataReaderImpl.h
dds/DCPS/InstanceState.cpp
dds/DCPS/RTPS/ICE/AgentImpl.cpp
dds/DCPS/ReactorInterceptor.cpp
dds/DCPS/ReactorInterceptor.h
dds/DCPS/RecorderImpl.cpp
dds/DCPS/RemoveAssociationSweeper.h
dds/DCPS/Watchdog.cpp
dds/DCPS/transport/framework/DataLink.cpp
dds/DCPS/transport/framework/DataLinkWatchdog_T.h
dds/DCPS/transport/framework/TransportClient.cpp
dds/DCPS/transport/framework/TransportClient.h
dds/DCPS/transport/multicast/MulticastSession.cpp
dds/DCPS/transport/multicast/ReliableSession.cpp
dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.h

To support a straight enqueue while processing commands in the
ReactorInterceptor, it was necessary to release the queue lock before
each command was executed.  This broke the existing semantics of wait
because the following sequence was possible:
Non-reactor thread: execute_or_enqueue (command is placed on the
queue)
Reactor thread: command is take off the queue but not executed yet
Non-reactor thread: wait (returns immediately since the queue is
empty)
... wait returned without the command being executed ...
Solution: enqueue and execute_or_enqueue return a Command with a wait
method.  A thread can use this wait on a specify command to complete.
The ReactorInterceptor signals the Command to unblock any waiting thread.

ReactorInterceptor wait is broken

---

dds/DCPS/DiscoveryBase.h

This is handled in every other place, but not here. It prevented me from building on Windows.

[3.13] Only include DDS Security member when OPENDDS_SECURITY is set

---

docs/dependencies.md

'FindPacakge'  changed to 'FindPackage'

Minor typo in CMake documentation

---

dds/DCPS/SubscriberImpl.cpp
tests/DCPS/QueryCondition/QueryConditionTest.cpp

Delete DR Listeners in `run_complex_filtering_test` before cleanup to try to fix occasional failures on the scoreboard.

Fix for Occasional QueryCondition Test Failure

---

dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp

Not sure why this was just copying the prefix, but it needs to be the whole guid in order for build_meta_submessage_map to pull the right destination addresses.

fixing durability directed gap destinations

---

cmake/OpenDDSConfig.cmake

Fix for Cmake changes in #1256

cmake: link to iphlpapi without check on windows

---

dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp

There was already a stubbed writer RCH here, not sure why we weren't using it...
Grab a full RCH to RtpsWriter before releasing Datalink's lock in order to prevent deletion while we're attempting to call customize_queue_element_helper.

Fix gcc asan issue in RtpsUdpDatalink's customize_queue_element

---

dds/DCPS/transport/framework/TransportSendBuffer.cpp
dds/DCPS/transport/framework/TransportSendBuffer.h
dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp
dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.h

Issue: Discovered a deadlock scenario in the WaitForAck tests that results from a user thread sending data and the reactor thread resending data in response to a NACK within a very tight (but possible) window.
Solution: Split the locking inside RtpsWriter apart and protect elems_not_acked_ separately from the rest of RtpsWriter's members.  In addition, add thread safety mechanisms to SingleSendBuffer to protect against multithreaded access (same two sources) in order to avoid potential corruption / segfaults.

Improve locking around RtpsWriter's usage of SingleSendBuffer

---

dds/DCPS/Service_Participant.cpp

Fixing gccasan issue for invalid use after free of global const ACE_CString object by changing to const char[]. The service participant object needs to have/return an ACE_CString, but there's no need for the default global variable used in initialization to be one. The issue seems to happen when ServiceParticipant instance() is re-created as part of another global/static object's shutdown process, which may be its own issue that needs to be addressed at some point.

Fixing gccasan issue for invalid use after free

---

dds/DCPS/ReactorInterceptor.cpp
dds/DCPS/transport/shmem/ShmemDataLink.cpp
dds/DCPS/transport/shmem/ShmemDataLink.h
dds/DCPS/transport/shmem/ShmemReceiveStrategy.cpp
dds/DCPS/transport/shmem/ShmemReceiveStrategy.h
dds/DCPS/transport/shmem/ShmemSendStrategy.cpp
dds/DCPS/transport/shmem/ShmemTransport.cpp
dds/DCPS/transport/shmem/ShmemTransport.h
tests/DCPS/SharedTransport/shmem.ini

Primary Issue: We can't be sure of publisher write speed vs reader read speed and the shmem transport doesn't have backpressure, so the shared memory segment needs to be able to hold the entire 100 messages or there's always the potential that the writer will fill the segment. A better solution would be to implement real checks for backpressure, but is beyond the scope of this change.
Solution: Increase test memory segment to accommodate 100 messages.
Secondary Issue: Occasional SEGV due to reads during shutdown. Introduce locking around shutdown and allocator acquisition, and introduce additional checks in send and receive strategies after they've grabbed a pointer to the allocator. We will eventually want to migrate this to use RCH rather than straight pointers in case it gets deleted …

Fix Intermittent SharedTransport Shmem Test Failures

---

dds/DCPS/RTPS/Spdp.cpp

Changed destination_endpoint_guid values to GUID_UNKNOWN when creating or replying to GMCLASSID_SECURITY_AUTH_HANDSHAKE (see 7.4.3.6.1)

Destination endpoint GUID Values corrected per the DDS Security specification

---

dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp
dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.h
tests/DCPS/SetQosPartition/publisher.cpp

Discovered SEGV issues due to concurrent access of the receive strategy during send_final_acks() and shutdown. Protect interactions with RtpsUdpDataLink::receive_strategy_ by locking the strategy_lock_ (which is already locked during shutdown).

Resolve SetQosPartition Errors

---

tests/DCPS/MultiTopic/MultiTopicTest.cpp

Issue: MultiTopic datareaders create individual datareaders based on the default topic qos for their constituent topics. Since the topic qos was not specified, it resorted to best effort, meaning that the waits for publications matched were not guaranteed to work.
Solution, set the topic qos for the constituent topics to reliable.

fixing topic reliability for multitopic test

---

dds/DCPS/RTPS/Sedp.cpp

This is confusing / inaccurate and it doesn't look like we rely on it for anything. When SEDP multicast is on, the correct multicast address is already correctly added to the list of multicast locators. If we "need" this behavior for some reason, we should fix whatever isn't working correctly instead of relying on this.

Remove Multicast Address from SPDP List of Unicast Locators

---

dds/DCPS/RcObject.h

Export RcObject symbol in order to facilitate WeakRcHandle::lock()'s dynamic_cast (needs typeinfo).

Export RcObject's Symbols

---

dds/DCPS/Service_Participant.cpp
dds/DCPS/Service_Participant.h

One of two changes I'm bringing over from bench.
It lets someone set a default for `DCPSConfigFile` that will be used if `-DCPSConfigFile` was not passed to `TheParticipantFactoryWithArgs` or if `TheParticipantFactory` was called. Of course this means it must be called before `TheParticipantFactory(WithArgs)`. If this is not used at all, then OpenDDS will initialize normally.
Here is an example of how I'm using it in the bench test controller application:
```C++
TheServiceParticipant->default_configuration_file(
ACE_TEXT_CHAR_TO_TCHAR(join_path(bench_root, "control_opendds_config.ini").c_str()));
```

Support setting a default Configuration File

---

dds/idl/marshal_generator.cpp
tests/DCPS/Compiler/annotations/topic_annotations_test_lib/topic_annotations_test.idl
tests/DCPS/Compiler/annotations/topic_annotations_test_main/main.cpp
tests/DCPS/Compiler/idl_test_nested_types_lib/NestedTypesTest.idl

This was the other change I made in bench that I wanted to bring over. It allows typedefs of structs to be keys. The problem is that it doesn't seem to be a problem with annotations, only pragmas, but I added a annotation test anyway.

Using Typedefs of Structs as Keys

---

dds/DCPS/RTPS/BaseMessageUtils.cpp
dds/DCPS/RTPS/RtpsDiscovery.h
dds/DCPS/RTPS/Sedp.cpp
dds/DCPS/RTPS/Spdp.cpp
dds/DCPS/RTPS/Spdp.h
tools/rtpsrelay/RtpsRelay.cpp

This allows the application participant in the RtpsRelay to not send heartbeats and other writer messages.

Add option for disabling builtin SEDP writers

---

dds/DCPS/DiscoveryBase.h
dds/DCPS/JobQueue.h
dds/DCPS/PeriodicTask.h
dds/DCPS/RTPS/RtpsDiscovery.cpp
dds/DCPS/RTPS/RtpsDiscovery.h
dds/DCPS/RTPS/Sedp.cpp
dds/DCPS/RTPS/Sedp.h
dds/DCPS/RTPS/Spdp.cpp
dds/DCPS/RTPS/Spdp.h
dds/DCPS/ReactorInterceptor.h
dds/DCPS/ReactorTask.cpp
dds/DCPS/ReactorTask.h
dds/DCPS/SporadicTask.h
dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp
dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.h
dds/DCPS/transport/rtps_udp/RtpsUdpInst.cpp
dds/DCPS/transport/rtps_udp/RtpsUdpInst.h
tools/rtpsrelay/RelayHandler.cpp
tools/rtpsrelay/RelayHandler.h
tools/rtpsrelay/RtpsRelay.cpp

* Add INFO_DST to SPDP messages that are sent in response to
discovered a new participant.  This allows the RtpsRelay to only
forward the SPDP message to the intended destination.
* Both SPDP and RTPS transports send a beacon to the RtpsRelay.  The
period of the beacon is configurable.  The beacon is sent
unconditionally.
* Polling was converted to events in SPDP to handle authentication
timeouts and resends.
* Three helper classes:
* JobQueue - allows a thread to post a job on a Reactor.
* PeriodicTask - a wrapper for periodic tasks.
* SporadicTask - a wrapper for sporadic (one-shot) tasks.
* ReactorTask has an implicit ReactorInterceptor.
As an aside, the JobQueue was motivated by a deadlock where a
ReactorInterceptor command acquired a lock so that a subsequenct
execute_or_enqueue was …

SPDP improvements for the RtpsRelay

---

tests/DCPS/RtpsRelay/Unit/main.cpp
tools/rtpsrelay/AssociationTable.cpp
tools/rtpsrelay/AssociationTable.h
tools/rtpsrelay/PublicationListener.cpp
tools/rtpsrelay/PublicationListener.h
tools/rtpsrelay/ReaderListener.cpp
tools/rtpsrelay/RelayHandler.cpp
tools/rtpsrelay/RelayHandler.h
tools/rtpsrelay/RtpsRelay.cpp
tools/rtpsrelay/SubscriptionListener.cpp
tools/rtpsrelay/SubscriptionListener.h
tools/rtpsrelay/WriterListener.cpp
tools/rtpsrelay/lib/QosIndex.cpp
tools/rtpsrelay/lib/QosIndex.h
tools/rtpsrelay/lib/Relay.idl

Previously, the relay addresses were bundled with the reader and
writer entries.  Suppose there are two relays A and B and a client
connects to A, switches to B, and then switches back to A before the
participant lease duration.  This causes A to write entries for the
participant and then B will write entries for the participant.
However, the client is associated with A but the topic says it should
be associated with B.
To solve this problem, remove the relay addresses from the reader and
writer entries and create a new topic for participant to relay
pairings (Responsible Relay).  The relays maintain the Responsible
Relay topic based on the traffic that they are observing.  The Reader
and Writer entries are just for matching.
For this change, we had to remove the local/remote distinction …

RtpsRelay:  Relay addresses not updated when client changes servers

---

dds/DCPS/RTPS/Sedp.cpp
dds/DCPS/RTPS/Spdp.cpp
dds/DCPS/RTPS/Spdp.h

When security is enabled for a participant, only include the ICE agent
info in the secure SPDP messages.

ICE Agent Info exchanged in the clear when security is enabled

---

dds/DCPS/DataReaderImpl.cpp
dds/DCPS/DataReaderImpl_T.h
dds/DCPS/DataSampleHeader.cpp
dds/DCPS/DataSampleHeader.h
dds/DCPS/DataWriterImpl.cpp
dds/DCPS/DataWriterImpl_T.h
dds/DCPS/InstanceState.cpp
dds/DCPS/InstanceState.h
dds/DCPS/InstanceState.inl
dds/DCPS/RTPS/Sedp.cpp
dds/DCPS/RTPS/Sedp.h
dds/DCPS/SafetyProfileStreams.cpp
dds/DCPS/SafetyProfileStreams.h
dds/DCPS/SubscriberImpl.cpp
dds/DCPS/WriterInfo.cpp
dds/DCPS/WriterInfo.h
dds/DCPS/security/CommonUtilities.cpp
dds/DCPS/security/CommonUtilities.h
dds/DCPS/security/CryptoBuiltInImpl.cpp
dds/DCPS/transport/tcp/TcpConnection.cpp
dds/DCPS/transport/tcp/TcpConnection.h
tests/DCPS/GroupPresentation/DataReaderListener.cpp
tests/DCPS/Presentation/main.cpp
tests/DCPS/UnionTopic/UnionTopic.cpp
tests/DCPS/ViewState/main.cpp
tests/DCPS/ZeroCopyRead/main.cpp

- Normalize these enum-like value to string functions, by making them return `const char *` instead of `OPENDDS_STRING` (Fix for https://github.com/objectcomputing/OpenDDS/issues/1188) and having them behave the same when an invalid value is passed:
- `DataSampleHeader.cpp`:
- `to_string(MessageId)`
- `to_string(SubMessageId)`
- `InstanceState.cpp`:
- `InstanceState::instance_state_string(DDS::InstanceStateKind)`
- `InstanceState::instance_state_string()`
- `Sedp.cpp`:
- `Sedp::Msg::msgTypeToString(MsgType)`
- `Sedp::Msg::msgTypeToString()`
- `SafetyProfileStreams.cpp`:
- `retcode_to_string(DDS::ReturnCode_t)`
- `WriterInfo.cpp`:
- `WriterInfo::get_state_str()`
- `security/CommonUtilities.cpp`:
- `ctk_to_dds_string(const CryptoTransformKind&)`
- `transport/tcp/TcpConnection.cpp`:
- …

Normalize Enum-like Values to String Functions

---

.travis.yml
DevGuideExamples/DCPS/Messenger/.gitignore
DevGuideExamples/DCPS/Messenger/CMakeLists.txt
DevGuideExamples/DCPS/Messenger/DataReaderListenerImpl.cpp
DevGuideExamples/DCPS/Messenger/Messenger.mpc
DevGuideExamples/DCPS/Messenger/Publisher.cpp
DevGuideExamples/DCPS/Messenger/README.md
DevGuideExamples/DCPS/Messenger/Subscriber.cpp
DevGuideExamples/DCPS/Messenger/rtps.ini
DevGuideExamples/DCPS/Messenger/run_test.pl
Dockerfile
INSTALL.md
README.md
appveyor.yml
azure-pipelines.yml
bin/dcps_short_tests.lst
bin/dcps_tests.lst
configure
docs/android.md
docs/dependencies.md
docs/guidelines.md

Also added bits to make it easier to run `DevGuideExamples/DCPS/Messenger` in RTPS mode so the user can run RTPS with no tests and added an example `CMakeLists.txt`.

Make "--no-tests" the Default in the Configure Script

---

dds/DCPS/DataWriterImpl_T.h
tests/DCPS/Rejects/run_test.pl

It looks like Rejects is supposed to give this error, but it's failing on the scoreboard because I slightly changed the message in #1371.

Fix Rejects Test

---

dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp
dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.h

Same idea as #1382 but this time in the transport lib

RtpsUdpDataLink: avoid local classes since they can't be template arguments

---

dds/DCPS/LinuxNetworkConfigMonitor.cpp
dds/DCPS/LinuxNetworkConfigMonitor.h
dds/DCPS/RTPS/GuidGenerator.cpp
dds/DCPS/Service_Participant.cpp

Enable using `LinuxNetworkConfigMonitor` from #1365 on Android. Should have thought of this before, but it slipped my mind that `ACE_LINUX` doesn't get defined on Android.
Being built on OpenDDS-Android here: https://travis-ci.org/iguessthislldo/OpenDDS-Android/builds/615397160

Enable LinuxNetworkConfigMonitor on Android

---

tests/cmake_integration/CMakeLists.txt
tests/cmake_integration/Messenger/CMakeLists.txt
tests/cmake_integration/Messenger/Messenger_1/CMakeLists.txt
tests/cmake_integration/Messenger/Messenger_2/CMakeLists.txt

This will make it much easier to change the cmake tests because right now they are hardcoded on the scoreboard for each build. The downside to is it requires unique target names in each project, but that's not different from MPC. The alternative method I also explored was using [`ExternalProject_Add`](https://cmake.org/cmake/help/latest/module/ExternalProject.html), which I started [here](https://github.com/objectcomputing/OpenDDS/compare/master...iguessthislldo:igtd/cmake_tests_external_project). I would like to go with this one though because it seems like dealing with `ExternalProject_Add` is probably a bigger pain than making sure the target names are unique.

Add Master CMakeLists.txt for CMake Tests

---

MPC/config/dcps_ts_defaults.mpb
MPC/modules/IDLBase.pm
NEWS.md
dds/idl/annotations.h
dds/idl/be_global.cpp
dds/idl/be_global.h
dds/idl/be_util.cpp
dds/idl/dds_visitor.cpp
dds/idl/dds_visitor.h
docs/migrating_to_topic_type_annotations.md
tests/DCPS/Compiler/is_topic_type/.gitignore
tests/DCPS/Compiler/is_topic_type/README.md
tests/DCPS/Compiler/is_topic_type/no_dn/is_topic_type_no_dn.mpc
tests/DCPS/Compiler/is_topic_type/run_test.pl
tools/modeling/plugins/org.opendds.modeling.sdk.model/xsl/mpc.xsl

- Made root default nested behavior like the traditional behavior or `--default-nested` is now the default.
- Use the term "topic type annotations" instead of "topic annotations" to try to avoid giving the impression that only the `@topic` annotation is the only thing being talked about or it's the only annotation that should be used.
- Warn when structs that are declared to be topic types using both `DCPS_DATA_TYPE` and the new topic type system have inconsistent keys between the two systems.
- Suppress DCPS_DATA_TYPE warnings in generated modeling IDL.

Improvements for Topic Type Annotations

---

bin/dcps_tests.lst
configure
dds/DCPS/DomainParticipantFactoryImpl.cpp
dds/DCPS/DomainParticipantFactoryImpl.h
dds/DCPS/TopicDetails.h
dds/DCPS/WriteDataContainer.cpp
dds/DCPS/WriteDataContainer.h
dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp
dds/DCPS/transport/rtps_udp/RtpsUdpReceiveStrategy.cpp
tests/DCPS/Deadline/subscriber.cpp
tests/DCPS/FooTest5/publisher.cpp
tests/DCPS/LargeSample/Writer.cpp
tests/DCPS/ManyToMany/Writer.cpp
tests/DCPS/ManyTopicMultiProcess/Writer.cpp
tests/DCPS/ManyTopicTest/Writer.cpp
tests/DCPS/ManyTopicTest/Writer.h
tests/DCPS/Rejects/subscriber.cpp
tests/DCPS/RtpsDiscovery/RtpsDiscoveryTest.cpp
tests/DCPS/SetQosPartition/publisher.cpp
tests/DCPS/SetQosPartition/subscriber.cpp
tests/DCPS/TcpReconnect/publisher.cpp
tests/DCPS/Thrasher/DataReaderListenerImpl.cpp
tests/DCPS/Thrasher/DataReaderListenerImpl.h
tests/DCPS/Thrasher/ParticipantTask.cpp
tests/DCPS/Thrasher/ParticipantTask.h
tests/DCPS/Thrasher/Subscriber.cpp
tests/DCPS/Thrasher/run_test.pl
tests/DCPS/Thrasher/thrasher_rtps.ini
tests/Utils/StatusMatching.h

On the DDS Build Scoreboard I noticed a stack trace pointing to a corrupted free in DomainParticipantFactoryImpl::delete_participant's use of Util::remove() and it looks like we're not correctly using the participants_protector_ mutex in this instance. Fixed this, added locking / copying around another accessor of the same data structure (internals are RcHandles), and migrated to a non-recursive mutex because it didn't look like we needed one.

Add Thrasher Test for rtps_udp transport, Fix WaitForAck & Durability Issues It Exposed

---

dds/DCPS/RTPS/RtpsDiscovery.cpp
dds/DCPS/transport/rtps_udp/RtpsUdpInst.cpp

Solution: Check for DCPSSecurity whenever UseIce is active.

OpenDDS crashes when UseIce=1 but DCPSSecurity=0

---

azure-pipelines.yml
dds/InfoRepo/DCPSInfoRepo.mpc
java/dds/dcps_java.mpc
java/idl2jni/codegen/idl2jni_codegen.mpc
java/idl2jni/corba/idl2jni_corba.mpc
java/idl2jni/runtime/idl2jni_runtime.mpc
java/tao/tao_java.mpc

The last build of #1429 was actually a failure for the Linux Release build, but I have no idea why. I'm also adding `set -e` to the scripts in the Linux builds to make them fail on non-zero exit statuses.

Make install with DESTDIR (for Java bindings)

---

dds/DCPS/Definitions.h
dds/DCPS/DomainParticipantImpl.cpp

This PR removes two macros to avoid naming conflicts with other libraries as explained in this issue: #1433

Remove macros: DUP and NO_DUP to avoid naming conflicts.

---

dds/DCPS/transport/rtps_udp/RtpsUdpInst.cpp

Though we should probably limit this per RtpsWriters based on DataWriter resource limits QoS.

Revert default rtps_udp nak_depth to zero (infinite) to prevent lost data for reliable connections

---

dds/DCPS/RTPS/Sedp.cpp
dds/DCPS/RTPS/Spdp.cpp

Solution: Use the correct check for to_param_list.  Also, make style
of to_param_list consistent.

Sedp::Writer::write_dcps_participant_secure has inverted condition

---

Dockerfile
hooks/build

Use `ACE_CONFIG_OPTION` and `ACE_SOURCE_DIR` options to pick difference ACE source.
`ACE_CONFIG_OPTION` can be used to select `--ace-github-latest` instead of the default `--doc-group`.
`ACE_SOURCE_DIR` copies the correct files based on the ACE source to `/usr/local/share/ace/MPC`. Defaults to `/opt/OpenDDS/ACE_wrappers/MPC`. Use `/opt/OpenDDS/ACE_TAO/ACE/MPC` when using `--ace-github-latest` in `ACE_CONFIG_OPTION`.

Docker build: optional ACE source

---

dds/DCPS/transport/framework/DataLink.h
dds/DCPS/transport/framework/DataLink.inl
dds/DCPS/transport/framework/DataLinkSet.h
dds/DCPS/transport/framework/DataLinkSet.inl
dds/DCPS/transport/framework/TransportSendBuffer.cpp
dds/DCPS/transport/framework/TransportSendBuffer.h
dds/DCPS/transport/framework/TransportSendStrategy.cpp
dds/DCPS/transport/framework/TransportSendStrategy.h
dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp
dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.h
dds/DCPS/transport/rtps_udp/RtpsUdpSendStrategy.cpp
dds/DCPS/transport/rtps_udp/RtpsUdpSendStrategy.h

Primary issue was that packet removal was violating the datalink (e.g. writer) / send-strategy locking order requirement. Secondary issue included the fact that the code path for removal bounced back and forth between the strategy and datalink (including send buffer) several times.
This solution overrides datalink framework methods so they can be implemented in rtps writer directly while the lock is held, and manually handles retaining items in the send buffer to avoid the back & forth. Should also be slightly more efficient in terms of comparing match criteria / building TQE & SeqNum sets.

Fix deadlock causes by packet removal during reliable resend

---

tools/rtpsrelay/RelayHandler.cpp

Solution: Print the error message that causes a read with negative bytes.

RtpsRelay: Inadequate logging for handle_input

---

cmake/dds_idl_sources.cmake

Fix the issue when an IDL is added as a PUBLIC or INTERFACES sources of a target, the generated cpp files also listed as PUBLIC or INTERFACE files for the target.

CMake: fix public idl cpp sources

---

dds/DCPS/transport/framework/ThreadPerConnectionSendTask.cpp

By only signaling for the thread to wake up on complete (SEND_STOP) requests.

Reduce Lock Contention in ThreadPerConnectionSendTask Queue

---

dds/DCPS/transport/tcp/TcpConnection.cpp
dds/DCPS/transport/tcp/TcpInst.cpp
dds/DCPS/transport/tcp/TcpInst.h
dds/DCPS/transport/tcp/TcpInst.inl
dds/DCPS/transport/tcp/TcpTransport.cpp

Added tcp connection timeout for active tcp connection attempts.
When unreachable locations were being found in the OS interfaces
the connection attempt was hanging for an indefinite amount of time.
However, this was not configurable on the active side. Configurable
option (active_conn_timeout_period) was added as a TCP-specific option
with a default of 5 seconds.
(cherry picked from commit 2b568a772ee143b47eff84d3a7b4da30c3a3de63)

Adding TCP transport active connection timeout

---

dds/DCPS/transport/framework/TransportClient.cpp

Removed break from active processing side to allow continuance of loop to process candidate links when the first connection link fails to succeed. The loop was kicking out too early. 
On the passive side of association, for loops that have multiple impls to look at for candidate association was kicking out after the first indication of a successful impl existence, but when the link was null, it did not proceed to the next one in the list to check further, but was simply returning out of the associate method.
(cherry picked from commit d6a38fca10a435bb8638d0c6e044a1a6b77f6ae5)

Handling multiple transport instances

---

MPC/config/dds_openssl.mpb

This is pulled from https://github.com/objectcomputing/OpenDDS/pull/1066. I thought it was fixed by https://github.com/DOCGroup/ACE_TAO/pull/858, but I didn't make sure OpenDDS was using `ace_openssl` instead of `openssl` directly. Now I see `ace_openssl` is broken in OpenDDS on top of the fact that the issue never was fixed. This applies the fix from #1066 to get around `ace_openssl`. Will have to create some sort of test for this at some point if we ever get Android testing.

Keep Linkage Private for OpenSSL on Android

---

dds/DCPS/RTPS/Spdp.cpp

This is to address a start-up condition where SEDP is already engaged
in ICE and needs the local agent info for SPDP but SPDP has not added
its endpoint to the ICE agent.

Add SPDP ICE endpoint before SEDP is initialized

---

tools/rtpsrelay/PublicationListener.cpp
tools/rtpsrelay/RelayHandler.cpp
tools/rtpsrelay/SubscriptionListener.cpp
tools/rtpsrelay/utility.h

Root cause is copying GUIDs between C++11 and non-C++11 code.

Fix compiler warnings in RtpsRelay

---

dds/DCPS/RTPS/GuidGenerator.h
dds/DCPS/RTPS/RtpsDiscovery.cpp
dds/DCPS/RTPS/RtpsDiscovery.h

... instead of letting it pick a random value

RTPS Discovery: added a configurable way to start the participant counter in the GUID at 0

---

dds/DCPS/RTPS/ParameterListConverter.cpp
dds/DCPS/RTPS/ParameterListConverter.h

Fix from changing `int`s to `bool`s in #1453. This is why I don't like indentation that's not based on tab stops.

ParameterListConverter: Fix Indentation

---

.gitmodules

Corporate firewalls tend to block `git:` protocol/port. For the retrieval and build process to work, the protocol must be changed to `https:`.

Change submodule retrieval protocol to https

---

dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp
dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.h

- allow heartbeats with the "first" number one larger than the "last"
- for volatile durability, first received data is delivered

rtps_udp 2.4 interop fixes

---

dds/DCPS/transport/framework/TransportSendBuffer.cpp
dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp

A number of things were wrong here. I hadn't pulled the RemoveAllVistitor usage out into RtpsUdpDatalink, I had accidentally copied the wrong buffer's iterator for fragments. I also wasn't checking to see if the buffer was non-null before calling release, but that only mattered because I was copying from incorrect buffer iterator.

Fix Unlocked Removal Methods & Usage For TransportSendBuffer / SingleSendBuffer

---

README.md
dds/DCPS/TimeTypes.h

OpenDDS will now need DOC Group ACE/TAO 2.5.7 or OCI TAO 2.2a patch 17 or later for monotonic time support.

Remove Manual Monotonic Time Support Check

---

.mailmap
AUTHORS
NEWS.md
PROBLEM-REPORT-FORM
VERSION.txt
dds/Version.h
tools/scripts/gitrelease.pl

- New version scheme where between releases OpenDDS master will have a version consisting of the next planned major or minor version and `-dev` (`3.14.0-dev` in the current case).
- Release Script Changes:
- Modify for new version scheme, allowing next version to be overridden.
- Use `Getopt::Long`.
- Turn `STEPS` argument into an option because of issues with the step expressions and `Getopt::Long`
- Release date inserted into files is now shorter: Feb 22 2020, for example.
- Regularize step names.
- Added `OPENDDS_IS_RELEASE` to `dds/Version.h` which is defined as 1 in releases, 0 all other times.
- Update `AUTHORS` file.

Use "-dev" version suffix to indicate development versions (master branch between releases)

---

dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp
dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.h

Eliminate race condition where data could enter RtpsWriterInfo's held_ container after RtpsUdpDataLink::pre_stop() but before object destruction, causing SEGV when held object tried to release non-existent buffer.

Honor DataLink::pre_stop for RTPS readers

---

dds/DCPS/RTPS/Spdp.cpp
dds/DCPS/RTPS/Spdp.h

Both SPDP's match_unauthenticated and match_authenticated make use ACE_Reverse_Lock in order to update the BIT information. Unfortunately, this can lead to invalidation of iterators and references acquired before the lock was released. Care needs to be taken to refresh & check iterators after the reverse lock is used, as well as avoiding use of references to protected objects after the reverse lock is used (prefering pointers, which can be refreshed).

Protect Use of DiscoverParticipantIter Across ACE_Reverse_Lock Usage in SPDP

---

dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp

Release both mutexes in RtpsUdpDataLink::process_data_i before calling up into the transport framework with invoke_on_data_callbacks in order to prevent deadlock.

Prevent Deadlock in RtpsUdpDataLink::process_data_i

---

dds/DCPS/Service_Participant.cpp
dds/DCPS/security/BuiltInPluginLoader.cpp
dds/DCPS/security/BuiltInPluginLoader.h

Clean up NetworkConfigMonitor and BuiltinPluginLoader on shutdown.
This allows the service participant to be destroyed and recreated.

Support recreating the service participant

---

dds/DCPS/ReactorInterceptor.cpp
dds/DCPS/ReactorInterceptor.h

The primary motivator for this was mutrace's output. When running a mutrace'd worker alongside a bench scenario, the ReactorInterceptor show up in most of the top contention slots, which I'm guessing comes mostly from holding the lock while calling notify when the reactor thread is idle (and so it immediately tries to grab the lock). The addition of the state flag and the queue swapping was intended to prevent some of the back & forth.

Fix Mutex Contention Within ReactorInterceptor

---

bin/PerlDDS/Run_Test.pm
tests/DCPS/Messenger/run_test.pl

Default to passing `-DCPSSecurityDebug 9` when `-Config OPENDDS_SECURITY` is passed, unless `-DCPSSecurityDebug` or `-DCPSSecurityDebugLevel` was specified in the test or `DCPSSecurityDebug` or `DCPSSecurityDebugLevel` environment variables were set.
Fixes secure messenger test failing on non-secure scoreboard builds caused by #1572. `-Config OPENDDS_SECURITY` will have to be passed on all security builds, but I'm ready to commit that.

Control for Security Debug in PerlDDS

---

dds/DCPS/transport/rtps_udp/RtpsUdpReceiveStrategy.cpp

since some implementations aren't compatible

RTPS 2.4: ignore directed write from previous minor versions

---

tests/DCPS/WaitForAck/Publisher.cpp
tests/DCPS/WaitForAck/rtps.ini

In order to ensure safety profile build successes

Increase pool_size and wait time parameters for WaitForAck Test

---

tools/scripts/gitrelease.pl

- Fix:
- Verifying and inserting release status message into `NEWS.md`
- Creating release flag file
- Interpreting command exit statuses for extracting ACE/TAO and
generating Doxygen files.
- Use passive FTP connection by default with option for an active one.
- Add different commit message for post release changes.
- Die immediately when `VERSION` argument is invalid.

gitrelease.pl: Fixes from 3.14 release

---

bin/dcps_tests.lst

Scoreboard tests are failing because the machines aren't set up with RapidJSON. As a result, the test doesn't build but the test script was still being called. Eventually we need to update the scoreboard machines to have RapidJSON, but until that happens this should prevent errors.

Add RapidJSON config to bench tests

---

dds/DCPS/RTPS/ICE/AgentImpl.cpp
dds/DCPS/RTPS/ICE/AgentImpl.h
dds/DCPS/RTPS/ICE/Checklist.cpp
dds/DCPS/RTPS/ICE/Checklist.h
dds/DCPS/RTPS/ICE/EndpointManager.cpp
dds/DCPS/RTPS/ICE/EndpointManager.h
dds/DCPS/RTPS/ICE/Task.cpp
dds/DCPS/RTPS/ICE/Task.h

The time-based behavior of Checklists, ServerReflexiveTasks, and
ChangePasswordTasks is governed by the AgentImpl.  There was no way to
remove a Task from the queue of Tasks waiting on a timer.
Consequently, manual memory management was used to 1) prevent a Task
from entering the queue twice and 2) to destroy the Task as a
scheduled event.  The problem is the ServerReflexiveTask and
ChangePasswordTask have the same lifetime as their parent
object (EndpointManager) but the destruction was solely under the
control of the ServerReflexiveTask.  Thus, a destroyed
ChangePasswordTask may be in the queue of Tasks waiting on a timer.
Solution: Change the queue of Tasks to hold weak references.

Use reference counting for ICE

---

dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp
dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.h

The association design requires that a writer receive an acknack from
a reader and reader receives data or a heartbeat from writer.  There
were two issues with this design.
If writer has no data, it will not respond to the acknack with a
heartbeat so the writer will be associated but the reader will not.
There was no reliability in the design as the reader would not retry
to send the acknack.
Solution: Add retry logic to the reader so it will resend acknacks and
add logic to the writer so that it will respond with a heartbeat.

Fix reliability in rtps_udp

---

tools/rtpsrelay/RelayHandler.cpp

The participant statistics were computed after the sample was
written.
Solution: Compute the participant statistics before writing the
handler statistics.

Participant statistics in RtpsRelay not computed before write

---

configure

If `--wireshark[-cmake]` is passed without `--glib`, then `--glib` should be implied, but that wasn't occurring early enough in the script for that to work.
Also changed some usages of `$!` to `$?` in Qt stuff because it's slightly more correct.

configure: Fix Issue with Implied --glib

---

dds/DCPS/DataReaderCallbacks.h
dds/DCPS/DataWriterCallbacks.h

Fix for #1594
These exports are required in order for the messenger example ( and likely other opendds) to run on android when compiled with clang.  There was a dynamic cast failing during info repo discovery because these exports were missing.

Adding Missing Exports for Getting InfoRepo Disc. Working on Android

---

dds/DCPS/RTPS/Sedp.cpp
dds/DCPS/RTPS/Spdp.cpp
dds/DCPS/RTPS/Spdp.h

SEDP can determine a server reflexive address before SPDP has
registered its endpoint with the ICE Agent.  For secure updates, SEDP
will incorporate the local agent info for the SPDP endpoint.  These
leads to an assert since SPDP has not registered its endpoint.
Solution: Check that the endpoint has registered with the ICE Agent.

Fix race condition between SEDP STUN and SPDP

---

dds/DCPS/DataReaderImpl.cpp

It looks like I missed this case back in https://github.com/objectcomputing/OpenDDS/pull/863. All checks for if a given topic is a BIT should be done using the `topicIsBIT` function I added in that PR.

Replace Manual BIT Topic Check

---

dds/DCPS/transport/framework/DataLink.cpp
dds/DCPS/transport/framework/DataLink.h
dds/DCPS/transport/framework/TransportReassembly.cpp
dds/DCPS/transport/framework/TransportReassembly.h
dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp
dds/DCPS/transport/rtps_udp/RtpsUdpReceiveStrategy.cpp
dds/DCPS/transport/rtps_udp/RtpsUdpReceiveStrategy.h
performance-tests/bench_2/control_opendds_config.ini
performance-tests/bench_2/node_controller/main.cpp
tests/DCPS/UnitTests/Fragmentation.cpp

Fixing a number of issues with fragmentation:
1) Not handling duplicate fragments correctly (combined ranges can exceed duplicate range).
2) Storing fragments for writers we've never associated with (potentially never cleaned)
3) For RTPS, where we can calculate total # of fragments, we only ever nack the 'next' fragment, wasting time.
Minor tweaks to node_controller & control domain

Fix Fragmentation Issues

---

dds/DCPS/NetworkConfigModifier.h

Linux builds use LinuxNetworkConfigMonitor. Trying to build with
NetworkConfigModifier will fail unless ipv6 is enabled, since
ACE_OS::if_nametoindex is not defined.

Do not use NetworkConfigModifier for Linux builds.

---

dds/DCPS/RTPS/Spdp.cpp
dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp

Problem: The logic to join multicast groups on platforms that don't
have a network config monitor (NCM) creates a default NIC and populates it
with an address to be compatible with the NCM logic.  If IPV6 is
enabled, then the default address will be an IPV6 address meaning that
the IPV4 multicast groups will never be joined.
Solution: Always add an IPV4 address to the default NIC and add an
IPV6 address if appropriate.

Try to join IPV4 and IPV6 multicast groups when no NCM

---

dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp
dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.h

Fix for the Thrasher RTPS & Bench CI Disco Tests.

Remove reader_associator_ from RtpsUdpDataLink to prevent errant acknacks

---

dds/DCPS/DataWriterImpl.cpp

Specifically, fixing it for calls to on_publication_match to use PUBLICATION (not SUBSCRIPTION)

Fixing DataWriterImpl Listener Mask

---

Dockerfile

The RMW project is preparing to use ROS2 Foxy which is built on **Ubuntu Focal** (20.04). I tested the OpenDDS docker and found it needed a few changes. I also did some cleanup (removing gtest/gmock) and running the `show_build_config.pl` script after config based on @mitza-oci's request.

Docker updates for ubuntu focal

---

java/idl2jni/codegen/im_jni.cpp
java/idl2jni/tests/union/.gitignore
java/idl2jni/tests/union/TestUnion.cpp
java/idl2jni/tests/union/TestUnion.java
java/idl2jni/tests/union/UnionTest.idl
java/idl2jni/tests/union/idl2jni_test_union.mpc
java/idl2jni/tests/union/run_test.pl
java/tests/dcps_java_tests.lst

Unions with implicit defaults that don't have a branch selected need their discriminator values copied from C++ to Java.
There may be one more issue with unions that I'll add to this PR, but I wanted to get CI going on this part of it.

Fixed a corner case for IDL union code generation in Java

---

tools/rtpsrelay/RelayHandler.cpp

Note: INFO_SRC was added to the PAD messages.

RtpsRelay should not forward beacons

---

dds/DCPS/transport/framework/TransportReceiveStrategy_T.cpp
dds/DCPS/transport/framework/TransportReceiveStrategy_T.h
dds/DCPS/transport/rtps_udp/RtpsUdpReceiveStrategy.cpp

And where max packet size can be assumed and the buffer chain doesn't have to be so long / constantly checked.
The implementation is basically a copied & pared-down version of handle_dds_input, but it should only ever really need to use a single buffer at a time and not worry about reallocating / maintaining a giant read buffer chain (1000's of calls to ACE_Message_Block::total_length(), which then iterates over the whole chain).

Add a simpler 'handle_dds_input' for UDP protocols

---

dds/DCPS/DiscoveryBase.h
dds/DCPS/RTPS/Spdp.cpp
dds/DCPS/security/AuthenticationBuiltInImpl.cpp
tests/security/AccessControlTest.cpp
tests/security/Authentication/AuthenticationTest.cpp

One participant (the initiator) has discovered another
participant (the replier) and sent an auth request.  Due to SPDP
reset, it removes the participant but immediately rediscovers it and
sends another auth request.  If the replier receives the first auth
request, it will continue to respond to it but authentication will
fail as the initiator has changed the Diffie-Hellman parameters.
Solution:
1. The replier will not periodically resend replies.  It will only
send auth replies in response to an auth request.
2. If the replier detects that the auth request has changed, it will
recompute a new auth reply.

Only send auth replies for auth requests

---

dds/DCPS/Serializer.h

Discussed on the mailing list, with VS 2019 V16.7.0 Preview 1.0 there are 9 projects that don't build after doing a default "configure" -> "devenv DDS_TAOv2.sln" -> "Build Solution".
A fix is attached where #include <string> is added to dds/DCPS/Serializer.h so, presumably, something changed recently in VS2019 in relation to its mechanism for working out dependencies.

Fix to make master build on VS 2019 Version 16.7.0 Preview 1.0

---

dds/DCPS/DiscoveryBase.h

This was motivated by a deadlock.  The first thread was adding a
participant on the basis of a successful security handshake.  This
thread unlocks the SPDP lock so that it can call into the
ParticipantLocationTopic which acquires the sample lock and then
reacquires the SPDP lock.  The second thread was sending a periodic
announcement and, as a by-product, cleaning up expired participants.
This thread acquired the SPDP lock before calling into DiscoveryBase
to remove the participant.  The code in discovery base called into the
ParticipantLocationTopic with the SPDP lock.  The second thread then
attempts to acquire the sample lock.
Solution: Unlock the SPDP lock before interacting with the
ParticipantLocationTopic reader when removing a discovered participant.

Unlock for ParticipantLocationTopic unregister/dispose

---

dds/DCPS/DataReaderImpl.cpp
dds/DCPS/RemoveAssociationSweeper.h
dds/DCPS/transport/rtps_udp/RtpsUdpReceiveStrategy.cpp

Suppose that a Participant A is suspended long enough that it expires
for Participant B.  Participant A is then resumed.  In RTPS, this will
most likely cause a number of timers to fire include the one that will
cause Participant A to 1) expire Participant B and 2) send SPDP.  As
part of expiring Participant B, associations between writers in
Participant B and readers in Participant A will be scheduled for
removal (in Participant A).  Sending SPDP will restart the discovery
process.  This may cause associations between the readers and writers
to complete for the timer fires that causes the association to be
removed.  Finally, that timer will fire and remove the association
that was just added.
Solution: When adding an association to a reader, cancel any
RemoveAssociationSweeper that will …

Associations are removed after expire-associate

---

dds/DCPS/RTPS/RtpsDiscovery.cpp
tests/DCPS/ConfigFile/test1.ini

Fixes #1738 
This changes the code in RtpsDiscovery::Config::discovery_config(), specifically for the SpdpLocalAddress case, to use a version of the ACE_INET_Addr::set() functions that allows for an IP address without a port number (as is required for SpdpLocalAddress according to the OpenDDS Developers' Guide). This change follows the example of "InteropMulticastOverride".
Note: I've assumed the actual port used will overwrite the 0 it's set to .
In addition an SpdpLocalAddress is specified, in the correct format, in the test1.ini file in the tests/DCPS/ConfigFile directory is updated to exercise this code.

Handle SpdpLocalAddress formatted as defined in Dev Guide properly

---

dds/DCPS/transport/framework/DataLink.cpp

Fixes RestartTest from a SEGV when accessing recently-deleted listener maps.

Protect Listeners in DataLink::network_change()

---

MPC/config/opendds_security.mpb

`dcpslib` installs libraries to `$DDS_ROOT/lib`, which I'm certain is not the intention here.

Remove dcpslib from opendds_security.mpb

---

dds/DCPS/DiscoveryBase.h
dds/DCPS/RTPS/Sedp.cpp
dds/DCPS/RTPS/Sedp.h
dds/DCPS/RTPS/Spdp.cpp
dds/DCPS/RTPS/Spdp.h

An auth resend can cause the authentication process to get into a bad
state (stall and/or livelock).
Solution: Rework the state machine with the following objectives
1. Use sequence numbers for the stateless endpoints for at-most-once
processing.
2. Resend all handshake messages (request, reply, final) according to
the resend timer.  Finals are resent until a token is received from
the replier.
3. Resend auth reqs until a handshake message is received from the remote.
4. Further separate auth state from handshake state.  So that a
participant remains authenticated through a reauth scenario.

Authentication does handle resends

---

dds/DCPS/RTPS/Sedp.cpp
dds/DCPS/RTPS/Sedp.h
dds/DCPS/security/AuthenticationBuiltInImpl.cpp
dds/DCPS/security/AuthenticationBuiltInImpl.h
tests/security/Authentication/AuthenticationTest.cpp

Use a DomainParticipantQos Property_t to include them again

By default, omit optional properties from Authentication's handshake tokens

---

performance-tests/bench_2/builder/Common.cpp
performance-tests/bench_2/builder/Common.h
performance-tests/bench_2/builder/DataReader.cpp
performance-tests/bench_2/builder/DataWriter.cpp
performance-tests/bench_2/common/util.cpp
performance-tests/bench_2/common/util.h
performance-tests/bench_2/idl/Bench.idl
performance-tests/bench_2/node_controller/main.cpp
performance-tests/bench_2/test_controller/DdsEntities.cpp
performance-tests/bench_2/test_controller/DdsEntities.h
performance-tests/bench_2/test_controller/ScenarioManager.cpp
performance-tests/bench_2/worker/ForwardAction.cpp
performance-tests/bench_2/worker/WorkerDataReaderListener.cpp
performance-tests/bench_2/worker/WorkerDataWriterListener.cpp
performance-tests/bench_2/worker/WriteAction.cpp
performance-tests/bench_2/worker/main.cpp

Currently, delays in propagating configuration between the test controller and node controllers can cause different node controllers to launch their worker processes at different times. Improve this by sending the whole scenario at once to improve flow control issues and then wait for acknowledgement before sending a launch time.

Improve Coordination Between Bench's Test & Node Controllers

---

dds/DCPS/RTPS/ICE/Checklist.cpp

A sequence of events leading to the assert failing is:
1. Controlled agent nominates a candidate pair.
2. Controlled agent receives a check resulting in a new triggered
check.
3. The triggered check queue is not clear when the nominated candidate
pair succeeds.
Solution: Clear the triggered check queue before nominating a
candidate pair and do not generate triggered checks after the pair has
been nominated.

ICE: Empty triggered check queue assert fails in checklist_succeeded

---

dds/DCPS/transport/framework/TransportReceiveStrategy_T.cpp

Specifically, in TransportReceiveStrategy::handle_simple_dds_input() which is used by RtpsUdp transport instances.

Allow skipping of packets with bad transport headers 

---

dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp
dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.h
dds/DCPS/transport/rtps_udp/RtpsUdpTransport.cpp
dds/DCPS/transport/rtps_udp/RtpsUdpTransport.h

As I mentioned previously, this seems to be a pretty straightforward change and has performance improvements in the test environment for small & medium scale tests. However, at larger test scales it also seemed slightly less stable. I can't think of any good reasons why that would be the case, unless it's simply a matter of tying up the reactor thread with a larger number of individual writes. I'm hopeful that one of you might spot something obvious that I'm missing.

Prefer Unicast For INFO_DST Submessages

---

dds/DCPS/RTPS/Sedp.cpp
dds/DCPS/RTPS/Sedp.h

And deleting owned objects in destructor.

Fix potential leak in Sedp::Msg by checking for ownership

---

dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp

The first nack from a durable reader can result in a call to
send_and_gather_nack_replies that uses data in the send buffer to
process the nack or sends a gap instead.
Solution: Only process the nack if the reader is not expecting
durability data.

RTPS durability nacks gapped or answered from send buffer

---

dds/idl/metaclass_generator.cpp
tests/DCPS/MetaStruct/MetaStructTest.cpp
tests/DCPS/MetaStruct/MetaStructTest.idl

I did a check by moving the new test files to an old build of OpenDDS and running the test. As expected, it fails because it is not certain the length of a wchar. 
The new build of OpenDDS with the metastruct changes passes because a wchar is always 16bits.

XTypes: WChar Support in Metaclass Generator

---

dds/DCPS/XTypes/TypeObject.h
dds/idl/annotations.cpp
dds/idl/annotations.h
dds/idl/be_global.cpp
dds/idl/be_global.h
dds/idl/typeobject_generator.cpp
dds/idl/typeobject_generator.h

This is the IDL portion of the try construct card.  It consists of defining the annotation(s) and setting the member flags.  Also contains a bugfix where key was on wrong part of union member.

XTypes: IDL portion of TryConstruct

---

bin/PerlDDS/Run_Test.pm

- don't default to enabling all security debug flags
- provide a way to skip dumping out full log files

Run_Test.pm updates:

---

bin/dcps_tests.lst
performance-tests/bench_2/node_controller/main.cpp
performance-tests/bench_2/worker/main.cpp

Bench's worker was still using high_resolution_clock timer to generate absolute times, which causes issues on machines where high_resolution clock doesn't have a predictable epoch (windows). Switch these over to system_clock and enable the small "mixed" test while we're at it to stress test simultaneous reliable / durable messaging during discovery.

Fix Windows Bench Scoreboard Failures

---

dds/DCPS/RTPS/Sedp.cpp

Use local shutdown flag to prevent insertion, drain / delete message queue once stop is requested.

Fix Potential Memory Leak During Shutdown of SEDP Task Queue

---

dds/DCPS/transport/framework/TransportClient.cpp
dds/DCPS/transport/framework/TransportClient.h

CommandBase was storing TransportClient pointers, which may be invalid by the time the Reactor executes the command. Instead, store WeakRcHandle to TransportClient and lock / check before use.

Prevent invalid access in TransportClient::PendingAssocTimer::ScheduleCommand during shutdown

---

_sass/_base.scss

The color scheme for visited links darkens the brand color and eliminates the contrast between the link and text. Keeping links the original color resolves this issue while not impacting the user.
Current visited state
Change

Remove visited link css state

---

dds/DCPS/RTPS/Spdp.cpp
dds/DCPS/RTPS/Spdp.h

Sedp::data_received acquires the SPDP lock and may acquire the ICE
AgentImpl lock if it decides to send.  A successful ICE session will
have the ICE AgentImpl lock and needed to acquire the SPDP lock.
Solution
Break the deadlock by deferring ice_connect and ice_disconnect in SPDP.

Deadlock from ice_connect

---

dds/DCPS/DiscoveryBase.h

A reverse lock was added but the guard to use it was not added.
Solution
Add the guard.

remove_discovered_participant doesn't unlock before calling BITS

---

dds/DCPS/DataWriterImpl.cpp
dds/DCPS/DataWriterImpl.h
dds/DCPS/DomainParticipantFactoryImpl.cpp
dds/DCPS/DomainParticipantFactoryImpl.h
dds/DCPS/DomainParticipantImpl.cpp
dds/DCPS/DomainParticipantImpl.h
dds/DCPS/MessageTracker.cpp
dds/DCPS/MessageTracker.h
dds/DCPS/PublisherImpl.cpp
dds/DCPS/PublisherImpl.h
dds/DCPS/Service_Participant.h
dds/DCPS/Service_Participant.inl
dds/DCPS/WriteDataContainer.cpp
dds/DCPS/WriteDataContainer.h
dds/DCPS/transport/framework/SendResponseListener.cpp

If multiple `DataWriter`s are being deleted in a `DomainParticipant` or `Publisher`, use PendingTimeout for a single deadline to finish pending data and control writes for all the writers, instead of waiting for at least a separate data and control deadline for every single writer. Also start instance unregisters for all writers before setting and waiting on the deadline.
These changes should dramatically reduce the amount of time `Publisher::delete_contained_entities` and `DomainParticipant::delete_contained_entities` block for multiple writers, especially when there are a large amount of them.

Improve Efficiency of Waiting on Pending Writes

---

dds/DCPS/Serializer.h
dds/DCPS/Serializer.inl
dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp
dds/DdsDcpsCore.idl
dds/idl/be_global.cpp
dds/idl/marshal_generator.cpp
dds/idl/ts_generator.cpp

Set the allowed data representation of types without a annotation to all of them, or all true. I might have gotten mixed up with the fact that in `DataRepresentationAnnotation::node_value_exists`, when there is an annotation, the starting value has to be all false and then the annotations add values to it.
Also added some misc minor fixes, mostly cherry-picked from #1846 so that they might get merged faster.

XTypes: Fix Default Allowed Data Representation and Other Misc Fixes

---

performance-tests/bench_2/example/config/scenario/ci_disco_flag.json
performance-tests/bench_2/example/config/worker/ci_disco_flag.json
performance-tests/bench_2/idl/Bench.idl
performance-tests/bench_2/worker/WorkerDataReaderListener.cpp
performance-tests/bench_2/worker/WorkerDataReaderListener.h
performance-tests/bench_2/worker/WorkerDataWriterListener.cpp
performance-tests/bench_2/worker/WorkerDataWriterListener.h
performance-tests/bench_2/worker/main.cpp

Adds a delay to Bench 2 worker until all readers and writers are discovered or times out.

Implement Wait-for-Discovery-Complete for Bench Worker

---

bin/dcps_tests.lst
performance-tests/bench_2/example/config/scenario/ci_mixed.json
performance-tests/bench_2/example/config/worker/ci_disco.json
performance-tests/bench_2/example/config/worker/ci_disco_flag.json
performance-tests/bench_2/example/config/worker/ci_echo_client.json
performance-tests/bench_2/example/config/worker/ci_echo_client_frag.json
performance-tests/bench_2/example/config/worker/ci_echo_server.json
performance-tests/bench_2/example/config/worker/ci_fan_client.json
performance-tests/bench_2/example/config/worker/ci_fan_client_frag.json
performance-tests/bench_2/example/config/worker/ci_fan_server.json
performance-tests/bench_2/example/config/worker/ci_mixed_daemon.json
performance-tests/bench_2/example/config/worker/ci_mixed_master.json
performance-tests/bench_2/example/config/worker/ci_mixed_worker.json
performance-tests/bench_2/run_test.pl
performance-tests/bench_2/test_controller/ScenarioManager.cpp
performance-tests/bench_2/test_controller/main.cpp
performance-tests/bench_2/worker/main.cpp

Updating Bench to use value-initialize objects before parsing from JSON (to avoid raw memory values), updating bench CI configs to use discovery wait flag where applicable (all but ci_mixed), forking showtime_mixed_10 into separate ci_mixed scenario and adding expected entity counts.

Updating Bench To Use Discovery Wait Flag, Fix Failing Tests

---

dds/DCPS/StaticDiscovery.cpp

Fix for warning:
dds/DCPS/StaticDiscovery.cpp:333:81: warning: missing initializer for member ‘OpenDDS::DCPS::ReaderAssociation::serializedTypeInfo’ [-Wmissing-field-initializers]
{reader.trans_info, readerid, reader.subscriber_qos, reader.qos, "", "", 0};

missing initializer warning fix

---

dds/DCPS/DataWriterImpl_T.h
dds/DCPS/Serializer.cpp
dds/DCPS/Serializer.h
tests/DCPS/Serializer/SerializerTest.cpp

XTypes 1.3 7.6.3.1.2 says we should set the 2 LSB of the second byte of the options to be the number of bytes required to make the serialized size of the payload align to 4.

Support Padding Marker in Encapsulation Options

---

dds/DCPS/JobQueue.h
dds/DCPS/RTPS/Sedp.cpp
dds/DCPS/RTPS/Sedp.h
dds/DCPS/RTPS/Spdp.cpp
dds/DCPS/RTPS/Spdp.h
dds/DCPS/transport/framework/TransportInst.cpp
dds/DCPS/transport/framework/TransportInst.h
dds/DCPS/transport/multicast/MulticastDataLink.cpp
dds/DCPS/transport/multicast/MulticastDataLink.h
dds/DCPS/transport/multicast/MulticastDataLink.inl
dds/DCPS/transport/multicast/MulticastTransport.cpp
dds/DCPS/transport/udp/UdpDataLink.cpp
dds/DCPS/transport/udp/UdpDataLink.h
dds/DCPS/transport/udp/UdpDataLink.inl
dds/DCPS/transport/udp/UdpTransport.cpp

SEDP messages are queued and processed on a different thread than the
SEDP transport.  This queue has blocking behavior and causes a
deadlock when it fills up.
Solution:  The solution is to create back pressure at the point of
input processing.  This means that the transport thread(s) that process
the input should be doing the work of processing the messages.  This
commit shifts all discovery processing to the SEDP transport thread
and eliminates the SEDP worker thread and SPDP transport thread.

RTPS Discovery does not degrade gracefully with load

---

dds/DCPS/DiscoveryBase.h
dds/DCPS/RTPS/ICE/EndpointManager.cpp
dds/DCPS/RTPS/ICE/Ice.h
dds/DCPS/RTPS/RtpsDiscovery.cpp
dds/DCPS/RTPS/RtpsDiscovery.h
dds/DCPS/RTPS/Sedp.cpp
dds/DCPS/RTPS/Sedp.h
dds/DCPS/RTPS/Spdp.cpp
dds/DCPS/RTPS/Spdp.h
dds/DCPS/transport/framework/TransportImpl.h
dds/DCPS/transport/framework/TransportInst.cpp
dds/DCPS/transport/framework/TransportInst.h
dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp
dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.h
dds/DCPS/transport/rtps_udp/RtpsUdpInst.cpp
dds/DCPS/transport/rtps_udp/RtpsUdpInst.h
dds/DCPS/transport/rtps_udp/RtpsUdpTransport.cpp
dds/DCPS/transport/rtps_udp/RtpsUdpTransport.h

The decision to use the RtpsRelay (or to only use the RtpsRelay) or
ICE can only be made at start time.  Users of OpenDDS want the ability
to dynamically turn off the RtpsRelay and ICE for testing purposes.
Solution: Make the corresponding configuration dynamic.  The
configuration for the RtspRelay is straightforward as it can be picked
up on the next send.  The configuration of ICE is more difficult since
ICE needs to be restarted for participants that have already been
discovered.
The code attempts to reset flags in the ParticpantLocationTopic.  The
ParticipantLocationTopic in a remote participant will be updated after
the corresponding entries time out.  To a certain extent, these
controls influence the ways in which other participants can discover a
given participant.  For example, …

User cannot dynamically toggle RtpsRelay and ICE

---

dds/idl/marshal_generator.cpp
tests/DCPS/Compiler/xcdr/xcdr.cpp
tests/DCPS/Compiler/xcdr/xcdr.idl

- Add more fields to the tested structs and unions: nested structs with different extensibilities, delimited types like sequence of non-primitive elements...
- Test structs and unions without data_representation annotations
- Add little-endian tests

XTypes: Improve XCDR2 tests

---

dds/DCPS/RTPS/Sedp.cpp

I didn't have security enabled in this build so these rc handles were invalid.

XTypes: Fix Segfault Caused By Misplaced #endif in Sedp

---

dds/DCPS/RTPS/ParameterListConverter.cpp
dds/DCPS/RTPS/RtpsCore.idl
dds/DCPS/RTPS/Sedp.cpp
dds/DCPS/Service_Participant.cpp
dds/DCPS/Service_Participant.h
dds/DCPS/Service_Participant.inl
dds/DdsDcpsCore.idl
java/dds/DDS/.gitignore

- Determine values for the enum “kind” and the 5 booleans in TypeConsistencyEnforcementQosPolicy (Annex D)
- These would be constants for our initial implementation, the user will not be able to change them
- Send these values in the SEDP Built-in Subscription endpoint

XTYPE-124: TypeConsistencyEnforcement QoS Policy (initial implementation)

---

dds/DCPS/transport/tcp/TcpConnection.cpp

Small spelling mistake I see in the logs that is bugging me.

RECONNECTED_STATE spelling mistake

---

dds/DCPS/DomainParticipantImpl.cpp
dds/DCPS/RTPS/Spdp.cpp
dds/DCPS/security/AccessControlBuiltInImpl.cpp
dds/DCPS/security/AccessControlBuiltInImpl.h
dds/DdsSecurityCore.idl

Problem
-------
The DDS Security Specification provides no way to return the handles
returned by validate_local_permissions and
validate_remote_permissions.  This creates a resource leak as local
and remote partipants are created and destroyed.
Solution
--------
Add a method return_permissions_handle to free the resources backing
the handle.

Permissions handles are not returned to Access Control Plugin

---

dds/DCPS/DataDurabilityCache.cpp
dds/DCPS/DataReaderImpl.cpp
dds/DCPS/DataReaderImpl.h
dds/DCPS/DataReaderImpl_T.h
dds/DCPS/DataSampleHeader.h
dds/DCPS/DataWriterImpl.cpp
dds/DCPS/DataWriterImpl.h
dds/DCPS/DataWriterImpl_T.h
dds/DCPS/Observer.cpp
dds/DCPS/Observer.h
dds/DCPS/ValueWriter.h
dds/idl/dds_generator.h
dds/idl/dds_visitor.cpp
dds/idl/value_writer_generator.cpp
dds/idl/value_writer_generator.h
tests/DCPS/Observer/Observer.mpc
tests/DCPS/Observer/TestObserver.cpp
tests/DCPS/Observer/TestObserver.h
tests/DCPS/Observer/run_test.pl
tests/DCPS/common/ConnectionRecordLogger.cpp
tests/DCPS/common/JsonValueWriter.cpp
tests/DCPS/common/JsonValueWriter.h
tests/DCPS/unit/MyTypeSupportImpl.h

Problem
-------
One of the primary motivations for the Observer interface is the
ability to log samples as they are written, received, and accessed.
Currently, users of the Observer interface receive a generic pointer
to sample data which may be a raw sample or something else.
There is no capability that allows a user to take this generic
pointer and log the sample contained therein.
Solution
--------
1. Standardize on the approach that the pointer in the Sample is a
pointer to a raw sample.
2. Introduce the ValueWriter interface and necessary support in the
IDL compiler to allow generic processing of the raw sample.
3. Add plumbing between generic and typed DataReader and DataWriter to
allow a user to dispatch a ValueWriter on the raw sample.
4. Provide an incomplete JsonValueWriter to …

Observed data cannot be logged

---

dds/idl/marshal_generator.cpp
tests/DCPS/Compiler/xcdr/xcdr.cpp
tests/DCPS/Compiler/xcdr/xcdr.idl

Remove data representation from the names and annotations of the non-topic types, modify the xcdr test and remove duplicates.

XTypes: Remove Data Repr. Annotations from XCDR Test

---

dds/DCPS/XTypes/TypeAssignability.cpp
tests/DCPS/UnitTests/.gitignore
tests/DCPS/UnitTests/UnitTests.mpc
tests/DCPS/UnitTests/XTypesAssignability.cpp

Update the assignability of enum types so that 2 enum types with different bit_bounds are not assignable.

XTypes: Enum bit_bound assignability refinement

---

dds/DCPS/JobQueue.h
dds/DCPS/ReactorInterceptor.cpp
dds/DCPS/ReactorInterceptor.h

Problem
-------
Currently, a typical DDS application might involve 50+
ReactorInterceptors.  Each ReactorInterceptor includes a deque.  A
deque is built from internal nodes.  The internal nodes typically have
a minimum size which is the lesser of the size of the value type and
some constant.  This constant can be much bigger than the size of the
value type.  Consequently, a deque that contains a only a few entries,
such as one for a ReactorInterceptor, is highly memory inefficient.
If an empty deque is 1K, then a typical DDS application will have 50K+
of memory that is not actually being used.
Solution
--------
Change ReactorInterceptor and Job queue to use vectors that are
swapped with empty vectors as they are being processed.

Deque is memory inefficient

---

dds/DCPS/DiscoveryBase.h
dds/DCPS/Service_Participant.cpp
dds/DCPS/Service_Participant.h
tools/rtpsrelay/RtpsRelay.cpp

Problem
-------
The DDS Specification says that the members of the
ReaderDataLifecycleQosPolicy are set to infinite which means a
participant will never purge the data stored in the builtin topics.  A
long-running participant will eventually run out of memory.
It is possible to manually change the qos for all of the builtin
participant data readers.  However, the addition of a new builtin
topic would render such code useless and the new builtin topic would
create another memory leak.
Solution
--------
Provide a mechanism to configure the ReaderDataLifecycleQosPolicy for
the builtin topic data readers.

BIT readers have spec-defined memory leak

---

dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp

Problem
-------
The BUNDLING_PLACEHOLDER was only removed for the first bundle in a
group.
Solution
--------
Save addresses for bundle to temporary set, erase
BUNDLING_PLACEHOLDER, and use temporary.

BUNDLING_PLACEHOLDER not removed in bundles

---

bin/dcps_tests.lst
tests/DCPS/Compiler/XtypesExensibility/Extensibility.idl
tests/DCPS/Compiler/XtypesExensibility/XtypesExtensibility.cpp
tests/DCPS/Compiler/XtypesExensibility/run_test.pl

Adding exten test to test list and removing cases that shouldn't have existed in the first place.

Xtypes: Extensibility test fixes

---

dds/DCPS/LinuxNetworkConfigMonitor.cpp

Moving to the LinuxNetworkConfigMonitor changed how we do joins on the loopback interface, breaking local discovery when no network connection is available. This allows multicast joins to be performed on the loopback interface despite lack of the explicit multicast flag and resolves the issue.

Perform Multicast Join on Loopback Interface

---

dds/DCPS/NetworkConfigModifier.cpp
dds/DCPS/NetworkConfigModifier.h
dds/DCPS/NetworkConfigMonitor.cpp
dds/DCPS/NetworkConfigMonitor.h

Adding mutex protection to NetworkInterface to allow for future thread-safe interactions and expanding exclude_from_multicast to handle configure_interface strings that are IP addresses, since this string comes directly from the MulticastInterface configuration option (which can optionally be an address) or the DCPSDefaultAddress (which is always an address).

Add Mutex Protection To NetworkInterface And Fix Interaction With MulticastInterface Addresses

---

dds/DCPS/transport/framework/TransportSendBuffer.cpp

Problem
-------
Entries are inserred into the `destinations_` map but never removed.
Solution
--------
Remove entries from `destinations_` when the corresponding entry is
removed from `buffers_`.

TransportSendBuffer leaks memory

---

dds/DCPS/DiscoveryBase.h
dds/DCPS/RTPS/RtpsCore.idl
dds/DCPS/RTPS/RtpsDiscovery.h
dds/DCPS/RTPS/RtpsSecurity.idl
dds/DCPS/RTPS/SecurityHelpers.h
dds/DCPS/RTPS/Sedp.cpp
dds/DCPS/RTPS/Sedp.h
dds/DCPS/RTPS/Spdp.cpp
dds/DCPS/RTPS/Spdp.h
dds/DCPS/StaticDiscovery.cpp
dds/DCPS/StaticDiscovery.h
dds/DCPS/security/AccessControlBuiltInImpl.cpp
dds/DCPS/security/AccessControlBuiltInImpl.h
dds/DCPS/transport/rtps_udp/RtpsUdpReceiveStrategy.cpp
tests/security/attributes/subscriber.cpp
tests/transport/spdp/spdp_transport.cpp

Problem 1
---------
The default configuration delays an SPDP resend for 3 seconds.
However, a participant A receiving an initial SPDP announcement from B
will attempt authentication with B.  However, B will ignore the
authentication messages because it has not discovered A.
Solution 1
----------
Send an SPDP announcement when attempting authentication with a newly
discovered participant.
Problem 2
---------
`match_authenticated` is called before the FINAL in the auth handshake
is sent.  This is problematic because `match_authenticated` is slow,
e.g., takes 1 second to complete.  The other participant is idle while
waiting for the FINAL and will call `match_authenticated` when it gets
the FINAL.
Solution 2
----------
Send the FINAL before calling `match_authenticated`.  While it doesn't …

Secure discovery is slow

---

dds/DCPS/NetworkConfigModifier.cpp

This PR is related to the fix of the loopback adapter multicast join on Linux to have “connection-less” discovery work (loopback adapter only). See https://github.com/objectcomputing/OpenDDS/pull/1953.

loopback multicast join

---

dds/DCPS/RTPS/ICE/Ice.cpp
dds/DCPS/RTPS/ICE/Ice.h

Problem
-------
The connectivity check with the RtpsRelay fails if a single message is
lost, either the binding request or its response.
Solution
--------
Send the request multiple times before reporting a disconnect.
Currently, this is hard-coded to 3 but could be made configurable.

Relay connectivity check is fragile

---

dds/DCPS/RTPS/Sedp.cpp

Problem
-------
The code path for discovered readers and writers in secure SEDP checks
that the topic is valid.  However, the topic name is not populated for
unregister/dispose.  Consequently, unregister/dispose messages are not
processed.
Solution
--------
Move the check later to ensure that the topic name is populated.

SEDP ignores dispose messages with security

---

dds/DCPS/RTPS/Sedp.cpp
dds/DCPS/RTPS/Sedp.h
dds/DCPS/transport/framework/TransportClient.h

Problem
-------
Every input message received by SEDP is placed in a JobQueue.  This
queueing is unnecessary.  Association complete messages are also
queued.  This was to avoid a deadlock but deadlock can be avoided by
checking if the writer/reader is reliable.  Finally, removal of a
subscription/publication queued a job to remove it from the BIT.  This
queueing is unnecessary.
Solution
--------
Remove the queueing.

Sedp needlessly defers work

---

dds/DCPS/DiscoveryBase.h

Problem
-------
With no timeout, the thread monitoring loop in DdsUpcalls::svc turn
into an infinite loop.
Solution
--------
Handle the case of no timeout for monitoring.

Infinite loop in DdsUpcalls::svc

---

dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp

Problem
-------
The "association complete" callback for a reliable RTPS writer is
called when the writer receives the first acknack for a reader.  If
the writer is durable, it causes the writer to send the durable data
for the new reader.  This is currently done and the end of the ACKNACK
processing.  Durable data is sent in response to an ACKNACK.
Consequently, a reader must send one ACKNACK to enqueue the durable
data and another to retrieve it.
Solution
--------
Invoke the callback earlier so the durable data will be available for
sending in response to the first ACKNACK.

RTPS Transport does send durable data for first ACKNACK

---

dds/DCPS/DiscoveryBase.h
dds/DCPS/RTPS/Spdp.cpp
dds/DCPS/RTPS/Spdp.h

Problem
-------
Every time the SPDP transport sends a local announcement, it loops
over all discovered participants to check if they have expired.  This
is not scalable.  Furthermore, participants with long resend periods
may accumulate a number of long expired participants.
Solution
--------
Use a TimeQueue and sporadic task to process the lease expirations as needed.

SPDP lease processing is not scalable

---

dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp
dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.h

Problem
-------
For each message, a (reliable) RtpsWriter loops through all readers to
check that none are expecting durable data for the purpose of
inserting a gap if a sequence number is skipped.
Solution
--------
Gaps should only be sent when the maximum sequence number increases.
When this happens, all readers can receive a gap.

RTPS reliable writes are not scalable

---

tools/rtpsrelay/HandlerStatisticsReporter.h
tools/rtpsrelay/RelayHandler.cpp
tools/rtpsrelay/RelayHandler.h
tools/rtpsrelay/RelayStatisticsReporter.h
tools/rtpsrelay/lib/Relay.idl

Problem
-------
The RtpsRelay uses non-blocking I/O.  In practice, it received
EWOULDBLOCK/EAGAIN errors when sending.  Increasing the OS UDP send
buffer size did not help.  The user-space UDP send buffer size is at a
maximum.
Solution
--------
Resurrect the logic that queues output messages to handle bursts.  The
next step may be to bound the length of the output queue.

RtpsRelay drops message when bursting

---

dds/DCPS/ReactorTask.cpp

Problem
-------
The thread monitoring code in ReactorTask runs for one cycle and then
degenerates into a busy loop.
Solution
--------
Reset the time given to run the event loop.

ReactorTask has a busy loop

---

dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp
dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.h

Problem
-------
An RtpsWriter loops through every reader to determine if it sent a
nack and is expecting data.
Solution
--------
Maintain a set of readers that have sent a nack.

RTPS send nack replies is not scalable

---

dds/DCPS/RTPS/RtpsDiscovery.cpp
dds/DCPS/RTPS/RtpsDiscovery.h
dds/DCPS/RTPS/Spdp.cpp

Problem
-------
When using the RtpsRelay and ICE, the SPDP port will send STUN packets
to both the SPDP and SEDP port of the relay.  In practice, this
confuses the router and the observed behavior is that all traffic from
the relay's SPDP port was dropped.  The SEDP and DATA channels when
using the same router are not affected.
Solution
--------
Add configuration so that SPDP will send STUN to the SPDP port of the RtpsRelay.

Some routers confused over STUN traffic

---

tools/rtpsrelay/HandlerStatisticsReporter.h
tools/rtpsrelay/ParticipantStatisticsReporter.h
tools/rtpsrelay/RelayHandler.cpp
tools/rtpsrelay/RelayHandler.h
tools/rtpsrelay/RelayStatisticsReporter.h
tools/rtpsrelay/lib/Relay.idl

Problem
-------
When a client sends a message to the RtpsRelay it may get forwarded to
N other clients.  The number N is the gain and is an important
statistic for the RtpsRelay as it will be more performant for small N
and can be used to diagnose potential scalability problems.
Messages where all submessages are prefixed with INFO_DST must be sent
to all named destinations (if they exist).  Otherwise, the relay must
forward the message using the association table.  When applied to
gain, the former is gain for directed messages and the latter is gain
for undirected messages.
Currently, the RtpsRelay does not distinguish these two cases.
Solution
--------
Add statistics for the maximum directed and undirected gain observed
over a statistics interval.

RtpsRelay stats don't distinguish directed and undirected gain

---

dds/DCPS/transport/rtps_udp/RtpsUdpTransport.cpp

This fixes unwanted multicast joins when using DCPSDefaultAddress

Use DCPSDefaultAddress to Initialize multicast_interface for RtpsUdpTransport Config

---

dds/DCPS/RTPS/Spdp.cpp

In order to avoid branching on uninitialized bytes / silence valgrind warnings.

Avoid RTPX check when RTPS has already succeeded 

---

dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp

Problem
-------
When processing an ack, the RtpsWriter iterates over all readers to
determine the minimum sequence number that must be retained and
therefore which samples can be released.
Solution
--------
Use the leading and lagging maps to find the minimum without iteration.

RTPS "acked by all" logic is not scalable

---

tools/rtpsrelay/RelayHandler.cpp
tools/rtpsrelay/RelayHandler.h

Problem
-------
The predicate for determining if a messagage was directed or
undirected is incorrect because `to` will be non-empty for undirected
sends.
Solution
--------
Determine if a message is undirected before populating `to` from the
association table.

max_undirected_gain is always zero

---

dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp
dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.h

Problem
-------
Reliable RtpsReaders do not send an ACKNACK to complete association.
Reliable RtpsWriters do not handle the case where a reader is
rediscovered after a network partition.  Reliable readers do not
perform adequate cleanup when a writer is removed.
Solution
--------
Add logic for readers to send ACKNAcks to complete association.  Add
logic to reset a reader.  Add cleanup logic.

Acknack processing does not handle reset

---

dds/DCPS/SporadicTask.h

The RcHandle in sporadictask.h was causing failures for the monitor task.  It has been changed to a WeakRcHandle instead, and the functions that use it now have a lock to grab a strong RcHandle.  Also added an error if that lock is not found.

Monitor Test Failure due to strong RcHandle

---

dds/DCPS/ReactorTask.h

Remove override from ReactorTask::open

---

dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp
tests/DCPS/Thrasher/ParticipantTask.cpp

Problem
-------
* The Thrasher Test does not allocate a large enough send buffer to
account for control messages in RTPS.
* An ACK does not clear the requested changes for a reader.  This may
cause the writer to send useless GAPs.
Solution
--------
* Increase the `nak_depth` parameter.
* Clear the requested changes for each received ACKNACK.

Reliabilty fixes for Thrasher test

---

dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp
dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.h

Problem
-------
When a reliable writer writes a sample, all of the reader will now be
lagging.  The writer only needs to send a single non-directed
heartbeat instead of sending a directed heartbeat to each reader.
Solution
--------
Send a non-directed heartbeat for the identified case which is not
applicable to the participant volatile secure writer.

RTPS direct heartbeats unnecessarily

---

dds/idl/dds_generator.h
dds/idl/typeobject_generator.cpp

Skip generating functions in typeobject_generator if the type map is
empty. Had to also rewrite the output stream to remove a function
declaration, but that should be okay since the file should be basically
empty.

XTypes: opendds_idl: Add Missing Include, Unused Func Warn

---

dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp

Problem
-------
If a writer is writing while the first reader associates, the initial
sequence number will jump from 0 to N creating a gap from 1 to N-1
which fouls durable readers.
Solution
--------
Don't insert a gap from 1 to N-1.

Durable writers can skip initial sequence numbers in RTPS

---

dds/DCPS/transport/framework/QueueTaskBase_T.h

This fixes an internal thread status monitoring high cpu usage issue.

Configure QueueTaskBase ACE_Condition to use monotonic time.

---

tests/DCPS/Monitor/publisher.cpp
tests/DCPS/Monitor/run_test.pl
tests/DCPS/Monitor/subscriber.cpp

Recent changes caused slower machines to have longer startup times for parts involved with the monitor test.  This means a few messages are missed at the startup, which is not a big deal but is marked as a test failure.  This should be seen as an adjustment to allow the test to be more lenient by allowing some of those missed messages at the start. A manual sleep also attempts to help delay the startup of the participant giving the other pieces more time to get set up.

Monitor Test Too Few Messages Received

---

bin/dcps_tests.lst
tests/DCPS/Thrasher/ParticipantTask.cpp
tests/DCPS/Thrasher/ParticipantTask.h
tests/DCPS/Thrasher/Publisher.cpp
tests/DCPS/Thrasher/Subscriber.cpp
tests/DCPS/Thrasher/run_test.pl

Problem
--------
The Thrasher tests create T reliable writers in T participants and 1
reliable subscriber.  The writers write N messages and the reader
checks that all messages are received.  The test stresses
discovery (especially RTPS) and reliability including features like
waiting for acknowledgements and waiting for match status.  Durability
is implicitly tested through discovery.  The test could be used to
diagnose problems with durability if it were extended.
Solution
--------
Add flags to enable durability.  When the writer is durable, it either
1) waits for a match and then writes data or 2) writes data and then
waits for a match.

Thrasher test lacks durability scenarios

---

performance-tests/bench_2/node_controller/main.cpp

Due to signal handling code in WorkerManager's constructor, delay its creation until after reception of full scenario description in order to avoid preventing signals between runs. Also check to see if we received a signal at the end of a run to speed up shutdown.

Bench2: Fix Signal Handling Hang-Up in Node Controller

---

dds/DCPS/transport/framework/TransportClient.cpp
dds/DCPS/transport/framework/TransportImpl.h
dds/DCPS/transport/multicast/MulticastTransport.cpp
dds/DCPS/transport/multicast/MulticastTransport.h
dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp
dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.h
dds/DCPS/transport/rtps_udp/RtpsUdpTransport.cpp
dds/DCPS/transport/rtps_udp/RtpsUdpTransport.h
dds/DCPS/transport/shmem/ShmemTransport.cpp
dds/DCPS/transport/shmem/ShmemTransport.h
dds/DCPS/transport/tcp/TcpTransport.cpp
dds/DCPS/transport/tcp/TcpTransport.h
dds/DCPS/transport/udp/UdpTransport.cpp
dds/DCPS/transport/udp/UdpTransport.h
performance-tests/bench_2/worker/WorkerDataReaderListener.cpp
performance-tests/bench_2/worker/WorkerDataWriterListener.cpp
performance-tests/bench_2/worker/main.cpp

Problem
-------
When a reliable TransportClient using RTPS associates with a reliable
peer that peer is put in a pending state.  If the client disassociates
with the peer while it is still pending, then it is not cleaned up in
the datalink.  Consequently, the remote peers linger and consume
resources trying to associate.
Solution
--------
Inform the datalink that the pending peer should be disassociated.

Pending RTPS writers/readers orphaned

---

dds/DCPS/BuiltInTopicUtils.h
dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp
dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.h

Problem
-------
The reliable SPDP writer in the application participant of the
RtpsRelay can send undirected heartbeats that will be dropped by the
relay.
Solution
--------
Force directed heartbeats for the reliable SPDP writer.  This is a
work-around that may be removed in the future if the reliable SPDP
writer is disabled in the application participant.  Otherwise,
additional configuration plumbing will be needed to accomplish the
same result.

Application participant sends non-directed heartbeats

---

dds/DCPS/DisjointSequence.cpp
dds/DCPS/DisjointSequence.h
dds/DCPS/transport/framework/TransportSendBuffer.h
dds/DCPS/transport/framework/TransportSendBuffer.inl
dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp
dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.h
tests/DCPS/UnitTests/DisjointSequence.cpp

Problem
-------
The `send_and_gather_nack_replies` function attempts to not
send (undirected) gaps if a durable reader is detected.  This is
flawed in two ways.  First, a durable writer should never send an
undirected gap because it cannot know when a potential reader will
come online.  Second, the existing logic only checks readers that need
a reply instead of all of the readers when making the determination.
Solution
--------
Re-write `send_and_gather_nack_replies` so that naks for directed data
receive a directed reply (gap or data) and naks for undirected data
receive receive an undirected reply.  Directed data includes durable
resends and messages from the participant volatile secure writer.  The
code for responding to naks for durable data will/should not be
executed until the logic …

Durable RTPS writers may send gaps

---

dds/DCPS/RTPS/Spdp.cpp

Problem
-------
RtpsRelay deployments send directed SPDP announcements with a very
long period.  Furthermore, they send one (and only one) announcement
when a client is first discovered.  If that announcement is lost,
discovery will certainly stall and fail.
Solution
--------
Send an SPDP announcement with an authentication resend.  The client
will send SPDP to the relay frequently so the relay should discover
the client in a timely manner.  The relay will start authentication
resends, which happen with a very small period, so the client will
eventually discover the relay.
The non-secure case is not handled in this commit.

Lost SPDP prevents secure discovery

---

bin/dcps_tests.lst

Currently the test sets up QoS in a way that not every sample is guaranteed.
A subsequent PR will update the QoS and revert this change to reinstate the tests.

Removed durable Thrasher from dcps_tests.lst

---

tests/DCPS/Messenger/Args.h
tests/DCPS/Messenger/DataReaderListener.cpp
tests/DCPS/Messenger/Writer.cpp

* tests/DCPS/Messenger/Args.h:
* tests/DCPS/Messenger/DataReaderListener.cpp:
* tests/DCPS/Messenger/Writer.cpp:

Use size_t to get rid of some c-style casts

---

dds/DCPS/RTPS/GuidGenerator.cpp

* dds/DCPS/RTPS/GuidGenerator.cpp:

Remove workaround for ACE 6.0

---

performance-tests/bench_2/worker/WriteAction.cpp
performance-tests/bench_2/worker/WriteAction.h
performance-tests/bench_2/worker/configs/simple_action_config.json

... but make it configurable so we can change as needed when testing needs demand it.

Bench2: Make worker's WriteAction use infinite wait_for_acks on stop()

---

performance-tests/bench_2/test_controller/main.cpp
tests/DCPS/TcpReconnect/publisher.cpp

OpenDDS/tests/DCPS/TcpReconnect/publisher.cpp:92:32: warning: format string is not a string literal (potentially insecure)
OpenDDS/performance-tests/bench_2/test_controller/main.cpp:10:32: warning: unknown warning group '-Wclass-memaccess'
OpenDDS/performance-tests/bench_2/worker/main.cpp:16:32: warning: unknown warning group '-Wclass-memaccess', ignored [-Wunknown-warning-option]

clang warning fixes

---

dds/DCPS/NetworkConfigMonitor.h

A seg fault would occur when trying to run rtps on android api 30 due to a missing export. This adds that export.

Segmentation Fault Due to Missing Export Android Api30

---

tests/security/attributes/run_test.pl

Depends on a perl module which is not part a default RHEL installation. Didn't add real functionality to the test, the progress is already visible because of the test count is shown

Remove usage of localtime

---

tests/DCPS/Messenger/DataReaderListener.cpp

* tests/DCPS/Messenger/DataReaderListener.cpp:

Change expected to size_t to fix comparison warning

---

dds/DCPS/security/CryptoBuiltInImpl.cpp

* dds/DCPS/security/CryptoBuiltInImpl.cpp:

Fixed unitialized warning on rhel75

---

tools/IntermediateTypeLang/cpp/itl/itl.hpp

```
../../tools/rapidjson/include/rapidjson/document.h: In instantiation of 'void rapidjson::GenericValue<Encoding, Allocator>::SetObjectRaw(rapidjson::GenericValue<Encoding, Allocator>::Member*, rapidjson::SizeType, Allocator&) [with Encoding = rapidjson::UTF8<>; Allocator = rapidjson::MemoryPoolAllocator<>; rapidjson::GenericValue<Encoding, Allocator>::Member = rapidjson::GenericMember<rapidjson::UTF8<>, rapidjson::MemoryPoolAllocator<> >; rapidjson::SizeType = unsigned int]':
../../tools/rapidjson/include/rapidjson/document.h:2363:55: required from 'bool rapidjson::GenericDocument<Encoding, Allocator, StackAllocator>::EndObject(rapidjson::SizeType) [with Encoding = rapidjson::UTF8<>; Allocator = rapidjson::MemoryPoolAllocator<>; StackAllocator = rapidjson::CrtAllocator; …
```

RapidJSON warning fix

---

dds/idl/be_produce.cpp

…current OpenDDS version. Through this check we force our users to regenerate all files with opendds_idl when they change their OpenDDS release
* dds/idl/be_produce.cpp:

Generate check that the generated header still matches with the current OpenDDS version

---

dds/idl/langmap_generator.cpp
tests/DCPS/Compiler/idl_test1_lib/FooDef.idl

* dds/idl/langmap_generator.cpp:
* tests/DCPS/Compiler/idl_test1_lib/FooDef.idl:
Matches the functionality as we have in TAOX11, see https://github.com/RemedyIT/taox11/blob/9719377a200a0859755c1dd4a064a2ebc9e21e2f/ridlbe/c%2B%2B11/templates/cli/hdr/struct_post.erb#L48

Only use {{}} as array initializer for arrays of pod types

---

dds/DCPS/DiscoveryBase.h
dds/DCPS/RTPS/Sedp.cpp
dds/DCPS/RTPS/Spdp.cpp
dds/DCPS/RTPS/Spdp.h

Problem
-------
The auth requester transitions immediately from
HANDSHAKE_STATE_WAITING_FOR_TOKEN to HANDSHAKE_STATE_DONE due to the
fact that association completes immediately.  This causes the
requester to only send the auth final once and not attempt any
resends.
Solution
--------
Eliminate the HANDSHAKE_STATE_WAITING_FOR_TOKEN state.  To handle
resends, a participant will send its most recent auth message when it
receives an auth message when in HANDSHAKE_STATE_DONE.

SPDP stops sending auth final

---

dds/DCPS/Service_Participant.cpp

Problem
-------
Service_Participant::get_discovery can be called from multiple threads
but is not thread safe.
Solution
--------
Add synchronization.

Service_Participant::get_discovery is not thread safe

---

tools/rtpsrelay/utility.h

Fixed unitialized warning on rhel75 with gcc48

---

tests/transport/best_effort_reader/SocketWriter.cpp

tests/transport/best_effort_reader/run_test.pl
[Details] 2020-12-09 23:16:23: ERROR: publisher returned 1 (started at 2020-12-09 23:16:23)
[Details] ERROR: subscriber timedout
[Details] 2020-12-09 23:16:48: ERROR: subscriber returned -1 (started at 2020-12-09 23:16:23)
[Details] 2020-12-09 23:16:23.589@LM_ERROR@(5812|880) ERROR: in socket_.send()bad address
[Details] test FAILED.
[Details] ERROR: test returned 1
[Details] 2020-12-09 23:16:48: ERROR: publisher returned 1 (started at 2020-12-09 23:16:48)
[Details] ERROR: subscriber timedout
[Details] 2020-12-09 23:17:13: ERROR: subscriber returned -1 (started at 2020-12-09 23:16:48)
[Details] 2020-12-09 23:16:48.771@LM_ERROR@(3476|6476) ERROR: in socket_.send()bad address
[Details] test FAILED.
[Details] ERROR: test returned 1

Best Effort Reader Test Fix for IPv6

---

dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp
dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.h

Problem
-------
The maxiumum expected sequence number is tracked for each reader of a
volatile writer.  The maximum sequence number doesn't advance unless a
message is sent to the reader.  At steady state, there will be one
reader whose maximum expected sequence number is lower than every
other reader.  This places a bound on what can be released by the
`acked_by_all_helper_i` function.  Consequently, the send buffer for
the volatile writer will accumulate messages in a long-running
process.
Solution
--------
Track the sequence numbers that send to each volatile reader and use
these to free elements in the send buffer using the assumption that
each sample is directed at a single reader.

Volatile Writer leaks resources

---

dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp

Problem
-------
Before, the datalink thread was responsible for invoking the callback
that replayed durable data.  Thus, durable replay was done when the
call returned.  Now, the discovery and/or user thread is responsible
for replaying durable data and it might not be finished by the time
the first nack arrives.  This results in a request that is gapped
leading to missed durable data.
Solution
--------
Prevent further nack processing by clearing the requests if the
durable data is not complete.

Durable replay not complete for nack

---

dds/DCPS/RTPS/Spdp.cpp
dds/DCPS/RTPS/Spdp.h

Problem
-------
A secure remote participant was never published to the participant BIT
and, consequently, the location topic was never published.
Solution
--------
When security is enabled, publish the participant in the BIT when the
secure SPDP message arrives.  Add the ability to publish the location
topic even when there are no updates.

Participant BIT and location BIT not populated

---

dds/DCPS/RTPS/Sedp.cpp
dds/DCPS/RTPS/Sedp.h
dds/DCPS/RTPS/Spdp.cpp

Problem
-------
The main challenge in reauthentication is re-keying the volatile
reader and writer.  The existing approach of disassociating and
associating does not work with the new and improved handling of crypto
tokens.  Specifically, the association does not result in the new
shared secret being installed.
Solution
--------
After disassociating, remove the crypto tokens for the remote volatile
reader and writer so that the call to associate will install the new
shared secret.

Reauthentication fails

---

dds/DCPS/RTPS/Spdp.cpp

Problem
-------
Suppose a request authenticates and sends the final.  The replier gets
the final to complete authentication.  If a message is duplicated or
resent for any reason, then the receiving participant will resend,
causing the other to resend, etc.
Solution
--------
Break the symmetry by only allow the request to resend when
authentication is complete.

Authentication gets into a message shootout

---

dds/DCPS/DiscoveryBase.h
dds/DCPS/RTPS/Sedp.cpp
dds/DCPS/security/framework/HandleRegistry.cpp
dds/DCPS/security/framework/HandleRegistry.h

Problem
-------
The HandleRegistry returns a default constructed
EndpointSecurityAttributes object which may contain uninitialized
values.  This causes the RtpsUdpReceiveStrategy to try to decode
messages that should not be decoded.
Solution
--------
Return an initialized EndpointSecurityAttributes object.

EndpointSecurityAttributes not initialized

---

dds/DCPS/ConditionVariable.h
tests/DCPS/ContentFilteredTopic/ContentFilteredTopicTest.cpp

Problem
-------
Passing a deadline of zero causes the condition to timeout immediately
instead of blocking.  This typically leads to a busy loop.
Solution
--------
Pass in null pointer when appropriate to cause the desired blocking behavior.

Improper wait in ConditionVariable with no deadline

---

tests/DCPS/C++11/Messenger/Subscriber/subscriber.cpp
tests/DCPS/DPFactoryQos/DataReaderListener.cpp
tests/DCPS/FooTest3_0/DataReaderListener.cpp
tests/DCPS/GroupPresentation/SubscriberListener.cpp
tests/DCPS/Monitor/DPMDataReaderListener.cpp
tests/DCPS/Monitor/DRMDataReaderListener.cpp
tests/DCPS/Monitor/DRPerMDataReaderListener.cpp
tests/DCPS/Monitor/DWMDataReaderListener.cpp
tests/DCPS/Monitor/DWPerMDataReaderListener.cpp
tests/DCPS/Monitor/DataReaderListener.cpp
tests/DCPS/Monitor/PublisherMDataReaderListener.cpp
tests/DCPS/Monitor/SPMDataReaderListener.cpp
tests/DCPS/Monitor/SubscriberMDataReaderListener.cpp
tests/DCPS/Monitor/TopicMDataReaderListener.cpp
tests/DCPS/Monitor/TransportMDataReaderListener.cpp
tests/DCPS/NotifyTest/DataReaderListener.cpp
tests/DCPS/RtiSerialization/DataReaderListener.cpp
tests/DCPS/RtpsRelay/Smoke/DataReaderListener.cpp
tests/DCPS/SetQosDeadline/DataReaderListener.cpp
tests/DCPS/SetQosPartition/DataReaderListener.cpp
tests/DCPS/SharedTransport/TestCase.cpp
tests/DCPS/SkipSerialize/DataReaderListener.cpp
tests/DCPS/StringKey/DataReaderListener.cpp
tests/DCPS/TcpReconnect/DataReaderListener.cpp

* tests/DCPS/C++11/Messenger/Subscriber/subscriber.cpp:
* tests/DCPS/DPFactoryQos/DataReaderListener.cpp:
* tests/DCPS/FooTest3_0/DataReaderListener.cpp:
* tests/DCPS/GroupPresentation/SubscriberListener.cpp:
* tests/DCPS/Monitor/DPMDataReaderListener.cpp:
* tests/DCPS/Monitor/DRMDataReaderListener.cpp:
* tests/DCPS/Monitor/DRPerMDataReaderListener.cpp:
* tests/DCPS/Monitor/DWMDataReaderListener.cpp:
* tests/DCPS/Monitor/DWPerMDataReaderListener.cpp:
* tests/DCPS/Monitor/DataReaderListener.cpp:
* tests/DCPS/Monitor/PublisherMDataReaderListener.cpp:
* tests/DCPS/Monitor/SPMDataReaderListener.cpp:
* tests/DCPS/Monitor/SubscriberMDataReaderListener.cpp:
* tests/DCPS/Monitor/TopicMDataReaderListener.cpp:
* tests/DCPS/Monitor/TransportMDataReaderListener.cpp:
* …

Log instance_state as readable string

---

dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp
dds/DCPS/transport/rtps_udp/RtpsUdpInst.cpp
dds/DCPS/transport/rtps_udp/RtpsUdpInst.h

Problem
-------
Applications setting max_message_size should set max_bundle_size.
Consequently, max_bundle_size should just be derived from
max_message_size to eliminate a configuration variable.
Solution
--------
Derive max_bundle_size from max_message_size.

max_bundle_size is unnecessary

---

dds/DCPS/InstanceDataSampleList.cpp
dds/DCPS/InstanceDataSampleList.h
dds/DCPS/InstanceDataSampleList.inl
dds/DCPS/SendStateDataSampleList.cpp
dds/DCPS/SendStateDataSampleList.h
dds/DCPS/SendStateDataSampleList.inl
dds/DCPS/WriterDataSampleList.cpp
dds/DCPS/WriterDataSampleList.h
dds/DCPS/WriterDataSampleList.inl

- Some enqueue/dequeue functions in the `InstanceDataSampleList`, `WriterDataSampleList`, and `SendStateDataSampleList` classes currently haven't properly updated the corresponding pointers in the affected `DataSampleElement` nodes.
- This also removes redundant logic and does reformatting for those list classes.

Update DataSampleElement's pointers in its related lists

---

dds/DCPS/DiscoveryBase.h
dds/DCPS/RTPS/Spdp.cpp

Problem
-------
Participant location updates are enqueued and processed but not
published until the participant appears in the BITs.  This is
problematic when using discovery since the participant will only
appear in the BITs after secure discovery.  Consquently, the location
may never get published or get published with an incorrect mask.
Solution
--------
Don't process the queue until the participant appears in the BITs.

Participant location updates ignored

---

dds/DCPS/transport/framework/TransportRegistry.cpp
dds/DCPS/transport/framework/TransportRegistry.h

xtypes branch prefers to use this wrapper instead of ACE's class directly

Use ConditionVariable in TransportRegistry

---

azure-pipelines.yml

For Azure pipelines tests moved wchar option from Debug to Release for VS 2017, as the test was running out of space

WCHAR test relocation for Azure Pipelines

---

configure
java/idl2jni/codegen/im_jni.cpp

Remaining warning is: 
/home/calabresec/3_16/testandroid/OpenDDS/build/target/ACE_wrappers/ace/Stack_Trace.cpp:55:1: warning: unused function 'determine_starting_frame' [-Wunused-function]
This has been a warning dealt with in the past and probably requires changes to ace.  It was fixed by us in the past to silence the warning on a different platform: https://github.com/DOCGroup/ACE_TAO/blob/6ac224067c083571fd1b00940e066e9ad3e2d582/ACE/ace/Stack_Trace.cpp#L746

Suppress ACE warnings for android and idl2jni boolean switch warning

---

dds/DCPS/transport/framework/TransportReceiveStrategy_T.cpp

Problem
-------
The transport receive strategy doesn't cleanup buffers (allocated with
`handle_simple_dds_input`).
Solution
--------
Delete the buffers in the destructor.

Transport receive strategy doesn't cleanup buffers

---

dds/DCPS/security/AccessControlBuiltInImpl.cpp
dds/DCPS/security/AccessControlBuiltInImpl.h
dds/DCPS/security/AuthenticationBuiltInImpl.cpp
dds/DCPS/security/AuthenticationBuiltInImpl.h
dds/DCPS/security/CryptoBuiltInImpl.cpp
dds/DCPS/security/framework/SecurityConfig.cpp
dds/DCPS/security/framework/SecurityConfig.h
tests/security/unit_tests/CryptoTransformTest.cpp

Problem
-------
The security plugins can't use reference counting for cleanup which
makes it more susceptible to resource leaks.
Solution
--------
This commit adds logging to monitor the growth of security related
data structures.  Additionally, a resource leak related to revoking
permissions was identified and fixed.

Security plugins leak resources

---

dds/DCPS/LinuxNetworkConfigMonitor.cpp

Reporting it as an error was bothering users as it gave the impression something unexpected had occurred in OpenDDS.

LinuxNetworkConfigMonitor error is now a warning for android

---

dds/DCPS/RTPS/Spdp.cpp
tests/transport/spdp/spdp_transport.cpp

Problem
-------
SPDP ignores the port of the SPDP local address.  Setting the SPDP
local address to just a port means that the request port number is
effectively ignored.
Solution
--------
Use the port of the SPDP local address so long as it is not zero.

Port for SPDP local address not respected

---

MPC/config/dcps_cm.mpb
dds/DCPS/DataReaderImpl_T.h
dds/DCPS/DiscoveryBase.h
dds/DCPS/GuidUtils.h
dds/DCPS/PoolAllocator.h
dds/DCPS/RTPS/Spdp.cpp
dds/DCPS/ReactorTask.cpp
dds/DCPS/ReactorTask.h
dds/DCPS/ReactorTask.inl
dds/DCPS/ReceivedDataElementList.h
dds/DCPS/Service_Participant.cpp
dds/DCPS/Service_Participant.h
dds/DCPS/TopicDescriptionImpl.h
dds/DCPS/transport/framework/QueueTaskBase_T.h
dds/DdsDcpsCore.idl
dds/FACE/FaceTSS.cpp
java/tests/internal_thread_status/InternalThreadListener.java
java/tests/internal_thread_status/internal_thread_status_test.mpc
tests/DCPS/InternalThreadStatus/InternalThreadStatus.mpc
tests/DCPS/InternalThreadStatus/InternalThreadStatusListenerImpl.cpp
tests/DCPS/InternalThreadStatus/publisher.cpp
tests/DCPS/UnitTests/.gitignore
tests/DCPS/UnitTests/GuidUtils.cpp
tests/DCPS/UnitTests/UnitTests.mpc

When using internal thread status BIT with conditions it's possible for one publish thread status to knock out the previous one before it can be read because the history depth is one and they are in the same instance.
Also:
- Refactor thread monitoring code by making common functions for generating the thread key and updating thread status.
- Create `OpenDDS::DCPS::String` to eventually replace `OPENDDS_STRING`.
- Other minor miscellaneous fixes.

[xtypes] Improve Thread Monitoring

---

.github/workflows/build_and_test.yml
.github/workflows/cancel_previous_runs.yml
.github/workflows/check_test_results.yml

The permissions for the previous round of GitHub actions workflows didn't work for pull requests, and according to [this article](https://securitylab.github.com/research/github-actions-preventing-pwn-requests), switching to pull_request_target was problematic for other reasons. This PR adjusts the workflows to avoid security vulnerabilities by splitting it into three separate workflows (cancel previous, build & test, and check results). It also adds ACE_TAO artifact caching for a small performance improvement.

Fix Workflow Permissions Issues and Add ACE_TAO Artifact Caching

---

dds/idl/marshal_generator.cpp
tests/DCPS/Compiler/TryConstruct/TryConstruct.idl

If there were a sequence or array in the 1st branch of the union it was causing an idl error because tmp would be undefined but used.  This fixes that.

Define "tmp" variable for sequence and array as first branch in unions

---

tests/DCPS/DomainRange/DomainRangeTest.cpp
tests/DCPS/DomainRange/run_test.pl

Domain 10 is problematic no matter what on Flea, I couldn't find why, and even after a restart it still fails if domain 10 is attempted to be used. It also appears domain 11 is problematic.
Additionally, having at least 5 readers with 5 domains fails on Flea.

DomainRange test fails on flea

---

bin/dcps_tests.lst
tests/DCPS/Compiler/TryConstruct/C++11/TryConstruct_C++11.mpc
tests/DCPS/Compiler/TryConstruct/Compiler.mpc

TC Test utilizes std strings and widestrings meaning it is incompatible with safety profile.  The test would require a good deal of changes to make it compliant, so for now we will just block it from being used with safety profile.

Prevent TryConstruct test from building or running for safety builds.

---

.github/workflows/check_test_results.yml

As long as the artifact has the correct name (```*_autobuild_output```) and is correctly formatted to contain the contents of the autobuild directory (most importantly, the JUnit xml report and a file containing the SHA of the triggering commit), this workflow should now build a matrix of publishing jobs based on discovered artifact names and will update the corresponding workflows and PRs with any test jobs that get run by the build_and_test workflow.
The biggest advantage here is that we can change, add, or remove test jobs with changes to a single file without needing to update this workflow in the future. We can even temporarily change them to check additional (or fewer) workflows, then change them back in the same PR when we're confident in the results.
Important Note: The current …

GitHub Actions: Update check_test_results action to generically handle test job artifacts

---

tests/DCPS/DataRepresentation/DataRepresentation.cpp
tests/DCPS/DataRepresentation/DataRepresentation.mpc

Sorry, I misunderstood how static libraries interacted with includes.  This should fix the problems on spider and bee regarding the Data Representation test.

Static Libs in DataRepresentation test need linking

---

tests/DCPS/WriteDataContainer/WriteDataContainerTest.cpp

When ownership_profile is disabled, DataWriter's HISTORY QoS must have kind of KEEP_LAST and depth of 1. Some test cases in the test currently set the HISTORY QoS to KEEP_ALL. This PR is to fix that.

Fix WriteDataContainerTest for when ownership_profile is disabled

---

dds/DCPS/RTPS/Sedp.cpp
dds/DCPS/RTPS/Spdp.cpp

To fix issue where type lookup service writer thinks it's already associated with a reader when it tries to associate, so it fails to fully associate.
Also clear deferred builtin samples that are send and other more minor changes.

Init Remote Associated Endpoints to Zero

---

dds/idl/dds_generator.cpp

Now creates a temp var that is initialized then assigned to the member.  Context is needed for non unions to prevent multiple declarations.

type_to_default patch for long double

---

dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp
dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.h

Problem
-------
OpenDDS's implementation of RTPS is not as responsive as it could be.
Specifically, various activities are gated by timers which leads to
idle time.
Solution
--------
* Send preassociation heartbeats and acknacks at the time of
association.
* Send preassociation heartbeats/acknacks in response to
acknacks/heartbeats.
* Send heartbeats after replying to a nack.

RTPS is not as responsive as it could be

---

bin/dcps_tests.lst
tests/DCPS/DataRepresentation/DataRepresentation.cpp
tests/DCPS/DataRepresentation/DataRepresentation.mpc

DR test without args is blocked in the tests list because it tries to use info repo.  Other fixes are to allow the test to compile on safety builds.

Data Representation test Safety Profile compatibility

---

bin/PerlDDS/Run_Test.pm
tests/DCPS/XTypes/Pub/XTypesPublisher.cpp
tests/DCPS/XTypes/Sub/XTypesSubscriber.cpp
tests/DCPS/XTypes/run_test.pl

Reviewed the way that run_test.pl in tests/DCPS/XTypes uses the perl test framework and what it expects in terms of timing of tests.  Sleep is not necessary since the Perl script can determine when the child process(es) exit.
In addition to the Perl part of this issue, replace sleep in the C++ test code with the use of WaitSet and Conditions.

Changed XType test flow to event driven, removing Sleep statements.

---

.github/workflows/build_and_test.yml
bin/PerlDDS/Run_Test.pm
bin/dcps_tests.lst
dds/DCPS/RTPS/Spdp.cpp
dds/DCPS/StaticDiscovery.cpp
dds/DCPS/StaticDiscovery.h
dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp
dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.h
dds/InfoRepo/DCPSInfo_i.cpp
performance-tests/bench_2/builder/DataReader.cpp
performance-tests/bench_2/builder/Topic.cpp
performance-tests/bench_2/builder/Topic.h
performance-tests/bench_2/node_controller/ProcessStatsCollector.cpp
performance-tests/bench_2/node_controller/ProcessStatsCollector.h
performance-tests/bench_2/worker/WorkerDataReaderListener.cpp
performance-tests/bench_2/worker/main.cpp
tests/DCPS/ContentFilteredTopic/ContentFilteredTopicTest.cpp
tests/DCPS/StaticDiscovery/DataReaderListenerImpl.h
tools/modeling/codegen/model/Service_T.cpp
tools/modeling/tests/modeling_tests.lst
tools/rtpsrelay/lib/QosIndex.h

Several Updates:
- Split "build" and "test" jobs into two parts for greater flexibility
- Update output format to use correct "triggering commit" SHA for the "Check Test Results" action
- Add build warning annotations for build jobs
- Small improvements in build flag coverage

Update "Build & Test" Action

---

dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp

Problem
-------
If multiple participants are exchanging tokens at once, a volatile
reader may ack a sequence number beyond what was expected.  This case
is not handled by the current leader/lagger tracking.
Solution
--------
Allow a volatile reader to ack beyond it's expected max and adjust
it's expected max if it does so.

Volatile reader can ack beyond expected maximum sequence number

---

dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp

Problem
-------
For background see #2338.  A reader that acks beyond its expected max
sequence number may already be a leader.  The existing code only
removes it from the lagger set so it will be inserted twice into the
leader SNRIS and cause an assert.
Solution
--------
Generalize code so that the reader is removed from the correct SNRIS.

Volatile reader may go from leader to leader

---

dds/DCPS/Service_Participant.cpp
dds/DCPS/Service_Participant.h
dds/idl/marshal_generator.cpp
dds/idl/typeobject_generator.cpp

The get_minimal_type_map function call in typeobject_generator.cpp was not thread safe and was possibly the cause of an error occurring on bee where TLS would fail.  This is a fix to make that section of code thread safe.  I did not see the TLS error in my testing on bee.

get_minimal_type_map_private call not thread safe for cpp03

---

dds/DCPS/RTPS/RtpsDiscovery.cpp
dds/DCPS/RTPS/RtpsDiscovery.h
dds/DCPS/RTPS/Sedp.cpp

Problem
-------
RtpsDiscovery can be delayed by dropped messages.  By default, these
messages will only be retried after the default heartbeat period of 1
second.
Solution
--------
Expose the heartbeat period.

RtpsDiscovery does not expose heartbeat period

---

dds/DCPS/RTPS/RtpsDiscovery.cpp

Problem
-------
The heartbeat period for SEDP cannot be set through a configuration
file.  See #2380.
Solution
--------
Add `SedpHeartbeatPeriod` configuration parameter.

Heartbeat period not available for configuration in RTPS Discovery

---

dds/DCPS/SubscriberImpl.cpp
dds/DCPS/SubscriberImpl.h

Mainly to say the topic name in case the reader is builtin, because it would have an unknown guid.

Tweak delete_datareader Precondition Warning

---

tests/DCPS/Messenger/Args.h
tests/DCPS/Messenger/DataReaderListener.cpp
tests/DCPS/Messenger/DataReaderListener.h
tests/DCPS/Messenger/Messenger.idl
tests/DCPS/Messenger/Messenger.mpc
tests/DCPS/Messenger/Writer.cpp
tests/DCPS/Messenger/Writer.h
tests/DCPS/Messenger/publisher.cpp
tests/DCPS/Messenger/run_test.pl
tests/DCPS/Messenger/stack_subscriber.cpp
tests/DCPS/Messenger/subscriber.cpp

Since this test always seems to get copied to make new tests, let's reduce the number of bad habits and anachronisms that will get copied in the future.
- Make includes match guidelines and added missing includes.
- Replaced var `is_nil` checks with straight checks.
- Replaced `OPENDDS_STRING` with `OpenDDS::DCPS::String`.
- Fixed style of function signatures.
- Removed blank lines of copyright notices. I still don't know the
reason for these.
- Other misc. fixes

Cleanup tests/DCPS/Messenger

---

dds/DCPS/Service_Participant.cpp
dds/DCPS/Service_Participant.h
dds/idl/typeobject_generator.cpp

Problem
-------
Initialization of statics is not thread-safe on all compilers.  See #2362.
Solution
--------
Add lock to serialize initialization of type identifier.

Initialization of TypeIdentifier is not thread-safe

---

dds/DCPS/XTypes/TypeLookupService.cpp
dds/DCPS/XTypes/TypeLookupService.h

Problem
-------
A TypeLookupService object can be accessed concurrently by a user
thread and discovery.  As this access is not serialized, it may lead to
data corruption.
Solution
--------
Add locking.

TypeLookupService is not thread-safe

---

dds/DCPS/RTPS/ParameterListConverter.cpp
dds/DCPS/RTPS/RtpsCore.idl
dds/DCPS/transport/rtps_udp/RtpsSampleHeader.cpp
dds/idl/marshal_generator.cpp
tests/DCPS/UnitTests/ut_ParameterListConverter.cpp

RTPS spec version 2.3 Table 9.13 has footnote 3 that describes how the "kind" field of ReliabilityQosPolicy needs special treatment. Currently we are reusing the same struct from DCPS inside RTPS Discovery, however this is not necessary (since it goes through ParameterListConverter anyway) and causes problems for XTypes (TryConstruct is putting special-case checks into the code generator).

Removed special case encoding of ReliabilityQosPolicy's kind in SEDP

---

dds/DCPS/transport/rtps_udp/RtpsUdpSendStrategy.cpp
dds/DCPS/transport/rtps_udp/RtpsUdpSendStrategy.h

Add protection from multiple threads calling into send_rtps_control (either version) at the same time and clobbering the message block's continuation field, which _needs_ to reliably be null when the Message_Block_Ptr falls out of scope so it doesn't try to release / free any input submessage buffers.

Protect RtpsUdpSendStrategy RTPS header ACE_Message_Block

---

dds/DCPS/transport/framework/TransportReceiveStrategy_T.cpp
dds/DCPS/transport/framework/TransportReceiveStrategy_T.h
dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp
dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.h
dds/DCPS/transport/rtps_udp/RtpsUdpReceiveStrategy.cpp
dds/DCPS/transport/rtps_udp/RtpsUdpReceiveStrategy.h

This implements the ability for threads to enable / disable per-thread submessage queueing, which then allows the bundling algorithm to work more effectively across several calls to send responses. This is most important, for example, when responding to an incoming packet.

Reinstate RTPS Submessage Bundling Using Per-Thread Submessage Queues

---

dds/idl/dds_generator.cpp
dds/idl/dds_generator.h
dds/idl/field_info.cpp
dds/idl/field_info.h
dds/idl/marshal_generator.cpp
dds/idl/metaclass_generator.cpp
dds/idl/metaclass_generator.h
tests/DCPS/Compiler/underscore_fields/.gitignore
tests/DCPS/Compiler/underscore_fields/test.idl
tests/DCPS/Compiler/underscore_fields/underscore_fields.mpc

ROS generates IDL with underscores appended for variable names as captured in the example `test.idl`. The current `opendds_idl` does not generate compilable C++ code. This fix creates a test to capture the expectation and remedies the issue.

opendds_idl fix for underscore fields

---

tools/rtpsrelay/ParticipantListener.cpp
tools/rtpsrelay/PublicationListener.cpp
tools/rtpsrelay/SubscriptionListener.cpp

Problem
-------
Users of the RtpsRelay need a way to correlate DDS guids with
application identifiers stored in user data.
Solution
--------
Log the BuiltinTopicData for discovered participants, publications,
and subscriptions.

RtpsRelay doesn't log user data

---

dds/DCPS/RTPS/Sedp.cpp

Problem
-------
The secure type lookup writers are not discharged of deferred samples
when their association is complete.
Solution
--------
Invoke `send_deferred_samples` on the secure type lookup writers when
their association is complete.

Sedp does not send secure deferred type lookup samples

---

dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp
dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.h

Fix a SEGV caused by race condition in customize_queue_element_helper that causes a sample to be 'delivered' after its allocator has been destroyed.

Fix RTPS Writer Shutdown Race Condition

---

dds/DCPS/transport/framework/TransportSendBuffer.cpp
dds/DCPS/transport/framework/TransportSendBuffer.h
dds/DCPS/transport/framework/TransportSendBuffer.inl
dds/DCPS/transport/multicast/ReliableSession.cpp
dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp
dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.h

Problem
-------
1. `max_sn_` and the send buffer are not synchronized.
`max_sn_` is increased before the corresponding sample is place in
the send buffer.  Between these two activities, the task for
sending heartbeats and nack responses may access `max_sn_` and the
send buffer and send incorrect gaps and heartbeats.
2. Various methods in SingleSendBuffer lacked synchronization.
An inspection of the send buffer revealed that many methods are not
synchronized.  Many of these methods are used as a group and need
to be transactional.
Solution
--------
1. Add missing synchronization to SingleSendBuffer.
2. Introduce a proxy object for the SingleSendBuffer that holds the
lock.
3. Extend SingleSendBuffer with a set of sequence numbers that will
eventually be inserted.  Sequence numbers in this …

SingleSendBuffer lacks synchronization

---

dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp

Problem
-------
The call to `add_on_start_callback` in RtpsUdpDataLink is protected by
the `readers_lock_`.  `add_on_start_callback` can eventually call
`make_reservation` which requires the same lock.
Solution
--------
Move the call to `add_on_start_callback` out of the scope of the `readers_lock_`.

add_on_start_callback deadlock

---

dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp
dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.h

Problem
-------
A heartbeat can elicit an immediate acknack from a reader.  This
acknack in turn could elicit another heartbeat.  This leads to a
downward spiral.
Solution
--------
Resurrect the `readers_expecting_heartbeat_` member and logic to defer
the response to a non-final ack.

Immediate replies to acknacks leads to shootout

---

dds/DCPS/RemoveAssociationSweeper.h

Problem: The scheduled timeout is doing invalid reads / writes on a WriterInfo object that was previously deleted.
Solution: Use the sweeper's mutex to protect access to info_set_ and make better use of RcHandle objects.

Fix Valgrind Issue In RemoveAssociationSweeper

---

dds/DCPS/ReactorInterceptor.cpp
dds/DCPS/ReactorInterceptor.h
dds/DCPS/SporadicTask.h

Problem
-------
Scheduling a SporadicTask is now in the path of writing a reliable
sample.  As the writing thread is not the same as the SporadicTask
thread, the schedule commands will be queued.
Solution
--------
Optimize by not enqueuing a schedule/cancel command when the
previously enqueued command is the same.

SporadicTask schedule is on the reliable write path

---

dds/DCPS/transport/framework/TransportReceiveStrategy_T.cpp
dds/DCPS/transport/framework/TransportReceiveStrategy_T.h
dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp
dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.h

The current implementation of thread queuing for sending bundled RTPS submessages uses copy-based insertion and doesn't leverage the fact that the calling context no longer needs access to the created RTPS submessages. Without full support for C++11, one potential avenue for improvement come from using std::vector's swap method to avoid the unnecessary copy.
In addition, make use of a scoped object for controlling begin / end of thread queuing for ease of use and maintainability.
And lastly, a bit of logging cleanup to avoid shadowing certain variables and to make log message formats consistent.

Minor Bundling Improvements and Logging Cleanup

---

tests/DCPS/QueryCondition/QueryConditionTest.cpp

Test code uses a quoted string, which seems to fail at runtime currently, see issue #2449

Test extension for query condition using a string

---

dds/DCPS/RTPS/RtpsDiscovery.cpp
dds/DCPS/RTPS/Spdp.cpp
dds/DCPS/RTPS/Spdp.h

Problem
-------
A change in SPDP relay address will not be picked up until the timer
expires.  This may cause a delay when recovering from connectivity
problems.
Solution
--------
Send an SPDP message to the relay when the address changes.

SPDP may be delayed by one period when changing relay address

---

.github/workflows/build_and_test.yml

As part of our modernization of our CI/Scoreboard we wanted to migrate all of our CI to github actions.  This PR represents the first step of that.  It has migrated all of our CI builds from Azure and Jenkins to GHA.  Some extraneous builds were removed and others were changed.  
There are documents in confluence and the google drive describing the plan and the problems remaining.
The Safety and Static builds are expected to fail for this PR.

Github Actions Update + Migration from Azure/Jenkins

---

dds/DCPS/JsonValueWriter.h
dds/DCPS/RTPS/BaseMessageUtils.h
dds/DCPS/RTPS/Logging.cpp
dds/DCPS/RTPS/Logging.h
dds/DCPS/RTPS/RtpsCore.idl
dds/DCPS/RTPS/Spdp.cpp
dds/DCPS/transport/framework/TransportDebug.cpp
dds/DCPS/transport/framework/TransportDebug.h
dds/DCPS/transport/framework/TransportReceiveStrategy_T.cpp
dds/DCPS/transport/framework/TransportReceiveStrategy_T.h
dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp
dds/DCPS/transport/rtps_udp/RtpsUdpReceiveStrategy.cpp
dds/DCPS/transport/rtps_udp/RtpsUdpReceiveStrategy.h
dds/DCPS/transport/rtps_udp/RtpsUdpSendStrategy.cpp
dds/DCPS/transport/rtps_udp/RtpsUdpSendStrategy.h

Problem
-------
In some situations, it is impossible to collect a packet capture for
debugging RTPS issues.  In this case, it is desirable to have a log of
the RTPS messages.
Solution
--------
Add support for logging RTPS messages.  Payloads for DATA and
DATA_FRAG submessages are not logged.  Messages are logged before any
encryption is applied and after all decryptions are applied.

RTPS messages are not logged

---

dds/DCPS/DiscoveryBase.h

Problem
-------
The type lookup support does not filter out remote-remote matches.
Furthermore, a match that does not require a type lookup inserts into
a datastructure which is never cleaned.
Solution
--------
Detect remote-remote matches and don't insert when not necessary.

Type lookup leaks memory for remote-remote

---

.github/workflows/check_test_results.yml

Problem:
Github Actions API limits number of listed artifacts to 30, with the option to list up to 100 per 'page'. This was causing build & test runs with more than 30 artifacts to have artifacts that were invisible to the check test results action.
Solution:
Update the check test results action's scripts to iterate over all pages of artifacts at maximum size until all artifact descriptions have been collected.

Handle Multiple Pages of GHA Artifacts in Check Test Results Action

---

java/idl2jni/codegen/im_jni.cpp
java/idl2jni/runtime/idl2jni_runtime.cpp

This fixes local reference table overflow crashes in Android 7.

Clean up jni local references.

---

dds/idl/dds_generator.h
dds/idl/marshal_generator.cpp
tests/DCPS/Compiler/xcdr/xcdr.cpp

When the value has no selected member there is no EMHEADER.

Corrected serialization for XCDR2 mutable unions.

---

dds/DCPS/DataReaderImpl.cpp
dds/DCPS/DiscoveryBase.h
dds/DCPS/GuidUtils.h
dds/DCPS/RTPS/Sedp.cpp
dds/DCPS/RTPS/Spdp.cpp
dds/DCPS/RecorderImpl.cpp
dds/DCPS/StaticDiscovery.cpp
dds/DCPS/security/framework/HandleRegistry.cpp
dds/DCPS/transport/rtps_udp/RtpsUdpTransport.cpp

Also remove `GuidPrefixEqual` since nothing was using it as a struct and replaced it with a normal function.

Avoid Matching on RTPS Relay

---

dds/DCPS/security/SSL/DiffieHellman.cpp
dds/DCPS/security/SSL/DiffieHellman.h

AddressSanitizer is pointing out a global-buffer-overflow issue in the DiffieHellman code where it's technically comparing the length of an octet sequence (of potentially arbitrary length) against fixed-length string constants and using the sequence length to do the comparison. In practice, the lengths will probably be from a small subset of known algorithm names, and since they seem to be null terminated the "overflow" will probably only ever be a single character, but we probably ought to clean it up.
Optionally, we could also investigate why the octet sequences are null terminated and clean that up to avoid the "trimming" math that needs to happen in compare, but the current changes at least resolve the address sanitizer complaints.

Fix address sanitizer global-buffer-overflow issue in DiffieHellman.cpp

---

.github/workflows/build_and_test.yml
azure-pipelines.yml
tests/cmake_integration/Nested_IDL/CMakeLists.txt

The initial PR for GHA did not have working static builds. This PR fixes them by removing the test build option so that the builds do not run out of disk space.  Additionally dev guide messenger test is built/run so that we have at least a little test coverage in the CI for static builds.
Similar to other GHA PRs, there will need to be a name reversion 8 days after the PR is merged due to cacheing of build artifacts.
To reviewers: The only non uncommenting changes are the ./configure options, and adding DevGuideExamples sections to each.

Static Build Fix for GitHub Actions

---

dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp
dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.h

There's currently a race condition with the scheduled heartbeat timers and RtpsWriter destruction, especially when a "stopped" writer allows incoming packets to reschedule the heartbeat timer before being destroyed.

Fix RTPS Writer Shutdown Memory Access Issue

---

dds/DCPS/DiscoveryBase.h
dds/DCPS/DomainParticipantImpl.cpp
dds/DCPS/RTPS/Sedp.cpp
dds/DCPS/RTPS/Sedp.h
dds/DCPS/RTPS/Spdp.cpp
dds/DCPS/RTPS/Spdp.h
dds/DCPS/StaticDiscovery.h

There are a couple race conditions causing heap-use-after-free ASAN issues in Spdp/Sedp.
- First, a race condition exists between SpdpTransport::handle_input() and Spdp's destructor. Simply moving to a weak object handle during the call to data_recieved potentially causes the reactor thread in charge of cleaning up its own reactor, so the actual shutdown work for Spdp needed to be moved to a separate method to allow trivial behaviors in ~Spdp().
- Second, the reverse locking was still causing issues with the iterators, but this time it was because the "updated" iterators weren't getting passed back up into calling methods when applicable, and also because we weren't checking to see if the pdata object in disassociate was being invalidated after our reverse lock to call disassociate_helper …

Fix Spdp Shutdown / Dispose Memory Access Issues

---

.github/workflows/build_and_test.yml

Problem:
The current "Build & Test" workflow has quite a few jobs in it, and approximately 1/3 of them (the ACE_TAO jobs) run immediately upon seeing a triggering event. Even though new pushes to qualifying branches will also trigger the "cancel duplicate builds" workflow, there's not much of a guarantee that these ACE_TAO jobs won't run first, clogging up the job queue even when they are destined to be canceled (imagine several rapid pushes on the same PR).
Solution:
Add an "initial" job that waits for the accompanying "cancel" workflow to finish running (and canceling previous build jobs) before starting any of the current workflow jobs. This should hopefully help smooth things out and allow the cancel workflow to run more quickly even when there are lots of PR commits going on across …

Adding wait_for_cancel Job To Github Actions 'Build & Test' Workflow

---

.github/workflows/build_and_test.yml

Problem:
It's easy to inadvertently introduce memory leaks and invalid memory access issues, and most developers don't use address sanitation instrumentation as part of their normal development process. As a result, leaks and bad access issues often make it into master before being caught by our scoreboard's ASAN build.
Solution:
Now that we're making greater use of Github Actions for CI/CD, we can fairly easily add an ASAN build to our list of builds to help catch these issues before they get merged into master.

Adding ASAN Build to Github Actions 'Build & Test' Workflow

---

dds/DCPS/DataReaderImpl.h
dds/DCPS/DataReaderImpl_T.h
dds/DCPS/ZeroCopySeq_T.cpp
dds/DCPS/ZeroCopySeq_T.h
dds/DCPS/ZeroCopySeq_T.inl
tests/DCPS/ZeroCopyRead/main.cpp
tests/DCPS/unit/MyTypeSupportImpl.h

If a data sequence object was reused in a scenario involving a previous read of a different instance, the zero-copy count of a sample wasn't being decremented when it should've been. This resulted in an incorrect outstanding zero-copy loan error when trying to delete the data reader.
This fixes that and adds a case to the ZeroCopyRead test to try to simulate that sequence of events.

Add Missing Decrement to ZeroCopyDataSeq

---

dds/DCPS/RTPS/Sedp.cpp
dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp
dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.h
dds/DCPS/transport/rtps_udp/RtpsUdpInst.cpp
tests/DCPS/RtpsRelay/Smoke/DataReaderListener.cpp
tests/DCPS/SetQosPartition/Writer.cpp
tests/DCPS/SetQosPartition/subscriber.cpp

Problem
-------
A slow or no longer existing reader will cause the heartbeat period to
grow to the maximum.  This will persist until the defunct reader is
purged from the sytem.
Solution
--------
1. Remove the logic for computing an adaptive heartbeat period.
2. Use a separate timer for nack responses.
3. Add filtering based on reflecting heartbeat counts that discards
acknacks that are too old.  This is to handle cases where the
round-trip latency is greater than the heartbeat period.

Slow and no longer existing readers slow association

---

.github/workflows/build_and_test.yml

Enables the run-vcpkg Action to cache its results using this string as part of the cache key.

GitHub Actions: vcpkg needs a full git hash

---

tests/cmake_integration/generated_global/idl/CMakeLists.txt

The generated_global test was failing on static builds.  This removal was a remnant from when I was first trying to replicate the issue and is no longer needed.

patch for generated_global cmake test

---

tests/cmake_integration/CMakeLists.txt
tests/cmake_integration/Messenger/C++11_Messenger/CMakeLists.txt
tests/cmake_integration/Messenger/Messenger_1/CMakeLists.txt
tests/cmake_integration/Messenger/Messenger_2/CMakeLists.txt
tests/cmake_integration/Nested_IDL/CMakeLists.txt
tests/cmake_integration/generated_global/cpp/CMakeLists.txt
tests/cmake_integration/generated_global/idl/CMakeLists.txt
tests/cmake_integration/run_ci_tests.pl

The previous change made test unfailable.  This will actually allow the test to fail while blocking it from running when an undesired error would occur.

Generated Global blocked from running by --no-shared

---

.github/workflows/check_test_results.yml

By reducing total / concurrent REST API calls, and upgrading to publish action that strictly honors the 50 annotation limit.
Notes:
- We won't see any benefit from this until it gets merged to master.
- Tested on my on repo prior to this PR and seems to work correctly.

Attempt to Fix Check Test Results "Server Error" Message

---

tests/security/attributes/DataReaderListener.cpp
tests/security/attributes/Writer.cpp
tests/security/attributes/publisher.cpp

Problem:
The writer's KEEP_ALL was causing issues for NO_OWNERSHIP_PROFILE, causing the attributes tests to fail.
Solution:
KEEP_ALL isn't really necessary for this test, so rework instances to avoid need for KEEP_ALL so attributes testing can still be done when OWNERSHIP_PROFILE is disabled.

Allow Security Attributes Tests to run without OWNERSHIP_PROFILE enabled

---

_includes/footer.html

Legal asked us to add a copyright statement to the footer of all our websites. I added "&copy; 2021 Object Computing, Inc. All rights reserved." to the bottom of the page.

add copyright statement to footer

---

configure

Fixes #2518. Linux cross compiles should be able to safely use the normal Linux JNI headers.
Also remove line about `ANDROID_ABI` default macro that isn't true anymore in ACE7. Users will have to see the details in `android.md`.

configure: Allow Java with linux-cross, Fixes #2518

---

dds/DCPS/DataReaderImpl.cpp
dds/DCPS/DataReaderImpl.h
dds/DCPS/DataReaderImpl_T.h
dds/DCPS/DataWriterImpl.cpp
dds/DCPS/DataWriterImpl.h
dds/DCPS/DomainParticipantImpl.cpp
dds/DCPS/DomainParticipantImpl.h
dds/DCPS/EntityImpl.cpp
dds/DCPS/EntityImpl.h
dds/DCPS/InstanceState.cpp
dds/DCPS/PublisherImpl.cpp
dds/DCPS/RecorderImpl.cpp
dds/DCPS/ReplayerImpl.cpp
dds/DCPS/SubscriberImpl.cpp
dds/DCPS/SubscriptionInstance.cpp
dds/DCPS/SubscriptionInstance.h
dds/DCPS/TopicImpl.cpp
dds/DCPS/WriteDataContainer.cpp
docs/design/INSTANCE_HANDLES
examples/DCPS/DistributedContent/AbstractionLayer.cpp
tests/DCPS/BuiltInTopic/common.cpp
tests/DCPS/BuiltInTopicTest/monitor.cpp
tests/DCPS/RtpsDiscovery/RtpsDiscoveryTest.cpp
tools/monitor/MonitorTask.cpp

- DomainParticipantImpl::get_handle previously could do two different things, these are now separated into assign_handle and lookup_handle
- Added DomainParticipantImpl::return_handle

Internal tracking of InstanceHandles

---

dds/DCPS/RTPS/Sedp.cpp

Problem:
We're accessing a local map iterator within a reverse lock for the "update" case of SEDP's publication and subscription data handling.
Solution:
The "new" case is already making a copy of the relevant data to use during the reverse locking. Update the "update" case to do the same.

Cleanup Memory Access Inside SEDP BIT Update Reverse-Locking

---

dds/DCPS/DiscoveryBase.h
dds/DCPS/RTPS/Spdp.cpp
dds/DCPS/RTPS/Spdp.h

Problem
-------
In some environments, unicast is scheduled before multicast.  For
completing authentication, this causes a delay since the SPDP message
that is necessary to start authentication on a remote may be delivered
after the authentication messages (even though the code clearly sends
them in the correct order).
Solution
--------
Send directed SPDP messages via unicast.

Directed SPDP messages are sent via multicast

---

dds/DCPS/RTPS/RtpsDiscovery.cpp
dds/DCPS/RTPS/RtpsDiscovery.h
dds/DCPS/RTPS/Sedp.cpp
dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp
dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.h
dds/DCPS/transport/rtps_udp/RtpsUdpInst.cpp
dds/DCPS/transport/rtps_udp/RtpsUdpInst.h
examples/DCPS/ishapes/main.cpp
java/dds/OpenDDS/DCPS/transport/RtpsUdpInst.java
java/dds/OpenDDS_DCPS_jni.cpp

Problem
-------
For reliability, RTPS sends small messages like heartbeats, acknacks,
and gaps.  When the RtpsUdpDataLink was using consolidate timers,
these messages were bundled together which had the advantage of
reducing the overhead associated with sending a bunch of small
messages.
Solution
--------
Add a send queue to the RtpsUdpDataLink that is sent whenever it is
full (enough) or after a configurable delay.

RTPS sends too many little messages

---

dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp
dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.h

Minor adjustments to RtpsReader shutdown to prevent deadlock in SporadicTask's cancel_and_wait().

Prevent Deadlock During RtpsReader Shutdown

---

dds/DCPS/security/Authentication/LocalAuthCredentialData.cpp
dds/DCPS/security/SSL/Certificate.cpp
dds/DCPS/security/SSL/SignedDocument.cpp

Problem:
SequenceBackInsertIterator for OctetSeq is particularly inefficient due to repeated resize / memcpy calls for what can usually be done with a single resize & memcpy.
Solution:
Avoid using SequenceBackInsertIterator for OctetSeq.

Remove SequenceBackInsertIterator for OctetSeq

---

dds/DCPS/RTPS/ParameterListConverter.cpp

Problem:
RTPS::ParameterList uses add_param() to grow a parameter lists by a single parameter, but add_param() simply increases the underlying TAO Unbounded_Value_Sequence's length by 1, which reallocates & copies values for every resize.
Solution:
As a simple improvement, occasionally resize the underlying sequence to be larger than necessary and then resize it back to the correct length in order to increase the maximum beyond what's necessary and avoid extra allocations. This particular scheme reallocates every time length() reaches the next power of 2.

Improve ParameterList Growth Performance

---

dds/DCPS/security/AccessControl/Governance.cpp
dds/DCPS/security/AccessControl/Permissions.cpp

Problem:
AccessControl's use of XercesC++ makes repeated unnecessary calls to DOMNodeList::length() and DOMNodeList::item(), both of which are relatively heavy weight tree operations that use dynamic casting internally.
Solution:
Use the stack to cache calls to these functions when reading from constant DOMs.

Performance Improvements for Access Control's use of Xerces

---

.github/workflows/build_and_test.yml

To get better call stacks for Address Sanitizer issues within glibc:
- Use CPPFlags over FLAGS_C_CC in order to avoid optimization flag issue,
-  Migrate to gcc address sanitizer
Once we have improved call stacks, add suppressions for:
- ipv6 leak in getaddrinfo
- send_graceful_disconnect_message

Migrate GHA to GCC Address Sanitizer, Add Suppressions

---

dds/DCPS/RTPS/Sedp.cpp
dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp
dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.h

Problem
-------
The type lookup endpoints are durable.  This causes type lookup to
work the first time and fail afterwards.
Solution
--------
Make type lookup endpoints volatile (7.6.3.3.3 in XTypes spec).

Type lookup endpoints are durable

---

dds/DCPS/DisjointSequence.h

(possibly) final round of changes for standard libraries that have
distinct types for iterator and const_iterator of set

DisjointSequence: more iterator changes

---

dds/DCPS/DataReaderImpl.h
dds/DCPS/DataReaderImpl_T.h
dds/DCPS/DiscoveryBase.h
dds/DCPS/RTPS/Spdp.cpp
dds/DCPS/RTPS/Spdp.h
dds/DCPS/ReactorTask.cpp
dds/DCPS/ReactorTask.h
dds/DCPS/Service_Participant.cpp
dds/DCPS/Service_Participant.h
dds/DCPS/transport/framework/QueueTaskBase_T.h
dds/DCPS/transport/framework/TransportImpl.cpp
tests/DCPS/InternalThreadStatus/DataReaderListenerImpl.h
tests/DCPS/InternalThreadStatus/InternalThreadStatusListenerImpl.cpp
tests/DCPS/InternalThreadStatus/InternalThreadStatusListenerImpl.h
tests/DCPS/InternalThreadStatus/publisher.cpp
tests/DCPS/InternalThreadStatus/run_test.pl
tests/DCPS/unit/MyTypeSupportImpl.h

- Rename `ThreadStatus` to `ThreadStatusManager` to better reflect what it is.
- Removes finished threads from the global `ThreadStatusManager` so they don't continue to get written in the Thread BIT if there is another participant that's already running or going to run.
- Each participant gets its own local `ThreadStatusManager` to sync with the global one so that each participant can correctly do a single dispose for each finished thread.
- Fix a `ACE_HAS_MINIMUM_BIT` that should be `DDS_HAS_MINIMUM_BIT`.

Better Support for Thread BIT When There are Multiple Participants

---

tests/security/attributes/run_test.pl

This scalar needs to be a string, not a reference to a string

Security attributes test: fixed Perl

---

.github/workflows/build_and_test.yml

Also rename some test_ jobs to devguide_ to avoid confusion with autobuild test jobs.

GHA: Add Shorter Job Timeouts for "Test" Jobs to Avoid 6 Hour Wait

---

dds/DCPS/DataReaderImpl.cpp
dds/DCPS/DataReaderImpl.h
dds/DCPS/DataWriterImpl.cpp
dds/DCPS/DataWriterImpl.h
dds/DCPS/DomainParticipantImpl.cpp
dds/DCPS/DomainParticipantImpl.h
dds/DCPS/PublisherImpl.cpp
dds/DCPS/PublisherImpl.h
dds/DCPS/SubscriberImpl.cpp
dds/DCPS/SubscriberImpl.h
dds/DCPS/TopicImpl.cpp
dds/DCPS/TopicImpl.h

Problem:
Setting Listeners, especially setting them to NULL, is not thread safe.
Solution:
Add mutex protection around listener objects.

Add Mutex Protection For DDS Entity Listeners

---

dds/DCPS/RTPS/ICE/EndpointManager.cpp

Problem
-------
The ICE endpoint manager periodically changes the password.  This
causes new samples to be written to SEDP. If a participant is using
the relay but disconnected, these samples will be buffered.  (The long
term fix is for SEDP to replace the existig sample.)  Additionally,
these password changes generate useless traffic for the relay when
connected.
Solution
--------
Don't change the ICE password unless there are active checklists.

ICE password resets accumulate memory when disconnected from relay

---

tools/rtpsrelay/DomainStatisticsReporter.h
tools/rtpsrelay/HandlerStatisticsReporter.h
tools/rtpsrelay/RelayStatisticsReporter.h
tools/rtpsrelay/RtpsRelay.cpp

Problem
-------
The RtpsRelay defers writing statistics until a new sample needs to be
written and sufficient time has elapsed for writing that sample.  This
means that relay instances will not write statistics samples until
there is traffic.
A load balancer for the RtpsRelay may wish to use these statistics.
If they are unavailable, the load balancer may incorrectly assume that
no instances exist.
This leads to a startup deadlock.
Solution
--------
Write statistics on startup.

RtpsRelay doesn't publish statistics immediately

---

tools/rtpsrelay/ParticipantListener.cpp
tools/rtpsrelay/ParticipantListener.h
tools/rtpsrelay/PublicationListener.cpp
tools/rtpsrelay/PublicationListener.h
tools/rtpsrelay/RelayHandler.cpp
tools/rtpsrelay/RelayHandler.h
tools/rtpsrelay/SubscriptionListener.cpp
tools/rtpsrelay/SubscriptionListener.h

Problem
-------
If all of the clients of the RtpsRelay go down at the same time and
they have the same lease duration, then they will timeout in the relay
at the same time.  Given enough clients, the number of unregister
dispose messages floods the network at make the relay instance
unresponsive.
Solution
--------
Distribute the unregisters in time by queuing them and processing them
with a periodic task.  The proposed solution can be improved in at
least three ways:
1. Eliminate redundant code.
2. Use a sporadic task.
3. Make the period configurable and/or come up with a better heuristic.

RtpsRelay becomes non-responsive when mass disconnect

---

tools/rtpsrelay/Config.h
tools/rtpsrelay/HandlerStatisticsReporter.h
tools/rtpsrelay/RelayHandler.cpp
tools/rtpsrelay/RelayHandler.h
tools/rtpsrelay/RelayStatisticsReporter.h
tools/rtpsrelay/RtpsRelay.cpp
tools/rtpsrelay/lib/Relay.idl

Problem
-------
A new relay client introduces overhead in its instance via discovery
and then distribution since the information about the new client must
be distributed to other relays.  The message required can easily flood
a network when too many new client arrive in a time interval.
Solution
--------
Implement admission control in the relay.  The relay will ignore
messages from new clients whenever 1) the total number of clients
meets or exceeds a static limit or 2) the total number of new clients
exceeds a dynamic limit.

RtpsRelay gets overloaded when too many new clients

---

dds/DCPS/RTPS/Spdp.cpp
dds/DCPS/RTPS/Spdp.h

To match `local_sender_` that was moved in https://github.com/objectcomputing/OpenDDS/pull/2577
Also add check that SPDP is initialized before processing STUN messages.

Defer Enabling SPDP Period Tasks

---

.github/workflows/build_and_test.yml

Someday we want to be on ace7tao3 and we want a GHA build to check on our compatibility over time. This PR adds that to the u20_j_qt_ws_sec build.  There are multiple options for ACE7TAO3: major, minor, and micro.  I settled on minor but am open to changing.
Update 4/22/21: Changed the branch to be master instead of any of the 3 aforementioned branches.

Github Actions: Add ace7tao3 build to GHA

---

dds/DCPS/DCPS_Utils.cpp
dds/DCPS/DCPS_Utils.h
dds/DCPS/DataWriterImpl.cpp
dds/DCPS/DataWriterImpl_T.h
dds/DCPS/DiscoveryBase.h

We were incorrectly detecting if XCDR1 was really being used or was just in the list of the QoS. This PR changes to only use the writer QoS which should only have 1 item in it.

Properly Detect XCDR1 in Combination with Appendable or Mutable

---

performance-tests/bench/worker/WorkerDataReaderListener.cpp

This should hopefully resolve the GHA asan build assertion error.

Bench: Additional Locking to Protect Report in WorkerDataReaderListener

---

dds/DCPS/DiscoveryBase.h
dds/DCPS/RTPS/Spdp.cpp

- only track recvd AuthReq as an attribute of Discovered Participant
- requires discovery to happen "first" but both are resent periodically
- allows a reauthentication scenario to work when the Requester has
expired the peer and should be sending it a new AuthReq

Remove PendingRemoteAuthTokenMap from Spdp

---

dds/DCPS/security/CryptoBuiltInImpl.cpp

- the CryptoHandle may have been removed during the re-auth process
- new key is already getting associated with this CryptoHandle
- add this CryptoHandle to the other internal tables in the plugin

Fixed re-keying the endpoints that use derived keys

---

dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp

This is the initial fix for the GAP inversion assertion issue. Once a sender-side fix is in place to prevent the invalid GAP submessages, the OPENDDS_ASSERT statements can be removed.

Fix Assertion Issues From Inverted GAP Submessage Values

---

.github/workflows/build_and_test.yml

Wireshark was failing on our ubuntu builds due to a lack of apt-get update. I took this time to clean up some mess around wireshark that we had.

GitHub Actions: Wireshark Add apt-get update

---

docs/requirements.txt

This is the Pygments release with OMG IDL support from https://github.com/pygments/pygments/pull/1595.

Update Sphinx to use Pygments 2.9.0

---

tests/security/attributes/Writer.cpp
tests/security/attributes/Writer.h
tests/security/attributes/publisher.cpp

Problem: 
The security attributes test had a memory leak that occurs when the publisher/writer and subscriber/reader are never supposed to match.
Solution:  
I have added better handling for the timeout scenario in Writer.cpp to preempt the ending of the waitset and allow cleanup of the writer.  Currently the find match timeout is set to 5 seconds if a match doesn't happen. Considering we give most of the test scenarios 10 or 20 seconds, I think 5 seconds will work but am open to changing it. 
When this timeout occurs, I added additional cleanup to publisher.cpp which will properly clean up the writer before a CLEAN_ERROR_RETURN which then cleans everything else up.

Memory Leak Fix: Security Attributes Test

---

dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp
dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.h
dds/DCPS/transport/rtps_udp/RtpsUdpInst.cpp
dds/DCPS/transport/rtps_udp/RtpsUdpInst.h
dds/DCPS/transport/rtps_udp/RtpsUdpReceiveStrategy.cpp
dds/DCPS/transport/rtps_udp/RtpsUdpReceiveStrategy.h
dds/DCPS/transport/rtps_udp/RtpsUdpTransport.cpp
dds/DCPS/transport/rtps_udp/RtpsUdpTransport.h

Problem
-------
A participant A with multiple IP addresses may advertise all of them
in the locators of SPDP and SEDP.  The RtpsUdpDataLink of a peer B
will pick the first of each type, unicast and multicast, to determine
the addresses of entities in A.  Thus, participant B may use the wrong
address and fail to communicate with A.
Solution
--------
Use all of the unicast addresses.
Notes
-----
* ICE is useful in these situations as it will determine the correct
address to use.
* When security is enabled, ICE will not start until secure discovery
is complete meaning authentication and key exchange may fail without
this feature.

RtpsUdpDataLink can't handle more than one unicast address

---

tools/rtpsrelay/Config.h
tools/rtpsrelay/RelayHandler.cpp
tools/rtpsrelay/RtpsRelay.cpp

Problem
-------
Due to the way security + association is implemented, the RtpsRelay
often receives messages that is cannot decrypt or verify.  This
creates noise in the log.
Solution
--------
Don't log these warnings by default and provide an option to turn them
on.

RtpsRelay logs too many warnings

---

dds/DCPS/RTPS/Sedp.cpp

Previously we were erroring if both is_final and is_mutable were false.  instead we should silently return, and only error if both are true.

handle unknown entityid in sedp.cpp

---

dds/idl/dds_generator.cpp
dds/idl/dds_generator.h
dds/idl/ts_generator.cpp
tests/DCPS/Compiler/keywords/classic/keywords_classic.mpc
tests/DCPS/Compiler/keywords/cpp11/keywords_cpp11.mpc
tests/DCPS/Compiler/keywords/main.cpp
tests/DCPS/Compiler/keywords/run_test.pl
tests/DCPS/Compiler/keywords/test.idl
tests/dcps_tests.lst

…ause short_name is the escaped C++ name
* dds/idl/ts_generator.cpp:

Improved keyword and escape handling in TypeSupport code generation

---

etc/dds.doxygen
tools/scripts/gitrelease.pl

- Release Script
- Fix issue with DevGuide filename being wrong after version string change.
- Add `--ftp-port` option. There already was something passing in the port, but it wasn't a set value.
- Disable Doxygen Call Graphs
- I don't think they are worth the huge file sizes.

Tweak Release Script, Disable Doxygen Call Graphs

---

.github/workflows/build_and_test.yml

PR #2644 Seems to have fixed the TcpReconnect / send_graceful_disconnect_message leak, so hopefully we can remove the ASAN suppression for it now.

GHA Remove send_graceful_disconnect_message Suppression From ASAN Job

---

dds/DCPS/transport/framework/TransportReassembly.cpp
tests/DCPS/UnitTests/ut_Reassembly.cpp

Problem:
Sometimes, the NACKFRAG bitmap generated would extend past the last fragment.
Solution:
Check to make sure we're not overshooting the end.

Prevent Excessive NACKFRAG Bitmap

---

dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp
dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.h
dds/DCPS/transport/rtps_udp/RtpsUdpInst.cpp
dds/DCPS/transport/rtps_udp/RtpsUdpInst.h

Problem
-------
By default, the RtpsUdpDataLink expires durable data for a reader
after 60 seconds.  Practically, there is no value to doing this as a
severe communication problem will eventually lead to a disassociation
which then purges the data.
Solution
--------
Remove the `durable_data_timeout_` parameter and all associated logic.

RtpsUdp: expiring durable data has no practical value

---

.github/workflows/build_and_test.yml
tests/auto_run_tests.pl

So the ctest converter can work on Windows because it doesn't use shebangs.
Also:
- Add ability to specify CMake tests build directory
- Fix the ctest converter script not running if a test failed.
- Add CMake tests to some of the normal GHA thingys to see how it goes.

Added `auto_run_tests.pl --python`

---

tests/DCPS/XTypes/Pub/XTypesPublisher.cpp
tests/DCPS/XTypes/XTypes.h

Catching some late-emerging scoreboard failures.
1. an inconsistent topic count went to 2 and thus was counted as a failure (addressed)
2. reader still failed to detect a message sent by the writer or the writer failed to detect the reader was still subscribed.

extension to the XTypes test

---

configure

On Linux when using `--wireshark-cmake`, `--wireshark-lib` defaults to empty. Between making that option and now, a check was added for `%optdep` locations that require them not to be empty. This added a field to `%optdep` that allows the value to be empty.
As part of this I also rewrote `%optdep` to use hashes instead of arrays.

Fix `configure --wireshark-cmake` on Linux

---

.github/workflows/build_and_test.yml

So we don't have a weird mix of xerces / qt / wireshark versions, and so that these larger dependency installations continue to work over time (QT has been causing trouble on other builds).
And upgrade that one cache 2.1.4 action to match the others (2.1.5)

GitHub Actions: Normalize Calling 'apt-get update' Across Related Jobs

---

dds/DCPS/transport/framework/PacketRemoveVisitor.cpp
dds/DCPS/transport/framework/PacketRemoveVisitor.h
dds/DCPS/transport/framework/QueueRemoveVisitor.cpp
dds/DCPS/transport/framework/QueueRemoveVisitor.h
dds/DCPS/transport/framework/QueueRemoveVisitor.inl
dds/DCPS/transport/framework/TransportSendStrategy.cpp
tests/DCPS/EntityLifecycleStress/publisher.cpp
tests/dcps_tests.lst

Problems:
- Coverity Scan complained about checking write()'s return value
- Still encountering occasional issues in TransportSendStrategy cleanup due to QueueRemoveVisitor and PacketRemoveVisitor ignoring non-unique match criteria when the status is RELEASED (vs FOUND).
Solution:
- Fix publisher.cpp to check the return value of write()
- Pass "remove_all" flag into QueueRemoveVisitor and PacketRemoveVisitor and enforce compliance with non-unique flag when it's set to true (but default to false to preserve existing behaviors).

Updates for EntityLifecycleStress Test

---

dds/DCPS/transport/tcp/TcpTransport.cpp

I believe this will address this potential memory leak:
http://scoreboard.ociweb.com/dds_doc_ace6tao2_mantis_linux_gccasan_d1o0/2021_05_28_02_51_Full.html#error_2

Prevent TCP Connection Attempts During Shutdown

---

tests/auto_run_tests.pl

Problem:
Autobuild uses the string "auto_run_tests:" to determine new subsections, but recent changes to auto_run_tests.pl print that string for error messages as well as test sections.
Solution:
Reserve that exact string for test sections only.

Align auto_run_test.pl Output With Autobuild Subsection Expectations

---

_includes/footer.html

@mitza-oci I had a note that this needed to be done once we launched the foundation, so it just needs to be updated now.
Replaced Object Computing, Inc. with the OpenDDS Foundation (legal department asked for this change to be made once the foundation was live, which it now is)

changed copyright to OpenDDS Foundation

---

tools/rtpsrelay/ParticipantListener.cpp
tools/rtpsrelay/PublicationListener.cpp
tools/rtpsrelay/RelayAddressListener.cpp
tools/rtpsrelay/RelayPartitionsIncrementListener.cpp
tools/rtpsrelay/RelayPartitionsListener.cpp
tools/rtpsrelay/SpdpReplayListener.cpp
tools/rtpsrelay/SubscriptionListener.cpp

Problem
-------
The log messages for `on_data_available` in various listeners is
incorrect and doesn't describe why the take failed.
Solution
--------
Fix the log messages and add the status as a string.

RtpsRelay `on_data_available` logging is incorrect and uninformative

---

docs/dependencies.md
tests/auto_run_tests.pl
tests/cmake/ctest-to-auto-run-tests.py
tests/cmake/generated_global/README.md

Follow up to #2712
- `auto_run_tests.pl`:
- Make a separate ` --cmake-build-cfg`  for `ctest --build-config` because using the same value of `-ExeSubDir` as the MPC-based tests seems impossible. Default this to `"Debug"` on Windows for convenience.
- Default `--python` on Windows to `python`.
- Detect when a required build configuration is missing in `ctest-to-auto-run-tests.py` to give a friendly error instead of a confusing stack trace.
Also:
- Add Python to `docs/dependencies.md`
- Fixed spelling in `tests/cmake`

More Fixes for CMake Tests on Windows

---

MPC/config/dcps_idl_only_lib.mpb

see jira ticket 341. This change adds a dependency to ensure IDL related artifacts are built in proper order.

Parallel builds for safety profile 

---

tools/scripts/Dockerfile

Building and testing alternate configurations, especially complex ones
like Safety Profile, may be done using Docker containers.  This
Dockerfile sets up a baseline development environment using
Ubuntu 20.04 but doesn't make any decisions about how OpenDDS
is configured, which optional dependencies are used, etc.

Added a Dockerfile as a starting point for OpenDDS development

---

dds/DCPS/WriteDataContainer.cpp
dds/DCPS/transport/framework/TransportQueueElement.h
dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.h
tests/DCPS/DelayedDurable/DelayedDurable.cpp
tests/DCPS/DelayedDurable/DelayedDurable.mpc
tests/DCPS/DelayedDurable/README.txt
tests/DCPS/DelayedDurable/run_test.pl
tests/dcps_tests.lst

based on sequence numbers since WriteDataContainer uses this to keep the
list of durable data in order

rtps_udp: make data_delivered callbacks in order

---

dds/DCPS/transport/multicast/BestEffortSession.cpp
dds/DCPS/transport/multicast/MulticastTransport.cpp
java/tests/messenger/publisher/run_test.pl
java/tests/messenger/subscriber/run_test.pl
tests/DCPS/Messenger/Args.h
tests/DCPS/Messenger/DataReaderListener.cpp
tests/DCPS/Messenger/Writer.cpp
tests/DCPS/Messenger/Writer.h
tests/DCPS/Messenger/pub_multicast_be.ini
tests/DCPS/Messenger/pub_udp_free.ini
tests/DCPS/Messenger/publisher.cpp
tests/DCPS/Messenger/run_test.pl
tests/DCPS/Messenger/stack_subscriber.cpp
tests/DCPS/Messenger/sub_multicast_be.ini
tests/DCPS/Messenger/sub_udp_free.ini
tests/DCPS/Messenger/subscriber.cpp
tests/dcps_tests.lst

At some point we seem to have gotten rid of test coverage for best effort (reliable=0 in the transport config) multicast. This restores test coverage and get it working again enough to process with performance testing.

Fix BestEffort Multicast, Restore Test Coverage

---

dds/DCPS/transport/framework/TransportSendBuffer.cpp
dds/DCPS/transport/multicast/MulticastDataLink.cpp
dds/DCPS/transport/multicast/MulticastDataLink.h
dds/DCPS/transport/multicast/MulticastTransport.cpp
dds/DCPS/transport/multicast/MulticastTransport.h

Eventually, we should probably do the same optimization for the TransportQueueElements above (calling duplicate instead of clone_mb), but it requires more extensive changes to the transport framework.

Delay TransportQueue memcpy Until Required

---

tests/DCPS/SetQosPartition/rtps_rtps.ini

This should fix the SEGV for u18_esafe_js0.

Increase pool_size for SetQosPartition Test

---

dds/DCPS/transport/framework/NetworkAddress.cpp
dds/DCPS/transport/tcp/TcpReceiveStrategy.cpp
dds/DCPS/transport/tcp/TcpTransport.cpp
dds/InfoRepo/InfoRepoMulticastResponder.cpp

On Windows with a broken DNS setup the usage of `get_host_name()` could take seconds to return. Use `get_host_addr()` as alternative which is fast and tells more as it gives the concrete network interface used when multiple NICs are installed. 
We see it happen often on Windows that DNS is not setup correctly, when we stay away of using hostnames OpenDDS does work without problems when DNS is broken but the logging of the hostname is problematic.

Don't use get_host_name, use get_host_addr as alternative

---

tests/cmake/ctest-to-auto-run-tests.py

- Remove `-ExeSubDir` and argument from auto_run_test name to fix an
small issue on scoreboard where a CMake test gets multiple entries for
each `-ExeSubDir` permutation it has. The actual command will be put
before the test output along with the CMake test name.
- Decompress test output if needed, so passing `--no-compress-output` to
CTest is no longer always required. This is only for combination of
base64 encoding and gzip compression, so I'm going to continue to pass
it in `auto_runt_test.pl` because I don't know if CMake encodes the
test output different on different platforms/versions. This is more to
make my life easier when I just want to manually call ctest and run this script.

Small Improvements to `ctest-to-auto-run-tests.py`

---

tools/rtpsrelay/RelayHandler.cpp
tools/rtpsrelay/RelayHandler.h
tools/rtpsrelay/RelayStatisticsReporter.h
tools/rtpsrelay/lib/Relay.idl

Problem
-------
The pending set used to limit the discovery rate can saturate if a
client is able to send SPDP but unable to complete discovery for some
reason.  Upon saturation, discovery halts.
Solution
--------
Time out guids in the pending set after a lifespan.

RtpsRelay Pending set saturates

---

dds/DCPS/RTPS/ParameterListConverter.cpp
dds/DCPS/RTPS/RtpsCore.idl
dds/DCPS/RTPS/RtpsDiscovery.cpp
dds/DCPS/RTPS/RtpsDiscovery.h
dds/DCPS/RTPS/Spdp.cpp
dds/DCPS/RTPS/Spdp.h
tests/transport/spdp/spdp_transport.cpp
tools/rtpsrelay/RtpsRelay.cpp

Problem
-------
A participant that is using the RtpsRelay and ICE will send ICE
password changes to the application participant of the relay.  If the
participant changes to a different relay, then the participant will
changes its ICE password, send the samples, and then heartbeat.  The
new relay will not ack these heartbeats.  Relay application
participants typically have long lease durations so the unwanted
heartbeats could go on for a significant amount of time.
Solution
--------
1. Provide a PID that allow the application participant to identify
itself.
2. Provide logic that purges application participants when changing
the relay address.

ICE password changes increase load on RtpsRelay

---

dds/DCPS/RTPS/ICE/Checklist.cpp
dds/DCPS/RTPS/Spdp.cpp
dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp
dds/DCPS/transport/rtps_udp/RtpsUdpReceiveStrategy.cpp
dds/DCPS/transport/rtps_udp/RtpsUdpSendStrategy.cpp
dds/DCPS/transport/rtps_udp/RtpsUdpTransport.cpp
dds/InfoRepo/InfoRepoMulticastResponder.cpp

* dds/DCPS/RTPS/ICE/Checklist.cpp:
* dds/DCPS/RTPS/Spdp.cpp:
* dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp:
* dds/DCPS/transport/rtps_udp/RtpsUdpReceiveStrategy.cpp:
* dds/DCPS/transport/rtps_udp/RtpsUdpSendStrategy.cpp:
* dds/DCPS/transport/rtps_udp/RtpsUdpTransport.cpp:
* dds/InfoRepo/InfoRepoMulticastResponder.cpp:

Make use of DCPS::AddrToStringSize instead of hardcoded 256

---

tests/unit-tests/dds/DCPS/RTPS/ParameterListConverter.cpp

some older compilers are complaining about ambiguity here

ut for ParameterListConverter: ParameterId_t is in multiple namespaces

---

dds/DdsDcps.mpc
dds/idl/opendds_idl.mpc

allows the installed tree to be moved without breaking the links

make install: use relative links in prefix/share

---

dds/DCPS/Serializer.cpp
dds/DCPS/Serializer.h
dds/idl/marshal_generator.cpp
tests/unit-tests/dds/DCPS/Serializer.cpp

Makes use of the ScopedAllocationContext from previous PR, but also adds "min read" to it in order to force reading of full parameter size when deserialized objects don't take full size (e.g. vendor id).

Avoid Allocation of ACE_Message_Block in Rtps Parameter Deserialization

---

dds/DCPS/FileSystemStorage.cpp

* dds/DCPS/FileSystemStorage.cpp:

Removed usage of ACE_OSCALL_RETURN, that macro expands to just a return

---

dds/DCPS/RTPS/RtpsDiscovery.cpp
dds/DCPS/RTPS/Spdp.cpp
dds/DCPS/RTPS/Spdp.h

Problem
-------
If an RtpsRelay is restarted without changing network connectivity,
then a user has no incentive to reset the address and purge the old
application participant.
Solution
--------
When a new application participant is detected, remove all of the old
application participants.

RtpsRelay application participant purge is not robust

---

.github/workflows/check_test_results.yml

A short-term fix (but longer-term protection) against the cmake test relative path issue.
Successful "Check Test Results" run & publishing on my repo [here](https://github.com/simpsont-oci/OpenDDS/actions/runs/1013641824) despite test failures with relative paths as seen [here](https://github.com/simpsont-oci/OpenDDS/actions/runs/1013217234).

Have Check Test Results Protect Against Relative Paths In Test Names

---

dds/DCPS/QOS_XML_Handler/qos_xml_handler.mpc

both make install and IDE support require accurate lists of headers which can be derived from source files

qos_xml_handler.mpc: use defaults to avoid listing files

---

dds/DCPS/XTypes/TypeObject.h
tests/DCPS/Compiler/typeobject_hash_consistency/run_test.pl
tests/DCPS/Compiler/typeobject_hash_consistency/sample.idl
tests/dcps_tests.lst

see jira ticket 352. The problem was that the type objects for complete and minimal sequences and arrays had a field that was left uninitialized by the default constructor. so when those objects were serialized, hashed, then written out in a type support impl file, the hash would vary from one run to the next.
This patch solves theproblemby explicitly initializing the otherwise unused collection flag value.

TypeObject hash consistency fix

---

dds/DCPS/DiscoveryBase.h
dds/DCPS/RTPS/Spdp.cpp
dds/DCPS/Time_Helper.h
dds/DCPS/Time_Helper.inl
dds/DCPS/transport/framework/TransportClient.cpp
dds/DCPS/transport/framework/TransportImpl.h
dds/DCPS/transport/multicast/MulticastTransport.cpp
dds/DCPS/transport/multicast/MulticastTransport.h
dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp
dds/DCPS/transport/rtps_udp/RtpsUdpTransport.cpp
dds/DCPS/transport/rtps_udp/RtpsUdpTransport.h
dds/DCPS/transport/shmem/ShmemTransport.cpp
dds/DCPS/transport/shmem/ShmemTransport.h
dds/DCPS/transport/tcp/TcpTransport.cpp
dds/DCPS/transport/tcp/TcpTransport.h
dds/DCPS/transport/udp/UdpTransport.cpp
dds/DCPS/transport/udp/UdpTransport.h

Problem
-------
An association for a local reader that times out is removed from the
`pending_` set of the TransportClient and not added to the
`data_link_index_`.  A subsequent call to `disassociate` when
discovery times out is effectively a no-op.  For RTPS, this means that
the reader has a pre-association writer and will send pre-association
acknacks forever since the writer may never associate and never be
removed.
Solution
--------
- Add a parameter to `stop_accepting_or_connecting` that indicates
association failure.  RTPS will release its reservations when the
association fails.
- Fix a bug in `RtpsUdpDataLink::disassociated` where the parameters
to `release_reservations_i` were reversed.

RtpsUdpDataLink leaks remote writers on failed associations

---

dds/DCPS/AddressCache.h
dds/DCPS/PoolAllocator.h
dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp
dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.h
dds/DCPS/transport/rtps_udp/RtpsUdpSendStrategy.cpp
dds/DCPS/transport/rtps_udp/RtpsUdpTransport.cpp
dds/DCPS/transport/rtps_udp/RtpsUdpTransport.h
tests/unit-tests/dds/DCPS/AddressCache.cpp

Problem: We spend quite a bit of time calculating the lists of addresses needed to send each bundled message, but in reality these lists don't change all that often.
Solution: Cache them... both at the locator level and at the bundling level.

rtps_udp: address caching for locators / bundling

---

.github/workflows/build_and_test.yml
dds/DCPS/security/BuiltInPluginLoader.cpp
dds/DCPS/security/framework/SecurityRegistry.cpp
tests/unit-tests/dds/DCPS/security/framework/SecurityConfig.cpp

Issue 1: SecuityConfigTest fails with an assertion 
Solution has a straight forward component and a surprise. The straight forward part was to explicitly include a header related to the ACE service object that will be "loaded" when needed. This is necessary because the ACE Service Configuration framework abstracts away those details and so the linker doesn't see the need to include the appropriate object files in the final executable.
The surprise was that the loader class for this service object was using a locally defined static instance of a std::string initialized with a literal, but when that string was referenced during loader initialization which is also done during static initialization phase, the std::string value was empty or null. 
Issue 2: NetworkAddressTest 
On the github …

Fix failing unit tests on static builds

---

java/dds/dcps_java.mpc
java/idl2jni/corba/idl2jni_corba.mpc
java/idl2jni/runtime/idl2jni_runtime.mpc
java/tao/tao_java.mpc

This patch install the jar files into INSTALL_LIBDIR directory instead the `lib` directory.
This allows to be uniform with the rest of the installation of OpenDDS libraries.
And it removes an error when the installation uses the DESTDIR variable and with the `lib` directory doesn't exist. This is particularly true for the packaging of OpenDDS. The rpm packaging renames the opendds_dcps.jar file to $(DESTIDR)$(INSTALL_PREFIX)/lib, and it is impossible to copy the other files inside the directory.

java: installation of jar files

---

.github/workflows/build_and_test.yml
docs/internal/github_actions.rst
tests/dcps_tests.lst

Also: Normalized configuration names for no built-in topics

Exclude the BitDataReader test when not built with built-in topic support

---

.github/workflows/build_and_test.yml

This was causing failures on the CI and at least for now the solution is removing it.

GitHub Actions: Remove CMake from ASan build

---

dds/DCPS/AddressCache.h
dds/DCPS/PoolAllocator.h

Previous changes misunderstood purpose of different macros, broke safety profile builds. Need to revert changes and adjust AddressCache to use the correct macro.

Revert PoolAllocator 'typename' Macro Changes, Fix AddressCache Macro Usage

---

tests/security/security_tests.lst

totally remove the ParticipantLocationTopic test for ipv6 from the security_test.lst file

Resolve ParticipantLocationTopic Test Failures (IPv6)

---

dds/DCPS/transport/framework/TransportConfig.cpp

Similar to Spdp.cpp, class-scoped static const integers need definitions in the .cpp file, but older MSVC versions don't get this right

Workaround for older MSVC versions in TransportConfig

---

dds/CorbaSeq/Int8Seq.idl
dds/CorbaSeq/UInt8Seq.idl
dds/DCPS/Definitions.h
dds/DCPS/JsonValueReader.h
dds/DCPS/JsonValueWriter.h
dds/DCPS/OpenDDS_Util.mpc
dds/DCPS/RTPS/Logging.cpp
dds/DCPS/Serializer.h
dds/DCPS/Serializer.inl
dds/DCPS/ValueReader.h
dds/DCPS/ValueWriter.h
dds/idl/be_produce.cpp
dds/idl/dds_generator.h
dds/idl/itl_generator.cpp
dds/idl/langmap_generator.cpp
dds/idl/marshal_generator.cpp
dds/idl/rapidjson_generator.cpp
dds/idl/typeobject_generator.cpp
dds/idl/v8_generator.cpp
dds/idl/value_reader_generator.cpp
dds/idl/value_writer_generator.cpp
tests/DCPS/Compiler/char_literals/test.idl
tests/DCPS/Compiler/explicit_ints/main.cpp
tests/DCPS/Compiler/explicit_ints/test.idl
tests/DCPS/Compiler/rapidjson_generator/RapidJsonTest.cpp
tests/DCPS/Compiler/rapidjson_generator/RapidJsonTest.idl
tests/DCPS/Serializer/SerializerTest.cpp
tests/unit-tests/dds/DCPS/JsonValueReader.cpp
tests/unit-tests/dds/DCPS/JsonValueWriter.cpp

Use https://github.com/DOCGroup/ACE_TAO/pull/1621 if available to test for support for explicitly-named integer types added in https://github.com/objectcomputing/OpenDDS/pull/2814.
Also allow IDL files being processed by `opendds_idl` to include '.h' files since `tao_idl` doesn't seem to have a problem with it and it's needed for the `idl_features.h` file to work with both C++ and IDL.

Use TAO IDL Features Macros

---

tests/unit-tests/dds/DCPS/security/AccessControlBuiltInImpl.cpp
tests/unit-tests/dds/DCPS/security/SSL/Certificate.cpp

The security unit tests for Certificates and AccessControl fail on platforms with the older OpenSSL libraries. This is the result of preceding tests causing the OpenSSL library to purge its cipher and digest collections that had been initialized at test startup. The solution is to run through the openssl_init again at the start of these test groups.

fix unit test fails built with openssl 1.0.2

---

dds/DCPS/transport/framework/BuildChainVisitor.cpp
dds/DCPS/transport/framework/BuildChainVisitor.inl
dds/DCPS/transport/framework/CopyChainVisitor.cpp
dds/DCPS/transport/framework/CopyChainVisitor.h
dds/DCPS/transport/framework/CopyChainVisitor.inl
dds/DCPS/transport/framework/RemoveAllVisitor.cpp
dds/DCPS/transport/framework/RemoveAllVisitor.inl
dds/DCPS/transport/framework/ThreadPerConRemoveVisitor.cpp
dds/DCPS/transport/framework/TransportControlElement.cpp
dds/DCPS/transport/framework/TransportControlElement.h
dds/DCPS/transport/framework/TransportControlElement.inl
dds/DCPS/transport/framework/TransportCustomizedElement.cpp
dds/DCPS/transport/framework/TransportCustomizedElement.h
dds/DCPS/transport/framework/TransportCustomizedElement.inl
dds/DCPS/transport/framework/TransportQueueElement.h
dds/DCPS/transport/framework/TransportReplacedElement.cpp
dds/DCPS/transport/framework/TransportReplacedElement.h
dds/DCPS/transport/framework/TransportReplacedElement.inl
dds/DCPS/transport/framework/TransportRetainedElement.cpp
dds/DCPS/transport/framework/TransportRetainedElement.h
dds/DCPS/transport/framework/TransportRetainedElement.inl
dds/DCPS/transport/framework/TransportSendBuffer.cpp
dds/DCPS/transport/framework/TransportSendControlElement.cpp
dds/DCPS/transport/framework/TransportSendControlElement.h
dds/DCPS/transport/framework/TransportSendControlElement.inl
dds/DCPS/transport/framework/TransportSendElement.cpp
dds/DCPS/transport/framework/TransportSendElement.h
dds/DCPS/transport/framework/TransportSendElement.inl
dds/DCPS/transport/framework/TransportSendStrategy.cpp
tests/unit-tests/dds/DCPS/transport/framework/CopyChainVisitor.cpp

Performance Improvements From Profiling Fragmentation Tests
