dds/FACE/FaceTSS.h
dds/FACE/config/QosSettings.cpp
tests/FACE/Reliability/Publisher/Publisher.cpp
tests/FACE/Reliability/Subscriber/Subscriber.cpp
tests/FACE/Reliability/face_config.ini

TS API Update: Add processing of timeout in send_message to report an error if less than a reliable writer's max_blocking_time as well as add cases to Reliability test to verify success/error combinations

Ts api updates redmine 2334

---

dds/FACE/config/TopicSettings.cpp
dds/FACE/config/TopicSettings.h
tests/FACE/Messenger/face_config.ini
tests/FACE/Partition/face_config.ini
tests/FACE/Reliability/face_config.ini

Parse message definition GUID from topic portion of .ini file.  Add Message type guid id to topic portion of test .ini files

TS API Update:  Parse Message Definition GUID- Redmine Task #2379

---

dds/DCPS/DataReaderImpl.cpp
dds/DCPS/DataReaderImpl.h
dds/DCPS/RecorderImpl.cpp
dds/DCPS/RecorderImpl.h
dds/DCPS/RemoveAssociationSweeper.h
dds/DCPS/ReplayerImpl.cpp
tests/DCPS/RecorderReplayer/run_test.pl

Convert RecorderImpl to use ReactorInterceptor like DataReaderImpl and update test to use PendingTimeout.  Also add stop associating calls to the ReplayerImpl.

Recorder replayer updates

---

.gitignore
configure
performance-tests/DCPS/SimpleLatency/sample_pub.cpp

Added lynxos-178 as a valid target for the configure script.
Improved support for flexible directory layout of DDS_ROOT, ACE_ROOT, TAO_ROOT.

Configure script

---

NEWS
dds/DCPS/DataReaderImpl.cpp
dds/DCPS/DataWriterImpl.cpp
dds/DCPS/DomainParticipantImpl.cpp
dds/DCPS/DomainParticipantImpl.h
dds/DCPS/InstanceState.cpp
dds/DCPS/RTPS/BaseMessageUtils.h
dds/DCPS/RecorderImpl.cpp
dds/DCPS/ReplayerImpl.cpp
dds/DCPS/TopicImpl.cpp
dds/DCPS/transport/rtps_udp/RtpsUdpInst.cpp
examples/DCPS/DistributedContent/AbstractionLayer.cpp
tests/DCPS/BuiltInTopic/common.cpp
tests/DCPS/BuiltInTopicTest/monitor.cpp
tests/DCPS/RtpsDiscovery/RtpsDiscoveryTest.cpp
tools/scripts/gitrelease.pl

Some warning fixes, including requiring parameter to DomainParticipantImpl::get_handle().
NEWS updates, and gitrelelease.pl updates.

Warning fixes, updates for release

---

dds/DCPS/DataWriterImpl.cpp
dds/DCPS/DdsDcps_pch.h
dds/DCPS/StaticDiscovery.cpp
dds/DCPS/ZeroCopySeq_T.cpp

Fix Checked Iterators warning C4996 for zero copy sequence, other warnings

---

FACE/TS_common.hpp
dds/DCPS/RTPS/Sedp.cpp

VxWorks7 port (TS_common.hpp) and fixed bug in handling SedpLocalAddress config option.

Changes from VxWorks7 testing

---

bin/PerlDDS/Run_Test.pm
bin/dcps_tests.lst
tests/DCPS/FooTest5/DataReaderListener.cpp
tests/DCPS/FooTest5/common.cpp
tests/DCPS/FooTest5/common.h
tests/DCPS/FooTest5/run_test.pl
tests/DCPS/FooTest5/subscriber.cpp
tests/FACE/Compiler/idl_test_fixed/run_test.pl

* SafetyProfilePoolTest: require -Config OPENDDS_SAFETY_PROFILE
* FooTest5: always take
* TestFixed: use run_test.pl to launch

Multiple Test mods

---

configure
dds/DCPS/WriteDataContainer.cpp
tests/DCPS/StaticDiscovery/StaticDiscoveryTest.cpp

And fix an uninitialized variable in configure.

WriteDataContainer::obtain_buffer logging, StaticDiscoveryTest revert history change. 

---

dds/DCPS/DataReaderImpl.cpp

Wait to schedule sweeper until association completes, or at
lease a viable datalink has been created so that sweeper
does not timeout before it was even possible to receive messages.

EndHistoricSamplesMissedSweeper

---

appveyor.yml

Build tests\DCPS\Messenger and run rtps variant.

appveyor.yml update:

---

dds/DCPS/SendStateDataSampleList.h
dds/DCPS/SendStateDataSampleList.inl
dds/DCPS/WriteDataContainer.cpp

- One more fix for WDC buffer management with resends

Continued bug fixing for pull request #272

---

configure
examples/DCPS/ishapes/Circle.cpp
examples/DCPS/ishapes/Circle.hpp
examples/DCPS/ishapes/DDSShapeDynamics.cpp
examples/DCPS/ishapes/DDSShapeDynamics.hpp
examples/DCPS/ishapes/Shape.hpp
examples/DCPS/ishapes/ShapesDialog.cpp
examples/DCPS/ishapes/ShapesWidget.cpp
examples/DCPS/ishapes/ShapesWidget.hpp
examples/DCPS/ishapes/Square.cpp
examples/DCPS/ishapes/Square.hpp
examples/DCPS/ishapes/Triangle.cpp
examples/DCPS/ishapes/Triangle.hpp
examples/DCPS/ishapes/boost_or_cxx11.mpb
examples/DCPS/ishapes/ishapes.mpc

Builds on the change from pull request #329

configure and MPC support for C++11 version of ishapes; fixed a bug

---

dds/DCPS/DiscoveryBase.h

Add include to try to fix a build on the scoreboard

---

dds/DCPS/CoherentChangeControl.cpp

* dds/DCPS/CoherentChangeControl.cpp:

Check the return value of the serializer calls, see issue #340

---

MPC/config/dds_vc_warnings.mpb
tests/FACE/Partition/Subscriber/FacePartitionSubscriber.mpc

* MPC/config/dds_vc_warnings.mpb:

Disable another warning with nmake, see issue #354

---

examples/DCPS/ishapes/BouncingShapeDynamics.hpp
examples/DCPS/ishapes/DDSShapeDynamics.hpp
examples/DCPS/ishapes/ShapesDialog.cpp
examples/DCPS/ishapes/ShapesDialog.hpp

… the stub
* examples/DCPS/ishapes/BouncingShapeDynamics.hpp:
* examples/DCPS/ishapes/DDSShapeDynamics.hpp:
* examples/DCPS/ishapes/ShapesDialog.cpp:
* examples/DCPS/ishapes/ShapesDialog.hpp:

ishapes: Reduced includes of the typesupport impl header

---

tests/DCPS/LivelinessKeepAliveTest/LivelinessKeepAliveTest.mpc
tests/DCPS/LivelinessKeepAliveTest/publisher.cpp

Liveliness qos updates

---

dds/DCPS/Definitions.h
dds/DCPS/MultiTopicDataReaderBase.h
dds/DCPS/Service_Participant.h
dds/DCPS/TypeSupportImpl.h
dds/DCPS/transport/framework/TransportCustomizedElement.cpp
dds/DCPS/transport/framework/TransportSendControlElement.cpp
dds/DCPS/transport/framework/TransportSendElement.cpp

Make use of the new OPEN_DES_FREE_THIS to resolve compile warnings.

Make use of OPENDDS_DES_FREE_THIS

---

dds/InfoRepo/FederatorManagerImpl_updates.cpp

Fixed an uncaught exception which caused DCPSInfoRepo to crash occasionally.

Fix uncaught exception

---

tests/DCPS/TimeBasedFilter/main.cpp

Fixed problem with wide character build error.

Reliable Time Based Filter fixes for multiple build support

---

bin/dcps_tests.lst
dds/DCPS/DataReaderImpl.cpp
dds/DCPS/DataSampleHeader.h
tests/DCPS/TimeBasedFilter/main.cpp
tests/DCPS/TimeBasedFilter/run_test.pl

Working to clear up compiler warnings and some specific build issues.  Also debugging some failures in the reliable test case.

Time based filter updates

---

.travis.yml

Trying to enable the gh-pages branch so that it can try to build.

Try to get gh-pages branch building.

---

tests/FACE/Compiler/idl_test1_main/main.cpp
tools/scripts/gitrelease.pl

Corrected FACE idl_test1_main's interpretation of __OPENDDS_IDL version number

---

DDS_TAOv2.mwc
MPC/config/dcps_qos_xml_handler.mpb
MPC/config/dcps_qos_xml_handler_base.mpb
configure
dds/DCPS/QOS_XML_Handler/optional_ace_xml_utils.mpb
dds/DCPS/QOS_XML_Handler/qos_xml_handler.mpc

Contributed by Johnny Willemsen

Enable OpenDDS_QOS_XML_XSC_Handler when xerces3 is available, regardless of dds4ccm

---

dds/DCPS/DataReaderImpl_T.h
dds/DCPS/Serializer.cpp

Stricter check for invalid serialized data, especially string length larger than buffer remaining

Check for some types of invalid serialized data

---

dds/DCPS/DataWriterImpl_T.h

* dds/DCPS/DataWriterImpl_T.h:

Fixed logging statement

---

dds/DCPS/Qos_Helper.inl

Added datawriter qos validation debug messages

---

dds/DCPS/DataDurabilityCache.h

* dds/DCPS/DataDurabilityCache.h:

Fixed versioned namespace macro location

---

dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp
dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.h
tests/DCPS/StaticDiscovery/DataReaderListenerImpl.cpp
tests/DCPS/StaticDiscovery/DataReaderListenerImpl.h
tests/DCPS/StaticDiscovery/StaticDiscoveryTest.cpp

This fixes the tests/DCPS/StaticDiscovery/run_test.pl mpmrmw

Static discovery fix

---

appveyor.yml

Upgrade appveyor to use Visual Studio 2017, issue #507

---

bin/dcps_tests.lst
tests/DCPS/SampleLost/.gitignore
tests/DCPS/SampleLost/DataReaderListener.cpp
tests/DCPS/SampleLost/DataReaderListener.h
tests/DCPS/SampleLost/DataWriterListenerImpl.cpp
tests/DCPS/SampleLost/DataWriterListenerImpl.h
tests/DCPS/SampleLost/Messenger.idl
tests/DCPS/SampleLost/README
tests/DCPS/SampleLost/SampleLost.mpc
tests/DCPS/SampleLost/SampleLost_export.h
tests/DCPS/SampleLost/Writer.cpp
tests/DCPS/SampleLost/Writer.h
tests/DCPS/SampleLost/pub.ini
tests/DCPS/SampleLost/publisher.cpp
tests/DCPS/SampleLost/run_test.pl
tests/DCPS/SampleLost/sub.ini
tests/DCPS/SampleLost/subscriber.cpp

Written by @jwillemsen, this branch contains cherry-picked commits from PR #501

New test for "SampleLost"

---

.travis.yml

Java build failed with timeout again, so increasing the wait to 45 min.

Update travis.yml to increase the wait

---

dds/DCPS/transport/framework/TransportInst.cpp
dds/DCPS/transport/framework/TransportInst.h
dds/DCPS/transport/rtps_udp/RtpsUdpInst.h
dds/DCPS/transport/tcp/TcpInst.h
dds/DCPS/transport/udp/UdpInst.h

Another attempt to fix the IPv6 text representation without the dependencies on system calls.

Fix IPv6 address text representation problem

---

dds/DCPS/MultiTopicDataReaderBase.cpp
dds/DCPS/MultiTopicDataReaderBase.h

* dds/DCPS/MultiTopicDataReaderBase.cpp:
* dds/DCPS/MultiTopicDataReaderBase.h:

Fix compile errors/warnings as introduced by PR #540

---

tests/DCPS/ContentFilteredTopic/ContentFilteredTopicTest.cpp
tests/DCPS/Deadline/subscriber.cpp
tests/DCPS/QueryCondition/QueryConditionTest.cpp

* tests/DCPS/ContentFilteredTopic/ContentFilteredTopicTest.cpp:
* tests/DCPS/Deadline/subscriber.cpp:
* tests/DCPS/QueryCondition/QueryConditionTest.cpp:

Check return code of WaitSet::wait call in tests

---

dds/DCPS/DataReaderImpl.cpp
dds/DCPS/DataReaderImpl.h
dds/DCPS/DataWriterImpl.cpp
dds/DCPS/DataWriterImpl.h
dds/DCPS/PublisherImpl.cpp

* dds/DCPS/DataReaderImpl.cpp:
* dds/DCPS/DataReaderImpl.h:
* dds/DCPS/DataWriterImpl.h:
* dds/DCPS/PublisherImpl.cpp:

Removed dr/dw get_topic_name, just use the member directly

---

dds/DCPS/DataReaderImpl_T.h
dds/DCPS/InstanceState.inl

* dds/DCPS/DataReaderImpl_T.h:
* dds/DCPS/InstanceState.inl:

Fixed some typos in comments

---

DDS_TAOv2.mwc
README.md

…valuetype it should build it itself
* DDS_TAOv2.mwc:

Documentation changes in DDS_TAOv2.mwc and README.md

---

dds/DCPS/transport/framework/DataLink.cpp
dds/DCPS/transport/framework/NetworkAddress.cpp
dds/DCPS/transport/framework/TransportHeader.cpp
dds/DCPS/transport/framework/TransportHeader.h
dds/DCPS/transport/framework/TransportHeader.inl
dds/DCPS/transport/framework/TransportSendStrategy.cpp
dds/DCPS/transport/framework/TransportSendStrategy.h
dds/DCPS/transport/multicast/MulticastDataLink.cpp
dds/DCPS/transport/multicast/MulticastTransport.cpp
dds/DCPS/transport/rtps_udp/RtpsUdpSendStrategy.cpp
dds/DCPS/transport/rtps_udp/RtpsUdpSendStrategy.h
dds/DCPS/transport/udp/UdpTransport.cpp

* dds/DCPS/transport/framework/DataLink.cpp:
* dds/DCPS/transport/framework/NetworkAddress.cpp:
* dds/DCPS/transport/framework/TransportHeader.cpp:
* dds/DCPS/transport/framework/TransportHeader.h:
* dds/DCPS/transport/framework/TransportHeader.inl:
* dds/DCPS/transport/framework/TransportSendStrategy.cpp:
* dds/DCPS/transport/framework/TransportSendStrategy.h:
* dds/DCPS/transport/multicast/MulticastDataLink.cpp:
* dds/DCPS/transport/multicast/MulticastTransport.cpp:
* dds/DCPS/transport/rtps_udp/RtpsUdpSendStrategy.cpp:
* dds/DCPS/transport/rtps_udp/RtpsUdpSendStrategy.h:
* dds/DCPS/transport/udp/UdpTransport.cpp:

Const improvements, check return values in some places

---

dds/DCPS/DataReaderImpl_T.h
dds/DCPS/DataWriterImpl.cpp
dds/DdsDcpsSubscriptionExt.idl
tests/DCPS/SampleLost/DataReaderListener.cpp
tests/DCPS/SampleLost/DataReaderListener.h
tests/DCPS/SampleLost/subscriber.cpp

Created a PR to get this compiled, merge after #608

Fixes for total_count_changes not set back to 0 after invoking a listener

---

tests/DCPS/FooTest3_0/PubDriver.cpp
tests/DCPS/WriteDataContainer/WriteDataContainerTest.cpp

- FooTest3_0
- WriteDataContainer

Fixed Coverity-reported issues in tests

---

dds/InfoRepo/DCPS_IR_Participant.h
dds/InfoRepo/DCPS_IR_Topic.h
tests/DCPS/ZeroCopyRead/main.cpp

* dds/InfoRepo/DCPS_IR_Participant.h:
* dds/InfoRepo/DCPS_IR_Topic.h:
* tests/DCPS/ZeroCopyRead/main.cpp:

Fix propogate to propagate

---

dds/DCPS/DataReaderImpl.cpp
dds/DCPS/DataReaderImpl.h
dds/DCPS/RecorderImpl.cpp
dds/DCPS/RecorderImpl.h
dds/DCPS/RemoveAssociationSweeper.h
dds/DCPS/WriterInfo.cpp
dds/DCPS/WriterInfo.h

Fix RemoveAssociationSweeper failed to remove association problem

---

tests/DCPS/Reconnect/DataWriterListener.cpp
tests/DCPS/Reconnect/DataWriterListener.h

* tests/DCPS/Reconnect/DataWriterListener.cpp:
* tests/DCPS/Reconnect/DataWriterListener.h:

Layout changes in Reconnect test

---

dds/DCPS/RTPS/RtpsDiscovery.h

* dds/DCPS/RTPS/RtpsDiscovery.h:

Remove not needed include

---

dds/DCPS/Serializer.cpp

Fix gcc7.1 warnings

---

dds/DCPS/transport/tcp/TcpConnection.h

* dds/DCPS/transport/tcp/TcpConnection.h:

Fixed some typos

---

dds/DCPS/DataReaderImpl.cpp
dds/DCPS/DataWriterImpl.cpp
dds/DCPS/EntityImpl.h
dds/DCPS/TopicImpl.cpp

Make set_deleted/get_deleted/set_enabled of EntityImpl protected instead of public

---

dds/DCPS/DomainParticipantFactoryImpl.cpp
dds/DCPS/DomainParticipantImpl.cpp
dds/DCPS/DomainParticipantImpl.h

Change dp::is_clean to return a bool instead of int

---

dds/DCPS/InfoRepoDiscovery/InfoRepoDiscovery.cpp

* dds/DCPS/InfoRepoDiscovery/InfoRepoDiscovery.cpp:

Corrected check for when to use find_POA

---

dds/DCPS/DomainParticipantImpl.cpp
dds/DCPS/DomainParticipantImpl.h

* dds/DCPS/DomainParticipantImpl.cpp:
* dds/DCPS/DomainParticipantImpl.h:

Make client_refs_ an unsigned long and use prefix increment/decrement

---

tests/DCPS/Serializer_wstring/DataReaderListener.cpp
tests/DCPS/Serializer_wstring/Writer.cpp
tests/DCPS/Serializer_wstring/Writer.h

* tests/DCPS/Serializer_wstring/Writer.cpp:
* tests/DCPS/Serializer_wstring/Writer.h:

Add missing breaks

---

.travis.yml

Add osx to travis-ci

---

tests/DCPS/Serializer/SerializerTest.cpp

* tests/DCPS/Serializer/SerializerTest.cpp:

Add include of string

---

dds/DCPS/DomainParticipantImpl.cpp

* dds/DCPS/DomainParticipantImpl.cpp:

Only need a single space in the logging message

---

README.md
configure

Use new ACE 6.4.4 and TAO 2.4.4 for DOC group release

---

dds/idl/langmap_generator.cpp
tests/DCPS/FooTest3_0/SubDriver.cpp
tests/DCPS/Partition/Publisher.cpp
tests/DCPS/TestFramework/TestFramework_T.cpp
tests/DCPS/TransientLocalMultiInstanceTest/publisher.cpp
tools/monitor/MonitorDataStorage.cpp

* dds/idl/langmap_generator.cpp:
* tests/DCPS/FooTest3_0/SubDriver.cpp:
* tests/DCPS/Partition/Publisher.cpp:
* tests/DCPS/TestFramework/TestFramework_T.cpp:
* tests/DCPS/TransientLocalMultiInstanceTest/publisher.cpp:
* tools/monitor/MonitorDataStorage.cpp:

Removed double semi colon

---

.dockerignore
DevGuideExamples/DCPS/Messenger/docker-compose-inforepo.yml
DevGuideExamples/DCPS/Messenger/docker-compose.yml
DevGuideExamples/DCPS/Messenger/wait-for-it.sh
Dockerfile
README.md

Add a Docker image with a pre-built OpenDDS.
The name of the image (wilson/opendds) must change once this is merged into master.
See #703

Docker image

---

tests/DCPS/LivelinessKeepAliveTest/LivelinessKeepAliveTest_export.h
tests/DCPS/StringKey/pub_multicast.ini
tests/DCPS/StringKey/sub_multicast.ini

* tests/DCPS/LivelinessKeepAliveTest/LivelinessKeepAliveTest_export.h:
* tests/DCPS/StringKey/pub_multicast.ini:
* tests/DCPS/StringKey/sub_multicast.ini:

Zap some left over Ids

---

tools/scripts/gitrelease.pl

- Automate release commit
- Make cloning faster
- Fix .tar.gz and .zip creation so it doesn't destroy the clone
- Fix file names uploaded to github

Update release script

---

dds/DCPS/DataReaderImpl_T.h
dds/DCPS/ReceivedDataElementList.cpp

Fix unused parameter warning messages

---

dds/DCPS/PublisherImpl.cpp
dds/DCPS/Service_Participant.cpp
dds/DCPS/Service_Participant.h
dds/monitor/MonitorFactoryImpl.cpp
dds/monitor/README
tests/DCPS/Monitor/.gitignore
tests/DCPS/Monitor/mon.ini
tests/DCPS/Monitor/monitor.cpp
tests/DCPS/Monitor/pub.ini
tests/DCPS/Monitor/publisher.cpp
tests/DCPS/Monitor/run_test.pl
tests/DCPS/Monitor/sub.ini
tests/DCPS/Monitor/subscriber.cpp
tests/DCPS/RtiSerialization/run_test.pl

Add new DCPSMonitor config flag to fix Monitor test and make initialization easier.
Enhance Monitor test to really check the functionality is operational.

Fix Monitor test

---

configure

Use DOC Group TAO 2.4.6

---

.travis.yml
appveyor.yml
dds/DCPS/FilterEvaluator.cpp
dds/FACE/FaceTSS.cpp

and fixed an unrelated unused variable warning

Filter Eval: improved error message

---

dds/DCPS/QOS_XML_Handler/qos_xml_handler.mpc

* dds/DCPS/QOS_XML_Handler/qos_xml_handler.mpc:

Fixed error in this mpc file

---

dds/DCPS/QOS_XML_Handler/dds_qos.cpp
dds/DCPS/QOS_XML_Handler/dds_qos.hpp

* dds/DCPS/QOS_XML_Handler/dds_qos.cpp:
* dds/DCPS/QOS_XML_Handler/dds_qos.hpp:

Regenerated QoS XML files with the latest xsc version

---

README.md
bin/dcps_tests.lst
dds/idl/dds_generator.h
tests/DCPS/Instances/InstanceDataMap.h

Warnings and codacy

---

tools/scripts/generate_combined_doxygen.pl

Generates ACE docs in place instead of moving them afterwards.
This should make it possible to run this multiple times without issue.
Also tired to make the formatting more consistent where I could.

Fix Issue with generate_combined_doxygen.pl Failing After First Run

---

dds/idl/dds_generator.h
tests/DCPS/Compiler/idl_test1_lib/FooDef.idl

IDL compiler: support all valid bool-discriminated unions

---

quickstart/GettingStartedPi.html

Adapted from the Linux quickstart,
Screenshot of page:

website: Added Raspberry Pi Quickstart Page

---

dds/DCPS/transport/framework/DataLink.cpp
dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp
dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.h
tests/DCPS/Rejects/run_test.pl

Fix the deadlock issue for ManyToMany RTPS test

Deadlock fix

---

configure

Use DOC Group x.4.7

---

dds/DCPS/QOS_XML_Handler/dds_qos.cpp
dds/DCPS/QOS_XML_Handler/dds_qos.hpp
docs/schema/xsc-banner.cpp
docs/schema/xsc-banner.h

* docs/schema/xsc-banner.cpp:
* docs/schema/xsc-banner.h:

Use link to xsc repo for improvements to the generated code and regenerated with xsc

---

tools/dissector/plugin.cpp

The dissector can compile and register with the current experimental Wireshark version 2.5, but glib prints errors on startup and the dissector is never used. The way of registering plugins seems to have changed at some point and/or the old way was broken in 2.5. I would have preferred it not be able to compile verses having to figure that out myself, but this uses the new method if using Wireshark 2.5 or greater.

Dissector: Update Plugin Registration to work with Wireshark 2.5/2.6

---

dds/DCPS/DataReaderImpl.cpp
dds/DCPS/transport/framework/DataLink.inl
dds/InfoRepo/DCPS_IR_Subscription.cpp
tests/DCPS/BuiltInTopicTest/monitor.cpp
tests/DCPS/BuiltInTopicTest/prst_repo_run_test.pl
tests/DCPS/BuiltInTopicTest/subscriber.cpp

This has fixes for `tests/DCPS/BuiltInTopicTest/run_test.pl` and I tried to but couldn't fix anything with `tests/DCPS/BuiltInTopicTest/prst_repo_run_test.pl`. There are a few questions that I have put in the source.

Built In Topic Test Fixes

---

dds/DCPS/transport/framework/DataLink.inl

This partially reverts commit 517669567438adc118841e47caf673369ac45f47, reversing
changes made to 17d6b622b8a019648fd6c4ce646420cc764dad25.

Revert DataLink.inl change from "Merge pull request #828 from iguessthislldo/bit"

---

dds/FACE/FaceTSS.cpp

Catch all variants of Transport::Exception in FaceTSS

---

dds/DCPS/DataReaderImpl.cpp
dds/DCPS/WriterInfo.cpp
dds/DCPS/WriterInfo.h

(cherry picked from commit 597346e534c76853a68f1a2d767ff311a800c2cf)

Removed unused sequence number tracking in DataReaderImpl

---

index.markdown

The NEWS link does not seem to be working?

Update index.markdown (NEWS link is broken - needs .md extension)

---

configure

Use ACE 6.4.8 and TAO 2.4.8

---

configure

Upgrade to DOC Group ACE/TAO x.5.1

---

dds/DCPS/GuidUtils.h
dds/DCPS/RTPS/Sedp.cpp

Also a small debug logging cleanup to match create_and_send_datareader_tokens().

Check for BUILTIN entity kind when sending builtin crypto tokens.

---

dds/DCPS/RecorderImpl.cpp

Simplified some code and added some const

---

configure

Use new ACE/TAO x.5.2 release

---

configure
docs/qt.md

- Automatic Support for when Qt Build tools have a suffix
- Automatic Support for when Qt is an installed vcpkg package.
I will still need to update the documentation (and fix a few thing the qt documentation).

Better support for Qt5 in the Configure Script

---

dds/DCPS/SubscriberImpl.cpp
tests/DCPS/FooTest3_0/SubDriver.cpp

Use datareader_map_ to check for the contained readers

---

azure-pipelines.yml
dds/DCPS/DomainParticipantImpl.cpp
tests/security/AccessControlTest.cpp

Found a build error when trying different configure option combos for footprint testing.

Fixing build when no-builtin-topic and security flags are both configured

---

dds/DCPS/DataReaderImpl.cpp
dds/DCPS/DataWriterImpl.cpp
tests/DCPS/DPFactoryQos/publisher.cpp
tests/DCPS/DPFactoryQos/subscriber.cpp

Fixed set_qos method for not enabled DataWriters and DataReaders

---

dds/DCPS/RTPS/Sedp.cpp
dds/DCPS/transport/framework/DataLink.h
dds/InfoRepo/DCPS_IR_Topic.h
dds/InfoRepo/DCPS_IR_Topic_Description.cpp

* dds/DCPS/RTPS/Sedp.cpp:
* dds/DCPS/transport/framework/DataLink.h:
* dds/InfoRepo/DCPS_IR_Topic.h:
* dds/InfoRepo/DCPS_IR_Topic_Description.cpp:

Fixed subcription typo

---

.travis.yml

as described in https://blog.travis-ci.com/2018-10-04-combining-linux-infrastructures

Don't use sudo anymore and use travis_latest as group

---

tests/DCPS/InconsistentTopic/publisher.cpp
tests/DCPS/InconsistentTopic/subscriber.cpp

* tests/DCPS/InconsistentTopic/publisher.cpp:
* tests/DCPS/InconsistentTopic/subscriber.cpp:

Add includes as other tests do for static setup

---

dds/DCPS/GuidUtils.cpp

Assign variable as value when declaring it

---

dds/DCPS/DataReaderImpl.cpp
dds/DCPS/DataWriterImpl.cpp

* dds/DCPS/DataReaderImpl.cpp:

Don't use 0 but the correct macro for the return type

---

tests/DCPS/InconsistentTopic/subscriber.cpp

* tests/DCPS/InconsistentTopic/subscriber.cpp:

Fixed incorrect comparison, issue #995

---

Dockerfile

Disable tests and build Messenger by itself.

Build of Docker image timesout

---

configure

Use ACE 6.5.4 and TAO 2.5.4

---

.mailmap
AUTHORS
NEWS.md
tools/scripts/gitrelease.pl

Attempt to improve release script. These changes include:
- Fixes for #1038
- More proper markdown format of `NEWS.md` file, add timestamp to release
template.
- Redo how `AUTHORS` file is handled, try to leverage git's built in system
for correcting author info: `.mailmap`.
- Add missing entries to `AUTHORS`
- Explicit workspace for intermediate files that must be passed
- Download ACE/TAO automatically when needed for Doxygen
- Optionally define steps to perform using a notation listed in `--help`
- Removed `--step` option
- Expanded `--help` message
Created .mailmap and modified AUTHORS and NEWS.md to reflect these changes.

Release Script Fixes and Improvements

---

bin/dcps_tests.lst
dds/DCPS/DomainParticipantImpl.cpp
dds/DCPS/RTPS/Sedp.cpp
dds/DCPS/RTPS/Sedp.h
dds/DCPS/RTPS/Spdp.cpp
dds/DCPS/ReactorInterceptor.cpp
dds/DCPS/Service_Participant.cpp
dds/DCPS/transport/framework/TransportRegistry.cpp
dds/DCPS/transport/framework/TransportRegistry.h
dds/DCPS/transport/framework/TransportRegistry.inl
dds/DCPS/transport/rtps_udp/RtpsUdpLoader.cpp
dds/DCPS/transport/rtps_udp/RtpsUdpLoader.h
java/tests/hello/conditional_idlflags.mpb
java/tests/hello/hello_java_client.mpc
tests/DCPS/Restart/.gitignore
tests/DCPS/Restart/Messenger.idl
tests/DCPS/Restart/RestartTest.cpp
tests/DCPS/Restart/RestartTest.mpc
tests/DCPS/Restart/run_test.pl

PR1081 for the 3.13 branch: Service Participant, Transport Registry, RTPS libs updated to support certain Restart scenarios

---

configure

Upgrade to ACE+TAO 6.5.5

---

dds/DCPS/security/SSL/DiffieHellman.cpp

Fixes the diffie hellman code for public key retrieval. The primary issue was that the code was using DH_size() to calculate the public key size in bytes, which is meant for derived keys from DH_compute_key(), rather than using BN_num_bytes() on the internal BIGNUM representation of the public key. This seems to have been the primary cause of the intermittent failure.
This commit also does some some general code cleanup in DiffieHellman.cpp, including removal of operator()() for the sake of clarity (other operator() instances remain) and updating initial key general to exclusively use higher-level EVP_ methods for key generation. After initial key generation, sometimes the lower level APIs are still used.

Fix Periodic Diffie Hellman Test Failure

---

azure-pipelines.yml

Add clang8 to azure pipelines

---

configure

also cleaned up style for consistency

configure: updated Qt5 vcpkg support

---

azure-pipelines.yml
configure
tests/cmake_integration/run_ci_tests.pl

Add cmake test back to vs2019 now that cmake is upgraded on azure

---

configure

1.8.1 doesn't compile on CentOS/RHEL 6
https://github.com/google/googletest/pull/2085

Update googletest submodule to a commit on their 1.8.x branch after 1.8.1

---

.travis.yml
tests/DCPS/BuiltInTopic/BuiltInTopic.mpc
tests/DCPS/BuiltInTopicTest/BuiltInTopicTest.mpc

(cherry picked from commit 749b1d33305738069e96d1e60592397d991a31b0)

tweaking travis build to try to avoid 50 min timeout

---

azure-pipelines.yml

Add Visual Studio 2015 job to azure, see issue #999

---

.gitmodules
.travis.yml
MPC/config/rapidjson.mpb
configure

Doing what I should have done in #1097
- Fixed RapidJSON messages in configure scripts.
- Moved RapidJSON module from ITL into tools, something I meant to do but forgot.

Fixes for RapidJSON

---

_posts/2019-06-19-online-training.md

Created a News announcement of the Intro to OpenDDS training classes (C++ and Java) scheduled for July 2019.

Announce Intro to OpenDDS training in July 2019

---

configure

Otherwise the configure stops just to show you the git commit.

When Using --ace-github-latest, Don't Have Git Use a Pager

---

dds/DCPS/transport/rtps_udp/RtpsUdpReceiveStrategy.cpp

Fix for compiling with security and earlier versions of ACE

ICE and ACE_RECVPKTINFO

---

dds/DCPS/transport/rtps_udp/RtpsUdpSendStrategy.cpp

Problem: Send error when mixing secure and plain submessages
Solution: Allow plain submessages indicatated by null cryptohandle.

Serialization error when mixing secure and plain RTPS submessages

---

dds/DCPS/DomainParticipantImpl.cpp
dds/DCPS/TopicImpl.cpp

* dds/DCPS/DomainParticipantImpl.cpp:
* dds/DCPS/TopicImpl.cpp:

Check the debug level before logging the error

---

tests/DCPS/Presentation/main.cpp

Fix For Static Builds for #1094

Restore Includes in Presentation Test

---

dds/DCPS/DataReaderImpl.cpp
dds/DCPS/DataReaderImpl_T.h
dds/DCPS/GroupRakeData.cpp
dds/DCPS/InstanceState.cpp
dds/DCPS/InstanceState.h
dds/DCPS/InstanceState.inl
dds/DCPS/OwnershipManager.cpp
dds/DCPS/OwnershipManager.h
dds/DCPS/RakeResults_T.cpp
dds/DCPS/ReceivedDataElementList.cpp
dds/DCPS/ReceivedDataElementList.h
dds/DCPS/RequestedDeadlineWatchdog.cpp
dds/DCPS/StaticDiscovery.cpp
dds/DCPS/SubscriptionInstance.h

made the InstanceState an RcObject and cleaned up its uses in OpenDDS_Dcps

[3.13] InstanceState: use the ReactorInterceptor to mediate threading with the ACE Recator

---

dds/DCPS/DataReaderImpl.cpp
dds/DCPS/DataReaderImpl_T.h
dds/DCPS/GroupRakeData.cpp
dds/DCPS/InstanceState.cpp
dds/DCPS/InstanceState.h
dds/DCPS/InstanceState.inl
dds/DCPS/OwnershipManager.cpp
dds/DCPS/OwnershipManager.h
dds/DCPS/RakeResults_T.cpp
dds/DCPS/ReceivedDataElementList.cpp
dds/DCPS/ReceivedDataElementList.h
dds/DCPS/RequestedDeadlineWatchdog.cpp
dds/DCPS/SubscriptionInstance.h

made the InstanceState an RcObject and cleaned up its uses in OpenDDS_Dcps

InstanceState: use the ReactorInterceptor to mediate threading with the ACE Recator

---

performance-tests/DCPS/InfoRepo_population/InfoRepo_population.mpc
tests/DCPS/UnionTopic/UnionTopic.cpp

Fixes for #1233

---

dds/DCPS/transport/framework/TransportClient.cpp
dds/DCPS/transport/framework/TransportClient.h
dds/DCPS/transport/framework/TransportInst.cpp
dds/DCPS/transport/framework/TransportInst.h
tests/DCPS/ConfigTransports/DDSTEST.cpp
tests/DCPS/SetQosPartition/subscriber.cpp

Fixes for periodic SetQosPartition failures (segfault & test failure based on missed messages)

Setqospartion test reliable datareader

---

_posts/2019-10-03-dds-xrce.md
about/articles/mnb.markdown

OpenDDS.org updates to include Oct '19 SETT article.

Oct 2019 SETT article updates

---

.mailmap
AUTHORS
NEWS.md
tools/scripts/gitrelease.pl

These changes are from #1049 (3.13 already has #1038)

Bring master Release Script Changes into 3.13

---

dds/DCPS/RTPS/ICE/EndpointManager.cpp
dds/DCPS/RTPS/ICE/Stun.cpp
dds/DCPS/RTPS/ParameterListConverter.cpp
dds/DCPS/RTPS/Spdp.cpp

* Force loading of default plugins if necessary
* Fix deserialization bug
* Include ICE Agent Info in SPDP

Fix ICE bugs

---

.travis.yml

Moved travis-ci to ubuntu 18.04 with gcc8

---

dds/DCPS/RTPS/ParameterListConverter.cpp
dds/DCPS/RTPS/RtpsCore.idl
dds/DCPS/RTPS/Sedp.cpp
dds/DCPS/RTPS/Spdp.cpp
tests/security/TopicWithoutPermissions/.gitignore
tests/security/TopicWithoutPermissions/TopicWithoutPermissions.cpp
tests/security/security_tests.lst
tests/transport/spdp/spdp_transport.cpp

Add DomainID PID & Add Domain to SPDP Announcement ParameterList. Add & Apply Security Flag to DATA & DATAFRAG Submessages.

RTPS 2.4: SPDP Domain ID and BuiltinEndpointQos

---

dds/DCPS/DataReaderImpl.h
dds/DCPS/RTPS/BaseMessageTypes.h
dds/DCPS/RTPS/BaseMessageUtils.cpp
dds/DCPS/RTPS/BaseMessageUtils.h
dds/DCPS/RTPS/RtpsCore.idl
dds/DCPS/RTPS/Spdp.cpp
dds/DCPS/Stats_T.h
dds/DCPS/TimeDuration.h
dds/DCPS/TimeDuration.inl
dds/DCPS/Time_Helper.h
dds/DCPS/Time_Helper.inl
dds/DCPS/transport/rtps_udp/RtpsSampleHeader.cpp
dds/DCPS/transport/rtps_udp/RtpsUdpReceiveStrategy.cpp
tests/DCPS/TcpReconnect/.gitignore
tests/DCPS/UnitTests/.gitignore
tests/DCPS/UnitTests/RtpsDuration.cpp
tests/DCPS/UnitTests/UnitTests.mpc
tests/transport/rtps/publisher.cpp

Along with removal of some unused PIDs from the spec and warning cleanup.

RTPS 2.4 Time_t and Duration_t Changes

---

configure

configure script: option to download DOCGroup ACE 6.5.7 / TAO 2.5.7

---

dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp

in order to prevent deadlocking

Release link lock while calling gather_ack_nack on RtpsReaders

---

dds/DCPS/DomainParticipantImpl.cpp

Participant Location (connection endpoint) changes to fix failing tests

Fix tests that started failing with #1389

---

dds/DCPS/DomainParticipantImpl.cpp
dds/DCPS/TopicImpl.cpp
dds/DCPS/TopicImpl.h
tests/DCPS/ParticipantLocationTopic/publisher.cpp
tests/DCPS/ParticipantLocationTopic/relay.ini
tests/DCPS/ParticipantLocationTopic/run_test.pl
tests/DCPS/ParticipantLocationTopic/subscriber.cpp

Modify DomainParticipantImpl::is_clean to use new TopicImpl::topic_name. Modify ParticipantLocation test.

Fix ParticipantLocation Test

---

Dockerfile

Simple change to update Dockerfile to use Ubuntu bionic (18.04) release.

update Dockerfile to bionic base image

---

dds/DCPS/GuardCondition.cpp
dds/DCPS/GuardCondition.h
tests/DCPS/GuardCondition/GuardConditionTest.cpp

It's not an IDL type but it needs to act more like one.
LocalObject template not compatible with multiple interface inheritance.

Fixed GuardCondition's _narrow

---

DevGuideExamples/DCPS/Messenger/CMakeLists.txt
azure-pipelines.yml
cmake/init.cmake
configure
dds/DdsDcps.mpc
dds/idl/be_util.cpp
dds/idl/be_util.h
dds/idl/opendds_idl.mpc
java/dds/dcps_java.mpc
tests/cmake_integration/Messenger/Messenger_1/CMakeLists.txt
tests/cmake_integration/Messenger/Messenger_2/CMakeLists.txt

I'm using a prebuilt OpenDDS debian package for CI testing PyOpenDDS. I applied a workaround for https://github.com/DOCGroup/ACE_TAO/pull/1015 (just copying the file) , but [it still didn't work](https://github.com/iguessthislldo/pyopendds/commit/1845e136d1ab3f099b2dec1d60ce24d431237087/checks?check_suite_id=387454185).
I looked into it and it's looking into PREFIX/bin for it, but scripts are put into PREFIX/share/ace/bin. As that directory also has symlinks to the binaries PREFIX/bin, change the ACE_BIN_DIR variable to that.

Fix Issues with Installed OpenDDS

---

dds/DCPS/RTPS/Spdp.cpp

Update ParticipantLocationTopic for SPDP from RtpsRelay when using security

---

dds/DCPS/transport/framework/TransportQueueElement.inl
dds/DCPS/transport/framework/TransportSendBuffer.cpp

Also cache call to msg_payload in TQE's MatchOnDataPayload and minor cleanup.

Update SingleSendBuffer::release_acked to use Efficient Lookup By SequenceNumber

---

bin/PerlDDS/Run_Test.pm

Bug fix for executable existence check in tests

---

dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp
dds/DCPS/transport/rtps_udp/RtpsUdpTransport.cpp

Switch RTPS reliable readers to wait for remote heartbeat before fully accepting a connection

---

dds/DCPS/transport/tcp/TcpConnection.cpp
dds/DCPS/transport/tcp/TcpConnection.h
dds/DCPS/transport/tcp/TcpTransport.cpp
dds/DCPS/transport/tcp/TcpTransport.h

fix handle_close issue and code cleanup

Tcp reconnect fix

---

tests/transport/rtps_directed_write/.gitignore
tests/transport/rtps_directed_write/publisher.cpp

Directed write test cleanup

---

dds/DCPS/RTPS/Sedp.cpp
dds/DCPS/RTPS/Sedp.h
dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp
dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.h
tests/transport/rtps_directed_write/publisher.cpp
tests/transport/rtps_reliability/rtps_reliability.cpp

Fixes reader-side associations for RTPS

Fix multi-transport Messenger test

---

dds/DCPS/transport/framework/TransportSendBuffer.cpp
dds/DCPS/transport/framework/TransportSendBuffer.h
dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp

Remove delete / release from within SingleSendBuffer mutex locking / RtpsWriter mutex locking

---

azure-pipelines.yml

Cherry-picked just the VS2015 parts of #1532, to restore this build to passing

Azure Pipelines: Removed security from VS2015

---

dds/DCPS/RTPS/Spdp.cpp
dds/DCPS/debug.cpp
dds/DCPS/debug.h
dds/DCPS/security/AccessControl/Permissions.cpp
dds/DCPS/security/CryptoBuiltInImpl.cpp
dds/DCPS/transport/rtps_udp/RtpsUdpReceiveStrategy.cpp
tests/DCPS/Messenger/run_test.pl

Tweak security logging categories and bring some more logging points under the control of them.

Tweak Security Logging

---

dds/DCPS/transport/framework/TransportClient.cpp
dds/DCPS/transport/framework/TransportClient.h

It's currently possible to create a pending association and destroy a transport client before the pending association has time to fire and/or the cancel command can run to prevent it. This PR forces the pending association to use a WeakRcHandle to check to see if the TransportClient object still exists before attempting to call into the client, as well as migrating old pending association objects into a separate container rather than erasing them directly in order to give a safe location for timeouts to occur before a cancel timer command can execute. A "perfect" solution might use timeout objects that lived outside the transport client to catch instances where the pending association timer expires after transportclient destruction but before the cancel command can run, but that seemed …

Fix TransportClient::PendingAssoc Timeout SEGV Issues

---

README.md

Make use of https download.dre

---

dds/DCPS/security/AuthenticationBuiltInImpl.cpp
dds/DCPS/security/SSL/Certificate.cpp
dds/DCPS/security/SSL/SignedDocument.cpp

Changes to support loading security certificates from Android storage.

Android workarounds for C++ std library issues

---

dds/DCPS/RTPS/Spdp.cpp
dds/DCPS/RTPS/Spdp.h
dds/DCPS/transport/rtps_udp/RtpsUdpInst.cpp

This breaks certain versions of Linux.

Bug fixes related to IPV6 in RTPS

---

bin/dcps_tests.lst
tests/security/security_tests.lst

tests that need security-enabled builds go in security_tests.lst

ParticipantLocationTopic test: updated test lists

---

configure

https://gcc.gnu.org/projects/cxx-status.html#cxx2a

Detect std c++2a/c++20

---

dds/DCPS/OfferedDeadlineWatchdog.cpp

If deadline is being used and the write writes after the deadline and
another durable reader is associating then deadlock can occur.

Fix deadlock in OfferedDeadlineWatchdog

---

azure-pipelines.yml

This reverts commit d107805834cd30769ce14e0cb4a647ac3bf033f2.

Revert "azure-pipelines.yml: removed VS2019"

---

dds/DCPS/RTPS/Spdp.cpp
dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp
dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.h

For consistent sending of pre-association AckNacks

Migrate RtpsUdpDatalink's heartbeat replies to MultiTask

---

docs/guidelines.md

Add rule from https://github.com/objectcomputing/OpenDDS/pull/1675#discussion_r430561805
Also fix typo in order section.

guidelines.md: Tweak Includes Sections

---

dds/DCPS/RTPS/ICE/Checklist.h
dds/DCPS/RTPS/ICE/EndpointManager.cpp

The check was improved to check the consistency between the
EndpointManager data structures and the Checklists.

Improve check_invariants in ICE EndpointManager

---

tools/dissector/README.md
tools/dissector/packet-opendds.cpp

small function call changes to deal with updates that are part of xtypes

XTypes: fixes to wireshark for xtypes

---

dds/DCPS/TypeAssignability.cpp
dds/DCPS/TypeAssignability.h
tests/DCPS/UnitTests/XtypesAssignability.cpp

- Unit test for string types.
- Add public interfaces to TypeAssignability to facilitate testing.

XTypes: String test

---

dds/DCPS/TypeAssignability.cpp
tests/DCPS/UnitTests/XtypesAssignability.cpp

- Unit tests for enumeration and bitmask
- Fix assignability for enumeration

XTypes: Enumerated types test

---

.travis.yml
azure-pipelines.yml
cmake/api_macros.cmake
tests/cmake_integration/Messenger/C++11_Messenger/CMakeLists.txt
tests/cmake_integration/run_ci_tests.pl

Also updated run_ci_tests.pl to attempt C++11 test and shared libs for all 3 tests

CMake: support C++11 mapping when building shared libs

---

dds/DCPS/DCPS_Utils.cpp
dds/DCPS/DCPS_Utils.h
dds/DCPS/DataReaderImpl.cpp
dds/DCPS/DataWriterImpl.cpp
dds/DCPS/DataWriterImpl_T.h
dds/DCPS/TopicImpl.cpp

Adds a function to handle empty DR QoS which allows removal of code elsewhere and simplifies design.

XTypes: Data Representation Effective QoS

---

dds/DCPS/transport/multicast/MulticastTransport.cpp
dds/DCPS/transport/tcp/TcpInst.h
dds/DCPS/transport/udp/UdpInst.h

Update to #1727, avoid name resolution of DCPSDefaultAddress in ACE

---

dds/idl/be_global.h
dds/idl/typeobject_generator.cpp
dds/idl/typeobject_generator.h
etc/xtypes/opendds_typeobject.idl

Using IDL annotations to set flags

XTypes: Assignability Flags

---

tests/security/attributes/Args.cpp
tests/security/attributes/DataReaderListener.cpp
tests/security/attributes/Writer.cpp
tests/security/attributes/publisher.cpp
tests/security/attributes/run_test.pl
tests/security/attributes/subscriber.cpp

Also remove negative exit statuses.

Fix Unused Function Warning in Attributes Test

---

azure-pipelines.yml

Azure Pipelines: Use JAVA_HOME_12_X64 as location for java

---

support.html

@mitza-oci Here is the support page updated with Nicki's requests.
Proofread document; made minor capitalization and punctuation corrections; updated mailing list copy to include a link to OCI's resources page; updated commercial support section to include pre-paid support packages and new link; updated training section to include more information and updated links.

copy and link updates

---

dds/DCPS/CoherentChangeControl.cpp
dds/DCPS/DataSampleHeader.cpp
dds/DCPS/GuidUtils.cpp
dds/DCPS/RestoreOutputStreamState.h
performance-tests/bench_2/builder/Common.cpp
tests/DCPS/ParticipantLocationTopic/ParticipantLocationListenerImpl.cpp
tests/DCPS/Restart/RestartTest.cpp
tools/rtpsrelay/RelayHandler.h

Attempts to fix the last four medium impact issues reported by Coverity. Prompted by Coverity issue caused by changes in #1737.

Various Coverity Fixes

---

dds/DCPS/DataWriterImpl.cpp

restored setting historic_sample_ (from before #1732)

Fixing leaked durable buffered data

---

dds/DCPS/DataReaderImpl.cpp
dds/DCPS/transport/framework/TransportReceiveStrategy_T.cpp

Minor cleanup

---

dds/DCPS/DataReaderImpl.cpp
dds/DCPS/DataWriterImpl.cpp
dds/idl/ts_generator.cpp

A few minor fixes I've been sitting on.

XTypes: Minor Fixes

---

dds/DCPS/Serializer.cpp
dds/DCPS/Serializer.inl
tests/DCPS/UnitTests/.gitignore
tests/DCPS/UnitTests/Serializer.cpp
tests/DCPS/UnitTests/UnitTests.mpc

Draft PR to run Serializer tests.

Serializer tests

---

dds/DCPS/Serializer.cpp
dds/DCPS/Serializer.h
dds/idl/marshal_generator.cpp
tests/DCPS/Compiler/xcdr/xcdr.cpp

Implement must_understand flag in XCDR2 on the reader side.
https://trello.com/c/EtGCQW8X/86-xcdr-parameter-list-flags

XTypes: XCDR2 must_understand flag

---

.travis.yml
MPC/config/dcps_ts_defaults.mpb
azure-pipelines.yml
bin/dcps_tests.lst
cmake/tao_idl_sources.cmake
dds/DCPS/DiscoveryBase.h
dds/DCPS/RTPS/Sedp.cpp
dds/DCPS/RTPS/Spdp.cpp
dds/DCPS/RTPS/Spdp.h
dds/DCPS/transport/framework/TransportClient.cpp
dds/DCPS/transport/framework/TransportClient.h
dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp
dds/idl/be_init.cpp
dds/idl/dds_visitor.cpp
dds/idl/field_info.cpp
dds/idl/field_info.h
dds/idl/langmap_generator.cpp
dds/idl/marshal_generator.cpp
dds/idl/metaclass_generator.cpp
java/idl2jni/codegen/be_init.cpp
tests/DCPS/Compiler/anonymous_types/classic/.gitignore
tests/DCPS/Compiler/anonymous_types/classic/anonymous_types_classic.mpc
tests/DCPS/Compiler/anonymous_types/cpp11/.gitignore
tests/DCPS/Compiler/anonymous_types/cpp11/anonymous_types_cpp11.mpc
tests/DCPS/Compiler/anonymous_types/test.idl

merged master 1332fdc84e6d758be5ffcd2dd3077ebeacc82068 into xtypes

Xtypes master merge

---

dds/DCPS/RTPS/RtpsDiscovery.h

Optimized version of the function didn't write all bytes of the return value

Work around a bug on GCC 5.2

---

dds/DCPS/RTPS/RtpsDiscovery.h

apply GCC 5.2 workaround to GCC 4 as well

---

tests/DCPS/Observer/publisher.cpp
tests/DCPS/Observer/subscriber.cpp

Added wait for test to properly finish.

Observer test

---

README.md

The TAO DevGuide can be requested for free

---

FACE/StringManager.h
dds/DCPS/JsonValueWriter.cpp
dds/DCPS/JsonValueWriter.h
dds/idl/value_writer_generator.cpp
tests/DCPS/Observer/TestObserver.cpp
tests/DCPS/common/ConnectionRecordLogger.cpp

- FACE string manager compat without code generator change (partially reverts #1933)
- FACE safety profile conformance (no IOStreams)
- cleaned up the code generator
- made the code generator generate indented code

Value Writer cleanup

---

.github/workflows/fuzz.yml

Use checkout action to checkout ACE/TAO

---

dds/DCPS/DiscoveryBase.h
dds/DCPS/RTPS/ParameterListConverter.cpp
dds/DCPS/RTPS/ParameterListConverter.h
dds/DCPS/RTPS/RtpsDiscovery.cpp
dds/DCPS/RTPS/RtpsDiscovery.h
dds/DCPS/RTPS/Sedp.cpp
tests/DCPS/UnitTests/ut_ParameterListConverter.cpp

Added XTYPES switch to RTPS Discovery configuration. Made Type Information addition to the parameter list conditional.

Added XTYPES switch to RTPS Discovery configuration

---

azure-pipelines.yml

and some other cleanup of the pipelines steps

Azure Pipelines updates to work with changes on xtypes

---

dds/DCPS/LinuxNetworkConfigMonitor.cpp

It fixes the problem on my machine, interested how it runs on the CI

LinuxMonitor failing to bind socket

---

tools/rtpsrelay/RelayHandler.cpp
tools/rtpsrelay/RelayHandler.h

* INFO_DST processing
* Dispose race condition (manifests as test timeout)

RtpsRelay bugs

---

dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp
dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.h

Problem
-------
Entries are inserted and never removed.
Solution
--------
Use correct identifier when searching for item to remove.

`readers_of_writers_` map leaks

---

tests/DCPS/Compiler/xcdr/xcdr.cpp
tests/DCPS/Compiler/xcdr/xcdr.idl

Mostly code having to do with unions that was deferred last time.

xcdr Test: Remove Workarounds, Commented Out Code

---

dds/DCPS/security/AccessControlBuiltInImpl.cpp
dds/DCPS/security/AccessControlBuiltInImpl.h

Problem
-------
The `RevokePermissionsTimer` deadlocks with concurrent calls to
`start_timer` and `handle_timeout`.
Solution
--------
Replace `ACE_Event_Handler` with SporadicTask.

`RevokePermissionsTimer` deadlocks

---

tests/DCPS/Monitor/mon.ini
tests/DCPS/Monitor/monitor.conf
tests/DCPS/Monitor/run_odds_mon.pl

When using QT and running run_odds_mon.pl , the QT GUI was crashing.  This has been fixed.  The user needs to click to change qt tabs for stuff to appear but I don't think that can be fixed in our code.

QT run_odds_mon Failing

---

dds/DCPS/transport/tcp/TcpAcceptor.cpp
dds/DCPS/transport/tcp/TcpAcceptor.h
dds/DCPS/transport/tcp/TcpConnection.cpp
dds/DCPS/transport/tcp/TcpDataLink.cpp
dds/DCPS/transport/tcp/TcpTransport.cpp

And ineffective transport_shutdown in TcpAcceptor

Fixing graceful disconnect issue in TcpDataLink

---

tests/DCPS/DcpsIntegration/DomainParticipantListener.cpp
tests/DCPS/DcpsIntegration/DomainParticipantListener.h
tests/DCPS/DcpsIntegration/TopicListener.cpp
tests/DCPS/FooTest3_0/DomainParticipantListener.cpp
tests/DCPS/FooTest3_0/DomainParticipantListener.h
tools/modeling/codegen/model/NullParticipantListener.cpp

* tests/DCPS/DcpsIntegration/DomainParticipantListener.cpp:
* tests/DCPS/DcpsIntegration/DomainParticipantListener.h:
* tests/DCPS/DcpsIntegration/TopicListener.cpp:
* tests/DCPS/FooTest3_0/DomainParticipantListener.cpp:
* tests/DCPS/FooTest3_0/DomainParticipantListener.h:
* tools/modeling/codegen/model/NullParticipantListener.cpp:

Minor layout cleanup

---

dds/DCPS/RTPS/Sedp.cpp

added historic flag in write_participant_message

Fix memory leaks detected in the LivelinessTimeout test

---

bin/run_dds.pl
examples/DCPS/DistributedContent/main.cpp
tools/repoctl/repoctl.cpp

* bin/run_dds.pl:
* examples/DCPS/DistributedContent/main.cpp:
* tools/repoctl/repoctl.cpp:

Typo, command instead of commmand

---

dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp

Solves a 3-way deadlock using the "thread_per_connection" transport feature, but also adds better protection against changes to send strategy during shutdown / cleanup.

Fix locking / unlocking for RtpsUdpDatalink remove samples

---

dds/DCPS/DataReaderImpl.cpp
dds/DCPS/DiscoveryBase.h

* dds/DCPS/DataReaderImpl.cpp:
* dds/DCPS/DiscoveryBase.h:

Const additions

---

dds/DCPS/RTPS/Spdp.cpp
dds/DCPS/RTPS/Spdp.h

Proposed fix for failing to join multicast due to simultaneous calls.  This is occurring in windows 7 and remedy fedora builds.

Failed To Join Multicast (IPv6)

---

dds/DCPS/RTPS/RtpsDiscovery.h
dds/DCPS/RTPS/Spdp.cpp
tools/rtpsrelay/RtpsRelay.cpp

XTypes: Disable Type Lookup Service in RTPS Relay

---

tools/scripts/show_build_config.pl

* tools/scripts/show_build_config.pl:

Log the VERSION.txt in show_build_config.pl

---

dds/DCPS/security/AccessControlBuiltInImpl.cpp
tests/security/AccessControlTest.cpp

AccessControl: shut down RevokePermissionsTask cleanly

---

dds/DCPS/Service_Participant.cpp
dds/DCPS/Service_Participant.h

…ine from the log which versions are used
* dds/DCPS/Service_Participant.h:

Add a log of the OpenDDS and ACE version

---

dds/DCPS/RTPS/Sedp.cpp

Correct operation name in several Sedp logging messages

---

dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp
dds/DCPS/transport/tcp/TcpConnection.cpp

* dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp:

Add const to some local variables

---

dds/DCPS/transport/rtps_udp/RtpsUdpInst.cpp

* dds/DCPS/transport/rtps_udp/RtpsUdpInst.cpp:

Extended logging RtpsUdp logging with send/recv buffer and ttl values

---

tools/monitor/MonitorDataStorage.inl
tools/monitor/TreeNode.h

* tools/monitor/MonitorDataStorage.inl:
* tools/monitor/TreeNode.h:

Fix warnings when compiling monitor tool with latest fedora releases

---

dds/DCPS/ConfigUtils.cpp
dds/DCPS/DataWriterImpl.cpp
dds/DCPS/RawDataSample.cpp
dds/DCPS/RecorderImpl.cpp
dds/DCPS/ReplayerImpl.cpp
dds/DCPS/Service_Participant.cpp
dds/DCPS/StaticDiscovery.cpp
dds/DCPS/security/framework/SecurityRegistry.cpp
dds/DCPS/transport/framework/PerConnectionSynch.cpp
dds/DCPS/transport/framework/TransportRegistry.cpp

* dds/DCPS/ConfigUtils.cpp:
* dds/DCPS/RawDataSample.cpp:
* dds/DCPS/RecorderImpl.cpp:
* dds/DCPS/ReplayerImpl.cpp:
* dds/DCPS/StaticDiscovery.cpp:
* dds/DCPS/security/framework/SecurityRegistry.cpp:
* dds/DCPS/transport/framework/PerConnectionSynch.cpp:
* dds/DCPS/transport/framework/TransportRegistry.cpp:

Use bool literals

---

dds/DCPS/DCPS_Utils.cpp
dds/DCPS/DataWriterImpl.cpp
dds/DCPS/DomainParticipantImpl.cpp
dds/DCPS/FilterEvaluator.cpp
dds/DCPS/MessageTracker.cpp
dds/DCPS/NetworkConfigMonitor.cpp
dds/DCPS/PublisherImpl.cpp
dds/DCPS/SubscriberImpl.cpp
dds/DCPS/WriteDataContainer.cpp
dds/DCPS/transport/framework/NetworkAddress.cpp

* dds/DCPS/DCPS_Utils.cpp:
* dds/DCPS/DomainParticipantImpl.cpp:
* dds/DCPS/FilterEvaluator.cpp:
* dds/DCPS/MessageTracker.cpp:
* dds/DCPS/NetworkConfigMonitor.cpp:
* dds/DCPS/PublisherImpl.cpp:
* dds/DCPS/SubscriberImpl.cpp:
* dds/DCPS/WriteDataContainer.cpp:
* dds/DCPS/transport/framework/NetworkAddress.cpp:

Simplify boolean expressions

---

dds/DCPS/transport/tcp/TcpTransport.cpp

* dds/DCPS/transport/tcp/TcpTransport.cpp:

Minor logging enhancements to TcpTransport::passive_connection

---

dds/DCPS/transport/rtps_udp/RtpsUdpReceiveStrategy.cpp

* dds/DCPS/transport/rtps_udp/RtpsUdpReceiveStrategy.cpp:

Small change to make a log message consistent with the others

---

dds/DCPS/WaitSet.cpp
dds/idl/typeobject_generator.cpp

Fix warning and removed `narrow_from_decl`.

XTypes Branch: Minor Fixes

---

dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp

Problem
-------
RTPS heartbeat first is not initialized.
Solution
--------
Initialize heartbeat first.

RTPS heartbeat first is not initialized

---

dds/DCPS/DiscoveryBase.h

DiscoveryBase: initialization for new member of DiscoveredPublicaton/Subscription

---

dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp

Problem
-------
Before, the datalink thread was responsible for invoking the callback
that replayed durable data.  Thus, durable replay was done when the
call returned.  Now, the discovery and/or user thread is responsible
for replaying durable data and it might not be finished by the time
the first nack arrives.  This results in a request that is gapped
leading to missed durable data.
Solution
--------
Do not process requests for missing data messages when the reader is
still expecting durable data.  See
f19f4d0f3f533918735d9832b4c241b8455cc932.

Durable replay not complete for nack (round 2)

---

tests/DCPS/Compiler/idl_test1_lib/FooDef.idl

* tests/DCPS/Compiler/idl_test1_lib/FooDef.idl:

Add a union test with array members

---

dds/DCPS/TimeDuration.cpp
dds/DCPS/TimePoint_T.cpp

* dds/DCPS/TimeDuration.cpp:
* dds/DCPS/TimePoint_T.cpp:

Make use of std::numeric_limits when we have C++11 support

---

dds/DCPS/transport/framework/TransportRegistry.cpp
dds/DCPS/transport/framework/TransportRegistry.h
dds/DCPS/transport/multicast/MulticastLoader.cpp
dds/DCPS/transport/rtps_udp/RtpsUdpLoader.cpp
dds/DCPS/transport/shmem/ShmemLoader.cpp
dds/DCPS/transport/tcp/TcpLoader.cpp
dds/DCPS/transport/udp/UdpLoader.cpp
dds/InfoRepo/DCPSInfoRepo.mpc
dds/InfoRepo/DCPSInfo_i.cpp

And a build dependency issue for DCPSInfoRepo and the TCP transport.

Fix race condition in TransportRegistry::fix_empty_default()

---

configure
java/dds/dcps_java.mpc

The previous PR was failing windows java builds.  This should resolve that issue.
Previous PR: https://github.com/objectcomputing/OpenDDS/pull/2237

Patch for Android API30 Reconnect. 

---

tools/scripts/show_build_config.pl

* tools/scripts/show_build_config.pl:

Print also ACE version as output from show_build_config.pl

---

tests/security/attributes/run_test.pl

Increased timeout for unsecure test case

Attributes test timeout fix

---

dds/idl/marshal_generator.cpp

It appears as OctetSeq in RtpsCore.idl but is not actually a sequence

special cases for PID_XTYPES_TYPE_INFORMATION in opendds_idl

---

java/tests/dcps_java_tests.lst
tests/security/security_tests.lst

Test code is still compiled on relevant configurations, tests will be revised

removed "participant location" from test lists

---

java/idl2jni/codegen/im_jni.cpp

Namespace was causing error on scoreboard build

Patch for idl2jni boolean switch

---

bin/dcps_tests.lst

Was breaking github actions due to running C++11 trycon test on non c++11 platform.

added cxx11 req to tryconstruct c++11 test

---

dds/DCPS/DataReaderImpl.cpp
dds/DCPS/DataReaderImpl.h
dds/DCPS/DataReaderImpl_T.h
dds/DCPS/DataWriterImpl_T.h
dds/DCPS/DiscoveryBase.h
dds/DCPS/XTypes/TypeLookupService.cpp
dds/DCPS/XTypes/TypeLookupService.h
dds/idl/marshal_generator.cpp
tests/DCPS/unit/MyTypeSupportImpl.h

We need to have some sort of runtime warning when a user tries to use XCDR1 Appendable and a warning or error when a user tries to use XCDR1 mutable.

Xtypes xcdr1 warnings

---

dds/DCPS/RTPS/Spdp.cpp

Problem
-------
`process_location_updates_i` can be called with an invalid iterator.
Solution
--------
Add control and checking to avoid using an invalid iterator.

`Spdp::handle_participant_data` use invalid iterator

---

dds/idl/langmap_generator.cpp
tests/DCPS/Compiler/C++11/idl_test3_main/main.cpp

Fixes failing test in #2292 by partially reverting #2190 and #2169.

Restored previous approach to C++11 array initialization

---

dds/idl/dds_generator.cpp
dds/idl/marshal_generator.cpp
tests/DCPS/Compiler/TryConstruct/TryConstruct.idl

I also silenced a spammy unused var warning.

type_to_default changed to use  ACE_CDR_LONG_DOUBLE_ASSIGNMENT

---

dds/DCPS/Serializer.cpp
dds/DCPS/Serializer.inl
dds/DCPS/XTypes/TypeObject.cpp

Fix compile errors on FACE Conformance Test server

---

dds/DCPS/StaticDiscovery.cpp
tests/DCPS/RtpsRelay/STUN/StunClient.cpp
tools/dissector/sample_dissector.cpp

Also fixed warnings: some related and some unrelated

StunClient test - remove dependency on RtpsRelay's header

---

dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp
dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.h

(cherry picked from commit a6cf6a17d0f80c24c655a0b446a19e65ebe9107c)

rtps_udp: updates for leader / lagger issues

---

dds/DCPS/DomainParticipantImpl.cpp
dds/DCPS/GuidConverter.cpp
dds/DCPS/GuidConverter.h
dds/DCPS/RTPS/Sedp.cpp
dds/DCPS/security/AccessControl/Governance.cpp
dds/DCPS/security/AccessControl/Governance.h
dds/DCPS/transport/framework/TransportRegistry.cpp
tests/DCPS/UnitTests/GuidGenerator.cpp

Fixed Coverity warnings and renamed GuidConverter::uniqueId

---

dds/DCPS/XTypes/TypeAssignability.cpp
dds/DCPS/XTypes/TypeLookupService.cpp
tests/FACE/Messenger/run_test.pl
tests/FACE/SingleProcessMessenger/run_test.pl

Updated static analysis for allocators to only run once

Use allocator-enabled containers

---

about/dds_overview.html

Link to the global overview page for the 1.2 spec version and updated to formal/19-06-01 which is strangely DDS v1.2

Updated link to the OMG DDS spec

---

_includes/footer.html

www.omgwiki.org/dds redirects to the DDS Foundation

DDS foundation link replaces OMG Wiki link

---

dds/DCPS/DataReaderImpl_T.h

Problem
-------
The observer does not observe samples stored in the BIT readers.
Solution
--------
Extend `store_synthetic_data` to call the observer.

Observer does not observe BITs

---

azure-pipelines.yml
tests/DCPS/Compiler/idl_test1_lib/.gitignore
tests/DCPS/ContainsEntity/.gitignore
tests/DCPS/XTypes/Pub/.gitignore
tests/DCPS/XTypes/Sub/.gitignore

...and fixed a few missing ones

Gitignore: updated Azure Pipelines to tell us when an ignore is missing

---

configure
tools/scripts/show_build_config.pl

- fixed a bug in checking for safety profile (from #2312)
- corrected library paths for vcpkg-installed Qt5
- cleaned up output from show_build_config

configure and show_build_config updates

---

.github/workflows/build_and_test.yml
tools/scripts/gitrelease.pl

- Post Release Steps for Micro Releases
- Improve `--branch` Usage Warnings
- Fix Release Script Issues from 3.16 Release:
- Try to Fix Broken Pipe Error on `git diff`
- Fix Missing Announcement Email Step
- Fix Missing `--branch` Option Error

gitrelease.pl Fixes and Improvements

---

performance-tests/bench/report_parser/ArgumentParser.cpp
performance-tests/bench/report_parser/ArgumentParser.h
performance-tests/bench/report_parser/Enums.h
performance-tests/bench/report_parser/ParseParameters.h
performance-tests/bench/report_parser/ReportParser.cpp
performance-tests/bench/report_parser/ReportParser.h
performance-tests/bench/report_parser/TimeSeriesGnuPlotFormatter.cpp
performance-tests/bench/report_parser/TimeSeriesGnuPlotFormatter.h
performance-tests/bench/report_parser/main.cpp

…parser.
This is just a first step.  The parameters will be used to determine what report values get parsed and output.

Added parse parameters to report_parser

---

dds/DCPS/RTPS/Sedp.cpp
dds/DCPS/security/framework/SecurityConfig.h
dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp

Problem
-------
`get_handle_registry` can be invoked concurrently.
Solution
--------
Add a mutex to serialize access.

Race condition on `get_handle_registry`

---

dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp

Problem
-------
The current code sends heartbeats before the responses to nacks.  This
leads to the following behavior:
1. Writer sends heartbeat.
2. Writer sends data.
3. Reader responds to heartbeat with another nack.
4. Reader receives the data.
5. Writer receives the nack.
6. Writer sends heartbeat.
7. Writer sends data.
8. Reader responds to heartbeat with ack.
Solution
--------
Send the data before the heartbeats to the cycle is:
1. Writer sends data.
2. Writer sends heartbeat.
3. Reader receives the data.
4. Reader responds to heartbeat with ack.

Heartbeat before resent data leads to duplicate sends

---

configure

This was causing GHA problems.

configure: Windows with seperate ACE was trying to use platform_macros

---

dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp
dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.h

Problem
-------
1. Association for a reliable reader may complete for the reception of
the first sample for that reader.  While not technically incorrect,
it seems better for association to complete upon reception of the
first heartbeat.
2. The preassociation heartbeat sent to readers is condition on the
durability of the reader.  This logic duplicates what is already
present.
3. last field of a preassociation heartbeat was fixed at the maximum
sequence number when the reader was added.  Any writes during this
time would advance the sequence number meaning that the reader
would have to get at least two heartbeats to deliver data that it
potentially already has instead of one (assuming the first
heartbeat was lost).
Solution
--------
Apply the simplifications suggested.

Association logic for RTPS readers can be simplified

---

docs/internal/unit_tests.rst

Added a section describing an introduction to GTest as well as the checklist for adding a unit test.

Updating Unit Test Documentation

---

dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp

* dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp:

Fixed warning (Issue #2470)

---

.github/workflows/build_and_test.yml

The initial PR for GHA was unable to add CMake integration in a reasonable amount of time.  This is the PR to add that functionality. The cmake for static and safety builds probably require additional changes but they should be relatively minor and will be included with the PR for those two pieces.

GitHub Actions: CMake CI testing

---

dds/DCPS/DataReaderImpl.cpp
dds/DCPS/DataWriterImpl.cpp
dds/DCPS/DiscoveryBase.h
dds/DCPS/RTPS/Sedp.cpp
dds/DCPS/RTPS/Spdp.cpp
dds/DCPS/ReactorTask.cpp
dds/DCPS/Service_Participant.cpp
dds/DCPS/transport/framework/QueueTaskBase_T.h
dds/DCPS/transport/framework/TransportClient.cpp

- Log when Readers and Writers get a GUID. Also logs the topic type and topic name.
- Fix missing dash before metadata in OpenDDS version logging.
- Make all thread status logging I could find start at 4 to match the update logging point.
- Slap `DCPS_debug_level` on some logging points that were missing them.

Misc. Logging Changes

---

dds/DCPS/QOS_XML_Handler/XML_File_Intf.cpp

QOS_XML_File_Handler::get_profile: check whether we get a profile string

---

.github/workflows/build_and_test.yml
configure

Also has the PR 2502 commit on this branch

GitHub Actions: Wireshark on Windows

---

.github/workflows/build_and_test.yml

(to job ACE_TAO_u18_gcc10_i0w1_xer0)

Github Actions: Add Missing 'wait_cancel_previous' Dependency 

---

dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp

Problem
-------
Assume that two peers are local but also using the RtpsRelay.  A
preassociation acknack can be delivered after a postassociation
acknack.  This may be interpretted as a reset by the writer.  For
normal RTPS writers, this does not present a problem as it sends
another heartbeat and eventually gets the correct ack.
For the volatile writer in security, it presents a problem since the
value used for the heartbeat last is tracked separately.  If the data
has already been acknowledged, then the writer will send an invalid
heartbeat.  The reader will ignore the invalid heartbeat.  The writer
may keep sending the invalid heartbeat.
Solution
--------
Adjust the heartbeat for the volatile writer so that it is correct.

Delayed duplicate acknack leads to invalid heartbeat

---

dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp

Problem
-------
For background, see #2537.  A problem with the initial solution is
that resets may still occur due to the way zero-count acknacks are
handled.
A zero-count acknack is used for preassociation when reflecting
heartbeat counts.  Delivering a duplicate zero-count acknack late
causes a reset.
Solution
--------
Provide special handling for zero-count acknacks.  Specifically, they
need to be processed but they should only be used for completing
association.
This commit also resets the durable data to avoid a memory leak.

Zero-count acknacks may cause reset

---

.github/workflows/build_and_test.yml
.gitignore

Release configuration added for github actions. Due to size of builds, there needed to be removal of tests, which will be added later in another PR>

Github Actions: Release Builds

---

about/links.html

Added new links; replaced several broken links, added some space between paragraphs to space out links and make the page easier to read

Updates to Links Page

---

dds/DCPS/RTPS/Spdp.cpp

Following up on #2594. Also add locks to `thread_status_task`

Further Defer `enable_periodic_tasks`

---

.github/workflows/build_and_test.yml

This PR allows a manual rerun of any workflow which contains the workflow_dispatch line added by this PR. This means future PRs based off this master should be able to manually rerun.
This was tested by adding my to fork's master branch then manually running the CI: https://github.com/ClaytonCalabrese/OpenDDS/actions/runs/772256497

Github Actions: Add Workflow Dispatch for Manual Runs

---

dds/DCPS/transport/framework/NetworkAddress.cpp
dds/DCPS/transport/framework/NetworkAddress.h
dds/DCPS/transport/tcp/TcpConnection.cpp
dds/DCPS/transport/tcp/TcpInst.h
dds/DCPS/transport/tcp/TcpTransport.cpp
dds/DCPS/transport/udp/UdpInst.h
dds/DCPS/transport/udp/UdpTransport.cpp

Specifically, when the resolve order is unpredictable, choose one sensible address.

Attempt to Choose a Single Coherent Address

---

dds/DCPS/DisjointSequence.cpp
dds/DCPS/DisjointSequence.h
tests/DCPS/UnitTests/DisjointSequence.cpp

Problem
-------
Inserting into a DisjointSequence may throw.  Throwing in a
ReactorTask thread effectively kills that thread.
Solution
--------
Use an assert to forcibly terminate the process and potentially
generate a useful core file.

DisjointSequence insert throws

---

tests/cmake/run_ci_tests.pl

Change I wanted to put in #2616

Fix cmake_u18_gcc6_d0w1_cpp03 Workflow

---

.mailmap

Fixed typo

---

.github/workflows/build_and_test.yml

The ace7 gha build was not properly labeled.
One of the w16 builds was incorrectly named.

GitHub Actions: Naming fixes

---

.github/workflows/build_and_test.yml

* .github/workflows/build_and_test.yml:

Upgrade to vcpkg 2021.04.30

---

performance-tests/bench/example/config/scenario/ci_force_worker_assert.json
performance-tests/bench/example/config/scenario/ci_force_worker_deadlock.json
performance-tests/bench/example/config/scenario/ci_force_worker_segfault.json
performance-tests/bench/example/config/worker/ci_force_worker_assert.json
performance-tests/bench/example/config/worker/ci_force_worker_deadlock.json
performance-tests/bench/example/config/worker/ci_force_worker_noop.json
performance-tests/bench/example/config/worker/ci_force_worker_segfault.json
performance-tests/bench/node_controller/main.cpp
performance-tests/bench/run_test.pl
performance-tests/bench/test_controller/ScenarioManager.cpp
performance-tests/bench/worker/main.cpp

Add intentional segfault, assertion, deadlock behavior to worker process and verify that node_controller and test_controller handle failures appropriately on various platforms.

[Bench] Worker "Bad Actor" Tests For Control Plane Debugging

---

examples/DCPS/Messenger_IOGR_Imr/Aggregator.cpp
examples/DCPS/Messenger_IOGR_Imr/Aggregator.h
examples/DCPS/Messenger_IOGR_Imr/DataReaderListener.h
examples/DCPS/Messenger_IOGR_Imr/README
examples/DCPS/Messenger_IOGR_Imr/Writer.h
performance-tests/DCPS/README
performance-tests/DCPS/SimpleLatency/README
performance-tests/DCPS/TCPProfilingTest/README

* examples/DCPS/Messenger_IOGR_Imr/Aggregator.h:
* examples/DCPS/Messenger_IOGR_Imr/DataReaderListener.h:
* examples/DCPS/Messenger_IOGR_Imr/README:
* examples/DCPS/Messenger_IOGR_Imr/Writer.h:
* performance-tests/DCPS/README:
* performance-tests/DCPS/SimpleLatency/README:
* performance-tests/DCPS/TCPProfilingTest/README:

Some typo, layout, and comment changes

---

.github/workflows/build_and_test.yml

* .github/workflows/build_and_test.yml:

GitHub Actions: Upgrade to vcpkg 2021.05.12 release

---

tools/scripts/gitrelease.pl

- Fix DevGuide name being not quite right from #2674.
- Make release files use old version scheme for now.
- Don't use abosulte paths in md5 file.
- Do md5 file after the files it's for.

More Fixes for Release Script

---

tests/auto_run_tests.pl
tests/cmake/ctest-to-auto-run-tests.py

- Display ctest and ctest-to-auto-run-tests.py runs as tests to let
failures from them to be reported as tests and prevent scoreboard from
thinking the last non-cmake test failed. stdout from
ctest-to-auto-run-tests.py is captured and printed separately.
- Make ctest-to-auto-run-tests.py output look more like the real thing.

More CMake Test Changes

---

_posts/2021-06-03-dds-kubernetes-webinar.md

@mitza-oci Added this news post to help promote the webinar
co-promoting OMG/DDS Foundation webinar on DDS + Kubernetes

create news post about OMG event

---

_posts/2021-06-03-opendds-iot-webinar.md

announce July webinar

---

dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp

[RTPS] Improve AddrSet Granularity For Consolidated NACK Responses

---

.github/workflows/build_and_test.yml

Fix Short Job Timeouts, Show Build Config Order, Remove Meaningless Conditionals

[GitHub Actions] Miscellaneous Workflow Cleanup

---

dds/InfoRepo/InfoRepoMulticastResponder.cpp

* dds/InfoRepo/InfoRepoMulticastResponder.cpp:

Logging a ACE_TCHAR should be done using %s

---

dds/DCPS/transport/framework/NetworkAddress.cpp
dds/DCPS/transport/tcp/TcpTransport.cpp

* dds/DCPS/transport/framework/NetworkAddress.cpp:
* dds/DCPS/transport/tcp/TcpTransport.cpp:

Log the IP interfaces we have before trying to select the preferred one

---

dds/DCPS/transport/tcp/TcpConnection.cpp
dds/DCPS/transport/tcp/TcpTransport.cpp

* dds/DCPS/transport/tcp/TcpConnection.cpp:
* dds/DCPS/transport/tcp/TcpTransport.cpp:

Const changes

---

dds/DCPS/transport/framework/NetworkAddress.inl

* dds/DCPS/transport/framework/NetworkAddress.inl:

Add missing process/thread id to log message

---

dds/DCPS/transport/tcp/TcpTransport.cpp

* dds/DCPS/transport/tcp/TcpTransport.cpp:

Removed not used call of addr_to_string

---

.github/workflows/build_and_test.yml
docs/github_actions.md
docs/index.rst
docs/internal/github_actions.rst

This PR adds documentation describing github actions, and giving some usage advice for developers.
It also fixes a naming error I noticed while writing it.

GitHub Actions: documentation

---

dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp

* dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp:

Add missing process/thread id to logging message

---

tests/DCPS/LargeSample/Writer.cpp

* tests/DCPS/LargeSample/Writer.cpp:

Log the error code as string

---

examples/DCPS/DistributedContent/ApplicationLevel.cpp
tests/DCPS/LargeSample/LargeSample.mpc
tests/DCPS/ZeroCopyDataReaderListener/Writer.h

* examples/DCPS/DistributedContent/ApplicationLevel.cpp:
* tests/DCPS/LargeSample/LargeSample.mpc:
* tests/DCPS/ZeroCopyDataReaderListener/Writer.h:

Removed redundant white lines

---

tests/DCPS/Thrasher/Publisher.cpp
tests/DCPS/Thrasher/Subscriber.cpp
tests/DCPS/Thrasher/Thrasher.cpp

added pointer checks for pub/sub

Thrasher test bug fix

---

tests/DCPS/SampleLost/DataReaderListener.cpp
tests/DCPS/SampleLost/DataReaderListener.h
tests/DCPS/SampleLost/subscriber.cpp

SampleLost test: induce a sample lost event

---

DevGuideExamples/DCPS/Messenger/DataReaderListenerImpl.cpp
DevGuideExamples/DCPS/Messenger/Publisher.cpp
DevGuideExamples/DCPS/Messenger/run_test.pl

…e log to more easily match publisher/subscriber and see how long any operation takes
* DevGuideExamples/DCPS/Messenger/run_test.pl:

Updated DevGuideExamples Messenger logging settings

---

dds/DCPS/DataReaderImpl.cpp
dds/DCPS/RTPS/Sedp.cpp
dds/DCPS/RTPS/Spdp.cpp

* dds/DCPS/DataReaderImpl.cpp:
* dds/DCPS/RTPS/Sedp.cpp:
* dds/DCPS/RTPS/Spdp.cpp:

Fixed various operation names as part of the logging messages

---

dds/DCPS/RTPS/Sedp.cpp

Correct operation name logging in Sedp::write_publication_data_unsecure

---

dds/DCPS/DiscoveryBase.h

EndpointManager logging fixes

---

dds/DCPS/RTPS/Spdp.cpp

Fixed logging of operation name Spdp::SpdpTransport::write_i

---

tests/DCPS/Monitor/monitor.cpp
tests/DCPS/Ownership/DataReaderListener.cpp
tests/DCPS/Ownership/Writer.cpp
tests/DCPS/Serializer_wstring/DataReaderListener.cpp
tests/DCPS/XTypes/XTypes.h

* tests/DCPS/Monitor/monitor.cpp:
* tests/DCPS/Ownership/DataReaderListener.cpp:
* tests/DCPS/Ownership/Writer.cpp:
* tests/DCPS/Serializer_wstring/DataReaderListener.cpp:
* tests/DCPS/XTypes/XTypes.h:

Use %C for logging char*

---

performance-tests/bench/common/PropertyStatBlock.cpp

Fix Windows Vector Access Issues For Stats Consolidation

---

dds/DCPS/LogAddr.cpp

Use to_dds_string to replace snprintf.

LogAddr fix

---

dds/DCPS/transport/rtps_udp/RtpsUdpInst.cpp

* dds/DCPS/transport/rtps_udp/RtpsUdpInst.cpp:

Dump the responsive_mode value into the string

---

about/links.html

@mitza-oci Just adding the recent webinar to the list.

add link to July 2021 webinar video

---

dds/DCPS/QOS_XML_Handler/XML_String_Intf.h

* dds/DCPS/QOS_XML_Handler/XML_String_Intf.h:

XML::Environment_Resolver is a struct

---

performance-tests/bench/dashboard_summarizer/.gitignore
performance-tests/bench/dashboard_summarizer/Bench_dashboard_summarizer.mpc
performance-tests/bench/dashboard_summarizer/main.cpp
performance-tests/bench/install_bench.pl
performance-tests/bench/node_controller/Bench_node_controller.mpc
performance-tests/bench/report_parser/Bench_report_parser.mpc
performance-tests/bench/test_controller/Bench_test_controller.mpc
performance-tests/bench/test_controller/unit_tests/unit_tests.mpc

This will allow dashboard test scraping to run much more quickly

[Bench] Adding dashboard_summarizer tool for generating test run summaries across scenarios

---

dds/DCPS/Serializer.cpp
dds/DCPS/Serializer.h
dds/DCPS/Serializer.inl

- doxygen comments
- style guidelines
- simplification

Serializer cleanup

---

dds/DCPS/Service_Participant.cpp

Remove white space from log message

---

tools/rtpsrelay/RelayHandler.cpp
tools/rtpsrelay/RelayHandler.h

Problem
-------
RtpsRelay deadlocks.  Lock order is incorrect in SpdpHandler::handle_exception.
Solution
--------
1. Fix lock order in SpdpHandler::handle_exception.
2. Add a proxy argument to SpdpHandler::purge to re-enforce lock order.

RtpsRelay deadlocks

---

_posts/2021-08-12-countdown-to-fall-intro-class.md

@mitza-oci
Reminder news post about the Intro class

Fall intro class reminder post

---

dds/DCPS/transport/framework/TransportSendStrategy.cpp

* dds/DCPS/transport/framework/TransportSendStrategy.cpp:

Changed ACE_ERROR into a VDBG to not get this message on the console

---

dds/DCPS/security/AccessControl/Governance.cpp
dds/DCPS/security/AccessControl/Permissions.cpp
dds/DCPS/security/AccessControl/XmlUtils.cpp
dds/DCPS/security/AccessControl/XmlUtils.h
tests/unit-tests/dds/DCPS/security/AccessControl/XmlUtils.cpp

Fix XML-related Compile Issues

---

dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp

Follow-on from post-merge review of #2911

Allow fallback for unanswered heartbeats (part 2)

---

dds/DCPS/ConfigUtils.h
dds/DCPS/DataReaderImpl.cpp
dds/DCPS/FilterEvaluator.cpp
dds/DCPS/GuidConverter.cpp
dds/DCPS/SafetyProfileStreams.h
tests/DCPS/Compiler/xcdr/xcdr.cpp
tests/DCPS/EntityLifecycleStress/publisher.cpp
tests/DCPS/EntityLifecycleStress/subscriber.cpp
tests/DCPS/QoS_XML/dumpXMLString/qos_dumpXMLString.cpp
tests/unit-tests/dds/DCPS/security/SSL/SignedDocument.cpp
tools/dissector/sample_dissector.h

Fix Includes in SafetyProfileStreams.h

---

dds/DCPS/RTPS/Sedp.cpp

- Removed an unused variable and a duplicate include
- Normalized includes
- Did some cleanup around the unused variable

Minor Cleanup in `Sedp.cpp`

---

dds/DCPS/DataSampleHeader.h
dds/DCPS/transport/framework/TransportClient.cpp
dds/DCPS/transport/framework/TransportClient.h
dds/DCPS/transport/framework/TransportCustomizedElement.h
dds/DCPS/transport/framework/TransportCustomizedElement.inl
dds/DCPS/transport/framework/TransportQueueElement.h
dds/DCPS/transport/framework/TransportSendBuffer.cpp
dds/DCPS/transport/framework/TransportSendBuffer.h
dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp
dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.h
dds/DCPS/transport/rtps_udp/RtpsUdpReceiveStrategy.cpp

Reverts 2914, implements the same idea more cleaning on the writer side with initial directed heartbeats.

A better approach for preventing old data for RTPS non-durable readers

---

.github/workflows/build_and_test.yml

should start passing when DOC_Group/ACE_TAO #1665 is merged

GitHub Actions: asan options no longer needed

---

dds/DCPS/QOS_XML_Handler/QOS_Common.h
dds/DCPS/QOS_XML_Handler/QOS_DataReader_T.cpp
dds/DCPS/QOS_XML_Handler/QOS_DataReader_T.h
dds/DCPS/QOS_XML_Handler/QOS_DataWriter_T.cpp
dds/DCPS/QOS_XML_Handler/QOS_DataWriter_T.h
dds/DCPS/QOS_XML_Handler/QOS_DwDrTp_Base_T.cpp
dds/DCPS/QOS_XML_Handler/QOS_DwDrTp_Base_T.h
dds/DCPS/QOS_XML_Handler/QOS_DwTp_Base_T.cpp
dds/DCPS/QOS_XML_Handler/QOS_DwTp_Base_T.h
dds/DCPS/QOS_XML_Handler/QOS_PubSub_T.cpp
dds/DCPS/QOS_XML_Handler/QOS_PubSub_T.h
dds/DCPS/QOS_XML_Handler/QOS_Topic_T.cpp
dds/DCPS/QOS_XML_Handler/QOS_Topic_T.h
dds/DCPS/QOS_XML_Handler/QOS_XML_Loader.cpp
dds/DCPS/QOS_XML_Handler/QOS_XML_Loader.h
dds/DCPS/QOS_XML_Handler/TopicQos_Handler.h
dds/DCPS/QOS_XML_Handler/XML_File_Intf.cpp
dds/DCPS/QOS_XML_Handler/XML_File_Intf.h
dds/DCPS/QOS_XML_Handler/XML_Intf.cpp
dds/DCPS/QOS_XML_Handler/XML_Intf.h
dds/DCPS/QOS_XML_Handler/XML_String_Intf.cpp
dds/DCPS/QOS_XML_Handler/XML_String_Intf.h

* dds/DCPS/QOS_XML_Handler/QOS_XML_Loader.cpp:
* dds/DCPS/QOS_XML_Handler/QOS_XML_Loader.h:
* dds/DCPS/QOS_XML_Handler/XML_File_Intf.cpp:
* dds/DCPS/QOS_XML_Handler/XML_File_Intf.h:

Remove redundant void, add const

---

performance-tests/bench/common/PropertyStatBlock.cpp
performance-tests/bench/test_controller/main.cpp

Should improve consolidation performance for larger scenarios, and be especially helpful for ASAN builds.

[Bench] Update test_controller to use faster (vector) consolidate method for untagged stats

---

.github/workflows/workflow.yml
documents/building.html
index.html

Using an empty commit to force the website to update.

3.16.1 Website Update

---

dds/DCPS/DataReaderImpl.h
dds/DCPS/DataReaderImpl_T.h
dds/DCPS/DataWriterImpl.h
dds/DCPS/DataWriterImpl_T.h
dds/DCPS/DomainParticipantFactoryImpl.h
dds/DCPS/DomainParticipantImpl.h
dds/DCPS/PublisherImpl.h
dds/DCPS/TopicDescriptionImpl.h
dds/DCPS/TopicImpl.h
dds/idl/IDLTemplate.txt

* dds/DCPS/DataReaderImpl.h:
* dds/DCPS/DataReaderImpl_T.h:
* dds/DCPS/DataWriterImpl.h:
* dds/DCPS/DataWriterImpl_T.h:
* dds/DCPS/DomainParticipantFactoryImpl.h:
* dds/DCPS/DomainParticipantImpl.h:
* dds/DCPS/PublisherImpl.h:
* dds/DCPS/TopicDescriptionImpl.h:
* dds/DCPS/TopicImpl.h:
* dds/idl/IDLTemplate.txt:

Update OMG specification to formal/2015-04-10

---

dds/DCPS/RTPS/Spdp.cpp

Make error logs dependent on DCPS::DCPS_debug_level

---

dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp

Problem
-------
The RtpsUdpDataLink will not schedule a response when a stale nack is
received.  However, the desired response is recorded.  Another reader
that sends a valid nack will cause a response to the stale nack.
Solution
--------
Don't process the nack or the final flag if stale.

RtpsUdpDataLink responds to stale nacks

---

.github/workflows/build_and_test.yml
dds/DCPS/DataReaderImpl.cpp
dds/DCPS/DataReaderImpl.h
dds/DCPS/DataWriterImpl.cpp
dds/DCPS/DataWriterImpl.h
dds/DCPS/DiscoveryBase.h
dds/DCPS/EntityImpl.cpp
dds/DCPS/EntityImpl.h
dds/DCPS/RTPS/Sedp.cpp
dds/DCPS/RTPS/Spdp.cpp
dds/DCPS/WriteDataContainer.h
dds/DCPS/transport/framework/DataLink.cpp
dds/DCPS/transport/framework/DataLinkSet.cpp
dds/DCPS/transport/framework/DataLinkSet.inl
dds/DCPS/transport/framework/TransportImpl.cpp
dds/DCPS/transport/framework/TransportImpl.h
dds/DCPS/transport/framework/TransportSendStrategy.cpp
dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp
dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.h
dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.inl
dds/DCPS/transport/rtps_udp/RtpsUdpSendStrategy.cpp
dds/DCPS/transport/rtps_udp/RtpsUdpSendStrategy.h
dds/DCPS/transport/rtps_udp/RtpsUdpTransport.cpp
dds/DCPS/transport/tcp/TcpTransport.cpp
dds/InfoRepo/DCPSInfoRepoServ.cpp
dds/InfoRepo/DCPSInfoRepoServ.h
tests/DCPS/EntityLifecycleStress/rtps_disc_tcp.ini
tests/DCPS/EntityLifecycleStress/run_test.pl
tests/dcps_tests.lst
tests/tsan_tests.lst

Add a Thread Sanitizer builds and a few initial tests. Get the tests to pass in Thread Sanitizer.

Add TSAN workflow / tests

---

tools/scripts/gitrelease.pl

- Significant additions:
- Create or read a `info.json` file in the release workspace to persist values across runs or make sure arguments are consistent.
- Add a `--mock` option to make mock releases easier by doing some extra checks and faking the Doxygen and Devguide steps.
- Fixes for issues encountered during the previous releases:
- Try to fix issues with out-of-order releases like 3.16.1 by having the script know if the release is the highest versioned one so it doesn't update the latest-release branch and replace the latest release on the FTP server. Store this in `info.json` so it ideally only has to be checked once per release.
- Fix issue with setting and verifying the "release occurred" flag by storing it as a value in `info.json`.
- Remove an unhelpful override of a check …

Fix Release Script Issues from the 3.18.0 and 3.16.1 Releases

---

dds/DCPS/MultiTopicDataReaderBase.cpp
dds/DCPS/MultiTopicDataReaderBase.h
dds/DCPS/MultiTopicDataReader_T.cpp

Ensure the query plan for the desired topic is fully initialized upon receiving data related to it.

Fix for occasional timeout in MultiTopic test.

---

dds/idl/IDLTemplate.txt

Removed old workaround for TAO 2.0

---

_posts/2021-09-14-fall-opendds-security-workshoop.md

@mitza-oci Just adding an announcement for the upcoming class.

news post announcing Security class

---

foundation/minutes/2019-09-13.html

@mitza-oci Here are the meeting minutes for the 9/13 meeting; you might need to check the meta data at the top; I guessed on the order (I just added one to the last one).

Add 9/13 Meeting Minutes

---

tests/DCPS/UnitTests/DynamicData/DynamicData.cpp
tests/DCPS/UnitTests/DynamicData/DynamicData.idl

This PR adds the final extensibility cases tothe DynamicData unit test.

XTypes Dynamic: DynamicData Final Extensibility Unit Test

---

.github/workflows/build_and_test.yml
MPC/config/opendds_testing_features.mpb
dds/DCPS/RTPS/Sedp.cpp
dds/DCPS/RTPS/Sedp.h
dds/DCPS/RTPS/Spdp.cpp
dds/DCPS/transport/framework/TransportInst.cpp
dds/DCPS/transport/framework/TransportInst.h
dds/DCPS/transport/framework/TransportInst.inl
dds/DCPS/transport/rtps_udp/OpenDDS_Rtps_Udp.mpc
dds/DCPS/transport/rtps_udp/RtpsUdpSendStrategy.cpp
dds/DCPS/transport/rtps_udp/RtpsUdpTransport.cpp
dds/DdsDcps.mpc

Problem
-------
The OpenDDS user community is interested in running OpenDDS with RTPS
in lossy networks, e.g., mobile data networks.  Testing directly on
these networks or using a physical or virtual device to condition the
network is not always practical.
Solution
--------
Provide configuration options that cause messages to probabilistically
be dropped.

Users want to simulate lossy networks

---

dds/DCPS/security/OpenSSL_legacy.h
dds/DCPS/security/SSL/DiffieHellman.cpp

Replaces PR 3139, due to peculiar rebase result.

Initial support for OpenSSL 3

---

about/links.html

I also put the videos in order or publication.

Add Bench webinar to list

---

performance-tests/bench/builder/ListenerFactory.cpp
performance-tests/bench/builder/ListenerFactory.h
performance-tests/bench/node_controller/ProcessStatsCollector.cpp
performance-tests/bench/node_controller/main.cpp
performance-tests/bench/report_parser/ArgumentParser.cpp
performance-tests/bench/report_parser/main.cpp
performance-tests/bench/tcp_latency/tcp_latency.cpp
performance-tests/bench/test_controller/AllocationHelper.h
performance-tests/bench/test_controller/main.cpp
performance-tests/bench/udp_latency/udp_latency.cpp
performance-tests/bench/worker/ForwardAction.cpp
performance-tests/bench/worker/ReadAction.cpp
performance-tests/bench/worker/SetCftParametersAction.cpp
performance-tests/bench/worker/Utils.cpp
performance-tests/bench/worker/WriteAction.cpp
performance-tests/bench/worker/main.cpp

Problem: Recent Coverity scans were complaining about a number of issues in Bench, particularly uncaught exceptions and a few resource locking / cleanup issues.
Solution: These changes should resolve a large number of the issues

[Bench] Coverity Fixes

---

dds/DCPS/transport/framework/TransportInst.inl

Initialize TransportInst::count_messages_

---

dds/DCPS/RTPS/Sedp.cpp
dds/DCPS/RecorderImpl.cpp
dds/DCPS/RecorderImpl.h

There was a race between the populating of the dt_map_ and the checking of the map.

XTypes Dynamic: Fix dt_map_ race

---

dds/DCPS/RTPS/Spdp.cpp
dds/DCPS/ReactorTask.cpp
dds/DCPS/ReactorTask.h
dds/DCPS/ThreadMonitor.cpp
dds/DCPS/ThreadMonitor.h
dds/OpenddsDcpsExt.idl
java/tests/internal_thread_status/InternalThreadListener.java
tests/DCPS/InternalThreadStatus/InternalThreadStatusListenerImpl.cpp
tests/DCPS/RtpsRelay/Smoke/run_test.pl
tools/rtpsrelay/Config.h
tools/rtpsrelay/RelayThreadMonitor.cpp
tools/rtpsrelay/RelayThreadMonitor.h
tools/rtpsrelay/RtpsRelay.cpp

Add thread utilization percentage as a part of the builtin topic data for internal threads

thread utilization BIT data

---

tests/DCPS/BuiltInTopicTest/monitor.cpp
tests/DCPS/BuiltInTopicTest/prst_repo_run_test.pl

- Don't busy wait.
- Coordinate test script with termination of monitor1

Improvements to BuiltinTopicTest

---

tests/DCPS/QueryCondition/QueryConditionTest.cpp

Problem
-------
The listener in the QueryCondition test uses a read condition.  The
shutdown sequence in the test is:
1. `set_listener`
2. `delete_readcondition`
Currently, OpenDDS may retain a reference to and invoke the listener
after the call to `set_listener`.  In the problematic sequence, the
listener is being invoked after the call to `delete_readcondition`
which causes the error.
Solution
--------
Add logic to disable the listener before it is unset.

QueryCondition test has race condition on listener

---

foundation/minutes/2021-12-13.html

@mitza-oci I think I messed this up last quarter; here's hoping I got this one right!

December TAB Meeting Minutes

---

.github/workflows/build_and_test.yml
.github/workflows/build_u14_gcc4.Dockerfile
configure

Use the "problem matcher"
Build OpenDDS tests

Updated GCC 4.4 build in GitHub Actions

---

_posts/2022-01-20-q1-opendds-training-schedule.md

Q1 Training Announcement

---

docs/internal/github_actions.rst
docs/internal/running_tests.rst

https://github.com/objectcomputing/OpenDDS/pull/3278

Updated GHA and `auto_run_tests.pl` Sphinx Docs for #3278

---

dds/DCPS/RTPS/Spdp.cpp

It is expected that some ports may be taken and we need to keep trying

Spdp: "Trying next participantId" is not a warning

---

tests/auto_run_tests.pl
tests/cmake/ctest-to-auto-run-tests.py
tools/scripts/modules/tests/command_utils.pl

Also fix typo in `run_command` test

Seperate CMake Test Results from Processing Step

---

tests/cmake/Messenger/CMakeLists.txt
tests/cmake/Messenger/Messenger_Space/CMakeLists.txt

This will currently fail until another PR gets merged into ACE_TAO.

CMake Test: Processing IDL with Space In Path

---

about/articles/mnb.markdown

@mitza-oci @jrw972 Added two MNB articles to the list.

add recent MNB articles

---

2022-02-22-q2-opendds-training-schedule.md

Q2 Training Schedule Announcement

---

foundation/sponsor-list.html

add new community sponsor name to the list

---

dds/DCPS/NetworkAddress.cpp

Problem: Not using std::mem(cmp/cpy/set).
Solution: Use std::mem(cmp/cpy/set).

Make NetworkAddress Use FACE-Compliant APIs

---

dds/DCPS/Cached_Allocator_With_Overflow_T.h
dds/DCPS/DataSampleHeader.h
dds/DCPS/Definitions.h
dds/DCPS/Dynamic_Cached_Allocator_With_Overflow_T.h
dds/DCPS/InfoRepoDiscovery/DataReaderRemoteImpl.cpp
dds/DCPS/InfoRepoDiscovery/DataWriterRemoteImpl.cpp
dds/DCPS/NetworkConfigModifier.cpp
dds/DCPS/OpenDDS_Util.mpc
dds/DCPS/RcObject.h
dds/DCPS/Serializer.cpp
dds/DCPS/Serializer.inl
dds/DCPS/Util.h
dds/DCPS/XTypes/TypeLookupService.cpp
dds/DCPS/XTypes/TypeObject.cpp
dds/DCPS/debug.cpp
dds/DCPS/debug.h
dds/DCPS/security/AccessControl/Governance.cpp
dds/DCPS/security/framework/HandleRegistry.cpp
dds/DCPS/security/framework/SecurityConfig.h
dds/DCPS/transport/framework/TransportQueueElement.h
tests/DCPS/HelloWorld/subscriber.cpp
tests/FACE/MultiDomainMessenger/Subscriber/Subscriber.cpp
tests/FACE/SingleProcessMessenger/SingleProcess/SingleProcess.cpp

- reduce indirect inclusion of needed headers
- remove allocators from Definitions.h

Refactor some #includes and OpenDDS_Util.mpc

---

dds/DCPS/security/SSL/Certificate.cpp
dds/DCPS/security/SSL/DiffieHellman.cpp
dds/DCPS/security/SSL/PrivateKey.cpp
docs/dependencies.md

still working on DH and EC secret sharing functions.

OpenSSL 3 integration to avoid deprecated function calls.

---

dds/DCPS/ReceivedDataElementList.cpp
dds/DCPS/SubscriberImpl.cpp
tests/DCPS/GroupPresentation/DataReaderListener.cpp
tests/DCPS/GroupPresentation/DataReaderListener.h
tests/DCPS/GroupPresentation/GroupPresentation.mpc
tests/DCPS/GroupPresentation/SubscriberListener.cpp
tests/DCPS/GroupPresentation/SubscriberListener.h
tests/DCPS/GroupPresentation/Writer.cpp
tests/DCPS/GroupPresentation/Writer.h
tests/DCPS/GroupPresentation/publisher.cpp
tests/DCPS/GroupPresentation/run_test.pl
tests/DCPS/GroupPresentation/subscriber.cpp
tests/tsan_tests.lst

Various Other Fixes:
- Update GroupPresentation run script to use "setup_discovery"
- Update assert checks in ReceivedDataElementList to avoid unintentional SEGV during (already failed) checks
- Fix potential lock order issue in begin/end access in SubscriberImpl

Add GroupPresentation Test To TSAN CI Job

---

dds/DCPS/transport/multicast/MulticastInst.cpp
dds/DCPS/transport/shmem/ShmemInst.cpp
dds/DCPS/transport/tcp/TcpInst.cpp
dds/DCPS/transport/udp/UdpInst.cpp

* dds/DCPS/transport/shmem/ShmemInst.cpp:

Dump pool and hostname in ShmemInst::dump_to_str

---

tests/DCPS/MockedTypeSupport/MockedTypeSupport.cpp

Mostly formatting and logging changes to MockedTypeSupport.cpp.

Minor changes to MockedTypeSupport test

---

about/articles/mnb.markdown

@mitza-oci , just added a link to the new MNB article.

add DynamicData MNB article to list

---

_posts/2022-03-14-town-hall-announcement.md

Town Hall announcement for News page

---

docs/internal/github_actions.rst
tests/dcps_tests.lst

Some of our CI documentation was out of date due to a number of recent changes.

Test Unblocking and CI Documentation

---

dds/DCPS/Service_Participant.cpp

Directly assign result of call to variable

---

.github/workflows/build_and_test.yml

Try out 3.0.0 versions of `upload-artifact` and `download-artifact`

Bump Artifact Actions Versions to 3.0.0

---

dds/DCPS/Service_Participant.cpp

Make variable in parse_domain_range const

---

dds/DCPS/RTPS/Spdp.cpp

Accidental Check-In From #3435

Remove Unnecessary SPDP Debug Message

---

bin/PerlDDS/Process.pm
bin/PerlDDS/Run_Test.pm
tests/DCPS/DynamicTypes/run_test.pl

Revert "Return signal number in PerlDDS"

---

_posts/2022-04-06-new-case-study.md

News post announcing DRS Land System case study

---

.github/workflows/build_and_test.yml

for openssl and xerces-c packages

GitHub Actions: use a newer vcpkg commit

---

docs/conf.py
docs/internal/dev_guidelines.rst
docs/internal/unit_tests.rst

Also correct some links that are being redirected.

Ignore 403 Links in Sphinx

---

.github/workflows/build_and_test.yml
tests/cmake/Messenger/Messenger_2/CMakeLists.txt
tests/cmake/Messenger/Messenger_Space/CMakeLists.txt
tests/cmake/generated_global/cpp/CMakeLists.txt

The recent messenger test change I made broke the scoreboard for make install. This PR adds in fixes for that. It also expands the coverage of the make install part of CI to match that of the scoreboard.

GitHub Actions: Fix Make Install and Improve Coverage

---

dds/DCPS/WriteDataContainer.cpp

Problem: Coverity 1517517 complains about passing freed pointer (stale) into member function. The function checks for zero'd pointer values in order to take action, which can happen for other calls to this function.
Solution: Zero the pointer after free in case execution reaches this member function.

Fix WriteDataContainer Coverity Issue And Minor Cleanup

---

_posts/2022-05-04-q3-training-schedule.md

announce Q3 training classes

---

about/links.html

add Town Hall Meeting to videos links

---

dds/InfoRepo/FederatorManagerImpl_updates.cpp
tests/DCPS/Federation/DataReaderListener.cpp

- value-initialization for samples in the "update" methods to avoid parse errors
- minor correctness fix and style updates for Federation test's DataReaderListener

Fixes For Federation Test

---

_posts/2022-06-03-opendds-contributor-webinar.md

announce Q2 webinar

---

about/articles/mnb.markdown

added Bridging OpenDDS and MQTT Messaging to the top of the list
@mitza-oci

add June MNB article

---

tests/stress-tests/dds/DCPS/TimingChecker.cpp

Problem: Even a broken clock is right twice a day.  Sometimes the timing checks will accidentally pass on slow machines.
Solution: Run them multiple times, only accept if they pass every time.

Run TimingChecker Multiple Times For Stress Tests

---

foundation/minutes/2022-03-07.html

add TAB minutes from 3-7-22 meeting

---

about/links.html

Add OpenDDS Code Contributor webinar to video list

---

.github/workflows/build_and_test.yml

to generate stack traces from Perl scripts
set ptrace_scope to 0 on linux builds

GitHub Actions: enable debugger attach

---

dds/DCPS/DispatchService.cpp
tests/unit-tests/dds/DCPS/DispatchService.cpp
tests/unit-tests/dds/DCPS/EventDispatcher.cpp
tests/unit-tests/dds/DCPS/NetworkResource.cpp
tests/unit-tests/dds/DCPS/PeriodicEvent.cpp
tests/unit-tests/dds/DCPS/ServiceEventDispatcher.cpp
tests/unit-tests/dds/DCPS/SporadicEvent.cpp

Improve LCOV report numbers for EventDispatcher / EventBase, ServiceEventDispatcher, DispatchService, SporadicEvent

EventDispatcher Unit Test Coverage Improvements

---

tools/scripts/unit_test_coverage.sh

Problem
-------
The coverage script executes `rm` in a way that it will not have an
argument.
Solution
--------
Check the input to `rm`.

Coverage script executes rm without an argument

---

.github/workflows/build_and_test.yml
docs/internal/github_actions.rst

GitHub Actions: test with dds_suppress_anys=0

---

tests/DCPS/DataRepresentation/DataRepresentation.cpp

Follow-On from #3632. Fix DataRepresentation test as well.

Detach Conditions In DataRepresentation Test

---

_posts/2022-08-02-q4-opendds-classes-scheduled.md

announce October class schedule

---

.github/workflows/build_and_test.yml
dds/DdsDcps.mpc

Follow-up to #3557:
* Make the CI check for this configuration actually use it
* Fix use of tao_idl to be compatible with generated Any inserters/extractors

Fixed dds_suppress_anys=0

---

dds/DCPS/XTypes/DynamicDataImpl.cpp
tests/DCPS/RtpsRelay/Smoke/metachecker.cpp
tests/security/CheckInstance/CheckInstance.cpp
tools/rtpsrelay/RelayHttpMetaDiscovery.cpp

* CID 1519356
* CID 1519355
* CID 1519354
* CID 1519352
* CID 1519351
* CID 1519350
* CID 1519369
* CID 1519367
* CID 1519365
* CID 1519364
* CID 1519362
* CID 1519361
* CID 1519359

Coverity fixes

---

performance-tests/bench/test_controller/ScenarioManager.cpp
tests/unit-tests/dds/DCPS/JsonValueReader.cpp
tests/unit-tests/dds/DCPS/security/AccessControlBuiltInImpl.cpp

Problem: Warnings
Solution: Less Warnings

Windows Tests Warning Cleanup

---

dds/DCPS/DomainParticipantImpl.cpp
dds/DCPS/OpenDDS_Util.mpc

Update for OpenDDS_Util to build OpenDDS as a layer in VxWorks.
Also, minor correction to error messages in dds/DCPS/DomainParticipantImpl.cpp

VxWorks Cross Compilation

---

dds/DCPS/BuiltInTopicUtils.h

Check to make sure the we got the bit reader, as suggested here: https://github.com/objectcomputing/OpenDDS/discussions/3731.
Also fixed some other minor issues with the function:
- Added check for the bit subscriber.
- Fixed a return that was unreachable.
- Fixed function names in logging.
- Added more logging info and brought in line with the guidelines.

Add Checks to `instance_handle_to_bit_data`

---

bin/PerlDDS/ProcessFactory.pm
bin/PerlDDS/Run_Test.pm
dds/DCPS/BuiltInTopicUtils.cpp
dds/DCPS/Logging.cpp
dds/DCPS/Logging.h
dds/DCPS/RTPS/Spdp.cpp
dds/DCPS/RTPS/Spdp.h
dds/DCPS/Service_Participant.cpp
java/tests/participant_location/rtps_no_ice.ini
java/tests/participant_location/run_test.pl

Problem
-------
The Java ParticipantLocationTest sporadically fails in CI; both in GitHub Actions and the scoreboard.  The root causes is not obvious from the test logging.
Solution
--------
* Update the test framework for Java processes.
* Add logging for BIT activities.

Java ParticpantLocationTest sporadically fails

---

dds/DCPS/DataReaderImpl_T.h

* dds/DCPS/DataReaderImpl_T.h:

Make local variable const

---

dds/idl/marshal_generator.cpp

* dds/idl/marshal_generator.cpp:

Removed redundant whitespaces

---

dds/idl/marshal_generator.cpp
dds/idl/metaclass_generator.cpp

* dds/idl/marshal_generator.cpp:
* dds/idl/metaclass_generator.cpp:

Removed redundant whitespace generated and make index variable const

---

dds/idl/marshal_generator.cpp

* dds/idl/marshal_generator.cpp:

Fixed indentation issue in genereated operator<<

---

dds/DCPS/QOS_XML_Handler/QOS_Common.cpp
dds/DCPS/QOS_XML_Handler/QOS_Common.h
dds/DCPS/QOS_XML_Handler/QOS_DataReader_T.cpp
dds/DCPS/QOS_XML_Handler/QOS_DwDrTp_Base_T.cpp
dds/DCPS/QOS_XML_Handler/QOS_DwTp_Base_T.cpp
dds/DCPS/QOS_XML_Handler/README.md
dds/DCPS/QOS_XML_Handler/dds_qos.cpp
dds/DCPS/QOS_XML_Handler/dds_qos.hpp
docs/schema/dds_qos.xsd
tests/DCPS/QoS_XML/dump/qos.xml
tests/DCPS/QoS_XML/dump/qos_dump.cpp

Add support for setting DataRepresentationQosPolicy and TypeConsistencyEnforcementQosPolicy through XML

---

java/jms/src/org/opendds/jms/MessageConsumerImpl.java

Fixed Java syntax error in MessageConsumerImpl.java

---

performance-tests/bench/worker/Bench_Worker.mpc
performance-tests/bench/worker/main.cpp

Add includes & linking for InfoRepoDiscovery and Shmem transport to Bench worker for static builds.

[Bench] Add InfoRepoDiscovery and Shmem transport static includes to worker

---

dds/DCPS/transport/rtps_udp/RtpsUdpReceiveStrategy.cpp

Problem: This pathway is common and expected and not indicative of an error condition, so it shouldn't be a warning message.
Solution: Downgrade to "info".:

Reduce RtpsUdpReceiveStrategy Warning to Info

---

tests/tsan_tests.lst

Add `tests/DCPS/*Condition` tests to TSAN coverage.

Add Condition Tests To TSAN Coverage

---

dds/DCPS/transport/tcp/TcpDataLink.cpp

Fix a potential null_ptr dereference flagged by Coverity. Check for valid transport RCH inside "released" branch always needs to return a value (and not continue on to the rest of the function). Also cleaned up some raw pointers and "this->" cruft.

Fix Coverity Issue In TcpDataLink::reconnect

---

dds/DCPS/RcObject.h

Problem: The SharedTransport test has an intermittent crash (see [here](https://github.com/objectcomputing/OpenDDS/actions/runs/3725002360/jobs/6318021505#step:16:15)) that appears to be related a race condition on the WeakRcObject reference counts. TSAN does not report an issue because the count is atomic, but this is insufficient. Ironically, the easiest way to reproduce this issue was running the SharedTransport with TSAN reporting enabled (which would then miss the problem but cause a crash).
Solution: The count must be atomically correlated with the expired_ flag, meaning full use of the mutex is required for all changes to the count. As a result, the count no longer needs to be "atomic" since it will be protected by the mutex.

WeakRcObject Concurrency Fixes

---

README.md

Updated ACE/TAO versions as used by the configure script

---

dds/DCPS/XTypes/DynamicDataReaderImpl.cpp
dds/DCPS/XTypes/DynamicDataReaderImpl.h
dds/DCPS/XTypes/DynamicDataWriterImpl.h
dds/DCPS/XTypes/DynamicSample.cpp
dds/DCPS/XTypes/DynamicSample.h
dds/DCPS/XTypes/DynamicTypeSupport.cpp
dds/DCPS/XTypes/DynamicTypeSupport.h

Moved DynamicSample and the dynamic DW and DR to their own files.

Refactored the DynamicTypeSupport header and source files

---

dds/DCPS/RTPS/AssociationRecord.h
dds/DCPS/RTPS/Sedp.h
tests/unit-tests/dds/DCPS/RTPS/AssociationRecord.cpp

Problem
-------
The AssociationRecord classes in Sedp.h don't have unit tests.
Solution
--------
Factor out the AssociationRecord classes and add unit tests.

AssociationRecord lacks unit tests

---

dds/DCPS/RTPS/DiscoveredEntities.h
dds/DCPS/RTPS/Sedp.h
dds/DCPS/Time_Helper.h
dds/DCPS/Time_Helper.inl
tests/unit-tests/dds/DCPS/RTPS/DiscoveredEntities.cpp
tests/unit-tests/dds/DCPS/Time_Helper.cpp

Factor out DiscoveredParticipant, DiscoveredPublication, DiscoveredSubscription
Problem
-------
Sedp.h is too big.
Solution
--------
Make Sedp.h smaller by factoring out data structures.

Factor out DiscoveredParticipant, DiscoveredPublication, DiscoveredSubscription

---

dds/DCPS/RTPS/DiscoveredEntities.h
dds/DCPS/RTPS/Sedp.cpp
dds/DCPS/RTPS/Sedp.h
dds/DCPS/RTPS/Spdp.cpp
tests/unit-tests/dds/DCPS/RTPS/DiscoveredEntities.cpp

Remove GuidPrefixWrapper
Finishing TODO

Remove GuidPrefixWrapper

---

tools/modeling/tests/MessengerMC/fs_signal.cpp

Follow up to https://github.com/OpenDDS/OpenDDS/pull/4003

Compile Fix for MessengerMC Modeling Test

---

dds/DCPS/Serializer.cpp
tests/unit-tests/dds/DCPS/Serializer.cpp

Serializer: detect certain kinds of invalid CDR strings

---

tests/DCPS/LargeSample/run_test.pl
tests/DCPS/ManyToMany/run_test.pl
tests/DCPS/Messenger/run_test.pl

The things these comments reference were removed in https://github.com/OpenDDS/OpenDDS/pull/3711

Remove Leftover Redmine Comments

---

dds/DCPS/Serializer.cpp
tests/unit-tests/dds/DCPS/RTPS/RtpsCoreTypeSupportImpl.cpp
tests/unit-tests/dds/DCPS/Serializer.cpp

Serializer: detect other kinds of invalid CDR strings

---

tools/scripts/gitrelease.pl

- Changed GitHub organization to "OpenDDS".
- Fix and expand checks for PitHub HTTP errors.
- Rename `--write-authors` to `--update-authors` and add it to `--help`.
- Now the shapes demo GHA workflow isn't triggered unless the release is the very latest.

Post 3.23.1 Release Script Improvements

---

foundation/minutes/2022-12-05.html

Tab Minutes 2022-12-05

---

docs/internal/dev_guidelines.rst
docs/internal/docs.rst

Update the dev guidelines to reflect a consistent approach to whitespace surrounding braces.

Update Dev Guidelines For Whitespace Around Braces

---

dds/DCPS/transport/framework/ReceivedDataSample.cpp
dds/DCPS/transport/framework/TransportReassembly.cpp
tests/unit-tests/dds/DCPS/transport/framework/TransportReassembly.cpp

Clean up build warnings on Windows.

Fix Various TransportReassembly Compile Warnings

---

_includes/footer.html
htmlproofer.sh

Footer Copy Updated

---

tools/scripts/unit_test_coverage.sh

Problem
-------
Deriving code coverage from intentional unit testing slow and has broken recently due to compiler changes.
Solution
--------
Accumulate coverage for all unit tests.  While not intentional, the output is still useful and reveals areas where more testing is needed.

Intentional unit test coverage is not practical with current tools

---

dds/idl/dds_generator.cpp
dds/idl/dds_generator.h
dds/idl/langmap_generator.cpp
dds/idl/marshal_generator.cpp
dds/idl/metaclass_generator.cpp
dds/idl/topic_keys.cpp
dds/idl/topic_keys.h
dds/idl/ts_generator.cpp
dds/idl/typeobject_generator.cpp
dds/idl/value_reader_generator.cpp
dds/idl/value_writer_generator.cpp
tests/DCPS/Compiler/keywords/classic/keywords_classic.mpc
tests/DCPS/Compiler/keywords/cpp11/keywords_cpp11.mpc
tests/DCPS/Compiler/keywords/run_test.pl
tests/DCPS/Compiler/keywords/test.idl

Added test for looking for `_cxx_` in the *TypeSupportImpl.cpp file and fix instances where that happens.

Extend Proper Support for C++ Keywords in IDL

---

README.md
docs/devguide/xtypes.rst

Problem
-------
The README.md file does not contain a link to the online DevGuide.
Solution
--------
Add a link.

README does not link to online DevGuide

---

dds/DCPS/Definitions.h
dds/DCPS/DirentWrapper.h
dds/DCPS/XTypes/DynamicDataAdapter.h
dds/idl/dds_generator.cpp
dds/idl/dds_generator.h
dds/idl/dynamic_data_adapter_generator.cpp
dds/idl/marshal_generator.cpp
dds/idl/metaclass_generator.cpp
tests/DCPS/Compiler/idl_test3_lib/FooDef.idl
tests/unit-tests/dds/DCPS/XTypes/DynamicDataAdapter.cpp
tests/unit-tests/dds/DCPS/XTypes/DynamicDataAdapter.idl

Follow up to #4078, Fixes #4112 and #4109

Fix Warnings and Typedef of Typedef Build Issues

---

dds/DCPS/RTPS/Spdp.cpp

The loop for opening RTPS ports for a participant could theoretically go on forever. This stops it once it goes past the max UDP port. Also add a warning for going past the max participant id allowed in the RTPS spec (119, in section 9.6.2.3). As long as it doesn't result in an invalid port, going past that shouldn't cause a problem, but it could be a sign that OpenDDS has a limited number of ports at its disposal. Also another implementation could use this as a hard limit, but that's much less of a concern.

Add Some Extra Checks for RTPS Unicast Ports

---

dds/DCPS/InternalDataReader.h
dds/DCPS/InternalDataWriter.h
dds/DCPS/MulticastManager.cpp
dds/DCPS/MulticastManager.h
dds/DCPS/NetworkConfigMonitor.cpp
dds/DCPS/Qos_Helper.cpp
dds/DCPS/Qos_Helper.h
dds/DCPS/RTPS/ICE/AgentImpl.cpp
dds/DCPS/RTPS/Spdp.cpp
dds/DCPS/Service_Participant.cpp
dds/DCPS/Time_Helper.h
dds/DCPS/Time_Helper.inl
dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp
tests/unit-tests/dds/DCPS/InternalDataReader.cpp
tests/unit-tests/dds/DCPS/InternalDataWriter.cpp
tests/unit-tests/dds/DCPS/InternalTopic.cpp
tests/unit-tests/dds/DCPS/MockSubscriber.h
tests/unit-tests/dds/DCPS/Qos_Helper.cpp
tests/unit-tests/dds/DCPS/Time_Helper.cpp

Next round of Internal DDS improvements.

Internal DDS improvements

---

docs/news.d/security.rst

Add news for #4155

---

dds/idl/be_util.cpp
docs/devguide/opendds_idl.rst

The -Grapidjson flag has been removed.

Remove -Grapidjson flag [opendds_idl]

---

tools/rtpsrelay/GuidAddrSet.cpp

Bug was introduced in PR #4202

RtpsRelay: fixed bug in record_activity's use of remove in GuidAddrSet

---

dds/DCPS/transport/rtps_udp/RtpsUdpInst.cpp
dds/DCPS/transport/rtps_udp/RtpsUdpInst.h

Problem
-------
Missed the `send_delay_` variable in #4255.
Solution
--------
Add `send_delay_`.

`send_delay` does not have a variable

---

dds/DCPS/Message_Block_Ptr.h
tests/tsan_tests.lst
tests/unit-tests/dds/DCPS/Message_Block_Ptr.cpp
tools/rtpsrelay/GuidAddrSet.h
tools/rtpsrelay/RelayHandler.cpp
tools/rtpsrelay/RelayHandler.h

Also added RtpsRelay tests to tsan_tests

RtpsRelay: use ACE_Message_Block's locking strategy for cached SPDP

---

docs/internal/dev_guidelines.rst

See https://github.com/DOCGroup/ACE_TAO/discussions/2137

Workaround DOC Group Website Issue

---

dds/DCPS/ConditionImpl.h

Based on patch in OpenDDSharp @jmmorato

Added export macro to ConditionImpl

---

docs/news.d/4216.rst
docs/news.d/4226.rst
docs/news.d/4253.rst
docs/news.d/4254.rst
docs/news.d/4262.rst
docs/news.d/4265.rst
docs/news.d/4292.rst
docs/news.d/4293.rst
docs/news.d/4295.rst
docs/news.d/4298.rst
docs/news.d/build-and-install.rst
docs/news.d/config_store.rst
docs/news.d/remove-mailing-lists.rst
docs/news.d/remove-rapidjson-flag.rst

I'm not sure that we need to include the GHA changes.

Documentation for next release

---

dds/DCPS/XTypes/DynamicDataFactory.cpp
dds/DCPS/XTypes/DynamicDataFactory.h
dds/DdsDynamicData.idl
docs/news.d/xtypes-dynamic-data.rst

Problem
-------
The implementation of DDS::DynamicDataFactory is incomplete.
Solution
--------
Complete it by adding `delete_instance`.

Implementation of DynamicDataFactory is incomplete

---

dds/DCPS/ConfigStoreImpl.cpp
dds/DCPS/ConfigStoreImpl.h
dds/DCPS/Discovery.h
dds/DCPS/InfoRepoDiscovery/InfoRepoDiscovery.cpp
dds/DCPS/InfoRepoDiscovery/InfoRepoDiscovery.h
dds/DCPS/RTPS/RtpsDiscovery.cpp
dds/DCPS/RTPS/RtpsDiscovery.h
dds/DCPS/Service_Participant.cpp
dds/DCPS/Service_Participant.h
dds/DCPS/StaticDiscovery.cpp
dds/DCPS/StaticDiscovery.h
dds/DCPS/transport/framework/TransportInst.h
docs/news.d/config_store2.rst
performance-tests/DCPS/InfoRepo_population/run_test.pl
tests/DCPS/FindTopic/LocalDiscovery.cpp
tests/DCPS/FindTopic/LocalDiscovery.h
tests/unit-tests/dds/DCPS/ConfigStoreImpl.cpp

Problem
-------
InfoRepoDiscovery does not use ConfigStore. See #4134.
Solution
--------
Convert InfoRepoDiscovery to use ConfigStore.

`InfoRepoDiscovery` does not use `ConfigStore`

---

dds/DCPS/ConfigStoreImpl.cpp
dds/DCPS/ConfigStoreImpl.h
dds/DCPS/StaticDiscovery.cpp
dds/DCPS/StaticDiscovery.h
docs/news.d/config_store2.rst
tests/unit-tests/dds/DCPS/ConfigStoreImpl.cpp

Problem
-------
StaticDiscovery does not use ConfigStore. See #4134.
Solution
--------
Convert StaticDiscovery to use ConfigStore.

`StaticDiscovery` does not use `ConfigStore`

---

dds/DCPS/RTPS/ICE/AgentImpl.cpp
dds/DCPS/RTPS/ICE/AgentImpl.h
dds/DCPS/RTPS/ICE/Checklist.cpp
dds/DCPS/RTPS/ICE/EndpointManager.cpp
dds/DCPS/RTPS/ICE/Ice.cpp
dds/DCPS/RTPS/ICE/Ice.h
dds/DCPS/RTPS/RtpsDiscovery.cpp
dds/DCPS/Service_Participant.cpp
docs/devguide/run_time_configuration.rst
docs/news.d/config_store2.rst

Problem
-------
ICE does not use ConfigStore. See #4134.
Solution
--------
Convert ICE to use ConfigStore.

ICE does not use ConfigStore

---

dds/DCPS/ConfigStoreImpl.cpp
dds/DCPS/InternalDataReader.h
dds/DCPS/RTPS/Spdp.cpp
dds/DCPS/Service_Participant.cpp
dds/DCPS/StaticDiscovery.cpp
dds/DCPS/XTypes/DynamicDataBase.cpp
dds/DCPS/XTypes/DynamicDataImpl.cpp
dds/DCPS/XTypes/DynamicTypeImpl.cpp
dds/DCPS/XTypes/IdlScanner.h
dds/DCPS/XTypes/MemberDescriptorImpl.cpp
dds/DCPS/security/AuthenticationBuiltInImpl.cpp
dds/idl/dds_generator.h

- 1565926
- 1565951
- 1565956
- 1565958
- 1565962
- 1565966
- 1565979
- 1565993
- 1565995
- 1566005
- 1567659
- 1567660
- 1573396
- 1573398
- 1573400
- 1573403
- 1573404
- 1573405
- 1573406

Fix Coverity issues

---

.github/workflows/build_and_test.yml

Problem
-------
The tests results from GitHub Actions are not saved for further
analysis.
Solution
--------
Upload test results to Google Storage so they can be included on the
scoreboard.

Upload test results to Google Storage

---

dds/DCPS/ConfigStoreImpl.cpp
dds/DCPS/ConfigStoreImpl.h
dds/DCPS/Service_Participant.cpp
dds/DCPS/Service_Participant.h
tests/unit-tests/dds/DCPS/ConfigStoreImpl.cpp

Problem
-------
`[DomainRange/*]` does not use ConfigStore. See #4134.
Solution
--------
Convert `[DomainRange/*]` to use ConfigStore.

`[DomainRange/*]` does not use `ConfigStore`

---

tools/rtpsrelay/GuidAddrSet.cpp
tools/rtpsrelay/GuidAddrSet.h
tools/rtpsrelay/RelayHandler.cpp
tools/rtpsrelay/RelayHandler.h
tools/rtpsrelay/RelayThreadMonitor.cpp
tools/rtpsrelay/RtpsRelay.cpp
tools/rtpsrelay/SpdpReplayListener.cpp
tools/rtpsrelay/StatisticsWriterListener.h

Also simplified some of the code since we know that both DDS Security and C++11 (or above) are configured.

RtpsRelay: moved logging of common name in SpdpHandler

---

dds/DCPS/Service_Participant.cpp
dds/DCPS/Service_Participant.h

Problem
-------
`load_discovery_template` does not use ConfigStore.  See #4134.
Solution
--------
Convert `load_discovery_template` to use ConfigStore.

`load_discovery_template` does not use ConfigStore

---

.github/workflows/build_and_test.yml

Problem
-------
The autobuild is not building the index correctly due to the log file not ending with txt.
Solution
--------
Move the logs to add the txt suffix.

autobuild output for scoreboard is wrong

---

dds/DCPS/InfoRepoDiscovery/InfoRepoDiscovery.cpp
dds/DCPS/Service_Participant.cpp
dds/DCPS/transport/framework/TransportConfig.cpp
dds/DCPS/transport/framework/TransportConfig.h
dds/DCPS/transport/framework/TransportInst.cpp
dds/DCPS/transport/framework/TransportInst.h
dds/DCPS/transport/framework/TransportRegistry.cpp
dds/DCPS/transport/framework/TransportRegistry.h
dds/DCPS/transport/framework/TransportType.h
dds/DCPS/transport/multicast/MulticastLoader.cpp
dds/DCPS/transport/rtps_udp/RtpsUdpInst.cpp
dds/DCPS/transport/rtps_udp/RtpsUdpInst.h
dds/DCPS/transport/rtps_udp/RtpsUdpLoader.cpp
dds/DCPS/transport/shmem/ShmemLoader.cpp
dds/DCPS/transport/tcp/TcpLoader.cpp
dds/DCPS/transport/udp/UdpLoader.cpp

Problem
-------
`load_transport_templates` does not use ConfigStore.  See #4134.
Solution
--------
Convert `load_transport_templates` to use ConfigStore.

`load_transport_templates` does not use ConfigStore

---

.github/workflows/WinFlexBison_CMakePresets.json
.github/workflows/Wireshark_CMakePresets.json
.github/workflows/build_and_test.yml

This requires the use of CMakePresets.json

Upgrade the run-cmake GitHub Action to v10

---

dds/DCPS/QOS_XML_Handler/QOS_Topic_T.cpp
dds/DCPS/QOS_XML_Handler/QOS_Topic_T.h
tests/DCPS/QoS_XML/dump/qos_dump.cpp

Fixed Topic QoS XML handling

---

.github/workflows/build_and_test.yml

GitHub Actions: update apt repos

---

dds/DCPS/LinuxNetworkConfigMonitor.cpp
docs/devguide/building/android.rst

Also fix some minor typos in the section.

Expand Android Netlink Warning and Match it with DevGuide

---

FACE/Fixed.h
dds/DCPS/JsonValueReader.h
dds/DCPS/JsonValueWriter.h
dds/DCPS/PrinterValueWriter.h
dds/DCPS/ValueReader.h
dds/DCPS/ValueWriter.h
dds/idl/be_init.cpp
dds/idl/be_produce.cpp
dds/idl/dds_generator.h
dds/idl/langmap_generator.cpp
dds/idl/value_reader_generator.cpp
dds/idl/value_writer_generator.cpp
docs/news.d/value-reader-writer-fixed.rst
tests/FACE/Compiler/idl_test_fixed/TestFixed.cpp
tests/FACE/Messenger/Publisher/Publisher.cpp
tests/FACE/Messenger/Subscriber/Subscriber.cpp
tests/FACE/MultiDomainMessenger/Publisher/Publisher.cpp
tests/FACE/MultiDomainMessenger/Subscriber/Subscriber.cpp
tests/unit-tests/dds/DCPS/JsonValueWriter.cpp
tests/unit-tests/dds/DCPS/PrinterValueWriter.cpp

Also removed preprocessor conditionals for ACE_HAS_CDR_FIXED since all supported ACE versions have it.

Use ACE_CDR::Fixed as the type of fixed values in ValueReader and ValueWriter

---

dds/DCPS/ConfigStoreImpl.cpp
dds/DCPS/Service_Participant.cpp
dds/DCPS/Service_Participant.h
docs/news.d/config_store3.rst

Problem
-------
`[domain/*]` does not use ConfigStore. See #4134.
Solution
--------
Convert `[domain/*]` to use ConfigStore.

`[domain/*]` does not use `ConfigStore`

---

dds/DdsDcps.mpc

They will now be included in make install and make realclean

Added a few generated headers to DdsDcps.mpc

---

dds/idl/dds_generator.h
dds/idl/langmap_generator.cpp
dds/idl/ts_generator.cpp

also:
clean up redundant code
attempt to follow style guidelines in source and generated

opendds_idl: made versioned namespace support more consistent

---

dds/idl/dds_generator.h
dds/idl/marshal_generator.cpp

Fixes signed/unsigned warnings in generated code, as seen in https://github.com/OpenDDS/opendds-monitor/actions/runs/8405526105

Update integer type used internally for enums

---

docs/devguide/run_time_configuration.rst
docs/news.d/config_store_documentation.rst

Problem
-------
The new capabilities from the ConfigStore are not documented for users.
Solution
--------
Add to the configuration documentation.

Configuration with ConfigStore is not documented

---

cmake/README.md

Update Link in cmake/README.md

---

docs/devguide/building/index.rst

For reference, see https://github.com/OpenDDS/OpenDDS/issues/4674.

Clarify windows build instructions

---

java/dds/OpenDDS/DCPS/FakeAndroidNetworkCallback.java
java/dds/dcps_java.mpc

Generated makefile needs to see a .class file so it doesn't need to build every time make is run

Updated Java build (non-Android)

---

.github/workflows/build_and_test.yml
.github/workflows/cmake.yml
.github/workflows/ishapes.yml

* .github/workflows/build_and_test.yml:

[githubCI] Upgrade to vcpkg 2024.06.15

---

docs/conf.py
docs/devguide/internet_enabled_rtps.rst
docs/index.rst

Mostly related to RtpsRelay
Also updated copyright year
Top-level index page: use same format for link to devguide index as other links

Updated documentation

---

.github/workflows/sphinx_strict.yml
docs/build.py
docs/news.d/resend_period_fractions_seconds.rst

Fix News and Move Linkcheck to a Seperate Job

---

tools/scripts/gitrelease.pl

Fixes https://github.com/OpenDDS/OpenDDS/issues/4759 and some other issues I noticed in `--help`.

Minor Improvements to Release Script Output

---

dds/DCPS/transport/rtps_udp/BundlingCacheKey.h

Reorder constructor arguments to BundlingCacheKey to reflect actual u…sage and member order.

Reorder constructor arguments to BundlingCacheKey

---

docs/devguide/internet_enabled_rtps.rst
docs/news.d/relay-max-participants.rst
tools/rtpsrelay/Config.h
tools/rtpsrelay/GuidAddrSet.cpp
tools/rtpsrelay/GuidAddrSet.h
tools/rtpsrelay/RtpsRelay.cpp

provides another mechanism for detecting load on each RtpsRelay instance

Added -AdmissionMaxParticipantsRange to RtpsRelay options

---

dds/idl/dds_generator.cpp
dds/idl/dds_generator.h
dds/idl/dds_visitor.cpp
dds/idl/marshal_generator.cpp
dds/idl/ts_generator.cpp
java/tests/complex_idl/ComplexIDLTest.java
java/tests/complex_idl/Complex_Idl.idl

Problem
-------
Union topics do not compile with Java.
Solution
--------
Add support and a extend a test for union topics in Java.

Union topics are not supported in Java

---

dds/DCPS/transport/rtps_udp/RtpsUdpTransport.cpp
docs/news.d/release-reservatons.rst

This fixes a mistake made in https://github.com/OpenDDS/OpenDDS/pull/4731

Fix Swapped Arguments in RTPS/UDP

---

dds/DCPS/Definitions.h
dds/DCPS/Service_Participant.cpp
docs/design/security.md
docs/internal/dev_guidelines.rst
tools/scripts/gdbext.py

Also works around an issue in GDB when some pointers are dereferenced.

Embed GDB Extension in OpenDDS

---

tools/dds/rtpsrelaylib/Name.cpp
tools/dds/rtpsrelaylib/Name.h
tools/dds/rtpsrelaylib/PartitionIndex.h
tools/dds/rtpsrelaylib/Utility.h
tools/rtpsrelay/GuidAddrSet.cpp
tools/rtpsrelay/GuidAddrSet.h
tools/rtpsrelay/GuidPartitionTable.cpp
tools/rtpsrelay/GuidPartitionTable.h
tools/rtpsrelay/HandlerStatisticsReporter.h
tools/rtpsrelay/ParticipantListener.cpp
tools/rtpsrelay/ParticipantStatisticsReporter.h
tools/rtpsrelay/PublicationListener.cpp
tools/rtpsrelay/README.rst
tools/rtpsrelay/ReaderListenerBase.h
tools/rtpsrelay/RelayAddressListener.cpp
tools/rtpsrelay/RelayHandler.cpp
tools/rtpsrelay/RelayHandler.h
tools/rtpsrelay/RelayHttpMetaDiscovery.cpp
tools/rtpsrelay/RelayHttpMetaDiscovery.h
tools/rtpsrelay/RelayPartitionTable.h
tools/rtpsrelay/RelayPartitionsListener.cpp
tools/rtpsrelay/RelayStatisticsReporter.h
tools/rtpsrelay/RelayStatusReporter.cpp
tools/rtpsrelay/RelayStatusReporter.h
tools/rtpsrelay/RtpsRelay.cpp
tools/rtpsrelay/SpdpReplayListener.cpp
tools/rtpsrelay/SubscriptionListener.cpp

* Removed unused code and macros
* Moved some large inline functions to cpp files
* Used C++11 features for clarity

RtpsRelay cleanup

---

tools/rtpsrelay/GuidAddrSet.h

This was supposed to go in PR #4802

Continued RtpsRelay cleanup

---

dds/DCPS/transport/framework/TransportSendBuffer.h
dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp

From ASan
https://github.com/mitza-oci/OpenDDS/actions/runs/11071598667/job/30767764680

SingleSendBuffer::pre_clear() needs the lock

---

docs/devguide/quality_of_service.rst
docs/devguide/run_time_configuration.rst
docs/news.d/doc-fixes.rst
docs/news.d/gdb.rst

Also added news for GDB extension.

Documentation Fixes from 4784

---

cmake/build_ace_tao.cmake
docs/news.d/cmake-vs2015.rst

fix VisualStudio 2015 cmake check error

---

dds/DCPS/RTPS/ICE/AgentImpl.cpp
dds/DCPS/RTPS/ICE/AgentImpl.h

Problem
-------
Custom implementations of ReactorInterceptor duplicate code which makes maintenance difficult.
Solution
--------
To make the code easier to maintain, replace custom implementations of ReactorInterceptor with helper classes.

ICE::AgentImpl is a ReactorInterceptor

---

configure
dds/DCPS/JsonValueReader.h
dds/DCPS/JsonValueWriter.h
dds/DCPS/RTPS/ICE/Checklist.cpp
dds/DCPS/RTPS/ICE/Stun.cpp
dds/DCPS/RTPS/ParameterListConverter.cpp
dds/DCPS/RTPS/RtpsDiscoveryConfig.cpp
dds/DCPS/RTPS/Sedp.cpp
dds/DCPS/security/AccessControlBuiltInImpl.cpp
dds/DCPS/security/AuthenticationBuiltInImpl.cpp
dds/DCPS/security/CryptoBuiltInImpl.cpp
dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp
tests/Utils/Options.h

Also improved configure script's use of warning settings on VC++. This avoids "warning D9025: overriding '/W3' with '/W4'"

Fixed some warnings

---

tests/dcps_tests.lst

The STATIC_COMPILER configuration flag was copied by mistake

Update dcps_tests.lst entry for maps test

---

configure

Also some internal changes like treating the MPC features as a hash and cleanup for cross-compiled builds.

configure: Check Android NDK compiler's C++ standard level

---

docs/devguide/building/android.rst

Based on https://github.com/OpenDDS/OpenDDS-Android/pull/27#issuecomment-3132133286

Updated Android documentation

---

dds/DCPS/DataReaderImpl.cpp
dds/DCPS/DataReaderImpl.h
dds/DCPS/DataWriterImpl.h

Remove unused elements from DataReader/WriterImpl

---

.github/workflows/build_and_test.yml
configure
dds/DCPS/XTypes/TypeObject.cpp
dds/DCPS/XTypes/TypeObject.h
dds/idl/langmap_generator.cpp

resolves #5076, resolves #5091

TypeObject.h and IDL-to-C++11 code generation support for forward-declared types
