OpenDDS/OpenDDS

.github/workflows/check_test_results.yml
In the event that one of the check test result jobs matrix jobs fails (invalid input, job failure, etc), the other jobs should not get canceled.
=> Disable fail-fast strategy for matrix builds

dds/DCPS/Serializer.inl, tests/unit-tests/dds/DCPS/Serializer.cpp
For any alignment of a power of two (the only kind we support), this calculation avoids modulus calculation and branch prediction.
=> Use bitwise alignment calculation

dds/DCPS/RTPS/RtpsDiscovery.cpp, dds/DCPS/RTPS/RtpsDiscovery.h, dds/DCPS/RTPS/Spdp.cpp
Problem
-------
Participants that connect to the RtpsRelay over the public internet
will often have problems.  For example, a cable modem that is on the
fritz may be up for a minute and then down for 14 minutes.  This adds
load to the RtpsRelay as it has to discover the participant each time
if the participant's lease is small.
Solution
--------
Provide an option that allows a participant to extend the lease of
discovered participants.
=> RTPS Discovery: added a Lease Extension config option

dds/DCPS/transport/framework/TransportSendStrategy.cpp, dds/DCPS/transport/framework/TransportSendStrategy.h, dds/DCPS/transport/rtps_udp/RtpsUdpSendStrategy.cpp, dds/DCPS/transport/rtps_udp/RtpsUdpSendStrategy.h
Specifically, when security is disabled, don't call pre_send_packet to avoid duplication and extra message block allocations (even if data blocks are merely reference-incremented).
=> Avoid ACE_Message_Block duplication from pre_send_packet 

dds/DCPS/Hash.h, dds/DCPS/PoolAllocator.h, dds/DCPS/transport/framework/TransportReassembly.h
Problem: Fragment lookup gets expensive as number of FragKeys grow in size. Time spend in std::map lookups for FragKeys starts to become prohibitive for large numbers of publication ids & sequence numbers.
Solution: For C++11, std::unordered_map greatly reduces the lookup time for large numbers of FragKeys.
=> Use C++11 unordered_map for Fragment Lookup When Possible

tools/rtpsrelay/Config.h, tools/rtpsrelay/GuidPartitionTable.cpp, tools/rtpsrelay/GuidPartitionTable.h, tools/rtpsrelay/RtpsRelay.cpp
Problem
-------
The RtpsRelay is most efficient when an application is divided into a
number of small partitions.  Participants that (inadvertently) don't
specify any partitions are effectively placed in the same partition.
This partition can become large which degrades the performance of the
RtpsRelay.
Solution
--------
Add a control that allows the empty partition "" to be filtered.
=> Empty partitions degrade RtpsRelay performance

tools/dds/rtpsrelaylib/Utility.h, tools/rtpsrelay/RelayHandler.cpp, tools/rtpsrelay/RelayHandler.h, tools/rtpsrelay/RtpsRelay.cpp
Problem
-------
The RtpsRelay has two sets of things that expire:  the IP:port
combinations of clients and GUIDs that are pending (have not completed
discovery).  Both of these involved a multimap that goes from time to
the thing to be expired.  Eliminating the overhead of maintaing the
maps will increase the perfomance of the RtpsRelay.
Solution
--------
Replace the expiration multimaps with a list.  This may create an
inversion when tracking IP:ports where something that should expire
sooner is behind something that will expire later in the list.  In the
worst case, a IP:port might be removed after two expiration durations
which is acceptable.
=> RtpsRelay expiration can be more efficient

.github/workflows/build_and_test.yml
This PR increases the timeout of Compiler_* jobs due to them occasionally timing out.
It also removes Xerces and SSL from the w19 static Compiler_* jobs due to them running out of disk space.
=> GitHub Actions: Increase timeout on Compiler_* jobs.

tools/rtpsrelay/GuidPartitionTable.cpp, tools/rtpsrelay/GuidPartitionTable.h, tools/rtpsrelay/ParticipantListener.cpp, tools/rtpsrelay/ParticipantListener.h, tools/rtpsrelay/PublicationListener.cpp, tools/rtpsrelay/SubscriptionListener.cpp
Problem
-------
It is expected that RtpsRelay clients will determine and update their
server-reflexive address.  These updates will appear as new samples in
the BITs read by the RtpsRelay.  The RtpsRelay will log these updates
as new participants, publications, and subscriptions which is
misleading.
Solution
--------
Distinguish between new participants, publications, and subscriptions
and updates to existing ones.
=> RtpsRelay discovery logging and statistics don't handle updates

dds/DCPS/PeriodicTask.h, dds/DCPS/PublisherImpl.cpp, dds/DCPS/PublisherImpl.h, dds/DCPS/RTPS/Spdp.cpp, dds/DCPS/SporadicTask.h, dds/DCPS/transport/framework/TransportClient.cpp, dds/DCPS/transport/framework/TransportClient.h, dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp, dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.h, tests/DCPS/EntityLifecycleStress/subscriber.cpp
Running ThreadSanitizer against `tests/DCPS/Messenger/run_test.pl rtps_disc` and `tests/DCPS/EntityLifecycleStress/run_test.pl rtps_disc` revealed a number of data races and mutex lock order inversions (potential deadlocks).
These are some of the 'safer' / 'easier' changes that resulted in clean runs, but aren't enough on their own to fix all the reported issues or to allow a theoretical `tsan` build to catch these issues earlier.
In particular, the timer RCH changes in RtpsUdpDatalink are actually heap-use-after-free issues, resulting from the fact that the reactor believes it's holding a reference to the timer's RcEventHandler base class, when in reality these timers were simply deleted without regard for their reference count, since they were simple members of …
=> ThreadSanitizer Error / Warning Cleanup, Round 1

tests/unit-tests/dds/DCPS/Serializer.cpp
- fixed warnings
- avoid using identifiers that are reserved for the implementation
=> Serializer Unit Test cleanup

tests/unit-tests/tools/OpenDDS_RtpsRelayLib/Name.cpp, tools/dds/rtpsrelaylib/Name.cpp, tools/dds/rtpsrelaylib/Name.h, tools/dds/rtpsrelaylib/PartitionIndex.h, tools/dds/rtpsrelaylib/Utility.h, tools/rtpsrelay/Config.h, tools/rtpsrelay/DomainStatisticsReporter.h, tools/rtpsrelay/GuidPartitionTable.cpp, tools/rtpsrelay/GuidPartitionTable.h, tools/rtpsrelay/HandlerStatisticsReporter.h, tools/rtpsrelay/ParticipantStatisticsReporter.h, tools/rtpsrelay/RelayAddressListener.cpp, tools/rtpsrelay/RelayHandler.cpp, tools/rtpsrelay/RelayHandler.h, tools/rtpsrelay/RelayPartitionTable.h, tools/rtpsrelay/RelayPartitionsListener.cpp, tools/rtpsrelay/RelayStatisticsReporter.h, tools/rtpsrelay/RtpsRelay.cpp
Problem
-------
The RtpsRelay uses std::set and std::map in various places where
std::unordered_set and std::unordered_map may provide superior
performance.
The lookup of guid to partitions iterates over all readers/writers
with the given prefix requiring a log(N) find and P O(1) operations to
iterate.
Solution
--------
Replace ordered sets and maps with unordered ones where possible.  A
hash function for ACE_INET_Addr is need to convert the remaining
cases.
Add a cache for the guid to partitions lookup.
=> RtpsRelay is inefficient

dds/DCPS/SubscriberImpl.cpp
This PR focuses on two potential deadlock scenarios, both in the subscriber impl code, the function to get a list of current data readers and a function to notify datareaders. The problem is that multiple threads are passing through these functions and must mediate the sharing of resources using locks. However there is a lock on the SubscriberImpl object that is grabbed a the start of these functions, then during processing a second lock on the DataReaderImpl object is repeatedly taken while evaluating individual data readers. This triggers a deadlock when a thread is holding the DataReaderImpl instance lock and waiting for the SubscriberImpl lock, but another thread is holding the SI lock and wants the particular DataReaderImpl instance lock currently held by the first thread.
This …
=> Fix for deadlocks brought out by the GroupPresentation test.

.github/workflows/build_and_test.yml
In order to reduce strange timing behaviors for MacOS Virtual Environment Runner Agents, disable NTP per the workaround listed on [https://github.com/actions/virtual-environments/issues/820](https://github.com/actions/virtual-environments/issues/820).
=> Disable NTP for macos virtual environment runners

dds/DCPS/transport/framework/TransportReceiveStrategy_T.cpp, dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp, dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.h, dds/DCPS/transport/rtps_udp/RtpsUdpInst.cpp, dds/DCPS/transport/rtps_udp/RtpsUdpInst.h
Problem: We're currently relying on `new` for the allocation of all ACE_Message_Blocks, which can be slow
Solution: Create appropriate allocators for message blocks, data blocks, and data buffers (for both customized blocks & fragments, as well as "bundled" responses).
=> Make use of ACE's cached allocators for RtpsUdpDataLink's ACE_Message_Blocks

dds/DCPS/transport/framework/TransportReassembly.cpp, dds/DCPS/transport/framework/TransportReassembly.h
Problem: Currently, fragment insertion is O(n), which is problematic for samples with large numbers of fragments (especially when the "latest" fragment will usually be inserted at the end of the list being searched).
Solution: Retain current data structures, but add an additional index map to speed the initial lookup into the original list. Data structures must be kept in sync, but allows for O(log n) insertion times.
Future Work: This entire data structure probably ought to be replaced with an expanded version of the OrderedRanges data structure that lives inside DisjointSequence. It will need to be expanded (templatized?) to accept right-and-left-combinable "payloads", but the benefits would include easier testability and reduced code-complexity for fragmentation reassembly.
=> Improve Worst-Case Fragment Insertion Complexity

tests/DCPS/LivelinessTest/DataReaderListener.cpp, tests/DCPS/LivelinessTest/DataReaderListener.h, tests/DCPS/LivelinessTest/LivelinessTest.cpp
Problem: The Automatic reader was in rare cases getting interrupted while it was still handling the message that was received.  If the writer was shut down before the read/take was completed, an incorrect liveliness changed value would occur.
Solution: I introduced a way of tracking where the message has been read by the automatic data reader listener, and block the deletion of writer/publisher until the message has been handled.
=> Liveliness Test: Automatic Reader receives incorrect liveliness change count

dds/DCPS/FibonacciSequence.h, dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp, dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.h, tests/unit-tests/dds/DCPS/FibonacciSequence.cpp
Problem: In periods of high congestion, heartbeat traffic can become excessive.
Solution: Allow fallback for heartbeat periods when heartbeats go unanswered.
=> Allow fallback for unanswered heartbeats

dds/DCPS/DataReaderImpl.cpp, dds/DCPS/DataReaderImpl.h, dds/DCPS/DataReaderImpl_T.h, dds/DCPS/SubscriberImpl.cpp, tests/DCPS/GroupPresentation/SubscriberListener.cpp, tests/DCPS/GroupPresentation/SubscriberListener.h, tests/DCPS/GroupPresentation/Writer.cpp
This PR adds a couple more uses of local copies of otherwise locked data to avoid conflicts across function calls. This PR also aaddresses some peculiar code specific to the GroupPresentation test case.
=> more deadlock risk mitigation when using Topic presentation QOS

dds/DCPS/DataSampleHeader.h, dds/DCPS/transport/framework/TransportClient.cpp, dds/DCPS/transport/framework/TransportClient.h, dds/DCPS/transport/framework/TransportCustomizedElement.h, dds/DCPS/transport/framework/TransportCustomizedElement.inl, dds/DCPS/transport/framework/TransportQueueElement.h, dds/DCPS/transport/framework/TransportSendBuffer.cpp, dds/DCPS/transport/framework/TransportSendBuffer.h, dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp, dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.h, dds/DCPS/transport/rtps_udp/RtpsUdpReceiveStrategy.cpp
Problem: non-durable RTPS can currently receive historical samples when writer cache (heartbeat window) is slow to update (e.g. when readers do not shut down cleanly).
Solution: non-durable RTPS readers should filter samples based on source timestamps (or received timestamps, if source timestamps are not available) in order to prevent delivery of samples generated prior to time of discovery / association.
=> Filter pre-discovery RTPS samples for non-durable readers

tools/rtpsrelay/GuidPartitionTable.cpp, tools/rtpsrelay/GuidPartitionTable.h
Problem
-------
Under heavy load, the handler thread of the RtpsRelay seems to block
when a participant is discovered or a participant times out.  This
shows up as network receive errors.  The timeout case indicates that a
problem exists regardless of extra messaging required for discovery.
The common link in both scenarios is that GuidPartition table is
updated which may lead to samples being written by the relay
participant.
Upon inspection, the lock protecting the GuidPartition table is held
while the samples are written.  Thus, the application participants
discovery thread acquires the lock, updates the GuidPartition table,
and then writes to the relay participant topics.  The handler is
unable to access the GuidPartition table during this transaction.
Solution
--------
Refactor the …
=> Lock held when writing relay participant topics

tools/modeling/tests/StockQuoter/StockQuoter.opendds
The StockQuoter had a race due to having the wrong QoS policy.  There was no guarantee that the reader would be handling the messages by the time the writer was writing, and it was only storing the last 1 message that was received.  If the writer wrote more than 1 message in the time it took to starting handling the messages on the readers' side, the test would time out as the 10 expected messages would never be reached.
=> StockQuoter Race Condition

tools/rtpsrelay/Config.h, tools/rtpsrelay/RelayHandler.cpp, tools/rtpsrelay/RtpsRelay.cpp
Problem
-------
The send and receive buffers for the RtpsRelay are not configurable.
Solution
--------
Expose an option and set the receive buffer size.
=> RtpsRelay buffer size is not configurable

dds/DCPS/transport/framework/TransportReassembly.cpp, dds/DCPS/transport/framework/TransportSendBuffer.cpp, dds/DCPS/transport/framework/TransportSendBuffer.h, dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp, dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.h
Problem: Writers of fragmented data have issues reconnecting after all readers disconnect (and pre_stop_helper is called) because "late" fragments fool the writer into thinking they have access to the full range of fragments for a given sequence number. When the reconnect occurs, the writer then issues an incorrect heartbeat range, and a reliable reader is never able to recover all the fragments required to deliver sample data.
Solution: advance a "minimum" SN for the send buffer when sequence numbers are acked, preventing futher inserts from being used with that sequence number. This blocks the "late" fragments and prevents the inaccurate heartbeat.
Note: A few other issues were identified and cleaned up in this PR as well, noticeably corruption of NackFrag submessages through reuse of a …
=> Writers of Fragmented Data Samples Have Issues Reconnecting

dds/DCPS/RTPS/RtpsDiscovery.cpp, dds/DCPS/RTPS/RtpsDiscovery.h, dds/DCPS/RTPS/Sedp.cpp, dds/DCPS/RTPS/Spdp.cpp
Problem
-------
The send and receive buffer sizes for RtpsDiscovery (the SPDP socket
and SEDP socket) are not configurable.  Certain applications like the
application participant in the RtpsRelay may need to configure these
buffer sizes.
Solution
--------
Add configuration options for setting the buffer sizes.
=> RtpsDiscovery buffer sizes are not configurable

dds/DCPS/transport/framework/TransportReassembly.cpp, dds/DCPS/transport/framework/TransportReassembly.h, dds/DCPS/transport/udp/UdpReceiveStrategy.cpp, dds/DCPS/transport/udp/UdpReceiveStrategy.h
Given that the discovery thread is allowed to clear fragments on association / disassociation, mutex protection is required for the TransportReassembly class.
=> Use mutex protection for TransportReassembly

dds/DCPS/DataReaderImpl.cpp, dds/DCPS/DomainParticipantImpl.cpp, dds/DCPS/DomainParticipantImpl.h, tests/DCPS/BuiltInTopic/common.cpp
it is because of a race between the main thread and a service thread. This commit addresses that case.
It does this by adding a method to the Domain Participant servant impl to wait until it is positively signaled that a desired instance handle has been assigned for a given GUID. The new method is called await_handle() and is similar to the method lookup_handle().
=> Added DomainParticipantImpl::await_handle

cmake/api_macros.cmake
When having an IDL file in a library that is dependent on an IDL file in another library, a duplicate BUILD_DLL would be created for the first library inside the second library.
This can be prevented by changing PUBLIC to PRIVATE as done in this PR.
=> CMake: Prevent Duplicate BUILD_DLL creation

.github/workflows/build_and_test.yml, docs/internal/github_actions.rst, tests/dcps_tests.lst
The goal of this PR is to document why we have some tests blocked from running in GitHub Actions, and to unblock things that are failing also on the scoreboard.
I removed the flags and after each run, if a test failed on both the latest scoreboard run, as well as the CI run, I reblocked it and logged the reason for test failure.
Here is my google sheets I used for logging failures: 
https://docs.google.com/spreadsheets/d/1S9UfzzA_2PF9pWW3znLuYKvi2OlA04QG-qwYxDfCJ3k/edit?usp=sharing
If you feel there are any of the tests listed in the spreadsheet that should also be blocked, please let me know.
Additionally, if you feel any of the blocked tests should be unblocked, please let me know.
=> GitHub Actions: Update .lst flags

dds/DCPS/RTPS/Spdp.cpp
Problem
-------
The replier side of auth does not back off send its authreq.
Solution
--------
Always back off when authenticating.
=> Auth backoff only applies to requester

dds/DCPS/transport/framework/TransportClient.cpp
Problem
-------
A passive pending connection that times out is not obvious from the
logs.
Solution
--------
Make it obvious.
=> TransportClient logging doesn't show pending timeouts

dds/DCPS/QOS_XML_Handler/QOS_XML_Loader.cpp, dds/DCPS/QOS_XML_Handler/QOS_XML_Loader.h, dds/DCPS/QOS_XML_Handler/XML_File_Intf.cpp, dds/DCPS/QOS_XML_Handler/XML_File_Intf.h, dds/DCPS/QOS_XML_Handler/XML_Intf.cpp, dds/DCPS/QOS_XML_Handler/XML_String_Intf.cpp, dds/DCPS/QOS_XML_Handler/XML_String_Intf.h
Extend QoS XML handlers to allow the user to pass its own XML_Error_Handler. Also use the XML Helper as member instead of using a hidden global static object which is not needed and could cause cleanup issues.
=> Extend QoS XML handlers to allow the user to pass its own XML_Error_Handler

tests/unit-tests/dds/DCPS/transport/framework/NetworkAddress.cpp
Problem: NetworkAddress Test currently fails intermittently due to address resolution issues for bing.com. It's likely that bing is load-balanced in such a way that DNS results are inconsistent, causing repeat lookups (part of the test) to return with different results.
Solution: Try a less popular domain name.
=> Attempt Workaround for Intermittent NetworkAddress Test Failures

dds/DCPS/AddressCache.h, dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp, tests/DCPS/RtpsRelay/Smoke/DataReaderListener.cpp
Problem: Messages sent to the RtpsRelay often need to be routed to different IPs based on the destination GUID. It therefore doesn't make much sense to bundle several destination GUIDs together when sending messages to the RtpsRelay.
Solution: Update the bundling algorithm to create new messages when the outbound set of addresses includes the RtpsRelay and a new destination GUID is encountered.
=> Reduce Bundling of RTPS Submessages when Sending to RtpsRelay

dds/DCPS/security/AccessControlBuiltInImpl.cpp, dds/DCPS/security/AuthenticationBuiltInImpl.cpp, dds/DCPS/security/AuthenticationBuiltInImpl.h, tools/rtpsrelay/RelayHandler.cpp, tools/rtpsrelay/RelayHandler.h
Problem
-------
When using security, the subject name of a participant can provide
useful information when debugging connectivity issues.
Solution
--------
Extract the subject name and log it.
=> RtpsRelay does not log subject name

cmake/dds_idl_sources.cmake, cmake/tao_idl_sources.cmake
We were assigning TAO_LIB_DIR to MSVC rather than the appropriate TAO_BIN_DIR.  These changes fix that.  Additionally, the function name has been change to better represent what the function does.
=> CMake: Assign runtime library tao_idl on MSVC

tests/DCPS/RtpsRelay/Smoke/run_lease_duration_test.pl, tools/rtpsrelay/RelayHandler.cpp, tools/rtpsrelay/RelayHandler.h
Problem
-------
An RtpsRelay client is moved into pending status when the RtpsRelay
receives any message and conditions allow the client to be admitted.
However, discovery will not start until an SPDP message is received
and a message on the SEDP port is received.  This could delay
discovery by the SPDP resend period.
Solution
--------
Record every new client but only admit them when SPDP is received and
an SEDP address is available.
=> RtpsRelay pending queue delays discovery

dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp
Problem
-------
The following sequence was observed:
1. A reliable reader dies unexpectedly with unacknowledged data.
2. This freezes the heartbeat first number.
3. A subsequent reliable reader was offered the heartbeat first and
had to nack/gap the entire sequence.
This is effectively the same problem as #2954 which does not address
the case where the reader is initialized with a non-directed
heartbeat.
Solution
--------
Send a "catch up" gap to readers that are nacking sequence numbers
below their starting sequence number.
=> RtpsUdpDataLink doesn't gap for new reliable reader

dds/DCPS/PoolAllocator.h, dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp, dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.h
Problem
-------
The send buffer in an RtpsWriter is never cleaned so long as there is
a pre-association reader.
Solution
--------
Track the sequence numbers promised to preassociation readers so they
are retained when association completes but allow the cleanup to occur.
=> RtpsWriter send buffer leaks with persistent pre-association reader

cmake/OpenDDSConfig.cmake
Resolves [issue #3003](https://github.com/objectcomputing/OpenDDS/issues/3003)
=> _ace_bin_hints/_tao_bin_hints Mix-up in OpenDDSConfig.cmake

dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp
Problem
-------
The `acked_by_all_helper_i` method determines the maximum sequence
number that has been acknowledge by all readers by considering
preassociation readers, lagging readers, and leading readers.  In the
special case of PARTICIPANT_VOLATILE_SECURE_WRITER, the leading
readers will all be at different sequence numbers.
`acked_by_all_helper_i` is picking the lowest leading sequence number
which may be lower than the sequence number determined from the
preassociation or lagging readers.  Data can only be acknowledged up
to the sequence number acknowledged by the oldest leading reader.
This causes the `send_buffer` to retain more samples than necessary.
Solution
--------
Use the highest sequence number from the leading readers.
=> PARTICIPANT_VOLATILE_SECURE_WRITER causes leak in send_buffer

dds/DCPS/RTPS/RtpsDiscovery.cpp, dds/DCPS/RTPS/RtpsDiscovery.h, dds/DCPS/RTPS/Spdp.cpp
This PR creates a max_lease_duration option that limits what participants can set their lease duration to be.
I set the default at 2x the default lease duration (600 seconds).
=> RTPS Discovery max_lease_duration config option

tests/DCPS/LivelinessTest/DataReaderListener.cpp, tests/DCPS/LivelinessTest/LivelinessTest.cpp
When the LivelinessTest was written 14 years ago, it used a count to keep track of liveliness. 
This lead to a problem with a remote reader where depending on whether the Transport, or the DCPSInfoRepo cleaned up first, we would get a different liveliness count.  In reality, it doesn't matter which order these cleanups happen in, so long as they both happen.
We already ensure this by checking the `verify_last_liveliness_status()` of each reader to make sure everything is clean upon the exiting of the test. As such, I removed the liveliness count because it was reporting problems that were not actually problems, indicating it is a bad metric for the test to be using when determining success.
=> Liveliness Test: Remove Counting

DevGuideExamples/DCPS/Messenger/CMakeLists.txt
Fixes issue seen in https://github.com/objectcomputing/OpenDDS/issues/3017.
The CMakeLists file is supposed to clean up generated headers in the source because they can conflict with the CMake build. It couldn't do that for two reasons:
- There was a typo in the code: `_headers` instead of `headers`. This made the code non-functional.
- If the typo is fixed it would remove `DataReaderListenerImpl.h` because the `file(GLOB` paths are absolute and the code the excludes the header isn't.
Fixed the typo and changed it to remove the result of `file(GLOB "DataReaderListenerImpl.h")` instead of just `"DataReaderListenerImpl.h"` from the list headers to remove.
=> Fix DevGuide Messenger CMakeLists Header Cleanup

dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp
Problem
-------
Removing a PVS reader that has unacknowledged data causes the send
buffer to grow.
Solution
--------
Clean up the send buffer.
=> Removing a PVS reader doesn't clean send buffer

dds/DCPS/RTPS/Sedp.cpp, dds/DCPS/RTPS/Sedp.h, dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp, dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.h
- Add RTPS support for REQUEST_ACK
- Add Sedp method to use it (currently unused)
- Generate RTPS heartbeats for REQUEST_ACK and END_HISTORIC_SAMPLES
=> RTPS Support For REQUEST_ACK and END_HISTORIC_SAMPLES Heartbeats

docs/conf.py
The bit of code to calculate the release tag for GitHub links apparently has never been tested with a micro release. I forgot to cast the micro `int` field to a `str`.
https://readthedocs.org/projects/opendds/builds/14811312/
https://github.com/objectcomputing/OpenDDS/runs/3705194668?check_suite_focus=true
=> Fix Building Sphinx Docs for Micro Releases

dds/DCPS/RTPS/RtpsDiscovery.cpp, dds/DCPS/RTPS/Sedp.cpp, dds/DCPS/RTPS/Sedp.h, dds/DCPS/RTPS/Spdp.h, dds/DCPS/StaticDiscovery.cpp, dds/DCPS/StaticDiscovery.h
Cleanup from https://github.com/objectcomputing/OpenDDS/pull/3015
=> Remove `typename` from Non-Template Classes

.github/workflows/build_and_test.yml
GitHub changed the path of OpenSSL on the MacOS 10.15 runners. This PR changes the path in our build_and_test.yml to reflect that.
Here is a short run that was done on my local branch proving the change works:
https://github.com/ClaytonCalabrese/OpenDDS/runs/3747903407?check_suite_focus=true
=> GitHub Actions: MacOS10 new OpenSSL path

dds/DCPS/RTPS/Sedp.h, dds/DCPS/StaticDiscovery.h
Since `OPENDDS_MAP_T` uses `typename` in safety profile.
Follow up to https://github.com/objectcomputing/OpenDDS/pull/3039
=> Remove `_T` from `MatchingDataMap` `typedef`s

dds/DCPS/transport/framework/TransportSendStrategy.cpp, dds/DCPS/transport/framework/TransportSendStrategy.h, dds/DCPS/transport/framework/TransportSendStrategy.inl, dds/DCPS/transport/multicast/MulticastSendStrategy.cpp
This should fix the SEGV for an empty packet chain in TransportSendStrategy.
It remains confusing to me, though, why this was necessary, since header_.length_ and pkt_chain_ seem to be "reset" at the same time when they are modified.
=> Fix SEGV in TransportSendStrategy for Empty Packet Chain

.github/workflows/build_and_test.yml
These 3 builds were using ace that enabled `--ipv6` and Test that passed `-Config IPV6` , but it was missing from the build step.
Builds are:
u20_p1_sec
u20_p1_asan_sec
u20_p1_tsan_sec
=> GitHub Actions: Add --ipv6 to u20 build configure steps

tools/dds/rtpsrelaylib/Relay.idl, tools/rtpsrelay/RelayAddressListener.cpp, tools/rtpsrelay/RelayAddressListener.h, tools/rtpsrelay/RelayPartitionsListener.cpp, tools/rtpsrelay/RelayPartitionsListener.h, tools/rtpsrelay/RelayStatisticsReporter.h, tools/rtpsrelay/RtpsRelay.cpp, tools/rtpsrelay/SpdpReplayListener.cpp, tools/rtpsrelay/SpdpReplayListener.h
To make sure clusters of relays are communicating with each other, add count of matches for the SPDP Relay, Relay Partitions, and Relay Addresses DataReaders to the Relay Statistics.
=> Add Counts of Remote Relay Publications to Stats

tests/unit-tests/dds/DCPS/Serializer.cpp
=> fixed one more warning in Serializer unit test

dds/DCPS/Definitions.h
Provide equivalent typedefs that work with all versions
=> Newer standard libraries have removed binary_function

tests/DCPS/DomainRange/run_test.pl
Problem
-------
The DomainRange test sometimes times out.
Solution
--------
Disable console logging.
=> DomainRange test times out

dds/DCPS/transport/framework/TransportReceiveStrategy_T.cpp, dds/DCPS/transport/rtps_udp/RtpsUdpReceiveStrategy.cpp
unnamed objects live until the end of the statement, unlike named
objects that live until the end of the scope
=> TransportReceiveStrategy: guard object must be named

.github/workflows/build_and_test.yml, tests/static_ci_tests.lst
The Static Compiler jobs were running out of disk space. As a result, I split the Compiler into 2 parts for the static builds. I also added the newer Compiler tests to `static_ci_tests.lst` so we should have more coverage than before.
Recently, we saw a timeout with one of the Static Compiler jobs, and decided to remove the timeouts from our workflow. The timeouts of individual tests are handled by their `run_test.pl` and we would like to run every test rather than cutting short.  This change was made possible because we removed the `check_test_results` workflow recently.
=> GitHub Actions: Split Compiler and Remove Timeouts

.github/workflows/build_and_test.yml
vcpkg installs Qt5 and its dependencies which wireshark needs
older vcpkg uses a bad download URL for PCRE
=> GitHub Actions: use a newer vcpkg

htmlproofer.sh
New pages will have invalid "Edit this page on GitHub" links until they are merged into the main repo's `gh-pages`.
=> Don't Check "Edit this page on GitHub" Links

dds/DCPS/transport/framework/TransportReceiveStrategy.cpp, dds/DCPS/transport/framework/TransportReceiveStrategy_T.h, dds/DCPS/transport/multicast/MulticastReceiveStrategy.cpp, dds/DCPS/transport/rtps_udp/RtpsUdpReceiveStrategy.cpp, dds/DCPS/transport/rtps_udp/RtpsUdpReceiveStrategy.h, dds/DCPS/transport/shmem/ShmemReceiveStrategy.cpp, dds/DCPS/transport/tcp/TcpReceiveStrategy.cpp, dds/DCPS/transport/udp/UdpReceiveStrategy.cpp
GCC 4.4 in particular needs a linkable symbol for these constants so we need it to live in a non-template translation unit.
=> Made previous TransportReceiveStrategy change compatible with older compilers

dds/DCPS/WriteDataContainer.cpp
Problem: It appears that sometimes data is removed from sent_data_ before remove_oldest_sample is able to remove it based on the contents of what can be removed from the writer.
Solution: This is probably a race condition of sorts, but when we detect it in the code it's probably not worth flagging as an error (with subsequent error messages and test failures).
=> Avoid Error Case For Sent Data In WriteDataContainer

dds/idl/v8_generator.cpp
Problem: The idl compiler's "scoped" method was updated to return a safer prefix, but the V8 generator which used it to check for builtin sequence types was not updated.
Solution: Update v8 generator's builtin sequence logic
=> Fix V8 Generator BuiltInSeq Check Logic

dds/DCPS/RTPS/Spdp.cpp
Problem: Recent code changes introduced dead code. Spdp's early return from processing messages from the relay when the relay isn't being used would never be called due to the way the boolean flags were defined.
Solution: differentiate between whether a message is from the known relay address and whether we can treat it as (validly, relay in use) from the relay.
=> Spdp 'from_relay' Coverity Fix (1510150)

dds/idl/v8_generator.cpp
Problem: V8 conversion code for wide strings allocate temporary buffers that don't include enough space for the terminating null character, causing writes into invalid memory.
Solution: Increase temporary buffer allocation by 1.
=> Fix V8 generator invalid write issue for wide strings

dds/DCPS/XTypes/DynamicData.cpp, dds/DCPS/XTypes/DynamicData.h, tests/DCPS/UnitTests/DynamicData/DynamicData.cpp
- Update `get_item_count` and `get_member_id_at_index` to handle omitted optional members in structures.
- Update `get_member_id_at_index` to handle member reordering in mutable structures.
- Update `get_value_from_union` to check for error conditions when reading union discriminator.
- Update `get_complex_value` to allow reading union discriminator into a `DynamicData` object.
=> Update get_member_id_at_index and get_complex_value in DynamicData

dds/idl/v8_generator.cpp
Problem: The v8_generator for opendds_idl neglects to use Nan in a number of places, causing build issues for other V8 versions.
Solution: Use Nan when possible to avoid version-lock
=> Improve Nan usage in V8 generator

tools/rtpsrelay/RelayAddressListener.cpp, tools/rtpsrelay/RelayPartitionsListener.cpp, tools/rtpsrelay/SpdpReplayListener.cpp
Problem
-------
The relay statistics for the RtpsRelay report the total publisher
count for various topics.  This is not useful for measuring cluster
connectivity.
Solution
--------
Report the current count.
=> RtpsRelay statistics contain total count for publishers

dds/DCPS/DataReaderImpl.cpp, dds/DCPS/DataReaderImpl.h, dds/DCPS/DataReaderImpl_T.h, dds/DCPS/DataWriterImpl_T.h, dds/DCPS/transport/framework/TransportClient.h, dds/DCPS/transport/framework/TransportRegistry.cpp, tests/DCPS/XTypes/Pub/XTypesPub.idl, tests/DCPS/XTypes/Pub/XTypesPublisher.cpp, tests/DCPS/XTypes/Sub/XTypesSubscriber.cpp, tests/DCPS/XTypes/run_test.pl, tests/DCPS/XTypes/tcp.ini
The previous PR for this option was here https://github.com/objectcomputing/OpenDDS/pull/3040
However, following discussion of the issue here:  https://github.com/objectcomputing/OpenDDS/issues/2946 , it was determined additional work was needed.
Rather than using a config option to determine encapsulation, it is now determined by the default of the transport (false for anything besides RTPS_UDP),
If the user has explicitly (not by default) selected XCDR/XCDR2 as their Data Representation QoS policy, it is enabled for that transport, regardless of the default. 
As a result of these changes, I made a couple updates to the XTypes test to ensure the `--tcp` option runs properly.
=> CDR Encapsulation option for non-rtps_udp transports: Follow up fixes

dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp, dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.h
The receive address may not be a valid locator since datagrams can be
sent from different addresses (other than those in the locator list).
This change makes it so that the receive address, without port number,
is used to find a matching locator.
=> Update use of receive address in RtpsUdpDataLink::accumulate_addresses

dds/DCPS/transport/framework/DataLink.cpp, dds/DCPS/transport/framework/DataLink.h, dds/DCPS/transport/framework/DataLink.inl, dds/DCPS/transport/framework/TransportSendStrategy.cpp, dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp, dds/DCPS/transport/tcp/TcpDataLink.cpp, dds/DCPS/transport/tcp/TcpDataLink.h, dds/DCPS/transport/tcp/TcpTransport.cpp, dds/DCPS/transport/tcp/TcpTransport.h, tests/DCPS/EntityLifecycleStress/publisher.cpp, tests/DCPS/EntityLifecycleStress/rtps_disc.ini, tests/DCPS/EntityLifecycleStress/subscriber.cpp, tests/dcps_tests.lst
RTPS Discovery is too slow to reliably discover in 2.5 seconds, even for small numbers of processes. Increase timeouts to actually exercise discovery, increase dcps tests to match tsan tests.
=> Increase EntityLifecycleStress Test Process Run Times and Coverage

tools/scripts/lint.pl
- Replaced all whitespace with a dot (`·`) in marked error output when color is enabled. This dot is used in other software to explicitly mark whitespace. This should make it less confusing if output hides this whitespace.
- Fixed ability to check files outside an OpenDDS repo. Remove unneeded `--ext-path` option.
- Check if directories are ignored by git to avoid unnecessary checks on the contents.
- Removed possibly confusing usage of both "color" and "colour".
- Rename `--files-only` to `--files-only-ouput` to be consistent with `--simple-output`. `--files-only` should still work though.
- Spelling and other minor fixes.
=> `lint.pl` Fixes

dds/DCPS/NetworkConfigMonitor.h, dds/DCPS/RTPS/GuidGenerator.h, dds/DCPS/RTPS/Spdp.h, dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.h, dds/InfoRepo/DCPSInfo_i.cpp
In Visual Studio (test with 2019, 2022) the names of the variables are confused and cannot be compiled. (`interface`, `small`)
=> Unable to compile due to variable name conflicts with some Windows API headers

dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp
It's possible for disassociate to be called when no locators exist, causing an unnecessary error condition. Instead, log the asymmetrical association behavior but allow the application to continue.
=> Remove Locators Assertion From RtpsUdpDatalink::disassociate

dds/DCPS/AddressCache.h, dds/DCPS/transport/rtps_udp/BundlingCacheKey.h, dds/DCPS/transport/rtps_udp/LocatorCacheKey.h, tests/unit-tests/dds/DCPS/AddressCache.cpp
Improvements based on profiling from centipede test environment. The bundling cache was having pretty significant slowdown copying keys when keys had large numbers of "to" guids.
Primary improvements are:
- AddressCache id_map_ (reverse map) now holds a vector of RcHandles to keys, keeping key-copying to a minimum when adding keys to the reverse map
- Precalculate hash value for bundling keys to avoid repeated lengthy calls to the hash function
=> Performance Improvements For AddressCache

dds/DCPS/RTPS/Spdp.cpp
Problem
-------
The check that ensures taht the source IP is in the locator list for
SPDP causes all dispose messages to be ignored because a dipose
message does not have a locator list.
Solution
--------
Only apply the check to data samples.
=> SPDP dispose messages are ignored

dds/DCPS/RTPS/Sedp.cpp, dds/DCPS/RTPS/Sedp.h
Problem: Occassionally, TSAN builds complain about a data race for use_xtypes_ in Sedp::init(). As an example, see https://github.com/objectcomputing/OpenDDS/runs/4512178391?check_suite_focus=true
Solution: Attempt to initialize variables early in the method, prior to triggering other threads, and then leave the values alone (and constant).
=> Fix SEDP Data Race

dds/DCPS/transport/rtps_udp/RtpsUdpSendStrategy.cpp
Problem: When send_bytes_i determines there are no viable addresses, it returns an error value, which suspends the send strategy and causes problems for subsequent sends.
Solution: If there are no valid addresses for the send, count the send as a success and return the full byte count.
=> Fix RtpsUdpSendStrategy::send_bytes_i Handling of Empty Address Set

tools/rtpsrelay/RtpsRelay.cpp
Problem
-------
When building infrastructure around the RtpsRelay, it is useful to
subscribe to individual relay instances.  One way is to use content
filtering, however, this is not supported on the publisher side for
RTPS and therefore will lead to many wasted messages.
Solution
--------
Partition the relay domain by the id of each instance.  Processes
interested in a specific relay instance can subscribe to that partition.
=> RtpsRelay topics are not partitioned

tests/DCPS/RtpsRelay/Smoke/.gitignore, tests/DCPS/RtpsRelay/Smoke/Smoke.mpc, tests/DCPS/RtpsRelay/Smoke/monitor.cpp, tests/DCPS/RtpsRelay/Smoke/monitor.ini, tests/DCPS/RtpsRelay/Smoke/publisher.cpp, tests/DCPS/RtpsRelay/Smoke/run_lease_duration_test.pl, tests/DCPS/RtpsRelay/Smoke/run_test.pl, tests/DCPS/RtpsRelay/Smoke/subscriber.cpp, tools/dds/rtpsrelaylib/Relay.idl, tools/rtpsrelay/Config.h, tools/rtpsrelay/GuidAddrSet.cpp, tools/rtpsrelay/GuidAddrSet.h, tools/rtpsrelay/ParticipantListener.cpp, tools/rtpsrelay/ParticipantListener.h, tools/rtpsrelay/ParticipantStatisticsReporter.h, tools/rtpsrelay/RelayParticipantStatusReporter.cpp, tools/rtpsrelay/RelayParticipantStatusReporter.h, tools/rtpsrelay/RtpsRelay.cpp
Problem
-------
The RtpsRelay does not expose the dynamic status of a client.  The
goal of exposing such information is to be able to determine if a
particular client is connected.  The desired status is:
1. Discovered - Client has completed discovery with the client.
2. Active - message received from client recently
3. Alive - not purged from relay handler
4. User data
Solution
--------
* Add a "Relay Participants" topic that has the desired status.  The
existence of an instance for a client says that it has been
discovered.
* Add a parameter `-InactivePeriod` to set the inactivity threshold.
=> RtpsRelay does not expose client status

dds/DCPS/DataReaderImpl.cpp
Problem
-------
Assume there are two writers on a topic using
`MANUAL_BY_TOPIC_LIVELINESS_QOS` and `assert_liveliness` and assume that
each instance belongs to a single writer.  If one writer goes away,
the instance state for the instances that it writes does not go to
`NOT_ALIVE_NO_WRITERS_INSTANCE_STATE` because the liveliness message
of the other writer prolong its lifetime.
Solution
--------
When applying a liveliness update to an instance, check that the
writer actually writes that instance.
=> Asserting liveliness prolongs lifetime of all instances

.github/workflows/build_and_test.yml
Until we resolve disk space issues for the Windows 2016 Server virtual environment runner, disable CMake tests on the larger (security) job in order to allow full test suite to run as normal.
=> Temporarily Disable CMake Tests For w16_x86_i0_sec Build

dds/DCPS/transport/framework/TransportCustomizedElement.cpp, dds/DCPS/transport/framework/TransportCustomizedElement.h, dds/DCPS/transport/framework/TransportQueueElement.h, dds/DCPS/transport/framework/TransportReassembly.cpp, dds/DCPS/transport/framework/TransportReassembly.h, dds/DCPS/transport/framework/TransportSendBuffer.cpp, dds/DCPS/transport/framework/TransportSendBuffer.h, dds/DCPS/transport/framework/TransportSendControlElement.h, dds/DCPS/transport/framework/TransportSendElement.h, dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp, dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.h, dds/DCPS/transport/rtps_udp/RtpsUdpReceiveStrategy.cpp
Problem: Fragment NACKing is non-optimal for a number of reasons:
- Heartbeats are sent for the sample before the final fragment has been sent, causing pre-emptive NACK_FRAGs
- Only one NACK_FRAG range is stored per sequence number, causing a delay in resends when multiple NACK_FRAGs have been sent between heartbeats
- NACK_FRAGs are being generated for fully "received" samples (i.e. unneeded)
Solution: Don't do those things.
=> Improve Fragment NACKing Behavior

dds/DCPS/DataReaderImpl.cpp
Problem: There's a race condition for resetting LivelinessChangedStatus *_count_change values in DataReaderImpl (as well as a data race for the internal object when releasing the lock).
Solution: Use the lock to copy status & reset values, pass the copy.
=> Fix LivelinessChangedStatus Count Values In DataReaderImpl

dds/DCPS/RemoveAssociationSweeper.h
Problem: RemoveAssociationSweeper tries to pre-calculate the last iterator, but on Windows this causes an iterator assertion when the set is empty (despite the fact it's never used).
Solution: Don't even proceed to making the calculation if the set is empty.
=> Fix Windows Iterator Assertion In RemoveAssociationSweeper

tests/DCPS/SetQosPartition/pubsub.cpp
Problem: Seeing intermittent failures caused by test not waiting for full disassociation before starting to write next set of samples.
Solution: Fix operation order issue.
=> Fix SetQosPartition Object Creation / Wait Order

tests/DCPS/TransientLocalMultiInstanceTest/DataReaderListener.cpp, tests/DCPS/TransientLocalMultiInstanceTest/DataReaderListener.h, tests/DCPS/TransientLocalMultiInstanceTest/publisher.cpp, tests/DCPS/TransientLocalMultiInstanceTest/subscriber.cpp
Problem: No thread synchronization mechanisms existed for the TransientLocalMultiInstance test. This caused data races in ThreadSanitizer reports.
Solution: Add a mutex to the DataReaderListener and use it.
=> Synchronization Fixes for TransientLocalMultiInstance Test

bin/PerlDDS/Run_Test.pm, dds/DCPS/DomainParticipantImpl.cpp, dds/DCPS/Service_Participant.cpp, tests/DCPS/DpShutdown/dpshutdown.cpp, tests/DCPS/DpShutdown/run_test.pl, tests/DCPS/FindTopic/run_test.pl, tests/DCPS/MultiTopic/run_test.pl, tests/DCPS/Thrasher/run_test.pl, tests/DCPS/ZeroCopyDataReaderListener/run_test.pl, tests/DCPS/sub_init_loop/run_test.pl, tests/dcps_tests.lst, tests/security/ConcurrentAuthLimit/run_test.pl
- DpShutdown Test
- Extend to cover shutdown and delete related stuff added in https://github.com/objectcomputing/OpenDDS/pull/3159
- Reformat to bring in line with the style guidelines
- Cleanup `run_test.pl`
- PerlDDS
- Remove unused `value_flag` and `get_value_flag`, add ability to get flag value using an optional argument to `flag`.
- Add support for `DCPSLogLevel`
- Put `-ORBLogFile` first to make sure debug level set and other messages are in the log file.
- Fix typos in log messages
=> Extend DpShutdown Test, PerlDDS Improvements

.github/workflows/build_and_test.yml, .github/workflows/lint.yml, .github/workflows/lint_build_and_test.pl, tests/auto_run_tests.pl, tests/cmake/ctest-to-auto-run-tests.py, tests/dcps_tests.lst
- `auto_run_tests.pl`:
- Two small parts of #2452: Automatically add  `-Config RTPS` and `-Config GH_ACTIONS` if running on GitHub Actions
- Automatically add an OS `-Config` value according to `$^O`.
- Try to fix issue with the CTest missing build config on Windows.
- `build_and_test.yml`:
- Add script to lint workflow that tries to determine when GHA C++ compiler problem matchers are needed.
- Added, removed, and moved problem matchers entries based on feedback from the script.
- Remove `-Config` options no longer needed because they are automatically added.
=> Various CI Fixes

dds/DCPS/MultiTopicDataReader_T.cpp, dds/DCPS/MultiTopicDataReader_T.h
The MultiTopic test is experiencing a few failures on the OpenDDS Scoreboard. Among these is one where an improperly joined sample in being inserted using `store_synthetic_data`. This happens if the order of received topics is done in such a way that all keys are known, but not all topics are received. A a topic causing cross join would then need to be received before the other remaining topic, leading to the failure.
Currently still need to resolve how to deal with the `ACE_GUARD` because it is attempting an empty `return` if uncommented.
=> MultiTopic Test Fix

dds/DCPS/RTPS/Sedp.cpp, dds/DCPS/RTPS/Sedp.h
Problem: We're currently copying the Reader and WriterAssociation objects around quite a bit, as well as the serialized type info during associations.
Solution: Make ReaderAssociationRecord and WriterAssociationRecord inherit from RcObject, only create them when necessary, and avoid extra copying when possible by assigning / serializing directly into the record objects (via const casts).
=> Reduce TransportLocatorSeq Copying in SEDP

bin/PerlDDS/Run_Test.pm, dds/DCPS/Service_Participant.cpp
Undoes a previous change in PerlDDS in https://github.com/objectcomputing/OpenDDS/pull/3270 and instead changes OpenDDS to process `-ORBLogFile` first to make sure as much logging as possible goes to the file.
=> Process Logging Options First

dds/DCPS/DataWriterImpl.cpp
Problem: TSAN Flagged an intermittent data race issue in LivelinessTest on [this PR build](https://github.com/objectcomputing/OpenDDS/runs/4928749930?check_suite_focus=true). It looks like we don't use the recursive mutex correctly for this small function.
Solution: Use the mutex.
=> Fix Data Race in DataWriterImpl::participant_liveliness_activity_after

dds/DCPS/RTPS/Sedp.cpp, dds/DCPS/RTPS/Sedp.h, dds/DCPS/RTPS/Spdp.cpp, dds/DCPS/RTPS/Spdp.h, dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp, dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.h, dds/DCPS/transport/rtps_udp/RtpsUdpReceiveStrategy.cpp, dds/DCPS/transport/rtps_udp/RtpsUdpReceiveStrategy.h, dds/DCPS/transport/rtps_udp/RtpsUdpTransport.cpp, dds/DCPS/transport/rtps_udp/RtpsUdpTransport.h
Problem
-------
Programs that exit normally will call the destructor for the
ICE::Agent singleton.  Later in the destruction sequence, the
singleton may be accessed again and re-created.  This leads to
problems since the newly created ICE::Agent cannot perform the desired
actions.
Solution
--------
Save a handle to the ICE::Agent instead of always going through the singleton.
=> ICE::Agent singleton accessed during shutdown

performance-tests/bench/dashboard_summarizer/main.cpp
Problem: The dashboard summary generator currently will match any scenario with the string "disco" as belonging to the "disco" scenario, and then the results for disco-relay and disco-repo get displayed incorrectly.
Solution: Match against the known string with a trailing underscore in order to avoid the same issue in the future.
=> [Bench Dashboard] Allow Scenario Name Prefix Overlapping

etc/tsan-suppr.txt, performance-tests/bench/worker/WorkerDataWriterListener.cpp
Fixing a data race for un-setting listener at the end of test execution.
=> [Bench] Minor TSAN fix for WorkerDataWriterListener::unset_listener

dds/DCPS/DataWriterImpl.cpp, dds/DCPS/DataWriterImpl.h, etc/tsan-suppr.txt
Problem: Local TSAN runs were complaining about data races surrounding DataWriterImpl's `get_max_sn()`.
Solution: Separate out SN handling granularity to use its own mutex.
=> TSAN Fixes for DataWriterImpl's Sequence Number Handling

dds/DCPS/TopicImpl.cpp, dds/DCPS/TopicImpl.h, etc/tsan-suppr.txt, tests/tsan_tests.lst
Problem: TSAN issues in TopicImpl surrounding inconsistent_topic_status_
Solution: Add mutex protection, make copies when required for safe access.
Also, expand TSAN coverage to include XTypes test
=> Inconsistent Topic TSAN Fix

dds/DCPS/ReactorTask.cpp
Problem
-------
ReactorTask catches exceptions, logs them, and throws them again.  The
stack may be lost so a stack trace does not show the source of the
exception.
Solution
--------
Don't catch the exception.
=> ReactorTask catches

dds/DCPS/RTPS/RtpsDiscovery.cpp, dds/DCPS/TimeDuration.h, dds/DCPS/TimeDuration.inl, tests/unit-tests/dds/DCPS/TimeDuration.cpp
Problem
-------
AuthResendPeriod is assumed to be in integer seconds.  Sub-second
durations are required.
Solution
--------
Allow AuthResendPeriod to be a decimal.
=> AuthResendPeriod is too granular

dds/DCPS/LinuxNetworkConfigMonitor.cpp, dds/DCPS/NetworkConfigModifier.cpp, dds/DCPS/NetworkConfigMonitor.cpp, dds/DCPS/NetworkConfigMonitor.h, dds/DCPS/RTPS/ICE/AgentImpl.cpp, dds/DCPS/RTPS/ICE/AgentImpl.h, dds/DCPS/RTPS/Spdp.cpp, dds/DCPS/RTPS/Spdp.h, dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp, dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.h
Problem: On machines with large numbers of network interfaces, holding an internal lock to iterate over the network interfaces and call add_listener is costly.
Solution: Make NetworkInterface inherit from RcObject and prefer the use of RcHandles to make copying lists of interfaces faster / safer, and then iterate over copies of the list rather than holding the lock.
=> Improve Mutex Contention in NetworkConfigMonitor

tests/security/attributes/run_test.pl
Problem
-------
The Partitions_Match and Partitions_Reordered scenarios of the
security attributes test are failing.  Root cause was a change in the
test script.
Solution
--------
Revert the changes.
=> Partitions_Match and Partitions_Reordered fail security attributes

tests/security/attributes/Writer.cpp, tests/security/attributes/subscriber.cpp
Problem: Using WaitSet waits with infinite durations are prone to "missed event" race conditions where the event happens between the initial check and the wait.
Solution: Prefer many shorter waits over a longer duration in order to always "eventually" catch any event missed from a race condition.
=> Avoid Infinite Duration WaitSet waits in Security Attributes Test

configure, docs/dependencies.md, examples/DCPS/ishapes/Circle.cpp, examples/DCPS/ishapes/Circle.hpp, examples/DCPS/ishapes/DDSShapeDynamics.hpp, examples/DCPS/ishapes/Shape.hpp, examples/DCPS/ishapes/ShapesDialog.cpp, examples/DCPS/ishapes/ShapesWidget.cpp, examples/DCPS/ishapes/ShapesWidget.hpp, examples/DCPS/ishapes/Square.cpp, examples/DCPS/ishapes/Square.hpp, examples/DCPS/ishapes/Triangle.cpp, examples/DCPS/ishapes/Triangle.hpp, examples/DCPS/ishapes/boost_or_cxx11.mpb, examples/DCPS/ishapes/ishapes.mpc
It was only used when building examples/DCPS/ishapes with old compilers
Since ishapes also requires Qt5 and is not configured by default, we
will assume a new enough C++ version
=> Remove boost as an optional dependency

configure
Prompted by a note in this
https://github.com/objectcomputing/OpenDDS/blob/c62aa01c8d97e41f498a3e4b6765531f3a59451e/docs/cmake.md#example-using-installed-opendds-unix-only
=> configure: Ensure `--prefix` is an Absolute Path

dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp
We don't have a TSAN test that covers it, but I think we want to unlock the reader / writer locks before calling into the link's queue_submessages function, since it has its own mutex to manage.
=> Minor Cleanup For Responsive Mode

dds/DCPS/RTPS/ParameterListConverter.cpp, dds/DCPS/RTPS/Sedp.cpp, dds/DCPS/SequenceIterator.h, dds/DCPS/Util.h, dds/DCPS/security/CryptoBuiltInImpl.cpp, dds/DCPS/transport/framework/TransportClient.cpp, dds/DCPS/transport/framework/TransportConfig.cpp, dds/DCPS/transport/framework/TransportStatistics.h, dds/DCPS/transport/rtps_udp/RtpsSampleHeader.cpp, dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp, dds/DCPS/transport/rtps_udp/RtpsUdpInst.cpp, dds/idl/marshal_generator.cpp, dds/idl/value_reader_generator.cpp, performance-tests/bench/test_controller/AllocationHelper.cpp, performance-tests/bench/test_controller/ScenarioManager.cpp
Expand `dds/DCPS/Util.h` helper utilities for managing TAO's sequence growth performance issues (reallocates for every "larger" length) and use them more consistently throughout the code to improve allocation performance.
=> Improve Sequence Growth Performance

tests/cmake/Messenger/CMakeLists.txt, tests/cmake/Messenger/Messenger_Space/CMakeLists.txt
The previous PR #3327 did not catch the Visual Studio 2010 on the scoreboard build machine. Digging further, it appears CMake has changed how it formats CMAKE_GENERATOR over time. As a result, we should switch to using a regex string of `Visual Studio 10.*`.
=> Patch: CMake: Block Messenger_Space test on VS2010

dds/DCPS/DataReaderImpl_T.h
Problem
-------
Allocations from `data_allocator_` in DataReaderImpl_T are
synchronized on the `sample_lock_`.  However, not all deallocations
are not synchronized.  For example, taking samples will place the
samples in a sequence and destroying the sequence may cause a
deallocation.
Solution
--------
Use a mutex in the relevant part of the allocator.
=> DataReaderImpl_T allocator is not thread safe

dds/DCPS/DataReaderImpl.cpp
Problem
-------
Setting the instance state may lead to invoking the listener.  To
allow the user to read samples, the sample lock is unlocked with a
reverse lock.  The reverse lock only works if the sample lock is
locked once.  (It is a recursive lock which is a problem in and of
itself.)  Some code paths that set the instance state lock the sample
lock multiple times so the reverse lock doesn't release the lock.
The problem is that the transport thread can be storing a sample and
then invoking the listener.  At this point the sample lock is not
locked.  Another thread, i.e., discovery or the service participant,
can then update the instance state due to liveliness.  This thread
will acquire and retain the sample lock when invoking the listener.
If the transport thread does a read or …
=> Sample lock is held too long

tests/unit-tests/dds/DCPS/NetworkAddress.cpp
Problem: NetworkAddress unit test is failing on windows builds because for IPv4 addresses, ACE_INET_Addr's 2-argmument constructor will set sockaddr_in.sin_zero bytes (reserved for system use) but ACE_INET_Addr's set_addr() does not copy them. So even if we wanted to copy / use them in NetworkAddress (doubtful), compatibility with set_addr() would still be a problem.
Solution: There are a number of ways to potentially resolve this, but given ACE_INET_Addr's current implementation of set_addr(), I would argue the best approach is to leave both ACE and NetworkAddress the way they are (NetworkAddress's primary benefit is being able to directly memcmp the entire structure and guarantee strict ordering... sin_zero bytes would break that guarantee), but to change the test to only test …
=> Tweak NetworkAddress Unit Test To Avoid set_addr() Issue

dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp
=> RtpsUdpDataLink: use ACE_INT16 as the NetworkAddress::get_type return type

bin/PerlDDS/Run_Test.pm, dds/DCPS/InfoRepoDiscovery/InfoRepoDiscovery.cpp, dds/DCPS/transport/framework/TransportRegistry.cpp, dds/DCPS/transport/framework/TransportRegistry.h, dds/DCPS/transport/multicast/MulticastLoader.cpp, dds/DCPS/transport/rtps_udp/RtpsUdpLoader.cpp, dds/DCPS/transport/shmem/ShmemLoader.cpp, dds/DCPS/transport/tcp/TcpLoader.cpp, dds/DCPS/transport/udp/UdpLoader.cpp
Problem
-------
A thread calling `create_inst` only waits if a load is pending.  For a
static build, there is no guarantee that the thread loading the
static libraries will have started the load.  Thus, `create_inst`
fails since it doesn't wait and then can't find the transport type.
Solution
--------
If desired, wait for the transport to be loaded by checking
`type_map_`.
=> TransportRegistry has load data race

dds/DCPS/DataReaderImpl.cpp, dds/DCPS/DataReaderImpl.h, dds/DCPS/DataReaderImpl_T.h, dds/DCPS/GroupRakeData.cpp, dds/DCPS/GroupRakeData.h, dds/DCPS/InstanceState.cpp, dds/DCPS/InstanceState.h, dds/DCPS/InstanceState.inl, dds/DCPS/RakeData.h, dds/DCPS/RakeResults_T.cpp, dds/DCPS/RakeResults_T.h, dds/DCPS/ReceivedDataElementList.cpp, dds/DCPS/ReceivedDataElementList.h, dds/DCPS/ReceivedDataElementList.inl, dds/DCPS/ReceivedDataStrategy.cpp, dds/DCPS/SubscriptionInstance.cpp, dds/DCPS/SubscriptionInstance.h, tests/DCPS/MockedTypeSupport/MyTypeSupportImpl.h
Problem: For large numbers of instances and instances, several lookups within DataReaderImpl_T are non-performant, opting to loop over the entire list of instances looking for appropriate samples, and then potentially looping over many samples to find matching samples.
Solution: Maintain separate lookup maps based on instance, view, and sample states, and keep them up to date as these values get updated.
=> Improve DataReader Lookup Speeds For Large Numbers of Instances

dds/DCPS/ReactorTask.cpp, dds/DCPS/ReactorTask.h, dds/DCPS/ReactorTask.inl, tests/transport/error_handling/main.cpp, tests/transport/rtps_reliability/rtps_reliability.cpp, tests/transport/simple/SimpleDataReader.cpp, tests/transport/simple/SimpleDataReader.h, tests/transport/simple/SimpleDataWriter.cpp, tests/transport/simple/SimpleDataWriter.h, tests/transport/simple/pub_main.cpp, tests/transport/simple/sub_main.cpp, tests/transport/spdp/spdp_transport.cpp, tests/tsan_tests.lst
Problem: "Early" access to ReactorTask's `interceptor` or `reactor_owner' members will result in use of incorrect values.
Solution: Delay accessor requests for these values until thread startup has been signaled.
=> Delay Access To ReactorTask Members Until Thread Is Started

tests/DCPS/TimeBasedFilter/main.cpp
The first sample is received after a delay in
safety profile builds. Discard the first sample
to avoid timing issues that cause test failures.
Update log messages.
=> Fix safety profile TimeBasedFilter test.

tests/DCPS/ConfigTransports/subscriber.cpp
Problem: The ConfigTransports Test's DataReaderListenerImpl class holds a reference to the program's options objects, but certain DDS entities might outlive these options objects.
Solution: Move the options objects further out in scope, so they outlive DDS entities.
=> ConfigTransports Test ASAN Fix

tests/DCPS/TransientLocalMultiInstanceTest/publisher.cpp, tests/DCPS/TransientLocalMultiInstanceTest/subscriber.cpp
Problem: TransientLocalMultiInstance Test will occassionally hang when the publisher exits before the subscriber processes have received all their data.
Solution: Use the publisher's DataReaderListeners (yes, you read that right) to see if the local datareaders have received their data. Then monitor both the current and total publication matches to see when all 4 total matches have been seen but only 2 remain (the 2 subscribers have exited). Then it's safe for the publisher to exit. The subscriber applications should exist as soon as they have their data.
=> Fix Intermittent Shutdown Order Issues In TransientLocalMultiInstance Test

quickstart/GettingStartedDocker.html
=> Quickstart/docker: users don't need to write rtps.ini

tools/scripts/gitrelease.pl
- Improvements to the step that creates the GitHub release:
- Add DevGuide to release files on Github.
- Try to make the step more robust so that a failure doesn't mean manually deleting the release on GitHub. If there is a failure, try to say when the release must be manually deleted.
- Add the proper MIME types for GitHub to use for the release files and error when missing MIME type for a file extension.
- I think micro releases should have started updating the website after https://github.com/objectcomputing/OpenDDS/pull/3099 so that the micro releases appear on the website, but this doesn't happen. This has been fixed.
- Mock Releases:
- Add `--mock-with-doxygen` to generate a real Doxygen instead of a fake one.
- Skip verify steps that don't have to apply to mock releases.
- Hide …
=> Release Script Fixes and Improvements

tests/DCPS/DpShutdown/dpshutdown.cpp
Problem
-------
DpShutdown test fails for t=tcp on static builds.
Solution
--------
Add missing include to register the transport.
=> DpShutdown test fails for t=tcp on static builds

.github/workflows/build_and_test.yml, dds/idl/marshal_generator.cpp, tests/DCPS/Compiler/idl_test1_lib/FooDef.idl
Fixes https://github.com/objectcomputing/OpenDDS/issues/3268. The check for a struct with just a octet sequence member added to support ROS didn't resolve the sequence base type. Fixed this and added a compiler test for this.
=> Fix #3268 opendds_idl Segfault

dds/DCPS/MulticastManager.cpp, dds/DCPS/RTPS/Spdp.cpp, dds/DCPS/ReactorTask.inl
Ubuntu 18 Thrasher Test SEGV:
```
(gdb) where
#0  0x00007fb157fa6f34 in ACE_Reactor::implementation (this=0x0) at /home/tsimpson/code/OpenDDS/ACE_wrappers/ace/Reactor.inl:126
#1  0x00007fb156600980 in ACE_Reactor::register_handler (this=0x0, io_handle=46, event_handler=0x7fb130009070, mask=1) at /home/tsimpson/code/OpenDDS/ACE_wrappers/ace/Reactor.cpp:347
#2  0x00007fb157220139 in OpenDDS::DCPS::MulticastManager::process (this=0x7fb130008ca8, samples=std::vector of length 4, capacity 4 = {...}, infos=std::vector of length 4, capacity 4 = {...}, 
multicast_interface="", reactor=0x0, event_handler=0x7fb130009070, multicast_group_address=..., multicast_socket=...) at /home/tsimpson/code/OpenDDS/dds/DCPS/MulticastManager.cpp:64
#3  0x00007fb157f9e859 in …
```
=> Protect Against Null Reactor In Spdp::SpdpTransport::on_data_available

tests/DCPS/DynamicTypes/Pub/XTypesDynamicPub.cpp, tests/DCPS/DynamicTypes/Recorder/XTypesDynamicRecorder.cpp
The DynamicTypes test was not providing debug statements for certain parts of the code. This makes it difficult to track issues from the provided logs. This PR is meant to help with that. Additionally this PR removes some unused code from the test.
=> Add Debug Statements to DynamicTypes Test

dds/DCPS/AssociationData.h, dds/DCPS/DataReaderImpl.cpp, dds/DCPS/DataWriterImpl.cpp, dds/DCPS/RTPS/Sedp.cpp, dds/DCPS/RTPS/Sedp.h, dds/DCPS/RTPS/Spdp.cpp, dds/DCPS/RTPS/Spdp.h, dds/DCPS/RecorderImpl.cpp, dds/DCPS/ReplayerImpl.cpp, dds/DCPS/StaticDiscovery.cpp, dds/DCPS/SubscriberImpl.cpp, dds/DCPS/transport/framework/TransportClient.cpp, dds/DCPS/transport/framework/TransportImpl.h, dds/DCPS/transport/framework/TransportInst.h, dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp, dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.h, dds/DCPS/transport/rtps_udp/RtpsUdpInst.cpp, dds/DCPS/transport/rtps_udp/RtpsUdpInst.h, dds/DCPS/transport/rtps_udp/RtpsUdpTransport.cpp, dds/DCPS/transport/rtps_udp/RtpsUdpTransport.h, dds/DdsDcpsInfoUtils.idl
Problem: For newly associated RTPS readers and writers, excess traffic may be generated until inbound traffic is received to determine a viable "last received" address. For readers and writers with many locators, the amount of redundant traffic can be significant.
Solution: When possible, use addresses / locators from discovery to "hint" at the last received address on association and cut down the amount of initially-generated traffic.
=> Last Received Address Hinting Using Discovery Info

.github/workflows/build_and_test.yml, NEWS.md, cmake/init.cmake, dds/DdsDcps.mpc
Follow up to https://github.com/objectcomputing/OpenDDS/pull/2740
Support `INSTALL_LIB` being used with `make install` to change the name of the `lib` directory. To make it possible for `find_package` to find the OpenDDS CMake module in this case, the installation destination for the CMake module was changed from `lib` to `share`.
=> Support INSTALL_LIB in CMake Module

dds/DCPS/RTPS/Spdp.cpp, dds/DCPS/ReactorInterceptor.cpp, dds/DCPS/ReactorInterceptor.h, dds/DCPS/ReactorTask.cpp, dds/DCPS/ReactorTask.h
Problem: ReactorInterceptor::execute_or_enqueue may currently wind up executing "unplanned" code if commands already exist in the command queue. As a result, any code that may even have a remote chance of calling execute_or_enqueue needs to release all held mutexes, or else the "unplanned" code may double-lock a held mutex.
Solution: Since this isn't really practical, one simple solution is to dis-allow "immediate" execution by the reactor thread when commands already exist in the command queue. This prevents running "unknown" code in-situ, and so hopefully the calling context knows enough about what will get called in order to release all mutexes which might cause deadlock.
=> Defer ReactorInterceptor Execution If Queue Is Non-Empty

.github/workflows/build_and_test.yml
After https://github.com/objectcomputing/OpenDDS/pull/3392 the script
can fail if it can't show some files. Removing it here because it wasn't
designed to work with installations.
=> Remove show_build_config.pl from GHA Job

.github/workflows/build_and_test.yml
OpenDDS's configure when given an already-configured ACE+TAO will not
edit the default.features.  We need default.features to have the expected
features in order to generate makefiles for specific tests later on.
This means that the generated ACE_TAO artifact is biased for how we're
going to use it in OpenDDS, but it's only used once so this should be fine.
=> GitHub Actions: default.features needed in ACE_TAO_u18_stat_qt_ws_sec

dds/DCPS/DataReaderImpl.h
Problem
-------
Allocations from rd_allocator_ in DataReaderImpl_T are synchronized on
the sample_lock_. However, not all deallocations are synchronized. For
example, taking samples will place the samples in a sequence and
destroying the sequence may cause a deallocation.
Solution
--------
Use a mutex in the relevant part of the allocator.
Note
----
This was the desired fix for #3335.
=> DataReaderImpl allocator is not thread safe

tools/inspect/README
The inspect tool was lacking a readme. I added on with the intent of quickly communicating the point of the tool, as well as provide usage instructions.
=> Add Inspect Tool README

dds/DCPS/JsonValueReader.h
Problem
-------
JsonValueReader can be used to load data.  The format of such an input
file should be a sequence of JSON Objects.  Currently, this doesn't
parse correctly as rapidjson expects there to be exactly one object in
the stream.
Solution
--------
Update the parse flags to stop after one object and not check for end
of document.
=> Json parsing requires "end of document"

dds/DCPS/StatusConditionImpl.cpp
Problem: Encountered the following issue while trying to expand WaitForAck Test
Solution: I believe the intent for ConditionImpl / StatusConditionImpl was to not hold the lock while calling into `WaitSet::signal()`, so I've scoped the lock in `StatusConditionImpl's::set_enabled_statuses()`
```
WARNING: ThreadSanitizer: lock-order-inversion (potential deadlock) (pid=17657)
Cycle in lock order graph: M727 (0x7b4800000308) => M1586 (0x7b40000021c8) => M727
Mutex M1586 acquired here while holding mutex M727 in main thread:
#0 pthread_mutex_lock <null> (publisher+0x44fdfe)
#1 ACE_OS::mutex_lock(pthread_mutex_t*) /home/tsimpson/code/OpenDDS/ACE_wrappers/ace/OS_NS_Thread.cpp:2078:3 (libACE.so+0x1a7f4a)
#2 ACE_OS::thread_mutex_lock(pthread_mutex_t*) …
```
=> Fix TSAN Issue in StatusConditionImpl

dds/DCPS/WaitSet.cpp, dds/DCPS/WaitSet.h, tests/unit-tests/dds/DCPS/WaitSet.cpp
Problem: WaitSet was using two distinct approaches to atomic operations, which allowed for a potential race condition when multiple threads tried to call WaitSet::wait() on the same WaitSet object (which is intended to be prohibited by the spec).
Solution: Remove use of std::atomic / ACE_Atomic_Op and place `waiting_` under the protection of the object's mutex. In addition, add a real unit test for WaitSet and include testing of the new functionality as part of the unit test.
=> Fix Potential WaitSet Concurrent Wait Issues, Add Unit Test

dds/idl/dds_generator.h, dds/idl/field_info.cpp, dds/idl/field_info.h, tests/DCPS/Compiler/anonymous_types/test.idl
Defining two anonymous `sequence<string>` members in the same struct causes a redefinition compile error in the type support. This happens because the anonymous type code relies on the pointer to the `AST_Decl` of the base type to tell if the type has already been used. The problem with that is apparently there can be multiple objects for string types.
This replaces the pointer with the classification of the container type and the classification and name of the base type.
=> Fix 2 Anon. `sequence<string>` in the same `struct`

NEWS.md, tools/scripts/release_notes/missing-news-prs.py
- One NEWS item is new and another one appears to be missing.
- Reversed missing-news-prs.py output as it appears to be going from
newest to oldest, when it should probably be the other way around.
Current order isn't going to be changed, as this isn't a big deal.
=> Update NEWS, Reverse missing-news-prs.py Output

dds/DCPS/DefaultNetworkConfigMonitor.h, dds/DCPS/LinuxNetworkConfigMonitor.cpp, dds/DCPS/NetworkConfigModifier.cpp, dds/DCPS/NetworkConfigModifier.h, dds/DCPS/NetworkConfigMonitor.cpp, dds/DCPS/NetworkConfigMonitor.h
Problem
-------
Recent changes to the NetworkConfigModifier break existing clients.
Solution
--------
Restore the old interface as much as possible.  The only remaining
incompatibility is that `add_address` now takes a flag indicating if
the interface can multicast.
Notes
-----
The `index` member of NetworkInterfaceAddress was removed.
Implementations must use names.
=> New NetworkConfigModifier interface breaks existing clients

dds/DCPS/RTPS/Sedp.h, dds/DCPS/RTPS/Spdp.cpp, dds/DCPS/StaticDiscovery.h
Problem: For local RTPS discovery using both ipv4 and ipv6, participant announcements received on different sockets may be processed slightly offset from one another. This causes troubles with the sequence counting reset method, since the sequence number is only ever compared to the last sequence number received and so it can bounce up and down.
Solution: Since we're considering these sequence counts to reset the whole discovered participant, only compare against the maximum sequence number received from that participant.
=> Modify SPDP Sequence Reset Counting To Track Max SN

dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp
Problem: When attached GUID sets (to_guids) are large, copying of MetaSubmessages is expensive and should be avoided if possible. The current code simply uses push_back to add a new MetaSubmessage to the result vector.
Solution: In some cases we know ahead of time a reasonable upper limit for the number of messages that will be added. In those cases, use reserve to pre-allocate an appropriate amount of space rather than relying on push_back.
=> Attempt To Use std::vector::reserve() To Avoid Copying Of MetaSubmessages

tests/DCPS/Thrasher/Publisher.cpp, tests/DCPS/Thrasher/thrasher_rtps.ini
Problem: On windows, for the very large Thrasher tests, SEDP connections are failing due the pending association timeout (60 seconds).
Solution: Increase SedpPassiveConnectDuration for RTPS Thrasher tests.
=> Windows Thrasher Test Cleanup

dds/DCPS/RTPS/Spdp.cpp
Problem: Shutdown is clearing the `tport_` member of spdp in the middle of process_participant_ice() because we're not guaranteeing mutual exclusion during / after checking shutdown flags.
Solution: Don't do that. Lock to check, and recheck when we release / reacquire the lock.
=> Lock SPDP During Shutdown Checks To Avoid NULL Transport SEGV in process_participant_ice()

tests/Utils/StatusMatching.h
Update StatusMatching wait logic to use infinite waits in order to gain confidence in WaitSet wait behaviors. If issues remain, this should make them more apparent, since the previous approach was meant to cover up issues with infinite waits.
=> Use Infinite Waits In StatusMatching

dds/DCPS/DomainParticipantImpl.cpp
Problem: There is no mutual exclusion mechanism for bit_subscriber_ beyond what's built into the reference counted type itself, so access needs to be made carefully by first making copies and then checking the value, otherwise one thread might reset the reference (shutdown) while another is trying to use it (e.g. in ownership_manager()) which can (and does) lead to a SEGV.
Solution: Update methods which use bit_subscriber_ to make short-lived copies for the sake of interaction to avoid race conditions.
=> Improve Access Behavior Surrounding DomainParticipantImpl::bit_subscriber_

dds/DCPS/DataSampleElement.h, dds/DCPS/DataSampleElement.inl, dds/DCPS/DataWriterImpl.cpp, dds/DCPS/WriteDataContainer.cpp, dds/DCPS/WriteDataContainer.h, dds/DCPS/transport/framework/TransportQueueElement.inl, tests/DCPS/ContentFilteredTopic/ContentFilteredTopicTest.cpp, tests/DCPS/ManualAssertLiveliness/Writer.cpp, tests/DCPS/WaitForAck/rtps.ini, tests/DCPS/WaitForAckRace/.gitignore, tests/DCPS/WaitForAckRace/WaitForAckRace.mpc, tests/DCPS/WaitForAckRace/publisher.cpp, tests/DCPS/WaitForAckRace/rtps.ini, tests/DCPS/WaitForAckRace/rtps_disc.ini, tests/DCPS/WaitForAckRace/rtps_disc_tcp.ini, tests/DCPS/WaitForAckRace/run_test.pl, tests/DCPS/WaitForAckRace/subscriber.cpp, tests/dcps_tests.lst, tests/tsan_tests.lst
Problem: Previous `wait_for_acknowledgments` behavior was poorly defined, since any acknowledgment would be applied universally across all readers.
Solution: In general, wait_for_acknowledgments should delay until every currently associated reader has acknowledged the current sequence number at the time of the call to wait_for_acknowledgments.
=> Test & Fixes For Durable WaitForAck

dds/DCPS/JsonValueWriter.h, dds/DCPS/Observer.cpp, dds/DCPS/RTPS/Logging.cpp, dds/DCPS/ValueWriter.h, dds/DCPS/XTypes/MemberDescriptor.h, dds/idl/value_writer_generator.cpp, tests/unit-tests/dds/DCPS/JsonValueWriter.cpp
Problem
-------
ValueWriter implementations may treat members that are keys
differently.  As a concrete example, consider a ValueWriter that
prepares a SQL INSERT statement for a received sample.  Most likely,
this will be an UPSERT which often requires a list of keys and a list
of non-keys.
Solution
--------
Change `begin_struct_member` to take an XTypes::MemberDescriptor which
contains the member name and a bool for key status.  This PR only sets
these two members.
=> key information not passed to `begin_struct_member`

tests/cmake/install/CMakeLists.txt
A warning added in CMake 3.23 warns when there's an unused argument to CMake. This is the case here where this argument is supposed to be a list being passed to a child CMake command. It's getting interpreted as a separate argument instead. The solution is, apparently, to replace it with this generator expression.
=> Fix One of the Install Test Configure Commands

dds/DCPS/ConditionImpl.cpp
Problem: Code was accessing protected data structure without mutex.
Solution: Don't do that. Just use the local copy.
=> Fix TSAN Issue In ConditionImpl.cpp

tests/DCPS/WaitForAckRace/publisher.cpp
Problem: Coverity doesn't like that WaitForAckRace's publisher is using an atoi from a command line variable as a loop boundary.
Solution: Add additional bounds checking so Coverity can sleep at night knowing no fewer than 1 and no more than 99 readers can be specified.
=> Fix Coverity Issue In WaitForAckRace Test

tests/DCPS/Thrasher/DataReaderListenerImpl.cpp, tests/DCPS/Thrasher/DataReaderListenerImpl.h, tests/DCPS/Thrasher/ProgressIndicator.cpp, tests/DCPS/Thrasher/ProgressIndicator.h, tests/DCPS/Thrasher/Publisher.cpp, tests/DCPS/Thrasher/Subscriber.cpp, tests/DCPS/Thrasher/Subscriber.h, tests/DCPS/Thrasher/thrasher_rtps.ini, tests/dcps_tests.lst
This PR expands some of the test coverage for Thrasher to more builds and makes the test able to run (with different assumptions) under the no ownership profile builds. It also makes the test resilient against association timeout errors which are problematic when association times start to exceed 30 seconds (expected when the VM is overloaded).
=> More Thrasher Cleanup, CI Coverage Expansion

dds/DCPS/DataReaderImpl.cpp
Problem: Captured another core file from SEGV in ownership code.
Solution: Pretty sure this function just needs to hold the mutex to prevent other threads from corrupting / invalidating map access.
=> Fix Another Potential Ownership SEGV Issue

java/tests/messenger/publisher/run_test.pl, java/tests/messenger/run_test.pl, java/tests/messenger/subscriber/TestSubscriber.java, java/tests/messenger/subscriber/run_test.pl
Messenger has multiple java errors on the scoreboard.
The first is due to a timeout with pending data.
The second is due to the guard condition being declared after the datareader.
This PR fixes those errors.
=> Java Messenger Test Fixes

dds/DCPS/DataWriterImpl.cpp, dds/DCPS/WriteDataContainer.cpp, dds/DCPS/transport/framework/DataLink.inl, dds/DCPS/transport/tcp/TcpConnection.cpp, dds/DCPS/transport/tcp/TcpDataLink.cpp, dds/InfoRepo/DCPS_IR_Domain.cpp, dds/InfoRepo/DCPS_IR_Domain.h
Problem: Under load, DCPSInfoRepo leaks some buffers from BIT writes.
Solution: prevent reinsertion of dropped / delivered buffers during shutdown & after disposal to avoid leaks
=> Fix Shutdown Leak In DCPSInfoRepo Under Load

java/tests/messenger/publisher/run_test.pl, java/tests/messenger/run_test.pl, java/tests/messenger/subscriber/run_test.pl, tests/DCPS/Messenger/publisher.cpp
The previous PR for Java Messenger test fixes was enabling `DCPSPendingTimeout` within a conditional meaning it wasn't being used on the scoreboard. This lead to the errors still happening. This PR move it outside of the conditional.
Additionally, UDP on the normal messenger test failed at least once, due to missing every message. Prior to the rewrite, there were some microsleeps to spread out the writing of messages in an unreliable Data Writer. This PR adds that sleep back to the test.
=> Messenger Test: Java and UDP Fixes

tests/DCPS/ConfigTransports/DDSTEST.cpp
accessing TransportClient's internals requires locking
Based on asan test failure in #3483
=> ConfigTransports test: fixed undefined behavior

tests/DCPS/Ownership/DataReaderListener.cpp, tests/DCPS/Ownership/DataReaderListener.h
Problem: Different threads can call the Ownership DataReaderListener's on_data_available method, causing a TSAN complaint.
Solution: Add a mutex to the DataReaderListener to avoid TSAN complaints
=> TSAN Fix and Minor Cleanup for Ownership Test DataReaderListener

dds/DCPS/DataReaderImpl.cpp, dds/DCPS/DataReaderImpl.h, dds/DCPS/WriterInfo.cpp, dds/DCPS/WriterInfo.h
Problem: When using wait_for_acknowledgments to determine delivery of samples, publishing applications which exit immediately may cause a race condition in associated subscribing applications between the delivery of held historic samples in WriterInfo::historic_samples_ and the disassociation caused by the exiting publisher.
Solution: In order to honor the assumption that all data "acknowledged" by the transport is delivered to the subscribing application, the DCPS layer needs to ensure that held historic samples are also guaranteed to be delivered to the subscribing application.
=> Always Deliver Held Historic Samples

dds/DCPS/transport/framework/TransportClient.cpp
Problem: Some variables were duplicated and/or shadowed.
Solution: Use existing when possible, use different variable names to prevent shadowing.
=> Minor Cleanup In TransportClient::initiate_connect()

dds/DCPS/SporadicTask.h, dds/DCPS/transport/framework/TransportClient.h, tests/unit-tests/dds/DCPS/SporadicTask.cpp
Problem: The non-id version of ACE_Timer_Heap_T has linear performance over all registered timers. For small numbers of timers, it's not a big deal, but generally good to avoid when possible by using the id version, which does an O(log(n)) lookup.
Solution: Store timer id when it makes sense to do so for faster cancels.
=> Avoid non-id version of canceling reactor timers where possible

dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp, dds/DCPS/transport/rtps_udp/RtpsUdpInst.cpp
Problem
-------
In reflective mode, the RTPS UDP transport attempts to ignore nacks
that are pipelined due to latency.  This is done by sampling the
heartbeat count to determine a minimum for the count member of an
acknack.  In the current code, this limit was updated every time a new
enough acknack was received.
In this scheme, there is the opportunity to send a heartbeat
immediately after an acknack is received but before the nack
response.  This means the acknack that reflects this heartbeat would
be processed.  Most likely, it would be a duplicate of the acknack
that caused the nack response.
Solution
--------
Adjust the limit in the nack response.  This will cause the writer to
ignore acknacks until the reader has had an opportunity to receive any
requested data.
=> Duplicate samples are received in reflective mode

dds/DCPS/NetworkResource.cpp, tests/unit-tests/dds/DCPS/NetworkResource.cpp
Hostname is extracted from an address string passed to `choose_single_coherent_address` using `substr` function. The second argument passed to `substr` seems to be the end index of the substring but it should be the number of characters in the substring. The current code works as long as the open bracket is at index 0 (`openb` is 0), but doesn't work in other cases, like `"    [::1234:abcd]:8080"`. This updates the calls to `substr` to use character count as its second argument.
=> Update extracting hostname to handle more general cases

etc/tsan-suppr.txt
Shows up occasionally in CI non-rtps Thrasher tests.
=> Add TAO_IIOP_Acceptor::hostname() suppression for TSAN

dds/DCPS/transport/framework/TransportDebug.cpp, dds/DCPS/transport/framework/TransportDebug.h, dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp, tests/DCPS/Messenger/publisher.cpp
Add support for explicitly logging non-final RTPS Submessages:
- HEARTBEAT & ACKNACK without FinalFlag
- NACKFRAG (implicitly non-final because it expects a response)
When the "log_nonfinal_messages" flag is set on the transport_debug configuration object, logging will occur for these non-final messages on both the send and receive sides in order to be able to accurately gauge lost messages and resends.
Also cleans up several log messages to more closely follow logging guidelines and make consistent use of the idiom `[GUID] -> [GUID]` to mean "FROM the first GUID TO the second GUID."
=> Add Debug Logging For Non-Final RTPS Messages

dds/DCPS/RTPS/ICE/Ice.cpp, dds/DCPS/RTPS/ICE/Ice.h, dds/DCPS/RTPS/Spdp.cpp, dds/DCPS/transport/rtps_udp/RtpsUdpTransport.cpp, dds/OpenddsDcpsExt.idl
Problem
-------
Measuring the latency of a connection can provide valuable information
for debugging and tuning.
Solution
--------
Measure the latency and report it via ConnectionRecord.
=> Latency is not reported in ConnectionRecord

dds/DCPS/RTPS/RtpsCore.idl, dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp, dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.h
Problem: Heartbeat count remapping currently reorders within a given RTPS message, but not across all messages sent in a given transaction. This can lead to dropped heartbeats when "earlier" message counts then block later messages.
Solution: There is no guarantee of message delivery order, but in general we should assume earlier messages will be delivered first. This means reordering counts across messages is required to prevent "blocking" of later submessages. But we also need to make sure that the count order within a given message doesn't cause blocking, which is especially relevant when a message contains both undirected and directed heartbeats from the same writer. We can accomplish this by developing a translation between existing heartbeat count values, placing low count values in …
=> Updates for Heartbeat Count Mapping

dds/DCPS/RTPS/Spdp.cpp, dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp, dds/DCPS/transport/rtps_udp/RtpsUdpTransport.cpp
Problem
-------
Logs in high latency scenarios with responsive mode and heartbeat
reflection show a number of acks being dropped due to heartbeat
reflection.  Theses nacks are only generated when a heartbeat is
received.
Solution
--------
* Send a heartbeat when adding a reader or on end historic
samples (not both).
* Always send a preassociation acknack when adding a writer.
* Don't send a heartbeat in process_acknack.  The nack response is
sufficient.
* Don't remove a reader that expects data if fragments have been
requested.
* Clean up acknowledged fragments.
* Send a heartbeat when data is requested.
=> RTPS transport sends too many heartbeats

dds/DCPS/RTPS/ICE/Ice.cpp, dds/DCPS/RTPS/ICE/Ice.h, dds/DCPS/RTPS/Spdp.cpp, dds/DCPS/transport/rtps_udp/RtpsUdpTransport.cpp
Problem
-------
The ConnectionRecords for tracking the RtpsRelay write when there is
no change.  This was added to track changes in latency.
Solution
--------
Track when a new latency measurement is available.
=> ConnectionRecord writes when no change

tests/DCPS/StaticDiscovery/DataReaderListenerImpl.cpp, tests/DCPS/StaticDiscovery/DataReaderListenerImpl.h, tests/DCPS/StaticDiscovery/StaticDiscoveryTest.cpp, tests/DCPS/StaticDiscovery/TestMsg.idl
Problem
-------
The StaticDiscovery test uses publication handles to track writers.
Publication handles can get reused which confuses the tracking.
Solution
--------
Track by GUID.
=> StaticDiscovery test uses publication handles

tests/stress-tests/dds/DCPS/MultiTask.cpp, tests/stress-tests/dds/DCPS/SporadicTask.cpp
Problem: The MultiTask and SporadicTask stress tests were relying on precise system timing to capture and test execution state between "fast" timer executions (seemingly by accident). As a result, the test would occasionally fail when system timing didn't exactly match expectations.
Solution: Attempt to move 2nd-to-last test captures after the "fast" sections and adjust expected total counts accordingly.
=> Update Stress Test Timings

dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp, dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.h
Problem
-------
The required acknack count flag is not reset.  The logic for updating
the required acknack count can be simplified.
Solution
--------
* Reset the flag when adding the submessage.
* Any submessage with the flag should update the count.
=> Required acknack flag not reset

MPC/config/dcps_v8.mpb, dds/idl/v8_generator.cpp
Problem: V8 generation for Windows Does Not Correctly Handle (non-native) LongDouble generation.
Solution: V8 generation should use ACE's LongDouble types / typedefs and associated macros.
=> V8 Generation LongDouble Fixes And Minor Formatting Cleanup

tests/stress-tests/dds/DCPS/MultiTask.cpp, tests/stress-tests/dds/DCPS/SporadicTask.cpp, tests/stress-tests/dds/DCPS/StressTests.mpc, tests/stress-tests/dds/DCPS/TimingChecker.cpp, tests/stress-tests/dds/DCPS/TimingChecker.h
Problem: Ace Scheduled Timers on some machines cannot be trusted to fire within 5ms of their scheduled execution. As a result, stress tests which rely on this assumption will sometimes fail on these machines.
Solution: Perform an initial check for timer performance to determine wither stress tests should use tight or relaxed timing requirements.
=> Change Strictness of Stress Test Requirements Based on Machine Performance

dds/DCPS/AddressCache.h, dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp, dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.h
Two Problems:
- Unlocking of the bundling cache between lookups allows other threads to make modifications to entries, possibly altering entry hash values and, as a result, desired locations within the bundling address hash map. This seems to have been an issue for a long time.
- Hash values of new bundling cache entries were not calculated until _after_ the initial find / insertion into the hash map, meaning new entries would always be hashed / mapped incorrectly. It's surprising this didn't cause more issues, but seems to be behind the recent intermittent vector assertion issues on windows, since the returned value from an insert would sometimes be garbage (uninitialized).
Solution:
- Add the ability to more globally "scoped lock" the cache for bundling and then make sure we calculate / …
=> Fix Address Hashing and Cache Locking Issues For RTPS

dds/DCPS/RTPS/Sedp.cpp, dds/DCPS/transport/framework/TransportClient.cpp
Problem
-------
Suppose that a local participant is using the RTPS transport and that
a remote participant's lease duration is less than the passive connect
duration.  Suppose that discovery proceeds to the point where a reader
on the local is sending preassociation acknacks to a remote writer
when the writer terminates.
The local reader will continue to send preassociation acknacks because
the call to remove the remote writer never comes.
Solution
--------
Add a call to `stop_accepting_or_connecting` when a pending
association is removed.
=> Associations not removed when participant expires

dds/DCPS/transport/rtps_udp/BundlingCacheKey.h, dds/DCPS/transport/rtps_udp/LocatorCacheKey.h
It seems like older compilers don't like this?
=> Avoid pragma pack of RcObject

.github/workflows/build_and_test.yml, dds/DCPS/DomainParticipantImpl.cpp, dds/DCPS/NetworkResource.cpp, dds/DCPS/NetworkResource.h, docs/internal/dev_guidelines.rst
A couple of functions in `NetworkResource` are updated to check for hostnames that resolve to bogus IP addresses.
- `get_fully_qualified_hostname`: ignore hostnames that resolve to an IP address that is not found from the list of IP interface addresses.
- `choose_single_coherent_address` (string version): cache addresses returned from `getaddrinfo` for Windows. Ignore the port numbers of the cached addresses. The port numbers are set accordingly before returning a chosen address to the caller.
In addition, it enables Windows 2022 GitHub Actions test jobs as the above changes should fix the IP choosing issue on Windows 2022.
=> Update logic for choosing address and hostname in NetworkResource

dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp, dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.h, tests/DCPS/StaticDiscovery/DataReaderListenerImpl.cpp, tests/DCPS/StaticDiscovery/run_test.pl
Problem
-------
Due to lazy loading in the transport framework, StaticDiscovery
"simulates" heartbeats and acknacks to drive discovery.  That is,
StaticDiscovery declares local writer/remote reader and local
reader/remote writer pairs to the RtpsUdpDataLink.  The datalink sends
heartbeats and acknacks for local writers and readers.  When activity
from the remote is detected (which may be simulated), the association
is added and the local writer/reader is created.
When a writer or reader is deleted, the data link resumes this
behavior, i.e., it sends heartbeats for writers that don't exist and
acknacks for readers that don't exist.  These messages can causes the
association to be added again.  For tests that rely on the
publication/subscription match status, this presents a problem since …
=> StaticDiscovery shutdown looks like startup

tests/DCPS/EntityLifecycleStress/subscriber.cpp, tests/DCPS/WaitForAckRace/subscriber.cpp
A few issues:
- std::thread_this::sleep_* seem prone to hanging forever when used in this way. Perhaps related to the timing of the first sleep of the clean up thread and the main thread's call to join? In any case, there's no need to structure the test this way, since it forces a mandatory sleep time when cleanup may already be complete. A better approach is to do timed waits on a condition variable to allow for early waking. This is potentially a problem for both WaitForAckRace and EntityLifecycleStressTest (which it was copied from).
- Specific to WaitForAckRace:
- since we're dealing with end-of-transmission vs shutdown, we need to be using while in on_data_available to make sure we get every piece of data available.
- the logic in wait_valid_data() is incorrect, since all valid data …
=> Cleanup Test Wait Logic for WaitForAckRace and EntityLifecycleStressTest Tests

tools/scripts/gitrelease.pl, tools/scripts/mock_download_server.py
This requires https://metacpan.org/pod/Net::SFTP::Foreign and that the ssh server can be connected to just by using `ssh USER@HOST`. This should us to avoid various difficulties with FTP.
Also:
- Added a `--skip-github` option to skip any step that has to do with GitHub, whether this is the remote git operations or using the GitHub API. This replaces the `--ignore-github-token` option which did some of this, but could cause some weird issues.
- Added `mock_download_server.py` which, along with a SSH server on the local system, can be used to mock the SFTP upload operations. These were harder to mock before because both a HTTP server and a FTP server had to be set up. Now just a SSH server has to be setup and the script provides the HTTP server. It also can generate a fake existing …
=> Release Script now uses SFTP instead of FTP

.gitignore, README.md, _includes/foundation_minutes_sidebar.html
Fix Jeykell template that produces a malformed `<ul>` element when there
are minutes entries in the "Minutes Archive" Box for multiple years.
Also added instructions on how to run `htmlproofer.sh` locally because
they were not there before and I had re-figure out how to run it.
=> Fix Jekyll Template Issue from #3551

tests/DCPS/DynamicTypes/run_test.pl
- When one subtest fails, it appears the logs for all the subtests are
dumped. This is fixed by using a separate TestFramework for each
subtest.
- Using `!=` to compare string instead of `ne` caused 8 out of the 20
subtests to be skipped.
These changes also appear to have the side effect of fixing an issue the
test has on the scoreboard, but I'm still investigating that.
=> Fix Issues with DynamicTypes run_test.pl

.github/workflows/build_and_test.yml, tools/scripts/autobuild_brief_html_to_text.pl
When autobuild's brief output contains stack trace reports of failed tests (https://github.com/DOCGroup/autobuild/pull/68), `autobuild_brief_html_to_text.pl` script just needs to convert it to text form and print it out.
=> Revert autobuild_brief_html_to_text.pl to only read autobuild's brief output

dds/DCPS/AddressCache.h, dds/DCPS/NetworkAddress.h, dds/DCPS/transport/rtps_udp/BundlingCacheKey.h, dds/DCPS/transport/rtps_udp/LocatorCacheKey.h, dds/DCPS/transport/rtps_udp/MetaSubmessage.h, dds/DCPS/transport/rtps_udp/RoutedGuidPair.h, dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp, dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.h, tests/unit-tests/dds/DCPS/AddressCache.cpp
Remove addr_guids from BundlingCacheKey to improve bundling cache lookup performance and work around for Static Discovery. This allows for AddressCache Key simplification and removes the need for keys to inherit from RcObject. Additionally, this PR combines the three separate bundling vector structures (submessages, sizes, addresses) into a single structure to reduce total number of allocations and improve code clarity.
=> Remove addr_guids from BundlingCacheKey for Performance

tests/DCPS/StaticDiscovery/DataReaderListenerImpl.cpp, tests/DCPS/StaticDiscovery/DataReaderListenerImpl.h, tests/DCPS/StaticDiscovery/StaticDiscoveryTest.cpp, tests/dcps_tests.lst
Problem
-------
Tests on Windows buildfarm VMs show that the StaticDiscovery mpmrmw
configuration may be generating too much load.
Solution
--------
Use a smaller configuration.
=> StaticDiscovery mpmrmw generates too much load

dds/DCPS/transport/framework/TransportDebug.h
To match documentation being added to the devguide.
=> Document `transport_debug` Category Names

tests/DCPS/XTypes/XTypes.mpc
IDL_Files need to be listed explicitly because two projects share the
directory.  If this is left defaulted, all *.idl files that exist at
the time projects are generated are included.  This leads to different
projects depending on when they are generated - before or after a
build is run.
=> Updated the XTypes test's mpc file

dds/DCPS/DataReaderImpl.cpp, dds/DCPS/DataReaderImpl_T.h, dds/DCPS/SubscriberImpl.cpp, tools/rtpsrelay/ParticipantListener.cpp, tools/rtpsrelay/PublicationListener.cpp, tools/rtpsrelay/SubscriptionListener.cpp
Problem
-------
Invocation of listeners for builtin topics is asynchronous.  Before,
invoking the listener, it checks for the DATA_AVAILABLE_STATUS flag
and then resets it after the listener is invoked.  This creates a race
condition where a new sample could be inserted before the listener
completes.  At that point, the status is incorrect and the listener
will not be called.
Solution
--------
Clear the status flag before invoking the listener.
=> Status flag race leads to missing listener invocation

dds/DCPS/security/CryptoBuiltInImpl.cpp, dds/DCPS/transport/rtps_udp/RtpsUdpSendStrategy.cpp, dds/DCPS/transport/rtps_udp/RtpsUdpSendStrategy.h
Problem
-------
The RtpsUdpSendStrategy sporadically reports an error when encoding a
submessage.  The submessage kind is a heartbeat so it must be a
writer.  Review of the code shows that it is probably the volatile
writer.
Solution
--------
Improve the logging to confirm it is the volatile writer and narrow
down the root cause.  The two possible causes are:
1. Sending to `GUID_UNKNOWN` which is a bug in the RtpsUdpDataLink.
2. No crypto handle for the remote datareader.  This could be caused
by a race condition where the heartbeat (presumably caused by
association) is sent before the handle is in place.
Also, improve the atomicity in the Crypto plugin.
=> RtpsUdpSendStrategy sporadically reports failure to encode submessage

dds/DCPS/RTPS/Sedp.cpp
Problem
-------
Removing crypto handles before disassociating means that the transport
could be trying to send but not get a handle.  This results in "failed
to encrypt" errors.
Solution
--------
Disassociate before removing the crypto handles.
=> SEDP removes crypto handles before dissassociating

configure, dds/DCPS/TimeDuration.inl, dds/DCPS/debug.cpp, dds/DCPS/debug.h, dds/DCPS/transport/framework/TransportDebug.cpp, tests/DCPS/BuiltInTopicTest/.gitignore, tests/DCPS/Ownership/publisher.cpp, tests/DCPS/XTypes/.gitignore
We're currently not taking advantage of all the checks that AddressSanitizer can make. This PR updates our AddressSanitizer builds to do additional checks including stack use after return and initialization order checking, as well as a few fixes for issues discovered.
One of the issues discovered exists in ACE static member initialization, so this PR will also need [that fix](https://github.com/DOCGroup/ACE_TAO/pull/1879) in order to successfully pass all tests.
=> Implement More Aggressive ASAN Options

MPC/config/optional_rtps_relay_lib.mpb, configure, tests/DCPS/Observer/TestObserver.cpp, tests/DCPS/common/ConnectionRecordLogger.cpp
Building the (admittedly odd) combination of safety profile + RapidJSON yields some compile errors surrounding the availability of `OpenDDS::DCPS::to_json()`. This PR should fix those build errors by checking for both RapidJSON availability as well as the lack of a safety profile build.
=> Fix Edge-Case Build Errors For RapidJson + SafetyProfile

FACE/Sequence.h, tests/DCPS/Compiler/idl_test1_lib/FooDef.idl, tests/FACE/Compiler/idl_test1_main/main.cpp
As an extension to the language mapping spec, these sequences have
always attempted to support binary == and != operators.  However, the
implementation wasn't correct for certain types of sequences where
directly comparing elements resulted in unwanted array-to-pointer
decay or comparison of strings by memory address instead of by contents.
This should resolve remaining warnings from GCC 12.
=> Sequences in FACE mapping: support == for any type

dds/DCPS/ThreadPool.cpp, dds/DCPS/ThreadPool.h
Problem: Safety Profile Does Not Allow For pthread_join (ACE_OS::thr_join returns -1 (Not Supported)).
Solution: Switch from Barrier to Condition + Count. Add additional counter for exited threads and use condition for both startup and shutdown (when join is not available) of thread pool.
=> ThreadPool Updates To Accommodate SafetyProfile

dds/DCPS/DataWriterImpl.cpp, dds/DCPS/DataWriterImpl.h
Problem: TSAN builds intermittently complain about a data race in DataWriterImpl::add_association when checking / assigning publication_id_.
Solution: This check / set should lock the mutex.
=> Fix TSAN Race Around DataWriterImpl's publication_id_

tools/rtpsrelay/RelayParticipantStatusReporter.cpp
Problem
-------
Changes in the active/alive status of a relay participant always show
the original user data from discovery.  Changes in user data are
written out correctly, but not cached for subsequent writes when the
active/alive status changes.
Solution
--------
Save the user data for subsequent writes.
=> RelayParticipantStatus reverts to original user data

dds/DCPS/MulticastManager.cpp, dds/DCPS/RTPS/Spdp.cpp
Problem
-------
The MulticastManager complains about an unexpected unregister.  These
can occur as part of a legitimate shutdown.
Solution
--------
Handle the unregister.
=> MulticastManager warns about unexpected unregister

dds/DCPS/Service_Participant.cpp, dds/DCPS/Service_Participant.h, dds/DCPS/Service_Participant.inl
Problem: The TSAN build intermittently complains about unprotected access to Service_Participant::shut_down_.
Solution: Use protected access to it.
=> Fix TSAN Issue Surrounding Service_Participant::shut_down_

dds/DCPS/RTPS/Spdp.cpp
Problem
-------
Tests that create and destroy participants very quickly sometimes
block.  The root cause is that the registration of handlers is
asychronous.  The bad sequence is that the unregistration of handlers
happens before the registration.  Registering the handler increases
the reference count of the SpdpTransport which blocks shutdown.
In this case, SPDP is registering the multicast handler.  The bad
sequence is:
1. Create transport.
2. Call shutdown.  Remove handlers complete.
3. `on_data_available` called and multicast handlers registered.
Solution
--------
Do not register the handlers if shutdown has started.
Reference
---------
PR #3608
=> SPDP refuses to shutdown

tools/scripts/unit_test_coverage.sh
Problem
-------
Processing all of the gcda files for a unit takes too long.
Solution
--------
Compute a baseline for gcda files and remove gcda files that don't
change when a unit is tested.
=> Intentional unit testing coverage is too slow

dds/DCPS/RTPS/Sedp.cpp, dds/DCPS/RTPS/Spdp.cpp, dds/DCPS/RTPS/Spdp.h, dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp, dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.h
Problem: MonotonicTimePoint::now() was showing up fairly high in the profiling results for the Thrasher test.
Solution: Several of the places where it was being called can make reuse of the same time value.
=> Reduce / Reuse Calls to MonotonicTimePoint::now()

dds/DCPS/Service_Participant.cpp, dds/DCPS/Service_Participant.h, dds/DCPS/Service_Participant.inl
Problem: See https://github.com/objectcomputing/OpenDDS/runs/7439373375?check_suite_focus=true
Solution: Break out protection of shut_down_ flag to allow read access without waiting on factor lock.
=> Split Out Service_Participant Protection Of shut_down_ Flag To Avoid Deadlock

dds/DCPS/Message_Block_Ptr.h, dds/DCPS/transport/framework/TransportSendStrategy.cpp, dds/DCPS/transport/framework/TransportSendStrategy.h, dds/DCPS/transport/framework/TransportSendStrategy.inl, etc/tsan-suppr.txt
Problem: Currently we suppress lock-order-inversion errors from ACE_Message_Block::release_no_delete, which seem to be caused by ACE_Message_Block chains with differently ordered locking_strategy_ pointers being called from different threads. In general, this is a problem with the locking strategy design of ACE_Message_Block, since ACE_Message_Block tries to acquire the locks of the chain sequentially as it follows the chain during a release.
Solution: Rather than trying to fundamentally change the design of ACE, which might break other users, we can optimize the behavior of Message_Block_Deleter to address the assumptions of OpenDDS, which is namely that it's acceptable to de-chain and individually release ACE_Message_Blocks, so they can lock and unlock their individual locking_strategy_ …
=> TSAN Fix And Remove Suppression For Lock-Order-Invserion Issues In Message_Block_Deleter

dds/DCPS/DataReaderImpl.cpp
Problem: Currently, commands are always logged even when no actual change is made, and log messages are ambiguous in meaning (i.e. Does "Unscheduled sweeper" mean that it's been unscheduled or that it ran when we didn't expect?).
Solution: Improve clarify log messages, only log them when a change in status has happened.
=> Improve Logging For EndHistoricSamplesMissedSweeper Commands

support.md
one of the URLs had a leftover quotation mark attached to it from last time it lived in an HTML page; I removed it.
@mitza-oci
=> remove wayward quotation mark

.github/workflows/build_and_test.yml, tests/unit-tests/run_test.pl
Problem: They sometimes take too long under valgrind, and as somewhat 'stressful' tests they're not well suited to timely and predictable execution under valgrind.
Solution: Keep them in the unit tests, but don't run them under valgrind.
=> Remove 'RecursiveDispatch' Unit Tests From valgrind CI Test Job

dds/DCPS/transport/framework/TransportRegistry.cpp, dds/DCPS/transport/framework/TransportRegistry.h, dds/DCPS/transport/multicast/MulticastLoader.cpp, dds/DCPS/transport/rtps_udp/RtpsUdpLoader.cpp, dds/DCPS/transport/tcp/TcpLoader.cpp, dds/DCPS/transport/udp/UdpLoader.cpp
Also, return an error if we try to load a library via ACE and it fails.
=> TransportRegistry::create_inst removed wait param

.github/workflows/build_and_test.yml, tests/valgrind_tests.lst
This should hopefully allow easier expansion / changes of coverage in the future and give output failures consistent reporting (annotations / autobuild artifacts, etc).
=> Use Autobuild to Run valgrind Job Tests For Consistency

.github/workflows/build_and_test.yml, .github/workflows/build_u14_gcc4.Dockerfile, configure, tests/DCPS/DataRepresentation/run_test.pl, tests/ubsan_tests.lst, tests/unit-tests/dds/DCPS/MemoryPool.cpp
Unit tests only, for now. Will incorporate (prior?) fixes once I see what's actually failing in the unit tests. The only default check from 'undefined' group that has been disabled is the check for invalid enum values, since that will take some thought and design changes for OpenDDS's code generation (and may not be worth the benefits).
=> Add Initial UndefinedBehaviorSanitizer (UBSAN) Jobs

dds/DCPS/transport/framework/TransportRegistry.inl
Problem
-------
The thread that calls `remove_inst` on the TransportRegistry acquires
the lock and then calls `shutdown` on the instance.  This thread
eventually wants the reactor token to shutdown the reactor.
The reactor thread may be processing an event (has the reactor token)
that causes the clean up of SEDP.  This causes SEDP to call
`remove_config` on the TransportRegistry.  `remove_config` wants the
lock.
Solution
--------
Call `shutdown` on the transport inst without the lock.
=> SEDP deadlocks on shutdown

performance-tests/bench/example/config/scenario/ci_disco_relay.json, performance-tests/bench/example/config/scenario/ci_disco_relay_only.json, performance-tests/bench/example/config/scenario/ci_disco_repo.json, performance-tests/bench/example/config/worker/ci_disco_relay.json, performance-tests/bench/example/config/worker/ci_disco_relay_only.json, performance-tests/bench/example/config/worker/ci_disco_repo.json, performance-tests/bench/idl/Bench.idl, performance-tests/bench/report_parser/SummaryJsonDashboardFormatter.cpp, performance-tests/bench/test_controller/ScenarioManager.cpp, performance-tests/bench/test_controller/main.cpp, tests/dcps_tests.lst, tests/tsan_tests.lst
Problem: Bench worker failures (missing reports / report parse failures) are not being correctly reported in test controller report's total error count.
Solution: Add them. Also updating some scenarios for consistency and enabling a few more more scenarios in CI that seem stable.
=> [Bench] Report Worker Failures In Test Total Error Count

tests/DCPS/RtpsRelay/Smoke/.gitignore, tests/DCPS/RtpsRelay/Smoke/Smoke.mpc, tests/DCPS/RtpsRelay/Smoke/metachecker.cpp, tests/DCPS/RtpsRelay/Smoke/run_test.pl, tools/rtpsrelay/Config.h, tools/rtpsrelay/RelayHttpMetaDiscovery.cpp, tools/rtpsrelay/RelayHttpMetaDiscovery.h, tools/rtpsrelay/RtpsRelay.cpp
Problem
-------
Clients of an RtpsRelay must be configured with the SPDP, SEDP, and
DATA ports of an RtpsRelay instance.  This can be done statically or
dynamically.  In the dynamic scenario, it is convenient to use
TCP/HTTP load balancing to select an instance.  The instance can
return its ports in response to an HTTP request from the client.  For
load balancing, it is useful to include a health check endpoint that
is tied to the RtpsRelay admission control.
The HTTP server to provide this functionality can be implemented
external to the RtpsRelay.  However, deployments will be simplified by
including an embedded webserver in the RtpsRelay can serve the
configuration and answer the healthcheck.
Solution
--------
Embed a webserver in the RtpsRelay that can respond to configuration
and …
=> RtpsRelay doesn't have embedded webserver for meta discovery

.github/workflows/build_and_test.yml, .github/workflows/build_u14_gcc4.Dockerfile, configure, dds/DCPS/Serializer.h, dds/DCPS/Serializer.inl, dds/DCPS/XTypes/DynamicDataImpl.cpp
Problem: The UBSAN build changes caused issues with the gcc 4.4 (non-c++11) build on CI. The configure script has a bug which inadvertently turns on optimization for this build, which appears to repeatedly hit an internal compiler bug in gcc 4.4.
Solution: Fix the configure script to avoid `-O3` flag, add symlink to dockerfile to quiet erroneous "no g++" messages, and fix a few low-hanging compiler warnings.
=> Fix gcc 4.4 Docker Build

configure
The configure script is incorrectly handling the `--optimize` flag due to how `--sanitize` flags were being parsed.
=> Restore Correct Optimize Flag Behavior

tests/DCPS/Observer/subscriber.cpp
Problem: Allocating a WaitSet on the stack and associating it with any condition attached to longer-lived DDS entities introduces the possibility of a stack-use-after-return ASAN error. For example: https://github.com/objectcomputing/OpenDDS/runs/7705454393?check_suite_focus=true
Solution: Make WaitSets heap-allocated objects.
=> Avoid Stack Allocation Of WaitSet In Observer Test

dds/DCPS/DataReaderImpl.cpp, dds/DCPS/DataReaderImpl.h
Problem: Occasionally shutdown hangs while checking if historic samples have been delivered due to a lock order inversion issue.
Solution: Don't lock publication_handle_lock_ so broadly in high level methods, preferring finer grained protection of handles and status.
=> Cleanup DataReaderImpl Use of publication_handle_lock_

dds/DCPS/DataWriterImpl.cpp, dds/DCPS/DataWriterImpl_T.h, dds/DCPS/PublicationInstance.h, dds/DCPS/WriteDataContainer.cpp, dds/DCPS/WriteDataContainer.h, tests/DCPS/FooTest3_0/PubDriver.cpp, tools/rtpsrelay/RtpsRelay.cpp
Problem
-------
Entries in the maps of DataWriterImpl_t and WriteDataContainer
correspond to instances.  Unregistering an instance should remove from
these maps to prevent a memory leak.
Solution
--------
Remove from these maps when instances are unregistered.
=> DataWriter doesn't remove unregistered instances

dds/DdsDynamicDataSeq.idl, tools/scripts/analyze_operator_new.sh
Problem
-------
TAO sequences are being compiled for safety profile which is resulting
in a call to global operator new.  The issue was introduced with
recent changes to Dynamic Data support.
Solution
--------
Don't compile the sequence types in safety profile.
=> TAO sequences compiled for safety profile

performance-tests/bench/worker/Bench_Worker.mpc
Problem: Bench worker has a feature to force SEGV… for testing node_controller response to spawned process death. Ubuntu 22 / gcc 11 creates a warning for known / detected dereference of null pointers, causing an unhelpful warning for this process.
Solution: Turn off this warning for bench worker project
=> Disable -Wnonnull for bench worker

dds/DCPS/StaticDiscovery.cpp, dds/FACE/config/QosSettings.cpp, tests/unit-tests/dds/FACE/config/QosSettings.cpp
Problem
-------
Parsing comma-separated lists of partitions names assumes each
partition is less than 127 characters.  A partition name longer than
this will cause buffer overflow.
Solution
--------
Check the length of the partition name and log an error if it is too
long.
=> Parsing partition names can result in buffer overflow

dds/DCPS/transport/framework/TransportClient.cpp
`TransportClient::PendingAssoc::initiate_connect` forgot to remove an invalid `TransportImpl` in a loop that seems to be the cause of the ConfigTransports test's timeout issue.
=> Fix infinite loop when initiating connection

performance-tests/bench/worker/Bench_Worker.mpc
Problem: Breaks verbatim inherited from other projects / configs
Solution: Use the inheritance flag for verbatim.
=> Fix Bench Worker MPC verbatim clause

dds/DCPS/DomainParticipantImpl.cpp, dds/DCPS/RTPS/RtpsDiscovery.h, dds/DCPS/RTPS/Sedp.cpp, dds/DCPS/XTypes/TypeAssignability.cpp, dds/DCPS/XTypes/TypeLookupService.cpp, dds/DCPS/XTypes/TypeLookupService.h, dds/DCPS/XTypes/TypeObject.h, dds/idl/be_global.cpp, dds/idl/be_global.h, dds/idl/typeobject_generator.cpp, tests/DCPS/Compiler/XtypesExtensibility/.gitignore, tests/DCPS/Compiler/XtypesExtensibility/Compiler.mpc, tests/DCPS/Compiler/XtypesExtensibility/Extensibility.idl, tests/DCPS/Compiler/XtypesExtensibility/XtypesExtensibility.cpp, tests/DCPS/Compiler/XtypesExtensibility/ZeroEnum.idl, tests/DCPS/ZeroEnum/.gitignore, tests/DCPS/ZeroEnum/README.rst, tests/DCPS/ZeroEnum/ZeroEnum.idl, tests/DCPS/ZeroEnum/ZeroEnum.mpc, tests/DCPS/ZeroEnum/publisher.cpp, tests/DCPS/ZeroEnum/rtps.ini, tests/DCPS/ZeroEnum/run_test.pl, tests/DCPS/ZeroEnum/subscriber.cpp, tests/dcps_tests.lst, tests/unit-tests/dds/DCPS/XTypes/DynamicTypeImpl.cpp
Problem
-------
The IDL compiler does not set the extensibility for an enum.
Solution
--------
Set the extensibility in the IDL compiler.  For backwards
compatibility, 1) the extensibility will be set on received
TypeObjects and 2) the IDL compiler will have an option for not
setting the extensibility.
=> Enums do not have extensibility set

dds/idl/v8_generator.cpp
Problem: Node.js on windows is having issues with istringstream due to redefining symbols from the C++ runtime library without regard for how users may be linking their code.
Solution: Since we don't have much control over Node.js, just avoid using these symbols to preserve the ability to use DLLs, etc.
=> Remove stringstream usage from V8 generator

dds/DCPS/StaticDiscovery.cpp, dds/FACE/config/QosSettings.cpp, tests/unit-tests/dds/FACE/config/QosSettings.cpp
Problem
-------
Partition parsing uses a fixed size buffer.  All partitions except the
last one are subject to a length check based on the size of the
buffer.
Solution
--------
Dynamically allocate a buffer to not impose a length restriction.
=> Partition parsing is inconsistent

tests/DCPS/ConfigTransports/subscriber.cpp
- Problem:
In one test case of the ConfigTransports test, the subscriber unnecessarily waits for the second writer of the publisher which caused the subscriber to time out.
- Solution:
Remove waiting from the subscriber.
=> Revert a change to ConfigTransports test

tests/auto_run_tests.pl
So that it will be output in case changing to the build directory fails.
=> Fix CMake Header in auto_run_tests.pl

dds/DCPS/NetworkAddress.cpp, dds/DCPS/transport/rtps_udp/RtpsUdpTransport.cpp, tests/unit-tests/dds/DCPS/NetworkAddress.cpp
Problem: Some machines give back IPv4-mapped IPv6 addresses from opened sockets, which weren't being caught by checking for `is_any()` before adding to the list of locators.
Solution:
- Update is_any() to check for IPv4-mapped IPv6 "any" (zeros) address.
- Add Unit Tests For This
- Explicitly check IPV6 addresses returned from IPV6 sockets and avoid subtle conversion to mapped IPV4 addresses.
=> Prevent Use Of IPv4-mapped IPv6 'Any' Addresses In RTPS Locators

dds/DCPS/DataReaderImpl.cpp
Problem: DataReaderImpl::get_topic_id() does not check the validity of topic_servant_ before dereferencing, which can lead to a SEGV as it does here: https://github.com/objectcomputing/OpenDDS/runs/8118287779?check_suite_focus=true
Solution: Check before dereferencing, returning unknown if the check fails.
=> Add Check Before Dereferencing DataReaderImpl::topic_servant_

tests/DCPS/AddressLookup/main.cpp
Problem: WinSock2 was not being properly initialized for some (all?) windows builds, causing interface lookup errors.
Solution: Use ACE::init() and ACE::fini() (via ACE_TMAIN) for the AddressLookup test.
=> Use ACE::init() for AddressLookup test

.github/workflows/build_and_test.yml
- All u18 jobs moved to u20
- JDK version upgraded: build_u20_i0_xer0_js0_j17 uses Java 17 (hence j17), upgraded from 12
- Compiler versions upgraded: build_u18_clang5_i0w1_sec became build_u20_clang12_i0w1_sec and build_u18_gcc6_d0w1_cpp03 became build_u20_gcc9_d0w1_cpp03
=> GitHub Actions: Migrate Ubuntu 18 to 20

dds/DCPS/DataReaderImpl.cpp, dds/DCPS/DataReaderImpl.h, dds/monitor/DPMonitorImpl.cpp, dds/monitor/DRMonitorImpl.cpp, dds/monitor/DWMonitorImpl.cpp
Problem: Previously, `DRMonitorImpl` could cause a SEGV by calling into `DataReaderImpl::get_topic_id()` after `DataReaderImpl::cleanup()` had been called (`topic_servant_` would be dereferenced when `0`). PR #3714 fixed this SEGV, but didn't attempt to address any larger design issues.
Solution: Upon reviewing the issue in more detail, it seems better to cache the topic id GUID during initialization (during `DataReaderImpl::init()`, similar to what's done in `DataWriterImpl`) so that "late" calls to `get_topic_id()` will still get the correct GUID (and not the default `GUID_UNKNOWN`) for any interested reports.
=> Cleanup DataReaderImpl::get_topic_id() and MonitorLib Usage

.github/workflows/build_and_test.yml
The MacOS 12 builds in GHA mysteriously fail.  This immediate cause is that large binary files are corrupt.  The goal of this PR was to add a manifest to determine if the corruption occurs before or after archiving.  However, after adding the manifest, the problem has not occurred.
=> GitHub Actions: MacOS 12 builds

docs/internal/dev_guidelines.rst
Updates developer guidelines with a note about correctly initializing ACE for OpenDDS applications.
=> Add Notes On Application Initialization To Dev Guidelines

dds/idl/ts_generator.cpp
Problem: Currently, both FACE and V8 code generation require global static initialization of generated `TypeSupport` objects which register instances of their respective types with the `Registered_Data_Types` static instance map. The V8 code generation will be going away shortly (in favor of ValueReader/Writer mappings), but with the addition of DynamicData more applications will arise where the TypeSupport is not always fully known at compile time.
Solution: make the addition of static initializers for registration of `TypeSupport` objects a standard part of `TypeSupport` code generation.
=> Updates For TypeSupport Initializers

.github/workflows/docker_image.yml, DevGuideExamples/DCPS/Messenger/docker-compose-inforepo.yml, DevGuideExamples/DCPS/Messenger/docker-compose.yml, Dockerfile
Dockerfile:
* reduce changes to PATH
* do not build tests/DCPS/Messenger
* use Ubuntu 20.04 "focal" as the basis
Docker Compose files
* work with default PATH
GitHub Actions
* added a workflow that builds the container image and puts it in GitHub's repository
=> Docker updates

dds/DCPS/RTPS/Sedp.cpp, dds/DCPS/RTPS/Sedp.h, dds/DCPS/RTPS/Spdp.cpp, dds/DCPS/RTPS/Spdp.h, tests/security/attributes/run_test.pl, tests/security/security_tests.lst, tests/transport/spdp/spdp_transport.cpp
Problem
-------
A participant with incompatible security attributes is discovered and then removed without resetting the iterator.  The invalid iterator then causes a run-time error.
Solution
--------
* Refactor the code in SPDP to make participant removal more obvious.
* Add/enable security tests that test this scenario.
* Fix the `SC1_sec_on_bad_perm_2_failure` scenario to use an access-controlled topic.
=> Unauthenticated participant leads to invalid iterator

dds/DCPS/transport/rtps_udp/RtpsSendQueue.cpp, dds/DCPS/transport/rtps_udp/RtpsSendQueue.h, dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp, dds/DCPS/transport/rtps_udp/ThreadedRtpsSendQueue.cpp, dds/DCPS/transport/rtps_udp/ThreadedRtpsSendQueue.h, tests/unit-tests/dds/DCPS/transport/rtps_udp/RtpsSendQueue.cpp, tests/unit-tests/dds/DCPS/transport/rtps_udp/ThreadedRtpsSendQueue.cpp
Problem: RtpsSendQueue checks for redundant can allow significantly lower counts to be added to the send queue.
Solution: Tighten checks against redundant to only allow repetitions of the current count to be added, and add pairwise purge-upon-association to handle instances of multiple associations happening without a disassociate
=> Tighten RtpsSendQueue Count Checks

.github/workflows/build_and_test.yml, dds/DCPS/NetworkConfigModifier.cpp
Problem: IPv6 compile error in `NetworkConfigModifier.cpp` (macOS).
Solution: Modify IPv6 path similar to previous changes to IPv4 path.
=> Fix macOS IPv6 Build Issue

tests/DCPS/Thrasher/thrasher_rtps.ini
Problem
-------
The Thrasher test is designed to stress the system and often results in lost packets.  In some situations, the packet loss is enough to trigger a rediscovery of a remote participant based on sequence number checking.
Solution
--------
Set a very high threshold for the sequence number reset logic.
=> Thrasher fails on certains VMs

dds/DCPS/DomainParticipantImpl.cpp
Problem: When recorders and replayers aren't cleaned up before topics, there's a chance to hit assertions in TopicDetails regarding the number of remaining local publications / subscriptions.
Solution: Clean up recorders & replayers after normal publications / subscriptions.
=> Clean Up Recorders / Replayers Before Removing Topics

dds/DCPS/DcpsUpcalls.cpp, dds/DCPS/DcpsUpcalls.h, dds/DCPS/Definitions.h, dds/DCPS/Logging.cpp, dds/DCPS/Logging.h, dds/DCPS/RepoIdTypes.h, dds/DCPS/SequenceNumber.h, dds/DCPS/Service_Participant.inl, dds/DCPS/WriteDataContainer.cpp, dds/DCPS/WriteDataContainer.h, dds/DCPS/ZeroCopyAllocator_T.inl, dds/DCPS/debug.h, dds/DCPS/transport/framework/TransportDebug.h, dds/DCPS/transport/framework/TransportSendStrategy.inl
Problem: Several of these comments are inaccurate, either with regard to the order of closing namespaces or with the actual namespace names themselves.
Solution: Clean them up for clarity and consistency.
=> Clean Up End-of-Namespace Comments

cmake/OpenDDSConfig.cmake, cmake/dds_idl_sources.cmake, cmake/tao_idl_sources.cmake, docs/cmake.md
- Modified opendds_idl and tao_idl cmake files to build for VxWorks on Windows.
- Split library dependencies based on OPENDDS_XERCES3 and OPENDDS_SECURITY.
=> Building for VxWorks on Windows

.github/workflows/docker_image.yml
Problem
-------
The Docker image workflow does not build release tags.  This is useful for trying specific versions.
Solution
--------
Build release tags.
=> Docker image workflow does not build release tags

dds/DCPS/transport/shmem/ShmemDataLink.cpp, dds/DCPS/transport/tcp/TcpConnection.cpp
Follow up to https://github.com/objectcomputing/OpenDDS/pull/3549
- Fix Coverity CID 1525386 where it noticed the arguments names to `GuidPair` where flipped from the constructor parameters. This couldn't cause an issue because both insertion and removal where flipped the same way, but this should be fixed anyway.
- Commit removal of 2 lines in `ShmemDataLink::stop_i` that should have gone into the 3549, but I missed when staging the changes chunk by chunk in neovim.
- Also fix possible null RcHandle access during shutdown when using tcp that was found when using rr.
=> Fixes for shemem and tcp Null Rch

dds/DCPS/MessageTracker.cpp
Problem: When waiting on pending connections with the debug level set, timeouts can potentially cause deadlock by locking the same mutex twice.
Solution: Call the non-locking version of pending_messages() when we already hold the lock.
=> Fix Potential MessageTracker Deadlock In wait_messages_pending

DevGuideExamples/DCPS/Messenger/run_test.pl
Problem: The run_test.pl test runner script in DevGuideExamples/DCPS/Messenger doesn't currently use the PerlDDS::TestFramework, which means it doesn't gain the nice error reporting functionality we've added for stuck / hung / crashed processes.
Solution: Since we're running these in CI, we should update the test script (and add DCPSPendingTimeout while we're at it).
=> Convert DevGuideExamples Messenger Test Runner Script To Use PerlDDS::TestFramework

.github/workflows/build_and_test.yml
Problem: Two problems: We're no longer covering RTPS tests on a number of macOS builds due to using the wrong auto_run_test.pl, and so the only failure reported for IPv6 RTPS on macOS was the cmake tests, which were running as expected. Unfortunately, re-enabling RTPS tests by running the correct script showed the extent of the problem.
Solution: The world is not ready for IPv6 test coverage on macOS 12. De-prioritize getting IPv6 RTPS support on macOS 12 and revisit it later. For now, re-enable RTPS test coverage but remove IPv6 coverage from the builds.
=> Partially Revert IPv6 Test Coverage Changes To macOS 12 Build

dds/DCPS/NetworkAddress.cpp, dds/DCPS/NetworkAddress.h, tests/unit-tests/dds/DCPS/NetworkAddress.cpp
Problem: During consideration of recent algorithm changes for IPv6 multicast support, it was determined that NetworkAddress had no direct support for determining whether a destination address was multicast or not, meaning that it would require conversion of the address to something like ACE_INET_Addr in order to make this check, which is not create for performance and code clarity.
Solution: Add the check to NetworkAddress (w/ unit test).
=> Add NetworkAdddress::is_multicast

.github/workflows/build_and_test.yml, etc/problem_matchers/gcc_problem_matcher.json, etc/problem_matchers/msvc_problem_matcher.json
Problem: Warning annotations referencing deprecation of actions based on Node.js 12: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12
Solution: Bump to newer version of actions which are based on Node.js 16.
=> Bump gcc/msvc "Problem Matcher" Action Version

dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp
Restart code on removing part of the preassociation acknack counting by removing gather and accumulation call in responsive_mode_ condition
=> Restart code on removing part of the preassociation acknack counting

tools/scripts/autobuild_brief_html_to_text.pl
Puts test failure lines into expandable / collapsible groups for easier viewing in GitHub Actions console logs.
=> Add Result Grouping For GitHub Actions Test Results

dds/DCPS/NetworkConfigMonitor.cpp, dds/DCPS/NetworkConfigMonitor.h
Problem: NetworkConfigMonitor is stored by RcHandle in the Service_Participant, but it has derived classes and no virtual destructor. See also unit test failure [here](https://github.com/objectcomputing/OpenDDS/actions/runs/3292216384/jobs/5427929382) (ignore other failures, they're from tests that shouldn't run in TSAN).
Solution: Make the destructor virtual.
=> NetworkConfigMonitor Should Have Virtual Destructor

dds/DCPS/transport/framework/TransportSendStrategy.cpp, dds/DCPS/transport/framework/TransportSendStrategy.h
Problem: ACE_Message_Blocks allocated as part of transport headers don't have locking strategies and, as a result, can cause race conditions when touched by different threads. See TSAN report [here](https://github.com/objectcomputing/OpenDDS/actions/runs/3293279313/jobs/5430419411).
Solution: Add lock pool and separate allocator.
=> Locks For Header Blocks

dds/DCPS/transport/rtps_udp/RtpsUdpTransport.cpp, dds/DCPS/transport/rtps_udp/RtpsUdpTransport.h, tests/tsan_tests.lst
Problem: TSAN is reporting a data race based on different threads interacting with the `relay_stun_task_falloff_` object.
Solution: It's not particularly pretty, but wrap interactions with that object in an ACE_Thread_Mutex.
=> Enable disco_relay Bench Scenario in TSAN Coverage and Fix Issues

dds/DCPS/RTPS/MessageTypes.h
Moved conditional check for OPENDDS_SECURITY to be around all types migrated from SecurityHelpers.h
Fixed #ifdef and #endif lines to start at the beginning instead of following whitespace.
=> Realign conditional definition of types migrated from SecurityHelpers.h

performance-tests/bench/node_controller/main.cpp
Fix uninitialized timestamp. Probably not an issue for the program execution, since it's set elsewhere, but this should make Coverity happy.
=> [Bench] Fix Coverity Issue 1526719

performance-tests/bench/builder/BuilderProcess.cpp, performance-tests/bench/builder/ConfigSectionManager.cpp, performance-tests/bench/builder/ConfigSectionManager.h, performance-tests/bench/builder_idl/Builder.idl, performance-tests/bench/worker/main.cpp
Problem: Static builds can make use of the empty config name section for storing default transport instances, causing trouble when custom config sections are loaded without a configuration file name name.
Solution: Since this is an opt-in behavior for static builds (and bench is opting in since it doesn't know which transport libraries will be required), it makes the most sense to have bench avoid using an empty configuration name.
=> [Bench] Give Name To Loaded Configuration To Avoid Static Build Issues

.github/workflows/build_and_test.yml
Problem: The xerces-c version installed by brew increased by a patch version, so the path we were using for it is no longer valid.
Solution: Fix the path issue by using find to locate the correct version directory of xerces-c 3.x
=> Fix CI brew xerces-c root

dds/DCPS/RTPS/ParameterListConverter.cpp
Messages need to end in \n
As long as we're changing them, follow current guidelines
=> Updated log messages in ParameterListConverter.cpp

performance-tests/bench/example/config/scenario/ci-disco-relay.json, tools/dds/rtpsrelaylib/Relay.idl, tools/rtpsrelay/Config.h, tools/rtpsrelay/GuidAddrSet.cpp, tools/rtpsrelay/GuidAddrSet.h, tools/rtpsrelay/RelayStatisticsReporter.h, tools/rtpsrelay/RtpsRelay.cpp
Problem: Under periods of abnormally high levels of discovery traffic (such as during overall system redeployment), the RtpsRelay struggles to maintain an optimal rate of participant discovery, in effect worsening the experienced problem of slow discovery times.
Solution: Add an admission control queue in order to only allow a limited subset of the unknown remote participants to go through discovery at once. The admission control queue maximum size (total undergoing discovery at a time) and admittance duration (time considered sufficient for aiding discovery) are both configurable.
=> RtpsRelay Admission Control

tools/rtpsrelay/Config.h, tools/rtpsrelay/RtpsRelay.cpp
Problem: For some testing use cases, it's helpful to have the RtpsRelay end "naturally" as opposed to being killed.
Solution: For these use cases, add a "RunTime" parameter which will cause the RtpsRelay to end naturally after the desired time.
=> Add a set runtime to RtpsRelay and enforce clean shutdown

dds/DCPS/TimeDuration.inl
From Profiling RtpsRelay. Fewer temporary objects, fewer function calls.
=> Minor Performance Improvements for TimeDuration

dds/DCPS/transport/rtps_udp/RtpsUdpTransport.cpp
Problem: Inconsistent Locking around usage of `link_` within RtpsUdpTransport.
Solution: Make it consistent.
=> Consistent Use of link_lock_ to protect link_ within RtpsUdpTransport

tools/rtpsrelay/RelayStatisticsReporter.h
Fix a data race between RelayHandler threads and DDS Listener threads when touching the relay statistics.
=> Fix TSAN data race in RelayStatisticsReporter

dds/DCPS/DataReaderImpl.h, dds/DCPS/TopicDescriptionImpl.h
Problem: https://github.com/objectcomputing/OpenDDS/actions/runs/3388172713/jobs/5631246398
Solution: Ultimately, this may require a mutex, but this PR is first attempting to resolve the "test / deleted / access" race condition issue by first making a copy and testing / accessing the copy rather than the class member.
=> Attempt to address data race in DataReaderImpl::get_value_dispatcher()

configure
* `CROSS-COMPILE = 1` needs to be set in platform_macros.GNU to be in effect during the TAO build
* When CC, CXX, LD variables are set explicitly, they may need to resolve to the `target-compiler`
=> configure script updates for cross-compiling

tools/rtpsrelay/GuidAddrSet.cpp
Problem: Using invvalid array comparison for GuidPrefix_t objects in RtpsRelay.
Solution: Use equal_guid_prefixes helper function.
=> Fix Invalid Array Comparison

dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp
When NACK messages come in, for whatever reason, with requests for "future" sequence number values (outside the advertised heartbeat range), avoid sending gap submessages in response, since we may eventually want to send valid data for those sequence numbers.
=> Avoid Sending Gap Submessages For Future Sequence Numbers

dds/DCPS/security/AccessControl/Governance.cpp, dds/DCPS/security/AccessControl/LocalAccessCredentialData.cpp, dds/DCPS/security/AccessControl/LocalAccessCredentialData.h, dds/DCPS/security/AccessControl/Permissions.cpp, dds/DCPS/security/AccessControlBuiltInImpl.cpp, dds/DCPS/security/SSL/Certificate.h, dds/DCPS/security/SSL/Err.h, dds/DCPS/security/SSL/SignedDocument.cpp, dds/DCPS/security/SSL/SignedDocument.h, tests/unit-tests/dds/DCPS/security/SSL/SignedDocument.cpp
Problem
-------
Loading a governance file or permissions file signed by Bouncy Castle fails.  The root cause is the (lack of) MIME parsing.
Solution
--------
Use openssl to extract the signed content.
=> SignedDocument can't handle non-openssl documents

dds/DCPS/RTPS/RtpsDiscovery.cpp
This was from prior PR 3859, where local method was left in original location in addition to being copied to new file:  
https://github.com/objectcomputing/OpenDDS/pull/3859
=> Fix for new compiler warning.  

performance-tests/bench/example/config/worker/ci-disco-long.json, performance-tests/bench/example/config/worker/ci-disco-relay-only.json, performance-tests/bench/example/config/worker/ci-disco-relay.json, performance-tests/bench/example/config/worker/ci-disco-repo.json, performance-tests/bench/example/config/worker/ci-disco.json, performance-tests/bench/example/config/worker/ci-echo-frag_client.json, performance-tests/bench/example/config/worker/ci-echo-frag_server.json, performance-tests/bench/example/config/worker/ci-echo_client.json, performance-tests/bench/example/config/worker/ci-echo_server.json, performance-tests/bench/example/config/worker/ci-fan-frag-ws_client.json, performance-tests/bench/example/config/worker/ci-fan-frag-ws_server.json, performance-tests/bench/example/config/worker/ci-fan-frag_client.json, performance-tests/bench/example/config/worker/ci-fan-frag_server.json, performance-tests/bench/example/config/worker/ci-fan-ws_client.json, performance-tests/bench/example/config/worker/ci-fan-ws_server.json, performance-tests/bench/example/config/worker/ci-fan_client.json, performance-tests/bench/example/config/worker/ci-fan_server.json, performance-tests/bench/example/config/worker/ci-mixed_daemon.json, performance-tests/bench/example/config/worker/ci-mixed_master.json, performance-tests/bench/example/config/worker/ci-mixed_worker.json, performance-tests/bench/example/config/worker/script.json, performance-tests/bench/example/config/worker/selfish-echo_client.json, performance-tests/bench/example/config/worker/showtime-mixed_daemon.json, performance-tests/bench/example/config/worker/showtime-mixed_master.json, performance-tests/bench/example/config/worker/showtime-mixed_worker.json, performance-tests/bench/example/config/worker/simple-echo_client.json, performance-tests/bench/example/config/worker/simple-echo_server.json, performance-tests/bench/example/config/worker/simple-tags_control.json, performance-tests/bench/example/config/worker/simple-tags_processing.json, performance-tests/bench/example/config/worker/simple-tags_raw.json
Problem: The bench test scenarios should ideally run in their own unique partitions to avoid accidental interactions with other active bench scenarios configured in such a way that they are mutually discoverable. This is the intended purpose of the `test_controller`'s "bench partition suffix". However, this suffix is only applied to partitions that begin with the "bench_" prefix, and currently the only scenario worker config files using such a partition are the "mixed" scenarios. Ideally, these should be universally used by example and CI scenario worker configuration files in order to avoid any cross-talk during normal, CI, or scoreboard testing. Any scenarios that don't provide a "bench_" partition do so at their own peril (or if they are certain they really need empty partitions, for …
=> [Bench] Update Bench Example and CI Configs To Use Unique Partitions

performance-tests/bench/dashboard_summarizer/main.cpp, performance-tests/bench/example/config/scenario/ci-disco-long.json, performance-tests/bench/example/config/scenario/ci-disco-relay-only.json, performance-tests/bench/example/config/scenario/ci-disco-relay.json, performance-tests/bench/example/config/scenario/ci-disco-repo.json, performance-tests/bench/example/config/scenario/ci-disco.json, performance-tests/bench/example/config/scenario/ci-echo-frag.json, performance-tests/bench/example/config/scenario/ci-echo.json, performance-tests/bench/example/config/scenario/ci-fan-frag-ws.json, performance-tests/bench/example/config/scenario/ci-fan-frag.json, performance-tests/bench/example/config/scenario/ci-fan-ws.json, performance-tests/bench/example/config/scenario/ci-fan.json, performance-tests/bench/example/config/scenario/ci-mixed.json, performance-tests/bench/idl/Bench.idl, performance-tests/bench/report_parser/SummaryJsonDashboardFormatter.cpp, performance-tests/bench/run_test.pl, performance-tests/bench/test_controller/main.cpp
Problem: The [OpenDDS Performance Dashboard](https://github.com/OpenDDS/opendds-performance-dashboard) currently must attempt to deduce certain kinds of metadata about various bench test scenarios from output filenames. This makes it difficult to add new test scenarios and is prone to breakages when file names change.
Solution: Allow scenarios to specify both "test run" and "scenario" parameter metadata that will get passed through to the test result output, and then eventually through the report_parser and dashboard_summarizer for eventual consumption and use by the OpenDDS Performance Dashboard.
Disclaimer: Merging these changes will cause temporary incompatibilities with the existing performance dashboard, as the output format for the dashboard_summarizer has changed to …
=> [Bench] Add Scenario and Test Run Parameters For Use In Performance Dashboard

dds/DCPS/XTypes/DynamicDataAdapter.h, tests/security/CheckInstance/CheckInstance.cpp
Problem
-------
DynamicDataAdapter doesn't increment the reference count for the `type` attribute.  This goes against convention and leads to memory problems.
Solution
--------
Increment the reference count.
=> DynamicDataAdapter doesn't increase refcount

dds/DCPS/DispatchService.cpp, dds/DCPS/DispatchService.h
For the sake of BITs, have the DispatchService use TheServiceParticipant's ThreadStatusManager.
=> Update DispatchService To Use ServiceParticipant's ThreadStatusManager

tests/dcps_tests.lst
This is the same problem as in https://github.com/objectcomputing/OpenDDS/pull/3520
=> Skip TypeSupportPlugin When dlclose is Broken

dds/DCPS/RTPS/RtpsDiscovery.cpp, dds/DCPS/RTPS/RtpsDiscoveryConfig.cpp, dds/DCPS/RTPS/RtpsDiscoveryConfig.h, dds/DCPS/RTPS/Spdp.cpp
Add a flag to SPDP to request a random SPDP source (unicast) port number (when SpdpLocalAddress does not reqest a specific port) rather than attempting to use the RTPS specification's formula for "well known" unicast port numbers.
=> Add SpdpRequestRandomPort

bin/.gitignore, configure
This script uses the same `mwc.pl` arguments (minus the workspace file) that OpenDDS was configured with. This is helpful for cases where ACE/TAO was separately configured in a generic way. In this case the default features file doesn't get updated and each feature has to be passed if running `mwc.pl` manually. This script will contain the features as well as the `-type` and `-static` if needed.
=> Add a `opendds_mwc.pl` Wrapper Script

tools/rtpsrelay/RelayParticipantStatusReporter.cpp
Problem: RtpsRelay active_ts and alive_ts statistics are using MonotonicTimePoint for their timestamps. which are not ideal for comparison between processes / machines.
Solution: Use SystemTimePoint for these values.
=> Update RtpsRelay alive and active Timestamps To Use SystemTimePoint

.github/workflows/build_and_test.yml, configure
Problems:
- ACE_TAO handles placement of optimization compiler flags (`-O3` or `-O0`, etc) slightly differently between gcc and clang platforms.
- The configure script currently attempts to default the `optimize` option (and ACE macro) to `0` (off) if either:
- The user did not specify an optimization level on the command line
- OR the user specified a sanitize option on the command line (with the thought that the sanitizer compiler args (which get added to `CPP_FLAGS`) will eventually override any arguments generated from an `optimize` option/macro of `0`)
- Unfortunately, this assumption only works for gcc because the clang platform will wind up overriding any optimization level set in `CPP_FLAGS` with its own `-O0`.
- As a result, we're currently running our sanitizer CI builds (which …
=> Fix 'sanitize' optimization levels for clang builds

dds/DCPS/XTypes/DynamicTypeSupport.h
Error is `C2487: 'DDS::DynamicDataReader::read_next_sample' : member of dll interface class may not be declared with dll interface`
Newer MSVC doesn't have the same problem, seems to be a compiler bug
=> DynamicDataReaderImpl: work around an error on older MSVC versions

.github/workflows/lint.yml
Now that the `.python_version` missing file issue seems to have been fixed in v1.20.1 (and v1 tag updated), revert back to v1 tag for our lint workflow to keep up-to-date with newer versions.
=> Revert Lint Workflow Back To actions-setup-perl v1

.github/workflows/build_and_test.yml
Update run-vcpkg action from v7 to v10, which requires non-trivial changes including creation of a JSON configuration / manifest file and use of environment variables to control which triplets are installed.
=> Update run-vcpkg action to v10

dds/DCPS/DataReaderImpl_T.h, dds/DCPS/InstanceState.cpp, dds/DCPS/InstanceState.h, dds/DCPS/LinuxNetworkConfigMonitor.h, dds/DCPS/ReceivedDataElementList.cpp, dds/DCPS/ReceivedDataElementList.h, dds/DCPS/SubscriptionInstance.cpp, dds/DCPS/SubscriptionInstance.h
Problem: Many classes in the DCPS layer make use of raw pointers for objects which already inherit from RcObject. Particularly, SubscriptionInstance and InstanceState have pointers to DataReaderImpl. The preferred approach is to make use of WeakRcHandles when possible to take advantage of the safety / reliability that comes from reference counting.
Solution: Convert several of these classes over to use WeakRcHandles.
=> Misc Cleanup For Reference Counting Of DataReaders

dds/DCPS/transport/framework/TransportClient.cpp
Each `DataSampleElement` has pointer to a `DataSampleElement` that is next to be sent (`next_send_sample_`).  This pointer is mutable and is modified by the friend class `SendStateDataSampleList`.  When the `dequeue` and `dequeue_head` methods are called, the `next_send_sample_` pointer is set to null.
`TransportClient::send_i` takes a `SendStateDataSampleList` which contains a list of `DataSampleElement` pointers.  Inside this method, the first data sample is taken from the head of the send list and inside a while loop, the next element to be sent is read using the `get_next_send_sample()` method called on the current send sample.  In some situations, the next send sample could be null and would cause a crash the next time around the loop.  The simple solution is to change the condition …
=> Check for null pointer when sending a data sample

.github/workflows/ishapes.yml
- no need to set up env vars that are never used
- updated gcc-problem-matcher action dependency
- use Windows 2022 base image
- updated run-vcpkg action dependency
- updated vcpkg version used by run-vcpkg
=> GitHub Actions updates for ishapes demo

dds/DCPS/XTypes/DynamicDataReaderImpl.cpp, dds/DCPS/XTypes/DynamicDataReaderImpl.h
Some older compilers need to see this inlined
=> DynamicDataReaderImpl: inline dynamic_hook function

tests/dcps_tests.lst
Problem: Duplicate test names cause PerlACE to overwrite the configuration parameter lists and produce undesired / unexpected behaviors when running tests. The bench `ci-disco-long` test is currently duplicated for GitHub Actions ASAN builds and Win32 builds.
Solution: Add an extra, unused parameter
=> Avoid Duplicate Test Names In Test Lists

dds/DCPS/transport/framework/TransportClient.cpp, dds/DCPS/transport/framework/TransportInst.cpp, dds/DCPS/transport/framework/TransportInst.h, dds/DCPS/transport/rtps_udp/RtpsUdpInst.cpp
Problem
-------
`rtps_relay_address_change` deadlocks if it causes the impl to be created.
Solution
--------
Don't create the impl.
There is no downside here, that is, when the impl is created, it will have the correct configuration.
=> `rtps_relay_address_change` deadlocks

.github/workflows/build_and_test.yml
One of wireshark's dependencies in vcpkg was broken.
Fixed by vcpkg PR 28919
=> GitHub Actions: update vcpkg commit for wireshark

dds/DCPS/ConnectionRecords.h, dds/DCPS/DataReaderImpl.h, dds/DCPS/InternalDataReaderListener.h, dds/DCPS/JobQueue.h, dds/DCPS/RTPS/Spdp.h, dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.h, dds/DCPS/transport/rtps_udp/RtpsUdpReceiveStrategy.cpp, dds/DCPS/transport/rtps_udp/RtpsUdpReceiveStrategy.h, dds/DCPS/transport/rtps_udp/RtpsUdpTransport.cpp, dds/DCPS/transport/rtps_udp/RtpsUdpTransport.h
Problem
-------
ASAN reports a data race stemming from the use of the data link from the `relay_stun_task` in RtpsUdpTransport.
Solution
--------
Replace the existing mutex in `relay_stun_task` with the data link mutex.
=> RtpsUdpTransport has data race from `relay_stun_mutex_`

dds/DCPS/security/SSL/SignedDocument.cpp
Problem
-------
Assume a usage of DDS Security where the same CA is used for both permissions and identity.  The certificates issued to particpants allow them to sign documents.  Assume the participant generates a permissions file and then signs it.  Chain verification causes verification attempts to succeed since the signing certificate, i.e., the participant's certificate, can be chained back to the permission CA's certificate (which is also the identity CA).
This problem was identified in
https://github.com/ros2/sros2/issues/282.
Solution
--------
Implement the suggestion in https://github.com/ros2/sros2/issues/282. Specifically, use PKCS7_NOINTERN to not accept any signatures in the signed document.  This, in turn, requires the use of the `certs` parameter to `PKCS7_verify`. …
=> Participants can sign their own permissions file if the same CA is used for both identity and permissions

tests/unit-tests/dds/DCPS/AddressCache.cpp
Problem: Coverity doesn't like to see `memcmp` calls that exceed the object bounds of the input pointer types (even if that's the desired / optimized behavior).
Solution: Since it's a unit test, performance isn't critical. Split the `memcmp` calls up in such a way that Coverity can sleep at night.
=> Resolve Coverity Issues In AddressCache Unit Test

tests/DCPS/SharedTransport/TestCase.cpp, tests/DCPS/TestFramework/TestFramework_T.h
The way the SharedTransport test is structured and the test assertions it makes really only make sense for reliable QoS and reliable transports. As such, the udp transport sometimes falls short (drops messages and/or has nothing to read) of the test expecations even though that's acceptable DDS behavior.
Make sure the test only enforces the strict requirements for reliable transports / entities.
=> Relax Best-Effort Requirements For SharedTransport Test

dds/DCPS/DataReaderImpl.cpp, dds/DCPS/transport/framework/ReceiveListenerSet.cpp, dds/DCPS/transport/framework/ReceiveListenerSet.h, dds/DCPS/transport/framework/ReceiveListenerSet.inl
`DataReaderImpl::state_update()` and the `ReceiveListenerSet` are inconsistent in how they apply their locking (the lock sometimes being applied, but not others).
Assuming these locks are serving a real purpose, we ought to be consistent / careful in how they are applied to avoid future thread safety issues.
=> Minor Improvements For Reader-Side Locking

dds/DCPS/LinuxNetworkConfigMonitor.cpp
LinuxNetworkConfigMonitor currently uses `notify_one` for its "waitable" conditions. This is probably fine for our current usage, but in general any number of threads could be waiting for this event, so `notify_all` is more appropriate since it will wake all threads to the relevant changes.
Change uses of `notify_one` to `notify_all`.
=> LinuxNetworkConfigMonitor Should Use `notify_all` For Waitable Conditions

dds/DCPS/Atomic.h, dds/DCPS/LocalObject.h, dds/DCPS/RcHandle_T.h, dds/DCPS/RcObject.h, tests/stress-tests/dds/DCPS/RcObject.cpp
It appears as though there is a race condition between `WeakRcHandle::lock()` and `RcObject::_remove_ref()`, likely called from `RcHandle::~RcHandle()` or `RcHandle::reset()`.
Create a stress test to expose the existing issue, then try to resolve it.
=> Add RcObject (et al.) Stress Test

dds/CORBA/tao/Exception.cpp, dds/DdsDcpsCore.idl, dds/idl/be_global.cpp, dds/idl/be_global.h, dds/idl/be_produce.cpp, java/dds/DDS/.gitignore
These are defined in XTypes 1.3 Table 43. They are specified in the context of the C++ language binding, but it makes more sense for them to be defined in IDL.
=> Add `DDS` IDL Namespace Primitives and Normalize `DdsDcpsCore.idl`

.github/workflows/build_u14_gcc4.Dockerfile, dds/DCPS/ReactorInterceptor.cpp, dds/DCPS/ReactorInterceptor.h, dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.h, dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.inl, dds/DCPS/transport/rtps_udp/RtpsUdpReceiveStrategy.cpp, dds/DCPS/transport/rtps_udp/RtpsUdpReceiveStrategy.h, dds/DCPS/transport/rtps_udp/RtpsUdpTransport.cpp, dds/DCPS/transport/rtps_udp/RtpsUdpTransport.h
Problem
-------
The changes from #3990 created a race where the socket handles are nulled out as part of the transfer to the data link before the `remove_handler` call.
Solution
--------
Capture the inputs to `register_handler` and `remove_handler` in ReactorInterceptor Commands.
=> Socket handles invalid in RtpsUdpTransport

dds/.gitignore, dds/CORBA/tao/Exception.cpp, tests/DCPS/ManyTopicTest/publisher.cpp, tests/DCPS/PersistentInfoRepo/Publisher.cpp, tests/DCPS/Reliability/pub/Publisher.cpp, tests/DCPS/StaticDiscovery/StaticDiscoveryTest.cpp, tests/DCPS/XTypes/Subscriber.cpp, tests/unit-tests/dds/DCPS/MemoryPool.cpp, tools/modeling/tests/MessengerMC/fs_signal.cpp, tools/modeling/tests/MessengerMC/fs_signal.h, tools/scripts/update_gitignore.pl
https://github.com/OpenDDS/OpenDDS/pull/3994
- Fixed missing `TAO_VERSION_CODE` on TAO 2.2 by using `TAO_MAJOR_VERSION` instead.
- Replaced reference to bugzilla ticket with https://github.com/DOCGroup/ACE_TAO/issues/2037
- Cleaned up and added sorting option for `update_gitignore.pl` used in #3994
- Replaced sprintf usage to satisfy build_m12_i0_j_FM-1f GHA warnings
- [Attempting ASAN fix for ManyTopicTest.](https://github.com/OpenDDS/OpenDDS/actions/runs/4015514096/jobs/6899467008#logs) The string in Foo3 appears to be missing a null terminator. The fix is assuming that the static buffer is causing the issue because there can multiple threads using the function.
=> Follow up to 3994 and Fix sprintf Warnings

tools/rtpsrelay/GuidPartitionTable.h
The index variable `idx` in `GuidPartitionTable::prepare_relay_partitions()` is not currently being incremented, even though it appears as though the code is set up to expect that.
Increment the index.
=> Fix index increment in GuidPartitionTable::prepare_relay_partitions

tools/dds/rtpsrelaylib/Relay.idl, tools/rtpsrelay/ParticipantListener.h, tools/rtpsrelay/PublicationListener.h, tools/rtpsrelay/ReaderListenerBase.h, tools/rtpsrelay/RelayAddressListener.h, tools/rtpsrelay/RelayPartitionsListener.h, tools/rtpsrelay/RelayStatisticsReporter.h, tools/rtpsrelay/RelayThreadMonitor.h, tools/rtpsrelay/RtpsRelay.cpp, tools/rtpsrelay/SpdpReplayListener.h, tools/rtpsrelay/StatisticsWriterListener.h, tools/rtpsrelay/SubscriptionListener.h, tools/rtpsrelay/WriterListenerBase.h
Relay cluster fragmentation is difficult to detect.
Ensure RtpsRelay's entities are tracking publication and subscription match counts, and writing them to the various relay statistics channels.
=> Add PublicationMatchedStatus Current Count To RtpsRelay Statistics

dds/DCPS/TopicDescriptionImpl.h, dds/DCPS/WriterInfo.h
Some of the Atomic types were inconsistent between C++11 and pre-C++11 builds, and older versions of Visual Studio are not happy with the new standard fixed size integral types.
Use ACE's fixed size types instead.
=> Fixes for new Atomic template types for pre-C++11 Windows builds

tests/stress-tests/run_test.pl
On slower VMs / configurations, the stress tests occasionally time out. The previous timeout was 60 seconds, and recent test additions have increased the overall time required to run the full test suite. In general, these aren't expected to hang or fail (and if they do, it indicates a problem that needs fixing), so increasing the timeout shouldn't increase the total test time, only reducing the number of false negatives.
Increase stress test timeout from 60 seconds to 180 seconds.
=> Increase Timeout For Stress Tests

.github/workflows/build_and_test.yml
This may avoid running of space during the build
=> GitHub Actions: Moved the part of build_w22_x86_i0_j_FM-1f that builds CMake tests

dds/DCPS/XTypes/DynamicDataBase.cpp, dds/DCPS/XTypes/DynamicDataBase.h, dds/DCPS/XTypes/DynamicDataImpl.cpp, dds/DCPS/XTypes/DynamicDataImpl.h, dds/DCPS/XTypes/DynamicDataXcdrReadImpl.cpp, dds/DCPS/XTypes/Utils.cpp, dds/DCPS/XTypes/Utils.h, tests/DCPS/FilterExpression/FilterExpression.cpp, tests/DCPS/FilterExpression/FilterStructDynamicTypeSupport.cpp, tests/DCPS/FilterExpression/FilterStructDynamicTypeSupport.h, tests/DCPS/QueryCondition/QueryConditionTest.cpp, tests/unit-tests/dds/DCPS/XTypes/DynamicDataImpl.cpp, tests/unit-tests/dds/DCPS/XTypes/DynamicDataXcdrReadImpl.cpp
Also used by content filtering to compare enum members to query string literals/parameters.
=> Dynamic Data: read/write enum members as strings

performance-tests/bench/node_controller/main.cpp, performance-tests/bench/worker/ForwardAction.cpp, performance-tests/bench/worker/ForwardAction.h
ForwardAction writes currently taking place under lock, preventing reads from updating queue and returning (potentially blocking transport reactor threads).
Copy and/or swap data out of the queue before writing in order to be able to release action's lock.
=> [Bench] Improve Worker ForwardAction Queue Locking Performance

dds/DCPS/RTPS/GuidGenerator.cpp, tests/unit-tests/dds/DCPS/RTPS/GuidGenerator.cpp
- Logging is left enabled for a failing case in the unit test and that logging is unconditional and isn't properly formatted.
- The unit test for `GuidGenerator` is in `dds/DCPS` when the class it's testing is in `dds/DCPS/RTPS`.
=> Fix Issues with GuidGenerator and its Unit Test

dds/DCPS/RTPS/Sedp.cpp, dds/DCPS/transport/rtps_udp/RtpsUdpReceiveStrategy.cpp, tests/security/SingleParticipantWithSecurity/governance.xml, tests/security/SingleParticipantWithSecurity/governance_signed.p7s
Problem
-------
A writer and reader in the same participant that uses non-trivial security fail to associate and exchange data.  The SingleParticipantWithSecurity tests this scenario but uses an "open" domain so all of the encryption and decryption logic was skipped.
Solution
--------
* Turn on encryption so that those code paths are exercised in the test.
* Fix code paths that cannot handle a remote writer being local.
=> Secure writer and reader in same participant do not associate

dds/DCPS/RTPS/Sedp.cpp
TSAN detected a [data race](https://github.com/OpenDDS/OpenDDS/actions/runs/4153628452/jobs/7186086575) (ci-disco-long) in SEDP replay of durable data. The problem appears to be that the `Sedp::replay_durable_data_for` never correctly acquires the Sedp mutex.
Acquire the mutex.
=> Fix data race in replay of Sedp durable data

configure
This can be used to have an x86_64 macOS system generate arm64 builds.
=> configure: Added macOS cross-compile

tools/dds/rtpsrelaylib/Relay.idl, tools/rtpsrelay/Config.h, tools/rtpsrelay/GuidAddrSet.cpp, tools/rtpsrelay/GuidAddrSet.h, tools/rtpsrelay/RelayHandler.cpp, tools/rtpsrelay/RelayStatisticsReporter.h, tools/rtpsrelay/RtpsRelay.cpp
RtpsRelay lacks certain features for gauging interaction with poorly behaving (either intentionally or unintentionally) participants, such as a limit for the maximum size of address sets associated with a participant and the ability to ignore/reject certain addresses which behave poorly (such as echoing back traffic) for a period of time.
Implement these features, as well as some logging surrounding the data structure sizes.
=> Add Hardening Features To RtpsRelay

dds/DCPS/transport/framework/TransportSendBuffer.cpp
The entries of the `destinations_` data structure within `TransportSendBuffer` appear to be maintained within `remove_i` and `release_i`, so the call to `erase` within `check_capacity_i` is no longer required, since it also subsequently calls `remove_i`.
Remove the extra call.
=> Remove Extra Call To destinations_.erase() In TransportSendBuffer

docs/index.rst, docs/internal/bench.rst, performance-tests/bench/README.md
Updates:
- Remove most references to "Bench 2" in favor of simply calling it "Bench" (version 2 where appropriate).
- Update build target names to match reality.
- Minor improvements to documentation clarity / readability.
- Provide path to example scenarios.
=> [Bench] Minor Documentation Updates

dds/DCPS/transport/framework/TransportRegistry.cpp
Problem
--------
Transport config and inst objects may have names that conflict when using configuration templates, even when they are in different domains. This may cause tests to fail.
Solution
--------
Add the domain to the identifiers.
=> Transport config and inst derived from template may conflict

README.md, configure
Problem
-------
The OpenDDS build process is dependent on OCI ACE/TAO releases which
will not be available or maintained in the future.
Solution
--------
Replace OCI ACE/TAO dependency with stable fork of ACE/TAO.
=> Use DOCGroup ACE6/TAO2 as default ACE/TAO for OpenDDS

dds/DCPS/Qos_Helper.cpp, dds/DCPS/Qos_Helper.h, dds/DCPS/Service_Participant.cpp, dds/DCPS/Service_Participant.h, dds/DCPS/Time_Helper.h, dds/DCPS/Time_Helper.inl, dds/DdsDcpsCore.idl, tests/unit-tests/dds/DCPS/MockLogger.h, tests/unit-tests/dds/DCPS/MockPublisher.h, tests/unit-tests/dds/DCPS/MockTopic.h, tests/unit-tests/dds/DCPS/Qos_Helper.cpp, tests/unit-tests/dds/DCPS/SporadicTask.cpp, tests/unit-tests/dds/DCPS/Time_Helper.cpp
Problem
-------
InternalDataWriters will be converted to use DDS::DataWriterQos. InternalDataWriters are often initialized in constructors meaning that we need a way to initialize the DDS::DataWriterQoS.
Solution
--------
Provide a builder to initialize DDS::DataWriterQos.
=> Initializing DDS::DataWriterQos for constructors is difficult

docs/devguide/alternate_interfaces_to_data.rst, docs/devguide/built_in_topics.rst, docs/devguide/conditions_and_listeners.rst, docs/devguide/content_subscription_profile.rst, docs/devguide/dds_security.rst, docs/devguide/getting_started.rst, docs/devguide/internet_enabled_rtps.rst, docs/devguide/introduction.rst, docs/devguide/java_bindings.rst, docs/devguide/modeling_sdk.rst, docs/devguide/opendds_idl.rst, docs/devguide/quality_of_service.rst, docs/devguide/run_time_configuration.rst, docs/devguide/safety_profile.rst, docs/devguide/the_dcps_information_repository.rst, docs/devguide/xtypes.rst
Problem
-------
The conversion of the DevGuide means that the concept of a "chapter" is no longer well defined.  Many references are introduced as "see section X".
Solution
--------
- Where possible remove the descriptor (chapter/section) of the target of the reference.
- Change generic references to be section.
=> DevGuide refers to chapters and sections

docs/custom.css
Top-level navigation sidebar links are a little hard to distinguish from one another because some of them will overflow into multiple lines. A `ul` tag would have bullets, but that's disabled in the theme's CSS. This overrides that and readds the bullets.
Here is a screenshot with the added bullets on the right side:
=> Add Bullets To Top-Level Sidebar Links in Sphinx

docs/conf.py
Not 100% sure, but shouldn't have the DevGuide now have the OpenDDS Foundation as author?
=> OpenDDS Foundation as author of DevGuide

dds/DCPS/transport/framework/TransportClient.cpp, dds/DCPS/transport/framework/TransportControlElement.cpp, dds/DCPS/transport/framework/TransportControlElement.h, dds/DCPS/transport/framework/TransportControlElement.inl, dds/DCPS/transport/tcp/TcpDataLink.cpp
Problem
-------
The `send_association_msg` method creates a special `REQUEST_ACK`
control message to signal that the local reader is ready to receive
data.  On receipt of the message, the remote writer completes the
association and can start sending data.  `send_association_msg` calls
`send_i` which checks if the publication id of the
`TransportControlElement` is for a stopped (local) client.  The
publication id returned by the `TransportControlElement` is always
GUID_UNKNOWN.  Thus, if GUID_UNKNOWN gets put into the stopped client
set then the `TcpDataLink` will never send the association message and
association will stall on the writer side.
`TransportClient` caches its guid when an association is made.
Suppose the `TransportClient` is stopped before an association.  In
this case the …
=> TcpDataLink fails to send association message

dds/DCPS/Comparator_T.h, dds/DCPS/DataCollector_T.h, dds/DCPS/GroupRakeData.h, dds/DCPS/RakeData.h, dds/DCPS/RakeResults_T.h, dds/DCPS/ZeroCopyAllocator_T.h, dds/DCPS/ZeroCopySeq_T.h, dds/DCPS/transport/framework/DataLinkCleanupTask.h, dds/DCPS/transport/tcp/Tcp.h, dds/DCPS/transport/tcp/TcpLoader.h, performance-tests/DCPS/Priority/Options.h, tests/DCPS/Priority/Options.h, tools/modeling/codegen/model/Config.h, tools/modeling/codegen/model/Entities.h, tools/modeling/codegen/model/TransportDirectives.h, tools/monitor/Options.h, tools/scripts/lint.pl
Some headers used `pre.h` without `post.h` which [leaks `pragma pack (push, 8)`]( https://github.com/DOCGroup/ACE_TAO/blob/ab3b192fcda5715a0c92e5627acdeb4e8f71911c/ACE/ace/pre.h#L17) into the code using those headers. Even if this was fixed, it's not clear what is gained by using these headers, except maybe [improved ABI compatibility](
https://github.com/DOCGroup/ACE_TAO/blob/ab3b192fcda5715a0c92e5627acdeb4e8f71911c/ACE/ChangeLogs/ChangeLog-2000a#L9726-L9762), in case the alignment changed somehow. OpenDDS doesn't guarantee ABI compatibility at all though, so this seems like this doesn't do anything for us. Instead of using these headers inconsistently, remove them everywhere except for the libraries that consistently use them, the modeling and the QoS XML libraries.
Also made some …
=> Remove Many Uses of `ace/pre.h` and `ace/post.h`

DevGuideExamples/DCPS/Messenger/docker-compose-inforepo.yml, DevGuideExamples/DCPS/Messenger/docker-compose.yml
Problem
-------
Docker compose files in DevGuideExamples reference ghcr.io/objectcomputing which is no longer being updated since OpenDDS is now under the opendds GitHub organization.
Solution
--------
Fix the references.
=> DevGuideExamples reference ghcr.io/objectcomputing

dds/DCPS/DataDurabilityCache.cpp, dds/DCPS/DataDurabilityCache.h, dds/DCPS/DomainParticipantFactoryImpl.cpp, dds/DCPS/Service_Participant.cpp, dds/DCPS/Service_Participant.h, dds/DCPS/Service_Participant.inl, dds/DCPS/debug.cpp, dds/DCPS/debug.h, dds/DCPS/transport/framework/TransportRegistry.cpp, dds/DCPS/transport/framework/TransportRegistry.h
Problem
-------
The `Service_Participant` does not use the `ConfigStore`.  See #4134.
Solution
--------
Convert the `Service_Participant` to use the `ConfigStore`.
* Methods that returned references to configuration values in `Service_Participant` have been removed.
* Various strings have changed type.
* Each configuration value has a canonical name starting with `OPENDDS`.  The rest of the name is taken from its position in the config file by considering the section name.  Camelcase is converted into all-caps with underscores.  The canonical name resembles an environment variable to enable eventual support for environment variables.  See `Service_Participant.h` for the current list of configuration values.
* Argument parsing has been consolidated.  Arguments starting with `-DCPS`, …
=> `Service_Participant` does not use `ConfigStore`

NEWS.md, docs/news.d/_releases/v3.24.0.rst, docs/news.d/sample_convert.rst
- Add https://github.com/OpenDDS/OpenDDS/pull/4144 to News
- Retroactively add new global options from https://github.com/OpenDDS/OpenDDS/pull/4071 to 3.24.0. I realized I missed them when going over the CMake documentation.
=> Corrections to the News

.editorconfig, docs/internal/dev_guidelines.rst
[EditorConfig](https://editorconfig.org/) can help enforce our text file formatting. It is natively supported by many editors including Visual Studio and Neovim (the fork of Vim I use) with plugins available for other editors. It's also used by many big projects such as Jekyll, Git, Rust, Python, and CMake (where I recently first noticed it). It's also used by Micronaut. This means even if it's not natively supported by a contributor's editor, there's a chance they already have a plugin for it installed.
=> Add `.editorconfig` and Document Lint Script

dds/idl/be_global.cpp, dds/idl/be_global.h, dds/idl/be_util.cpp, dds/idl/langmap_generator.cpp, dds/idl/ts_generator.cpp, docs/devguide/opendds_idl.rst, docs/news.d/equality_operators.rst, tests/DCPS/Compiler/C++11/idl_test_nested_types_lib/cxx11_idl_test_nested_types_lib.mpc, tests/DCPS/Compiler/idl_test_nested_types_lib/idl_test_nested_types_lib.mpc
Problem
-------
The type support for C++11 does not include equality operators (`==` and `!=`).  The operators make the IDL defined types easier to use with generic programming techniques.
Solution
--------
Implement support for `==` and `!=`.
=> Some language mappings don't support equality comparison

docs/build.py, docs/internal/docs.rst, docs/internal/release.rst, docs/internal/running_tests.rst
`docs/build.py` almost works on Windows, but there is an extra check for the existence of `sphinx-build` that apparently doesn't work on Windows because the virutalenv directory structure is different. It isn't really necessary anyways.
Also removed unnecessary `./` before scripts.
=> Update `docs/build.py` for Windows and Remove `./`

dds/DCPS/DataWriterImpl.cpp, dds/DCPS/DataWriterImpl.h, tests/DCPS/ManualAssertLiveliness/DataWriterListenerImpl.cpp, tests/DCPS/ManualAssertLiveliness/DataWriterListenerImpl.h, tests/DCPS/ManualAssertLiveliness/publisher.cpp
Problem
-------
PR #4180 requires that the GUID be set before using the TransportClient.  DataWriterImpl can set a liveliness timer that expires before the GUID is set which leads to an assertion.
Solution
--------
Defer scheduling the liveliness timer until after the GUID is set.
=> DataWriterImpl can send liveliness before GUID is set

NEWS.md, docs/build.py, docs/internal/github_actions.rst, docs/news.d/_releases/v3.25.0.rst, docs/sphinx_extensions/newsd.py
3.25.0 news had empty lines with tailing spaces in the RST news and broken encodings for single quotes in the GitHub release page. The trailing spaces was caused by some indent logic for indenting sections not checking if the line is empty before indenting. The broken single quotes were caused by Sphinx doing smartquotes and those non-ASCII quotes getting mangled by either the release script or maybe GitHub. This disables smartquotes in build.py, but if possible this should probably be something the Markdown builder sets since it doesn't make sense to do it in Markdown.
Also fixed some minor issues in the GHA document.
=> Fix Smartquotes and Trailing Spaces in News

docs/.readthedocs.yaml
This is apparently going to be required going forward: https://blog.readthedocs.com/migrate-configuration-v2/
=> Add Read the Docs Config File

dds/DCPS/XTypes/DynamicDataAdapter.cpp, dds/DCPS/XTypes/DynamicDataAdapter.h, dds/DCPS/XTypes/DynamicDataBase.h, dds/DCPS/XTypes/DynamicDataImpl.cpp, dds/DCPS/XTypes/DynamicDataImpl.h, dds/DCPS/XTypes/DynamicDataXcdrReadImpl.h, dds/DCPS/XTypes/DynamicSample.cpp, dds/idl/dynamic_data_adapter_generator.cpp, dds/idl/marshal_generator.cpp, docs/internal/dev_guidelines.rst, tests/DCPS/DynamicData/publisher.cpp, tests/DCPS/DynamicData/run_test.pl, tests/dcps_tests.lst
- Move the internal XCDR serialization functions for `DynamicDataImpl` out of its `DataContainer`. `DataContainer` now is just a container of the sample data which would facilitate serializing to other formats.
- Add new interfaces for XCDR serialization to `DynamicDataBase` that allow dynamic writers to send dynamic samples constructed from `DynamicDataAdapter` in addition to `DynamicDataImpl`.
=> Support sending `DynamicDataAdapter` sample via dynamic writer

.github/workflows/build_and_test.yml
Problem
-------
One GHA job used a hardcoded Java.
Solution
--------
Use an environment variable to find Java.
=> Java 8 has moved on Ubuntu 20 in GitHub Actions

dds/DCPS/ConfigStoreImpl.cpp, dds/DCPS/ConfigStoreImpl.h, dds/DCPS/transport/multicast/MulticastDataLink.cpp, dds/DCPS/transport/multicast/MulticastInst.cpp, dds/DCPS/transport/multicast/MulticastInst.h, dds/DCPS/transport/multicast/MulticastLoader.cpp, dds/DCPS/transport/multicast/MulticastSendStrategy.cpp, dds/DCPS/transport/multicast/MulticastSendStrategy.h, dds/DCPS/transport/multicast/MulticastSession.cpp, dds/DCPS/transport/multicast/MulticastTransport.cpp, dds/DCPS/transport/multicast/ReliableSession.cpp, dds/DCPS/transport/multicast/ReliableSession.h, dds/DCPS/transport/udp/UdpInst.h, docs/news.d/config_store.rst, java/dds/OpenDDS_DCPS_jni.cpp, java/dds/dcps_java.mpc, tests/unit-tests/dds/DCPS/ConfigStoreImpl.cpp, tools/modeling/plugins/org.opendds.modeling.sdk.model/xsl/traits_cpp.xsl
Problem
-------
`MulticastInst` does not use `ConfigStore`.  See #4134.
Solution
--------
Convert `MulticastInst` to use `ConfigStore`.
* The following members have been replaced with getters and setters:
- default_to_ipv6
- port_offset
- group_address
- local_address
- reliable
- syn_backoff
- syn_interval
- syn_timeout
- nak_depth
- nak_interval
- nak_delay_intervals
- nak_max
- mak_timeout
- ttl
- rcv_buffer_size
- async_send
=> `MulticastInst` does not use `ConfigStore`

dds/DCPS/transport/shmem/ShmemInst.cpp, dds/DCPS/transport/shmem/ShmemInst.h, dds/DCPS/transport/shmem/ShmemSendStrategy.cpp, dds/DCPS/transport/shmem/ShmemTransport.cpp, docs/news.d/config_store.rst
Problem
-------
`ShmemInst` does not use `ConfigStore`.  See #4134.
Solution
--------
Convert `ShmemInst` to use `ConfigStore`.
* The following members have been replaced with getters and setters:
- `pool_size_`
- `datalink_control_size_`
=> `ShmemInst` does not use `ConfigStore`

MPC/config/dcps_default_discovery.mpb, MPC/config/dcps_inforepodiscovery.mpb, dds/DCPS/InfoRepoDiscovery/InfoRepoDiscovery.cpp, dds/DCPS/transport/tcp/TcpConnection.cpp, dds/DCPS/transport/tcp/TcpInst.cpp, dds/DCPS/transport/tcp/TcpInst.h, dds/DCPS/transport/tcp/TcpInst.inl, dds/DCPS/transport/tcp/TcpTransport.cpp, dds/InfoRepo/DCPSInfo_i.cpp, docs/news.d/config_store.rst, java/dds/OpenDDS_DCPS_jni.cpp, tests/DCPS/ConfigFile/ConfigFile.cpp, tests/transport/error_handling/main.cpp
Problem
-------
`TcpInst` does not use `ConfigStore`.  See #4134.
Solution
--------
Convert `TcpInst` to use `ConfigStore`.
The signatures for methods manipulating the local address have changed
to be more consistent and to prevent the system from overwriting the
configuration provided by the user.
=> `TcpInst` does not use `ConfigStore`

dds/DCPS/RTPS/RtpsDiscovery.cpp
Problem
-------
During startup or shutdown, a participant might not exist from the perspective of RtpsDiscovery.  Updating locators at this time leads to a null pointer.
Solution
--------
Add check and logging.
=> Participant might not exist when updating locators

dds/DCPS/transport/udp/UdpDataLink.cpp, dds/DCPS/transport/udp/UdpInst.cpp, dds/DCPS/transport/udp/UdpInst.h, dds/DCPS/transport/udp/UdpTransport.cpp, docs/news.d/config_store.rst, java/dds/OpenDDS_DCPS_jni.cpp
Problem
-------
UdpInst does not use ConfigStore. See #4134.
Solution
--------
Convert UdpInst to use ConfigStore.
The signatures for methods manipulating the local address have changed
to be more consistent and to prevent the system from overwriting the
configuration provided by the user.
=> `UdpInst` does not use `ConfigStore`

dds/DCPS/transport/framework/TransportInst.h, tests/unit-tests/dds/DCPS/transport/framework/TransportInst.cpp
Problem
-------
ConfigValue and ConfigValueRef don't have an assignment operator which prevents users from copying values between TransportInsts.
Solution
--------
Add an assignment operator.
=> ConfigValue lacks assignment operator

docs/devguide/building/cmake.rst
The CMake 3.28 release candidate was put up recently and apparently the latest documentation is updated to point to release candidates. This updates URLs to the `install` command documentation, which seems to have had layout changed somewhat.
=> Fix Links in CMake Package Documentation

performance-tests/bench/example/config/scenario/ci-disco-relay.json, tests/DCPS/ParticipantLocationTopic/run_test.pl, tests/DCPS/RtpsRelay/STUN/run_test.pl, tests/DCPS/RtpsRelay/Smoke/run_lease_duration_test.pl
Problem
-------
The default -MetaDiscoveryAddress uses port 8080 which is often used by other services.  This causes the
`run_lease_duration_test.pl` to fail.
Solution
--------
Set the port to 0.
=> `run_lease_duration_test.pl` uses common port

docs/internal/release.rst, tools/scripts/gitrelease.pl
- Fixed Read the Docs links in README not getting updated properly.
- Fixed `gitrelease.pl --list` ignoring the current release workspace. This comes at the cost of having to have that workspace though.
- Re-enabled Read the Docs version activation and updated release doc for this.
- Other small fixes for the release doc.
=> Fixes for Release Script and Doc Post-3.26.0

cmake/init.cmake, docs/news.d/cmake-features.rst
Fixes #4328
The equivalent to many MPC features in CMake are built up using a function called `_opendds_feature` that adds features to lists to use. The issue is these lists are set as cache variables, which are persistent across CMake runs. This resulted in the features being appended each time, so they are listed multiple times in output and `default.features` if building ACE.
These don't really have to be cache variables, so just set them as normal variables in the parent scope.
Also fixed some typos in the same file and added a note about removing an include in the future.
=> "Un-cache" Feature Lists in CMake

.github/workflows/update-ace-tao.yml
I noticed that the new workflow from #4327 wasn't running. After a bit of investigation, I saw that I messed up the cron syntax as it shouldn't have that 0 at the start. Between testing it in my fork and making the PR I adjusted the time to be during the off hours of both Europe and America and must have messed it up then.
=> Fix Cron Expr in Update ACE/TAO Workflow

dds/DCPS/XTypes/DynamicDataAdapter.h, dds/DCPS/XTypes/DynamicDataImpl.cpp, dds/DCPS/XTypes/Utils.cpp, tests/unit-tests/dds/DCPS/XTypes/DynamicDataAdapter.cpp, tests/unit-tests/dds/DCPS/XTypes/DynamicDataAdapter.idl
This was made in response to upcoming changes to make `DynamicDataImpl` unions work more like C++ unions in https://github.com/OpenDDS/OpenDDS/pull/4278. This also works around a problem in `DynamicDataAdaptor` when using `get_complex_value` on union branches that haven't been initialized.
=> Init Union Branch in `DynamicData` `copy`

NEWS.md, docs/news.d/_releases/v3.24.0.rst, docs/news.d/_releases/v3.24.1.rst, docs/news.d/_releases/v3.24.2.rst, docs/news.d/_releases/v3.25.0.rst, docs/news.d/_releases/v3.26.0.rst, docs/news.d/_releases/v3.26.1.rst, docs/news.d/cmake-features.rst, docs/news.d/rtps-badmsg.rst, docs/news.d/rtps-parameterlist.rst, docs/sphinx_extensions/newsd.py, tools/scripts/gitrelease.pl
Added a small utility to cherry pick GitHub PRs to help prepare micro releases and fixed updating links in README for micro releases.
=> Sync 3.26.1 News and Release Script Updates

dds/CMakeLists.txt, dds/DCPS/XTypes/DynamicTypeImpl.cpp, dds/DCPS/XTypes/IdlScanner.cpp, dds/DCPS/XTypes/IdlScanner.h, dds/DCPS/XTypes/MemberDescriptorImpl.cpp, tests/unit-tests/dds/DCPS/XTypes/IdlScanner.cpp, tests/unit-tests/dds/DCPS/XTypes/MemberDescriptorImpl.cpp
Problem
-------
The MemberDescriptor implementation is incomplete.  Completing it is necessary to support user-constructed DynamicTypes.
Solution
--------
Complete MemberDescriptorImpl.
The largest part of the code is devoted to checking that default values are a valid IDL literal for the member type.  This prompted the creation of a primitive scanner.
=> MemberDescriptor implementation is incomplete

dds/DCPS/Service_Participant.cpp, docs/news.d/partfactnull.rst, tests/DCPS/SampleLost/run_test.pl
Right now it issues a warning and uses a default configuration. With this it logs an error and returns `NULL`. Also corrected other logging to match guidelines.
=> `TheParticipantFactory*` should return `NULL` for Missing Config File

.github/workflows/build_and_test.yml
Problem
-------
The index.html is not generated for the GHA builds.  This is preventing the scoreboard from showing these builds.
Solution
--------
Generate the index.
Notes
-----
Generating the index this way will only allow the most recent build to appear on the scoreboard.  Adding previous builds to the index will be addressed later.
=> index is not generated for GHA builds

dds/DCPS/PublisherImpl.cpp, dds/DCPS/SubscriberImpl.cpp, docs/news.d/create-writer-reader-topic.rst, tests/DCPS/TopicReuse/README.rst, tests/DCPS/TopicReuse/tpreuse.cpp
Problem
-------
Sections 2.2.2.4.1.5 and 2.2.2.5.2.5 of the DDS Specification say that `create_datawriter` and `create_datareader` should fail if the topic does not belong to the same participant as the publisher/subscriber.
Solution
--------
Add the necessary checks to `create_datawriter` and `create_datareader`.
=> `create_datawriter/datareader` do not check topic participant

tests/unit-tests/dds/DCPS/Qos_Helper.cpp
When trying to add the --tests into the bitbake recipe of meta-opendds I had this compilation error
```
| ...3.26.1/recipe-sysroot/usr/include/gmock/gmock-actions.h:1783:61: note: 'testing::DoAll' declared here |  1783 | internal::DoAllAction<typename std::decay<Action>::type...> DoAll(
|       |                                                             ^~~~~
```
The info from log.do_compile is:
`/home/jan/projects/mykas/build/tmp/work/cortexa72-poky-linux/opendds/3.26.1/git/aarch64-poky-linux-g++ -fvisibility=hidden -fvisibility-inlines-hidden -Wnon-virtual-dtor -ggdb -pthread -fno-strict-aliasing -Wall -W -Wpointer-arith -pipe -D_GNU_SOURCE  -I/home/jan/projects/mykas/build/tmp/work/cortexa72-poky-linux/opendds/3.26.1/git/ACE_wrappers -D__ACE_INLINE__ …
=> fixing DoAll -> testing::DoAll

dds/DCPS/Discovery.h, dds/DCPS/InfoRepoDiscovery/InfoRepoDiscovery.cpp, dds/DCPS/InfoRepoDiscovery/InfoRepoDiscovery.h, dds/DCPS/RTPS/RtpsDiscovery.cpp, dds/DCPS/RTPS/RtpsDiscovery.h, dds/DCPS/RTPS/RtpsDiscoveryConfig.cpp, dds/DCPS/RTPS/RtpsDiscoveryConfig.h, dds/DCPS/RTPS/Sedp.cpp, dds/DCPS/RTPS/Spdp.cpp, dds/DCPS/Service_Participant.cpp, dds/DCPS/Service_Participant.h, dds/DCPS/StaticDiscovery.cpp, dds/DCPS/StaticDiscovery.h, tests/security/ConcurrentAuthLimit/ConcurrentAuthLimit.cpp
Problem
-------
One of the goals of using the ConfigStore (#4134) is to minimize the number of entries in the ConfigStore that are generated by the framework itself.  Such entries are basically leaked.
The main culprit here is template support which
instatiates new `[domain]`, `[rtps_discovery]`, `[config]`, and `[transport]` sections.  This commit removes the need to instantiate `[rtps_discovery]` sections.
Solution
--------
Parameterize `RtpsDiscoveryConfig::default_multicast_group` on the domain so that it can be customized on the fly.
=> Discovery templates are not reused

cmake/scrape_gnuace.pl
This fixes #4381, still need to test with debuild as well
=> Ensure scrape_gnuace.pl doesn't try to parse make's `make[]` lines

docs/sphinx_extensions/links.py
This might be caused by a refactor that PyMuPDF is currently doing. This library is used to read the OMG spec table of contents to get the links. I could look into this further to see if this was intentional or a bug, but the fix seems to be trivial.
=> Fix Broken PDF Scraping in Sphinx

configure
The order of entries in `$platforminfo{$os}->{'compilers'}` is significant: check clang++ first, for consistency with g++.
Use a better regex to run gcc/clang version detection. 
Output the compiler's version string when configure is in verbose mode.
=> configure: improve clang-on-Linux support

dds/DCPS/transport/framework/TransportInst.cpp, dds/DCPS/transport/framework/TransportInst.h, dds/DCPS/transport/framework/TransportRegistry.cpp, dds/DCPS/transport/multicast/MulticastInst.cpp, dds/DCPS/transport/multicast/MulticastInst.h, dds/DCPS/transport/rtps_udp/RtpsUdpInst.cpp, dds/DCPS/transport/rtps_udp/RtpsUdpInst.h, dds/DCPS/transport/shmem/ShmemInst.cpp, dds/DCPS/transport/shmem/ShmemInst.h, dds/DCPS/transport/tcp/TcpInst.cpp, dds/DCPS/transport/tcp/TcpInst.h, dds/DCPS/transport/udp/UdpInst.cpp, dds/DCPS/transport/udp/UdpInst.h, tests/DCPS/MultiDPTest/subscriber.cpp, tests/DCPS/Thrasher/Publisher.cpp
Problem
-------
`TransportInst::load` is no longer necessary and can be removed.
Solution
--------
Remove `TransportInst::load`.
=> `TransportInst::load` is unnecessary

dds/idl/langmap_generator.cpp, tests/DCPS/Compiler/idl_test_nested_types_lib/NestedTypesTest.idl
Problem
-------
When using `-Lc++11 -Gequality`, the generated equality operator for a union is not in the appropriate namespace.  This leads to code that can't be compiled.  See #4447.
Solution
--------
Move the namespace scoping guard ahead of the operator generation and extend a test.
=> Equality operator not in namespace for `-Lc++11 -Gequality`

docs/devguide/shapes.rst, docs/internal/release.rst, tools/scripts/gitrelease.pl, tools/scripts/modules/command_utils.pm, tools/scripts/modules/ini.pm, tools/scripts/modules/misc_utils.pm
- Replace `--upload-shapes-demo` with `--upload-artifacts`, which will now upload the RTPS interop test in addition to the shapes demo.
- `--upload-shapes-demo`, now `--upload-artifacts` was unable to download artifacts from workflows. [This GitHub discussion answer](https://github.com/orgs/community/discussions/88698#discussioncomment-8252538) provided an overview of the issue. The artifact download URL was being redirected to an internal Microsoft one which rejects GitHub authentication. The solution was to use the `download` function instead of PitHub and make a special case where it detects the failed redirect and retries it without authentication.
- Replace the multiple `die_with_stack_trace` functions with a single implementation called `trace`. Also fixed the confusing off-by-one …
=> Post 3.27.0 Release Script Improvements

dds/DCPS/RTPS/Sedp.cpp, dds/DCPS/Service_Participant.cpp, dds/DCPS/transport/framework/TransportClient.cpp, dds/DCPS/transport/framework/TransportConfig.cpp, dds/DCPS/transport/framework/TransportConfig.h, dds/DCPS/transport/framework/TransportRegistry.cpp, dds/DCPS/transport/framework/TransportRegistry.h, java/dds/OpenDDS_DCPS_jni.cpp, tests/DCPS/ConfigFile/ConfigFile.cpp, tests/DCPS/Thrasher/Publisher.cpp, tools/modeling/plugins/org.opendds.modeling.sdk.model/xsl/traits_cpp.xsl
Problem
-------
`load_transport_configuration` uses `ACE_Configuration_Heap` and `ACE_Configuration_Heap` is being removed where possible as part of #4134.
Solution
--------
Simplify the arguments to only have the file name.
=> `load_transport_configuration` uses `ACE_Configuration_Heap`

dds/DCPS/RTPS/RtpsDiscoveryConfig.cpp
Problem
-------
Various setters in RtpsDiscoveryConfig are getting from the ConfigStore instead of setting.
Solution
--------
Change the get to set.
=> Various RtpsDiscoveryConfig setters don't set

bin/PerlDDS/Run_Test.pm, dds/DCPS/Service_Participant.cpp, dds/DCPS/Service_Participant.h, tests/DCPS/ConfigFile/ConfigFile.cpp, tests/DCPS/ConfigFile/run_test.pl
Problem
-------
OpenDDS cannot be configured with environment variables.  Configuring with environment variables is useful for containers and cloud deployments.
Solution
--------
Parse environment variables and add them to the ConfigStore.  Only environment variables starting with OPENDDS_ are parsed.  The remainder of the name is used as the key for the ConfigStore. Environment variables are processed before command-line arguments and the config file.
=> OpenDDS cannot be configured with environment variables

MPC/config/dcpslib.mpb, MPC/config/opendds_cxx11.mpb, MPC/config/opendds_uses_cxx11.mpb, MPC/config/rtps_relay_lib.mpb, java/tests/complex_idl/complex_idl_test.mpc, java/tests/multirepo/multirepo_test.mpc, java/tests/two_idl/two_idl.mpc, performance-tests/bench/bench_builder_exe.mpb, performance-tests/bench/bench_builder_idl_lib.mpb, performance-tests/bench/bench_exe.mpb, performance-tests/bench/bench_idl_lib.mpb, performance-tests/bench/builder/Bench_Builder.mpc, performance-tests/bench/builder_idl/Bench_Builder_Idl.mpc, performance-tests/bench/common/Bench_Common.mpc, performance-tests/bench/idl/Bench_Idl.mpc, tests/DCPS/C++11/Messenger/Publisher/DDS_Cxx11_Messenger_Publisher.mpc, tests/DCPS/C++11/Messenger/Subscriber/DDS_Cxx11_Messenger_Subscriber.mpc, tests/DCPS/Compiler/vread_vwrite/VreadVwriteTest.mpc
- `opendds_cxx11.mpb` Should Use `opendds_uses_cxx11.mpb`
- Tests, mpb files, and mpcs with a `libout` should not be using `dcpslib`.
- Add comments to `opendds_cxx11.mpb`, `opendds_uses_cxx11.mpb`, and `dcpslib.mpb` to try to make their usage clear.
- Replace projects `avoids += no_cxx11` with `opendds_uses_cxx11`.
=> Clean up C++11 and `dcpslib` related mpb files

tools/rtpsrelay/GuidAddrSet.cpp, tools/rtpsrelay/GuidAddrSet.h, tools/rtpsrelay/GuidPartitionTable.cpp, tools/rtpsrelay/GuidPartitionTable.h, tools/rtpsrelay/ParticipantListener.cpp, tools/rtpsrelay/PublicationListener.cpp, tools/rtpsrelay/RelayHandler.h, tools/rtpsrelay/RelayParticipantStatusReporter.cpp, tools/rtpsrelay/RelayParticipantStatusReporter.h, tools/rtpsrelay/SubscriptionListener.cpp
The tradeoff is that in certain cases the "session time" is no longer logged (with LogActivity=1).
=> RtpsRelay: reduce contention for GuidAddrSet's lock

dds/DCPS/InternalDataReader.h, dds/DCPS/InternalDataWriter.h, tests/unit-tests/dds/DCPS/InternalDataWriter.cpp
Problem
-------
It is foreseeable that "demuxing" will be a necessary feature of the Internal DDS system.  For example, suppose a socket abstract writes RTPS message samples which are keyed by the participant guid prefix. A reader is probably only interested in one participant.  The write could give the sample to all readers which would be inefficient since only one reader is actually interested.
Solution
--------
This solution assumes that an InternalDataReader reader is interested in a set of instances that known a priori and are specified explicitly.  The InternalDataReader indexes attached readers on the instances to efficiently deliver samples to readers that are only interested in those instances.
Note
----
A "real" DDS systems would content-filtering to accomplish the same …
=> Internal DDS cannot efficiently filter on instances

dds/DCPS/ConfigStoreImpl.cpp, dds/DCPS/ConfigStoreImpl.h, dds/DCPS/Service_Participant.cpp, dds/DCPS/Service_Participant.h, dds/DCPS/transport/framework/TransportRegistry.cpp, dds/DCPS/transport/framework/TransportRegistry.h, dds/DCPS/transport/framework/TransportRegistry.inl, dds/FACE/config/Parser.cpp, tests/DCPS/ConfigFile/README.rst, tests/DCPS/ConfigFile/run_test.pl, tests/DCPS/ConfigFile/test0.ini, tests/unit-tests/dds/DCPS/ConfigStoreImpl.cpp
Problem
-------
OpenDDS currently supports a single configuration file.  Supporting multiple configuration files would allow complex configurations to be broken down into more modular configuration files and it allows "base" configuration to be customized.
Solution
--------
Add a command-line argument named `-DCPSSingleConfigFile 0` to turn on support for multiple config files.  For backwards compatibility, the default is `-DCPSSingleConfigFile 0`.  When multiple config files are enabled, process command-line arguments in order and process each configuration file as it is encountered.  Multiple configuration files are supported via multiple `-DCPSConfigFile` arguments.
Configuration now processes environment variables first and then command-line arguments in order.  Each config file is …
=> Multiple config files are not supported

java/dds/OpenDDS/DCPS/TheServiceParticipant.java, java/dds/OpenDDS_DCPS_jni.cpp, java/tests/transport_config/TransportConfigTest.java
Problem
-------
The ConfigStore is not avaiable in Java.  If it was available, Java users could configure anything that can be configured.
Solution
--------
Expose the ConfigStore via the Service Participant.
=> ConfigStore is not available in Java

docs/conf.py, docs/devguide/annex.rst, docs/devguide/building/index.rst, docs/devguide/conditions_and_listeners.rst, docs/devguide/content_subscription_profile.rst, docs/devguide/dds_security.rst, docs/devguide/faq.rst, docs/devguide/getting_started.rst, docs/devguide/index.rst, docs/devguide/introduction.rst, docs/devguide/quality_of_service.rst, docs/devguide/quickstart/windows.rst, docs/devguide/run_time_configuration.rst, docs/devguide/the_dcps_information_repository.rst, docs/devguide/xtypes.rst, docs/glossary.rst, docs/news.d/devguide-qos.rst
- Quality of Service
- Rearranged to remove large default value tables.
- Added Data Representation and Type Consistency Enforcement.
- Every policy now has a box that says if it's mutable, if it affects writer-reader association, its default values, and links to the spec definition.
- Added many links to QoS policies
- Move fnmatch expressions into an "annex" file so it can be common between security and partitions QoS.
- Add definitions for "instance", "unregister", and "dispose" to the glossary.
=> Improve QoS Documentation

examples/DCPS/ishapes/ShapeType.idl
Problem
-------
The Shapes IDL doesn't match the interoperability IDL which is causing a lot of test failures.
Solution
--------
Update the IDL to match.
=> Shapes IDL doesn't match interoperability IDL

dds/idl/typeobject_generator.cpp, tests/DCPS/Compiler/union_defaults/union_defaults.idl
Fixes an issue introduced in #4519 and includes new test case from #4537
=> Corrected typeobject generation for unions that use qualified enumerators in branch labels

tests/DCPS/Compiler/union_defaults/union_defaults.idl
* tests/DCPS/Compiler/union_defaults/union_defaults.idl:
New error I found in the AXCIOMA unit tests after the merge of https://github.com/OpenDDS/OpenDDS/pull/4519
=> Extend test with a reproducer for `Unknown union label value` error

dds/DCPS/ConfigStoreImpl.cpp, dds/DCPS/ConfigStoreImpl.h, dds/DCPS/RTPS/Sedp.cpp, tests/unit-tests/dds/DCPS/ConfigStoreImpl.cpp
Problem
-------
SEDP creates ConfigStore entries for the transport instance that it creates.  These entries are not removed when the SEDP intance goes away.  Thus, an application that recreates participants that use RTPS Discovery will leak these entries.
Solution
--------
Remove the entries created by SEDP.
=> ConfigStore entries created by SEDP linger

.github/workflows/build_and_test.yml, dds/DCPS/RTPS/RtpsCore.idl, dds/DCPS/RTPS/RtpsDiscoveryConfig.cpp, dds/DCPS/RTPS/RtpsDiscoveryConfig.h, dds/DCPS/RTPS/RtpsSubmessageKind.idl, dds/DCPS/RTPS/Spdp.cpp, dds/DCPS/RTPS/Spdp.h, docs/devguide/run_time_configuration.rst, docs/news.d/spdp-user-tag.rst, tests/transport/spdp/spdp_transport.cpp
If the configuration specifies a non-zero tag, then that 32-bit value is added to the start of the SPDP participant announcement messages after the RTPS Header and its own Submessage Header.
=> Add a configurable "user tag" to SPDP

dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp
Problem
-------
When doing interoperability testing, OpenDDS was observed to send a nack for a sequence number that is no longer available.  The offending sequence is
1. Writer sends a HB for [X, X].
2. OpenDDS Reader sends a NACK for X.
3. Writer sends DATA with sequence number X + 1.
4. Writer sends HB for [X+1, X+1].
5. OpenDDS Reader sends a NACK for X.
OpenDDS should treat X as unavailable.
Solution
--------
The RtpsUdpDataLink contains a code fragment that handles this case but it is limited to the first heartbeat that was received.  Move this code out so that it is processed for each heartbeat.
=> RtpsUdpDataLink sends nacks when writer has clearly moved on

dds/DCPS/DataReaderImpl.cpp, dds/DCPS/transport/framework/DataLink.h, dds/DCPS/transport/framework/TransportImpl.h, dds/DCPS/transport/multicast/MulticastDataLink.h, dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.h, dds/DCPS/transport/rtps_udp/RtpsUdpTransport.cpp
This made a block of code public that probably wasn't supposed to be.
DataReaderImpl should not have conditional logic based on transport_type()
=> TransportImpl: remove unused member function decls

docs/devguide/built_in_topics.rst, docs/devguide/content_subscription_profile.rst, docs/devguide/dds_security.rst, docs/devguide/introduction.rst, docs/devguide/run_time_configuration.rst, docs/devguide/safety_profile.rst, docs/internal/bench.rst, docs/internal/docs.rst, docs/news.d/_releases/v3.27.0.rst, docs/sphinx_extensions/config_domain.py, docs/sphinx_extensions/custom_domain.py
Prompted by this comment: https://github.com/OpenDDS/OpenDDS/pull/4556#discussion_r1550398101
This is to avoid confusion with config store keys, which are basically the same thing, but it comes across as strange in the documentation to use the same term. This is mostly internal to the configuration domain code and usage, but has some references in the documentation.
Also:
- Linked configuration store key name to explanation of what the config store is.
- Fixed a bug in the shared domain code for CMake and configuration because I renamed `:cfg:key` to `:cfg:prop:` and it then seemed to be confusing `:cfg:prop:` for `:cmake:prop:` definitions and vice versa. This was because the Python classes for the two domains were sharing members they should not have.
=> Rename Configuration Keys to Properties

.github/workflows/Wireshark_CMakePresets.json, .github/workflows/build_and_test.yml
We can build the Wireshark libs without building the Qt GUI.  That allows us to skip downloading/building qt5.
=> Update GitHub Actions build for wireshark

docs/news.d/gov-gen.rst, tests/security/attributes/gov_gen.cpp
Problem
-------
The `gov_gen` application generates governance files for testing and signs them with openssl.  `gov_gen` has a bug on Debian 12.5 (openssl 3.0.11) where a null argument is passed.
Solution
--------
Pass `mem` as the "in"" parameter and use `PKCS7_STREAM`.
=> `gov_gen` uses openssl API incorrectly

.github/workflows/build_and_test.yml, .github/workflows/ishapes.yml, configure, docs/news.d/mpcopts.rst
Problem
-------
`--mpcopts` is a `configure` script option that accumulates additional options for MPC.  These values are split on spaces so `--mpcopts="-features no_opendds_testing_features=0"` results in two arguments to MPC: `-features` and `no_opendds_testing_features=0`.
This behavior complicates situations where one of the arguments to MPC contains spaces.  For example, `--mpcopts="-value_template build_flags+=-Wall -Werror" results in three arguments to MPC (and an error): `-value_template`, `build_flags+=Wall`, and `-Werror`.
Solution
--------
Remove the splitting functionality.
The examples above would now be written as
* `--mpcopts=-features --mpcopts=no_opendds_testing_features=0`
* `--mpcopts=-value_template --mpcopts=build_flags+="-Wall -Werror"`
=> `--mpcopts` values are split on spaces

.github/workflows/build_and_test.yml, .github/workflows/cmake.yml, build.ini, cmake/opendds_build_helpers.cmake, configure, docs/devguide/building/index.rst, docs/news.d/compiler-warnings.rst
=> Update compiler warning levels

docs/devguide/run_time_configuration.rst, docs/news.d/buffer-doc.rst
Problem
-------
The DevGuide doesn't document `send_buffer_size` and `rcv_buffer_size` for the `rtps_udp` transport and RTPS Discovery.
Solution
--------
Add documentation.
=> DevGuide doesn't document `send_buffer_size` and `rcv_buffer_size`

dds/DCPS/transport/framework/TransportSendStrategy.cpp, dds/DCPS/transport/framework/TransportSendStrategy.h, dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp, docs/news.d/heartbeat-fragmentation.rst
Problem
-------
Suppose a writer has an agressive heartbeat period and then writes a sample that is highly fragmented.  It is possible (probable) that the heartbeat timer will go off before all fragments have been sent.  The reader can then nack fragments that haven't even been sent.  The writer would then resend the requested fragments.
Solution
--------
Before sending a heartbeat, check that the user is not in the middle of a send.
The solution does not make a change for resends due to reliability and/or durability.  The reason for this is that sending heartbeats and nack responses are mutually exclusive based on locking.
=> rtps_udp sends heartbeats when sending fragments

dds/DCPS/ValueDispatcher.h
Problem
-------
The ValueDispatcher code assumes the value indicated by the void* is a KeyOnly<T>*.  This is incorrect as the void* is a T*.
Solution
--------
Assume the void* is a T* and construct the KeyOnly.
=> ValueDispatcher assumes pointer is KeyOnly

configure, dds/.gitignore
- Fix uninitialized value warning
- Tweak configure script output:
- Bring `--help` mostly back to 80-ish columns.
- Try to make new options a little more clear.
- Use "cross-compile" instead of "cross compile", "GoogleTest" instead of "Google Test", "CMake" instead of "cmake", etc.
- `--mpc:OPT` should accept `--mpc:*=OPT=VALUE`.
- Try to make how features are handled a little bit more sane by putting them all in `@features`. It's still not great and I know I'm at least partially to blame.
- Try to put all features not in `default.features` in `opendds_mwc.pl`.
- Add `OpenDDSCOnfig.h.bak*` to git ignore.
=> Improvements to configure Script

dds/DCPS/FilterEvaluator.cpp, dds/DCPS/FilterEvaluator.h, dds/idl/metaclass_generator.cpp
Problem
-------
The `Value` class used for `MetaStruct` has various constructors based on integer size and sign.  When constructing a `Value` from a wchar, different compilers make different choices.
Solution
--------
Provide explicit support for wchar conversion.
=> MetaStruct conversion of wchar is compiler dependent

docs/internal/dev_guidelines.rst
Problem
-------
The internal (developer) documentation lacks the policy used for managing the dependencies of OpenDDS.
Solution
--------
Add it.
=> Internal documentation lacks dependency management policy

bin/PerlDDS/Run_Test.pm
Problem
-------
Debugging is not turned on for the Messenger test.
Solution
--------
Turn on debugging.
=> Debugging output not available for Messenger test

dds/DCPS/Service_Participant.cpp
Problem
-------
Environment variables are not processed immediately by the Service Participant.  For many configuration keys, this is irrelevant.  For others, like those processed in
`Service_Participant::ConfigReaderListener::on_data_available`, it applies the configuration immediately.
A related problem is that if there are no arguments or configuration file, then the configuration from environment variables is not applied.  This prevents an "environment variable only" configuration from working properly.
Solution
--------
Invoke the listener after each environment variable is processed.
=> Environment variables are not processed immediately

.github/workflows/build_and_test.yml
Problem
-------
The macos-11 GHA runners are going away.
Solution
--------
Upgrade to macos-13.
=> macos-11 runners are going away

docs/build.py, docs/conf.py, docs/sphinx_extensions/links.py
- Ignore `dds-foundation.org` and `corba.org`, which have been returning 403 for a while
- Ignore login redirect on spec issues
- Completely omit generating links to all the spec sections when running `linkcheck`
=> Fix OMG-Related Link Checking Issues

.github/workflows/cmake.yml, cmake/build_ace_tao.cmake, docs/news.d/cmake_just_build_host_tools.rst
should fix #4645
Tested on Debian 12
=> cmake: ignore the not-used targets when building with just the host tools

MPC/config/dcps_optional_features.mpb
Reverts OpenDDS/OpenDDS#4671, the file really should be there, the new OpenDDSConfig header is the only place where OpenDDS features can be enabled safely
=> Revert "Add feature to disable include of OpenDDSConfig.h when compiling an IDL file"

dds/OpenDDSConfigWrapper.h
Removed OPENDDS_IGNORE_OPENDDSCONFIG_H_FILE, this new configuration file must be there, as some DDS features (like security) can only be enabled it this file, not from ace/config.h anymore
=> Update OpenDDSConfigWrapper.h, remove `OPENDDS_IGNORE_OPENDDSCONFIG_H_FILE` check

.github/workflows/ishapes.yml
Problem
-------
The `--mpc` argument to the Windows ishapes contains the "value."
Solution
--------
Split the argument into a `--mpc` argument and a `key=value` pair.
=> Arguments to the Windows ishapes build are over-quoted

dds/DCPS/RTPS/RtpsDiscovery.h, dds/DCPS/RTPS/RtpsDiscoveryConfig.cpp, dds/DCPS/RTPS/RtpsDiscoveryConfig.h, dds/DCPS/RTPS/Spdp.cpp, dds/DCPS/RTPS/Spdp.h, docs/news.d/msg_reset_checks.rst
Problem
-------
The config store reads `MAX_SPDP_SEQUENCE_MSG_RESET_CHECK` instead of `MAX_SPDP_SEQUENCE_MSG_RESET_CHECKS`.
Solution
--------
Add an "s".
Notes
-----
Introduced in #4361.
This may explain Thrasher test failures which use this feature.
=> MAX_SPDP_SEQUENCE_MSG_RESET_CHECK lacks an "s"

dds/DCPS/RTPS/Spdp.cpp, docs/news.d/spdp-infodst.rst, tests/transport/spdp/spdp_transport.cpp
If InfoDestinationSubmessage indicates this isn't directed at the current participant, the following DataSubmessage(s) are dropped.
=> Parse InfoDestinationSubmessages in incoming SPDP messages

tests/DCPS/RtpsRelay/Smoke/relay1.ini, tests/DCPS/RtpsRelay/Smoke/relay2.ini
Problem
-------
The RtpsRelay tests are a starting poing to users that want to use the RtpsRelay.  In any realistic deployment, the user must have `CheckSourceIp=false` in the configuration file.  Since the tests don't have this line, the user will have to learn "the hard way."
Solution
--------
Add `CheckSourceIp=false` to the configuration files.
=> RtpsRelay tests don't have CheckSourceIp=false

tools/scripts/gdbext.py
Features:
- Properly display GUID/BuiltinTopicKeys, GUID Prefixes, and GUID Entity IDs with known built-in names
- Shortcuts to important global singletons
- Shortcuts to all participants, discoveries, SPDP and SEDP instances, user readers, and user writers
- Helpers to make it easier to work with data structures in Python: `value_is`, `std_*_values`, `deref`, and `deref_holder`.
To use:
- Run `gdb -x path/to/gdbext.py ...` for a new session
- `source path/to/gdbext.py` for an existing session
Tested with Ubuntu 22.04 (GDB 12.1, gcc 11.4, and libstdc++ 3.4.30) This script might break with changes to either OpenDDS, GDB, or gcc/libstdc++
Example output:
```
(gdb) source gdbext.py
OpenDDS GDB Extension ==============================================================================
- …
```
=> GDB Extension to Help Debug OpenDDS

tests/unit-tests/dds/DCPS/RTPS/RtpsDiscoveryConfig.cpp
Problem
-------
The `spdp_multicast_address` method is sensitive to the `OPENDDS_RTPS_DEFAULT_D0` environment variable.  However, the unit test does not take it into account.
Solution
--------
Modify the unit test to accommodate `OPENDDS_RTPS_DEFAULT_D0`.
=> Unit test fails when `OPENDDS_RTPS_DEFAULT_D0` is set

dds/DCPS/RTPS/DiscoveredEntities.h, dds/DCPS/RTPS/Sedp.cpp, dds/DCPS/transport/framework/DataLink.cpp, dds/DCPS/transport/framework/DataLink.h, dds/DCPS/transport/framework/TransportClient.cpp, dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp, dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.h, dds/DCPS/transport/rtps_udp/RtpsUdpTransport.cpp, docs/news.d/rtps-udp-memory-leaks.rst, tools/rtpsrelay/GuidAddrSet.cpp
Locators were not being cleaned up correctly because there were two functions for cleaning up after remotes in `RtpsUdpDataLink`. These changes merge those two functions.
Also:
- Don't create locator entries for unknown remotes in `RtpsUdpDataLink::update_locators`
- Change `RemoteInfo::ref_count_` from `size_t` to `DDS::UInt32` to save a bit of space in 64-bit builds. For example, if the RtpsRelay SEDP transport is serving 10,000 participants with a `RemoteInfo` for each participant's 12 remote builtin entities, then this saves almost half a megabyte of memory.
- Methods for getting GUIDs from `DiscoveredParticipant` to simplify code
- Remove an unused function in Sedp
=> Fix Locator Memory Leak in RTPS/UDP Transport

dds/DCPS/ConfigStoreImpl.cpp, dds/DCPS/InstanceState.inl, dds/DCPS/NetworkResource.h, dds/idl/metaclass_generator.cpp, dds/idl/typeobject_generator.cpp, java/idl2jni/codegen/be_produce.cpp, performance-tests/DCPS/SimpleLatency/raw_tcp/publisher/TestDriver.cpp, performance-tests/DCPS/SimpleLatency/raw_tcp/subscriber/TestDriver.cpp, performance-tests/DCPS/TCPProfilingTest/raw_tcp/publisher/TestDriver.cpp, performance-tests/DCPS/TCPProfilingTest/raw_tcp/subscriber/TestDriver.cpp
This addresses most of the warnings that come from OpenDDS, except this warning in `dds/DCPS/Hash.cpp` that needs further look: `[build_m13_j_FM-1f: dds/DCPS/Hash.cpp#L135]
cast from 'const unsigned char *' to 'const MD5_u32plus *' (aka 'const unsigned int *') increases required alignment from 1 to 4 [-Wcast-align]`
The rest of the warnings come from ACE, TAO, and generated code by `tao_idl` which are the majority of all warnings.
=> Address warnings

docs/news.d/java-fixed-size-structs.rst, java/idl2jni/codegen/be_global.cpp, java/idl2jni/codegen/be_global.h, java/idl2jni/codegen/im_jni.cpp, java/tests/complex_idl/Complex_Idl.idl
Problem
-------
A topic type that has fixed size results in compilation errors in the generated code.
Solution
--------
Extend `idl2jni` to stub out return values for fixed-size structs.
=> Fixed-size structs don't compile with Java

docs/internal/release.rst
Problem
-------
- The release process cannot be performed on MacOS.
- There were some assumptions about micro releases that were not stated.
Solution
--------
- Add guidance for using a container to perform the release.
- Add detail about preparing the release branch for a micro release.
=> Release process lacks detail on micro releases and using containers

.github/workflows/build_and_test.yml
Problem
-------
As we approach OpenDDS 4, we will most likely have CI jobs with the same name running against version 3 and 4.  Currently, the OpenDDS version is not used when naming the result.  For clarity moving forward, the result should include the version.
Solution
--------
Extract the OpenDDS version from `dds/Version.h` and use it in the upload path.
=> OpenDDS version not accounted for in scoreboard

configure, docs/news.d/cross-java.rst
I took these lines out from the configure script for some reason in https://github.com/OpenDDS/OpenDDS/pull/4611. Without them the host build doesn't include idl2jni.
=> Fixed Cross-compiled Builds Using Java

.github/workflows/build_and_test.yml, docs/internal/github_actions.rst
=> GitHub Actions: ACE 7 is no longer used

dds/DCPS/AddressCache.h, dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp, docs/devguide/quality_of_service.rst, docs/news.d/addr-cache-leak.rst, tests/unit-tests/dds/DCPS/AddressCache.cpp
AddressCache has a `map_` that maps keys (local-remote GUID pairs in RTPS/UDP) to cache entries and a `id_map_` that maps GUIDs to a vector of related keys.
`id_map_` has two problems:
- The vector of keys are not checked if elements are being duplicated. These changes make it a set.
- `remove_id` removes the `id_map_` keys for the GUID argument (the remote GUID in RTPS/UDP), but not any keys that contain that GUID for other vectors in `id_maps_` (the entries under local GUIDs in RTPS/UDP). These changes try to clean up all the relevant GUIDs.
Also:
- A change to release reservation I meant to add in the other leak PR. If the release reservation is for a specific local-remote pair, it doesn't seem right to remove all messages for the remote from the send queue.
- Small fixes to the QoS …
=> Fixed Leak in `AddressCache` for RTPS/UDP Transport

support.md
Problem
-------
The support page has broken links and references OpenDDS Foundation as a support provider which is no longer relevant.
Solution
--------
Correct the broken links and text.
=> Support page has broken links

dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp
If the number of remotes and `meta_submessages` is large, then this will waste a lot of space.
=> Restrict Vector Reserve Count in `RtpsUdpDataLink`

docs/news.d/relay-thread-monitor.rst, tools/rtpsrelay/RelayThreadMonitor.cpp
All threads that have missed the deadline are reported before the process dies. These log messages include the timestamp of the most recent update for each thread that has missed the deadline.
=> Updated RelayThreadMonitor error reporting

docs/news.d/relay-admission-rate-limit.rst, tools/rtpsrelay/GuidAddrSet.cpp, tools/rtpsrelay/GuidAddrSet.h, tools/rtpsrelay/RelayHandler.cpp
For accurate rate limiting the relay needs to maintain this queue upon receipt of any valid message, not just those from new clients.
=> RtpsRelay: updated handling of admission control queue

dds/idl/typeobject_generator.cpp
Add type names for the generated `TypeObject`s to facilitate debugging.
=> Add comments for type names when generating complete `TypeObject`s

docs/build.py, docs/sphinx_extensions/links.py
[This page](https://opendds.readthedocs.io/en/master/internal/omg_spec_links.html) is supposed to list links to all the sections in all the spec, not just the specs like it does now. It was causing a lot of unwanted output in the link checker, so I tried to make it conditional in https://github.com/OpenDDS/OpenDDS/pull/4669. Unfortunately it looks like I broke the page so it never lists all the possible spec section links. These changes fix that.
Also added `--nitpicky`, `--keep-going`, and `--show-traceback` to the `sphinx-build` command of `build.py strict` to make output more useful.
=> Fix OMG Spec Links Page

tests/auto_run_tests.pl, tests/cmake/ctest-to-auto-run-tests.py
There's a check in the CTest scripts on Windows for the build configuration. If the configuration isn't valid, the script would return invalid results and lead to the fake auto_run_tests name being truncated. These changes pass the build configuration from `auto_run_tests.pl` and add extra checks to prevent this from happening again.
Also changed `auto_run_tests.pl` CMake output to make it linkable in the matrix changes in https://github.com/DOCGroup/autobuild/pull/74.
=> Fix `ctest-to-auto-run-tests.py` Output on Windows

dds/idl/metaclass_generator.cpp, tests/DCPS/Compiler/idl_test1_lib/FooDef.idl
```
module Test_Module
{
typedef sequence<char, 100> A_Char100S;
};
struct TestModuleStruct {
@id(1) sequence <Test_Module::A_Char100S> sequence_field3;
};
```
generates code that does not compile (g++, Ubuntu Jammy, x64, OpenDDS/master e613d2995c4) :
```
/home/ultra/src/OpenDDS/tests/DCPS/Compiler/xcdr/mutable_types2TypeSupportImpl.cpp: In function ‘bool OpenDDS::DCPS::gen_skip_over(OpenDDS::DCPS::Serializer&, OpenDDS::DCPS::IDL::DistinctType<std::vector<std::vector<char> >, OpenDDS::DCPS::TestModuleStruct_AnonymousType_9sequence_9field3_9seq_tag>*)’:
/home/ultra/src/OpenDDS/tests/DCPS/Compiler/xcdr/mutable_types2TypeSupportImpl.cpp:7357:87: error: ‘Test_9Module_9A_9Char100S_tag’ was not declared in this scope; did you mean ‘Test_9Module_A_9Char100S_tag’?
7357 | , …
```
=> Fix incorrect separator when generating tag type

dds/DCPS/transport/rtps_udp/RtpsUdpReceiveStrategy.cpp, docs/news.d/reallocating-buffer.rst, docs/news.d/tag-type-separator.rst
Problem
-------
The "reallocating primary receive buffer" log message shows up under the Info log level.  There are a number of reasons why the receive buffer needs to be reallocated and none of them warrant concern from users.
Solution
--------
Move to transport logging.
=> "reallocating primary receive buffer" shows up too often

dds/DCPS/DispatchService.cpp, dds/DCPS/JobQueue.cpp, dds/DCPS/ThreadStatusManager.cpp, dds/DCPS/ThreadStatusManager.h, docs/news.d/thread-status-manager.rst, tools/dds/rtpsrelaylib/Relay.idl, tools/rtpsrelay/GuidPartitionTable.cpp, tools/rtpsrelay/RtpsRelay.cpp
Some event loops process entire batches of events at once. Before this change, the batch of data would be considered an "Event" for the ThreadStatusManager.  With this change, each element within the batch counts as its own event for the ThreadStatusManager. That way the thread appears to be active and not stuck.
=> Updated ThreadStatusManager for iterative event handling

dds/DCPS/Timers.cpp, docs/news.d/boottime-timers.rst, tests/unit-tests/dds/DCPS/Timers.cpp
Problem
-------
Scheduling a timer with an interval but no delay causes the first firing of the timer to occur after the interval instead of as soon as possible.  Without CLOCK_BOOTTIME, the timer fires immediately and then starts to fire on the requested interval.
Solution
--------
Address the delay independent of the interval.
=> CLOCK_BOOTTIME timers ignore zero delay with interval

bin/PerlDDS/Run_Test.pm, dds/DCPS/DataReaderImpl.cpp, dds/DCPS/DataReaderImpl.h, dds/DCPS/WriterInfo.cpp, dds/DCPS/WriterInfo.h, tests/DCPS/TransientLocalMultiInstanceTest/.gitignore, tests/DCPS/TransientLocalMultiInstanceTest/DataReaderListener.cpp, tests/DCPS/TransientLocalMultiInstanceTest/DataReaderListener.h, tests/DCPS/TransientLocalMultiInstanceTest/publisher.cpp, tests/DCPS/TransientLocalMultiInstanceTest/run_test.pl, tests/DCPS/TransientLocalMultiInstanceTest/subscriber.cpp
Problem
-------
Custom implementations of ReactorInterceptor duplicate code which makes maintenance difficult.
Solution
--------
To make the code easier to maintain, replace custom implementations of ReactorInterceptor with helper classes.
=> EndHistoricSamplesMissedSweeper is a ReactorInterceptor

dds/DCPS/DataReaderImpl.cpp, dds/DCPS/DataReaderImpl.h, dds/DCPS/RecorderImpl.cpp, dds/DCPS/WriterInfo.cpp, dds/DCPS/WriterInfo.h
Problem
-------
Custom implementations of ReactorInterceptor duplicate code which makes maintenance difficult.
Solution
--------
To make the code easier to maintain, replace custom implementations of ReactorInterceptor with helper classes.
=> LivelinessTimer is a ReactorInterceptor

dds/DCPS/transport/framework/TransportClient.cpp, dds/DCPS/transport/framework/TransportClient.h
Problem
-------
Custom implementations of ReactorInterceptor duplicate code which makes maintenance difficult.
Solution
--------
To make the code easier to maintain, replace custom implementations of ReactorInterceptor with helper classes.
=> PendingAssocTimer is a ReactorInterceptor

docs/devguide/building/dependencies.rst, docs/devguide/internet_enabled_rtps.rst
Use a more specific link for the TAO Developer's Guide
CISA website is constantly failing the link check in GitHub Actions
=> Updated links in documentation

dds/DCPS/RTPS/Sedp.cpp, tests/DCPS/FlexibleTS/Controller/Controller.cpp, tests/DCPS/FlexibleTS/NewDevice/NewDevice.cpp, tests/DCPS/FlexibleTS/NewDevice/NewDevice.idl
Also test the case where types have a compatible change (adding a member to a struct)
=> Update FlexibleTypeSupport to handle an additional order of events

docs/requirements.txt
Fixes https://github.com/OpenDDS/OpenDDS/issues/4822 by updating to a version with a fix for https://github.com/liran-funaro/sphinx-markdown-builder/issues/25.
=> Update Sphinx Markdown Builder

dds/DCPS/FlexibleTypeSupport.cpp, dds/DCPS/FlexibleTypeSupport.h, dds/DCPS/TypeSupportImpl.h, dds/DCPS/XTypes/TypeObject.cpp
Problem
-------
Dependencies generated via FlexibleTypes were not calculated.
The algorithm for computing dependencies erroneously inserted the top-level type.
Solution
--------
* Add dependency support for FlexibleTypes.
* Correct the dependency algorithm.
=> TypeLookup fails with missing dependencies

dds/DCPS/Qos_Helper.h, dds/DCPS/Qos_Helper.inl, dds/DCPS/RTPS/RtpsDiscovery.h, dds/DCPS/RTPS/Spdp.cpp, dds/DCPS/RTPS/Spdp.h, docs/devguide/built_in_topics.rst, docs/news.d/harvest_control.rst, tests/DCPS/InternalThreadStatus/publisher.cpp, tools/rtpsrelay/RtpsRelay.cpp
Problem
-------
When thread status monitoring is enabled, all participants that use RTPS discovery will harvest the thread status from the monitor and publish it on the OpenDDSInternalThread BIT.  If there are multiple participants, they will each harvest.  Typically, an application will only look at one of the BIT readers with the result being that any monitoring logic may be operating on an incomplete set of data.
Solution
--------
Add a property `RTPS_HARVEST_THREAD_STATUS` that enables harvesting for particular participants.
=> Thread monitors may be starved for data

docs/conf.py, docs/news.d/harvest_control.rst, docs/sphinx_extensions/version_info.py
Fixes https://github.com/OpenDDS/OpenDDS/issues/4891
It will use the year from VERSION.txt if it's a release, else doesn't include a year.
Also fixed a link issue with https://github.com/OpenDDS/OpenDDS/pull/4887
=> Use Release Year in Sphinx Copyright

docs/news.d/rtpsrelay-service-participant.rst, tools/rtpsrelay/ParticipantListener.cpp, tools/rtpsrelay/PublicationListener.cpp, tools/rtpsrelay/RelayParticipantStatusReporter.cpp, tools/rtpsrelay/RelayParticipantStatusReporter.h, tools/rtpsrelay/SubscriptionListener.cpp
Problem
-------
The Service Participant thread invokes the BIT listeners in the RtpsRelay.  Given large enough batches, the listeners can occupy the processor long enough for the thread monitoring logic to trip.
Solution
--------
Add events for each sample to update the thread status.
Add logging to show the size of the batches.
=> Service Participant thread doesn't update thread status

dds/idl/typeobject_generator.cpp
This was accidentally lost in the change for PR #4898
=> Restore comment in generated code for complete TypeObjects

examples/DCPS/ishapes/CMakeLists.txt, examples/DCPS/ishapes/ishapes.mpc
Problem
-------
The iShapes demo doesn't have complete type objects which is something other vendors expect.
Solution
--------
Add complete type objects.
=> iShapes demo doesn't have complete type objects

docs/internal/dev_guidelines.rst
This is causing the linkcheck CI script to fail
=> Removed link to gnu.org in dev guidelines doc

docs/devguide/internet_enabled_rtps.rst, docs/news.d/rtpsrelay-synchronous-output.rst, tests/DCPS/RtpsRelay/Smoke/run_test.pl, tools/rtpsrelay/Config.h, tools/rtpsrelay/RelayHandler.cpp, tools/rtpsrelay/RelayHandler.h, tools/rtpsrelay/RtpsRelay.cpp
Problem
-------
The RtpsRelay uses an output queue.  When a message needs to be sent, the message is placed on a queue and a handler is registered with the reactor if necessary.  When the handler is invoked, a message is removed from the queue and sent. This avoid errors from the send buffer being full since the socket is non-blocking.
This design has shown to have undesirable behavior which stems from a lack of fairness between input and output processing.  That is, given that both tasks are ready, there is no guarantee that one will not be systematically preferred over another.  Given a high enough input rate, the output task will fall behind and the queue will grow.
Solution
--------
Introduce a `-SynchronousOutput` option that sends messages as soon as possible instead of queueing …
=> RtpsRelay output queue may be ill-behaved

dds/DCPS/RTPS/Sedp.cpp, dds/DCPS/TypeSupportImpl.cpp, dds/DCPS/XTypes/TypeLookupService.cpp, dds/DCPS/XTypes/TypeObject.cpp, dds/DCPS/XTypes/TypeObject.h, tests/unit-tests/dds/DCPS/XTypes/TypeObject.cpp
Problem
-------
The TypeLookupService doesn't support strongly connected components (SCCs) correctly.
Solution
--------
* Add the SCCId to dependencies when necessary (fixes `getTypeDependencies`).
* Update `getTypes` to consolidate type identifiers and send all components of an SCC.
=> TypeLookupService doesn't support SCCs

dds/DCPS/RTPS/AssociationRecord.h, dds/DCPS/RTPS/Sedp.cpp, dds/DCPS/RTPS/Sedp.h, dds/DCPS/transport/framework/DataLink.h, dds/DCPS/transport/framework/DataLinkSet.cpp, dds/DCPS/transport/framework/DataLinkSet.h, dds/DCPS/transport/framework/TransportClient.cpp, dds/DCPS/transport/framework/TransportClient.h, dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp, dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.h
Problem
-------
Enabling flexible types causes new publications and subscriptions to be written.  These are outside of the durable data which means they go through a delay, heartbeat, and acknack cycle.  This delays association since there is definitely a match but the local match cannot proceed without confirmation that the remote received the local publication/subscription.  The goal is to eliminate the delay.
Solution
--------
- Keep track of endpoints that write samples when enabling flexible types.
- Request acknowledgement on these endpoints.
- Enable support for request acknowledgements in RTPS.
- Update the progressive association logic to only require the reader to acknowledge the relevant publication/subscription.
=> FlexibleTypes delay association

tools/rtpsrelay/GuidPartitionTable.cpp
Problem
-------
Observations:
1. `GuidPartitionTable::lookup` creates a cache entry if it does not exist.
2. The discovery of a publication or subscription removes the cache entry if it exists and the partitions change.
3. The removal of a publication or subscription removes the cache entry if it exists.
4. `GuidPartitionTable::lookup` can be called before discovery completes.
In a scenario where discovery completes, the cache is eventually correct, that is, it is correct after the first lookup that follows the last publication or subscription.
In a scenario where dicovery doesn't complete, then the cache entry is created (1 and 4) but not removed (2 and 3).
Solution
--------
Only create a cache entry if the set of partitions is not empty which implies discovery is in progress or has …
=> RtpsRelay leaks memory for incomplete discoveries

docs/devguide/introduction.rst, docs/devguide/run_time_configuration.rst, docs/devguide/xtypes.rst
Problem
-------
The DevGuide lacks a section describing how to configure OpenDDS for interoperability.
Solution
--------
Add a section for interoperability.
=> DevGuide lacks section on interoperability

NEWS.md, docs/build.py, docs/conf.py, docs/news.d/_releases/v3.24.2.rst, docs/news.d/_releases/v3.26.0.rst, docs/news.d/_releases/v3.28.0.rst, docs/sphinx_extensions/links.py, docs/sphinx_extensions/newsd.py, docs/sphinx_extensions/opendds_logging.py
This should make Sphinx output the correct annotation in RST files in the PR in most situations except for when the content causing the error is in a news fragment. News fragments are used to generate two files at runtime, so the source info that Sphinx has for these files doesn't lead the correct annotation in the PR. See below for what the workaround looks like.
Also tried to improve link checking so it fails less often. This includes:
- Ignoring `:ghfile:` links. It's not really needed because they're checked locally. There's also a lot of them so it takes a while to check them and there's a greater chance for something going wrong.
- Ignoring links that fail with 409 HTTP status code. They happen a lot.
- Turning redirects on GitHub PR and issue links into errors because that means …
=> GHA Annotations and Better Link Check for Sphinx

cmake/dds_idl_sources.cmake, cmake/init.cmake, cmake/opendds_target_sources.cmake, docs/devguide/building/cmake.rst, docs/news.d/cmake-generated-target-folder.rst
When CMake generates projects for an IDE, all custom targets for IDL code generation will be grouped together in a folder.
=> CMake: Set the FOLDER property on custom targets

dds/DCPS/RTPS/Spdp.cpp, dds/DCPS/ThreadStatusManager.cpp, dds/DCPS/ThreadStatusManager.h, dds/OpenddsDcpsExt.idl, docs/devguide/built_in_topics.rst, docs/news.d/internal-thread-detail.rst, java/tests/internal_thread_status/InternalThreadListener.java, tools/rtpsrelay/RelayHandler.cpp, tools/rtpsrelay/RelayHandler.h, tools/rtpsrelay/RelayStatusReporter.cpp, tools/rtpsrelay/RelayStatusReporter.h, tools/rtpsrelay/RelayThreadMonitor.cpp, tools/rtpsrelay/RtpsRelay.cpp
This allows the ThreadStatusManager to track checkpoints of progress on event processing in each thread.
The RtpsRelay's RelayThreadMonitor reports the latest values on error.
=> Added detail fields to thread status

dds/DCPS/ConfigStoreImpl.cpp, dds/DCPS/ConfigStoreImpl.h, dds/DCPS/RTPS/MessageUtils.h, dds/DCPS/RTPS/RtpsDiscoveryConfig.cpp, dds/DCPS/RTPS/RtpsDiscoveryConfig.h, dds/DCPS/RTPS/Spdp.cpp, dds/DCPS/RTPS/Spdp.h, dds/DCPS/security/AuthenticationBuiltInImpl.cpp, docs/devguide/run_time_configuration.rst, docs/news.d/spdp-enhance.rst, tests/transport/spdp/spdp_transport.cpp, tests/unit-tests/dds/DCPS/ConfigStoreImpl.cpp
* Incoming SPDP can be ignored based on user tag 
* When requiring authentication, incoming SPDP using a different CA can be dropped
=> SPDP enhancements to avoid unneeded discovery traffic

docs/build.py, docs/devguide/building/android.rst
Apparently the link we're using is a redirect, but to the same URL with a / at the end. That doesn't seem to be the problem though. Using curl to see what's happening, the link is resolving, it's just ftp.gnu.org is taking a time long to respond. Ignore read timeouts in general, also saw one on Strawberry Perl website while testing.
=> Workaround libiconv URL Timeout Read

.github/workflows/android-ci.yml, .github/workflows/android-matrix.yml, .github/workflows/build_and_test.yml, .github/workflows/cmake.yml, .github/workflows/lint.yml, .github/workflows/sphinx_strict.yml
Otherwise they double up with pull request jobs.
Also:
- Also ignore `workflows/**` for any future custom workflow created
branches.
- Run Android Matrix after merge.
=> Don't Run Dependabot Jobs on Push 
